MERGE INTO `${ProjectID}.${TargetDatasetNames2}.production_order_fact` tgt
USING (WITH tmp_scr AS (SELECT

-- Combining columns which are required to make a key for the production_order_fact

  po.order_number || '-' || COALESCE(mpp.order_item_number,'') as production_order_key,
  po.order_number,
  po.order_type,
  po.company_code,
  po.created_on,
  po.change_date_for_order_master,
  mpd.material_number,
  mpd.plant,
  mpd.maintenance_status,
  mpd.plant_level_deletion_flag,
  mpd.valuation_category,
  mpd.batch_management_indicator,
  mpd.plant_specific_material_status,
  mpd.valid_from,
  mpd.abc_indicator,
  mpd.critical_part,
  mpd.purchasing_group,
  mpd.unit_of_issue,
  mpd.mrp_profile,
  mpd.mrp_type,
  mpd.mrp_controller_buyer,
  mpd.planned_deliv_time,
  mpd.goods_receipt_processing_time,
  mpd.period_indicator,
  mpd.assembly_scrap,
  mpd.lot_sizing_procedure,
  mpd.procurement_type,
  mpd.special_procurement_type,
  mpd.dependent_requirements_indicator,
  mpd.storage_costs_code,
  mpd.selection_method,
  mpd.discontinuation_indicator,
  mpd.effective_out_date,
  mpd.follow_up_material,
  mpd.requirements_group,
  mpd.mixed_mrp_indicator,
  mpd.scheduling_margin_key,
  mpd.automatic_fixing_planned_orders,
  mpd.automatic_release,
  mpd.backflush,
  mpd.processing_time,
  mpd.setup_time,
  mpd.interoperation_time,
  mpd.in_house_production,
  mpd.maximum_storage_period,
  mpd.time_unit,
  mpd.withdrawal_production_bin,
  mpd.rough_cut_planning,
  mpd.overdelivery_tolerance_limit,
  mpd.unlimited_overdelivery_allowed,
  mpd.underdely_tolerance,
  mpd.total_replenishment_lead_time,
  mpd.replacement_part,
  mpd.surcharge_factor_percent,
  mpd.state_of_manufacture,
  mpd.stock_type,
  mpd.sample_percentage,
  mpd.quarantine_period,
  mpd.qm_control_key,
  mpd.mean_inspection_duration,
  mpd.inspection_plan_indicator,
  mpd.documentation_required,
  mpd.active_substance,
  mpd.inspection_interval,
  mpd.next_inspection,
  mpd.loading_group,
  mpd.batch_management_requirement,
  mpd.quota_arrangement_usage,
  mpd.service_level,
  mpd.splitting_indicator,
  mpd.plan_version,
  mpd.object_type,
  mpd.object_id,
  mpd.availability_check,
  mpd.fiscal_year_variant,
  mpd.correction_factors,
  mpd.shipping_setup_time,
  mpd.shipping_processing_time,
  mpd.delivery_cycle,
  mpd.source_of_supply,
  mpd.automatic_purchase_order,
  mpd.source_list,
  mpd.commodity_code,
  mpd.country_of_origin,
  mpd.region_of_origin,
  mpd.commodity_code_unit,
  mpd.intrastat_material_group,
  mpd.planning_calendar,
  mpd.repetitive_manufacturing,
  mpd.planning_time_fence,
  mpd.consumption_mode,
  mpd.backward_consumption_period,
  mpd.forward_consumption_period,
  mpd.version_indicator,
  mpd.alternative_bom,
  mpd.bom_usage,
  mpd.task_list_group,
  mpd.group_counter,
  mpd.special_procurement_costing,
  mpd.production_unit,
  mpd.production_storage_location,
  mpd.mrp_group,
  mpd.component_scrap,
  mpd.certificate_type,
  mpd.inspection_setup,
  mpd.takt_time,
  mpd.coverage_profile,
  mpd.local_field_name,
  mpd.physical_inventory_indicator,
  mpd.variance_key,
  mpd.serial_number_profile,
  mpd.internal_object_number,
  mpd.configurable_material,
  mpd.repetitive_manufacturing_profile,
  mpd.negative_stocks,
  mpd.target_qm_system,
  mpd.planning_cycle,
  mpd.rounding_profile,
  mpd.reference_material_for_consumption,
  mpd.reference_plant_for_consumption,
  mpd.date_of_material,
  mpd.multiplier_for_reference_material,
  mpd.reset_automatically,
  mpd.customs_preference,
  mpd.exemption_certificate,
  mpd.exemption_certificate_number,
  mpd.issue_date_certificate,
  mpd.vendor_declaration_code,
  mpd.vendor_declaration_date,
  mpd.military_goods,
  mpd.isr_service_level,
  mpd.material_co_product,
  mpd.planning_strategy_group,
  mpd.material_internal_object_number,
  mpd.storage_location_external_procurement,
  mpd.bulk_material,
  mpd.cc_indicator_fixed,
  mpd.withdrawal_sequence_group,
  mpd.qm_material_authorization,
  mpd.adjustment_period,
  mpd.task_list_type,
  mpd.uom_group,
  mpd.conversion_group,
  mpd.air_bouyancy_factor,
  mpd.production_scheduling_profile,
  mpd.safety_time_indicator,
  mpd.safety_time,
  mpd.action_control,
  mpd.batch_entry,
  po.business_area,
  po.controlling_area,
  po.responsible_cost_center,
  po.order_currency,
  po.profit_center,
  po.sales_order_number,
  po.sales_order_item,
  po.project_definition,
  po.planner_group,
  po.wbs_element,
  po.mrp_controller,
  po.order_priority,
  po.created_by,
  po.order_category,
  po.location,
  po.production_supervisor,
  po.requesting_cost_center,
  po.last_changed_by,
  po.scheduling_type,
  po.customer_number,
  po.batch_number,
  po.planning_plant,
  po.production_version,
  po.system_status,
  po.status_object_confirmation,
  po.status_object_delivered,
  mpp.delivered,
mpp.actual_release_date,
mpp.planned_release_date,
mpp.scheduled_release_date,
mpp.actual_finish_date,
mpp.basic_finish_date,
mpp.scheduled_finish,
mpp.actual_start_date,
mpp.basic_start_date,
mpp.scheduled_start,
mpp.leading_order,
mpp.superior_order,
mpp.posting_date,
mpp.unit_execution_time,
mpp.unit_execution_time_exact,
mpp.planned_opening_date,
mpp.actual_scrap_quantity,
mpp.actual_execution_time,
mpp.actual_execution_time_exact,
mpp.actual_lead_time,
mpp.actual_lead_time_exact,
mpp.capacity_unit,
mpp.capacity_requirement,
mpp.actual_delivery_date,
mpp.planned_order_delivery_date,
mpp.base_unit_of_measure,
mpp.scrap_quantity,
mpp.planned_order_quantity,
mpp.planned_actual_scheduled_release_date,
mpp.planned_actual_scheduled_delivery_date,
mpp.scheduled_start_date,
mpp.planned_order,
mpp.order_item_number,
mpp.scrap_quantity_item,
mpp.order_item_quantity,
mpp.planned_target_release_deviation,
mpp.planned_target_delivery_deviation,
mpp.planned_target_start_deviation,
mpp.planned_lead_time,
mpp.target_actual_release_deviation,
mpp.target_actual_delivery_deviation,
mpp.target_actual_start_deviation,
mpp.planned_order_planned_start_date,
mpp.target_execution_time,
mpp.target_execution_time_exact,
mpp.target_lead_time,
mpp.target_lead_time_exact,
mpp.quantity_of_goods_received,
mpp.event,
mpp.leading_material,

-- Here we are comparing dw_last_udpate_date from all the input source table, Get the value which is greater and use that value to populate in the input_last_update_date

CASE WHEN mpd.dw_last_update_date > po.dw_last_update_date AND mpd.dw_last_update_date > mpp.dw_last_update_date 
     THEN mpd.dw_last_update_date
     WHEN po.dw_last_update_date > mpd.dw_last_update_date AND po.dw_last_update_date > mpp.dw_last_update_date 
     THEN po.dw_last_update_date
     ELSE mpp.dw_last_update_date
  END AS input_last_update_date,
  po.dw_active_indicator,
  md.material_uuid,
  pd.plant_uuid,
  cd.customer_uuid,
  (mpd.material_number || '-' || mpd.plant) as material_key,
  mpd.plant as plant_key,
  po.customer_number as customer_key
FROM  `${ProjectID}.${StagingDatasetName}.material_plant_data` mpd
       INNER JOIN `${ProjectID}.${StagingDatasetName}.production_orders` po
  ON  mpd.material_number = po.material_number
 AND  mpd.plant = po.plant
 AND  po.dw_active_indicator = mpd.dw_active_indicator
       LEFT JOIN `${ProjectID}.${StagingDatasetName}.material_production_planning` mpp 
  ON mpp.order_number = po.order_number 
 and mpp.material_number = po.material_number
 and mpp.plant = po.plant
 and mpp.cancel_data_record = ''
      LEFT JOIN `${ProjectID}.${TargetDatasetNames1}.material_dimension` md
  ON md.material_key = (mpd.material_number || '-' || mpd.plant)
 AND md.dw_active_indicator = 'Y' 
      LEFT JOIN `${ProjectID}.${TargetDatasetNames1}.plant_dimension` pd
  ON pd.plant_key = mpd.plant
 AND pd.dw_active_indicator = 'Y'
      LEFT JOIN `${ProjectID}.${TargetDatasetNames1}.customer_dimension` cd
  ON cd.customer_key = po.customer_number
 AND cd.dw_active_indicator = 'Y'
WHERE mpd.dw_active_indicator = 'Y'

-- Here we are try get from the audit table (layer1_audit_table) in which mode we are running the merge query. Based on that we have to deside which date column we need to use to fetch the records from the input table.

 AND (mpd.dw_last_update_date >= coalesce((SELECT CASE WHEN lat.full_delta_indicator = 'F' THEN lat.full_load_datetime
                                             WHEN lat.full_delta_indicator <> 'F' THEN lat.delta_load_datetime
                                             ELSE CAST('1900-01-01T00:00:00' AS DATETIME)
                                        END FROM `${ProjectID}.${StagingDatasetName}.layer1_audit_table` lat
                                WHERE lat.table_name = 'production_order_fact'),CAST('1900-01-01T00:00:00' AS DATETIME))
    OR po.dw_last_update_date >= coalesce((SELECT CASE WHEN lat.full_delta_indicator = 'F' THEN lat.full_load_datetime
                                             WHEN lat.full_delta_indicator <> 'F' THEN lat.delta_load_datetime
                                             ELSE CAST('1900-01-01T00:00:00' AS DATETIME)
                                        END FROM `${ProjectID}.${StagingDatasetName}.layer1_audit_table` lat
                                WHERE lat.table_name = 'production_order_fact'),CAST('1900-01-01T00:00:00' AS DATETIME))
    OR mpp.dw_last_update_date >= coalesce((SELECT CASE WHEN lat.full_delta_indicator = 'F' THEN lat.full_load_datetime
                                             WHEN lat.full_delta_indicator <> 'F' THEN lat.delta_load_datetime
                                             ELSE CAST('1900-01-01T00:00:00' AS DATETIME)
                                        END FROM `${ProjectID}.${StagingDatasetName}.layer1_audit_table` lat
                                WHERE lat.table_name = 'production_order_fact'),CAST('1900-01-01T00:00:00' AS DATETIME)))),
tmp_prod AS (SELECT ts.*,

-- Logic to convert all the input source columns to string datatype and concatenate the not null columns and make a MD5 key.

     TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    from unnest(split(trim(format('%t',(select as struct ts.* except(input_last_update_date))), '()'),', ')) col with offset 
    where not col IS NULL
    ))) as finalmd5key      
  from tmp_scr ts)

-- the base source data by creating join key is use to implement the SCD2 in the merge query. 

SELECT t.production_order_key as production_order_join_key,t.*
  from tmp_prod t
UNION ALL 

-- Generating extra row for changes records. The NULL join key forces records down the INSERT Path.

SELECT NULL as production_order_join_key,t.*
  from tmp_prod t
       INNER JOIN `${ProjectID}.${TargetDatasetNames2}.production_order_fact` pof
    ON  pof.production_order_key =  t.production_order_key 
   AND pof.finalmd5key <> t.finalmd5key
 WHERE pof.dw_active_indicator = 'Y') scr

-- Join the source  and the taget table using the join keys.

  ON  tgt.production_order_key = scr.production_order_join_key
WHEN MATCHED AND tgt.finalmd5key <> scr.finalmd5key THEN 
UPDATE set tgt.dw_end_date = CURRENT_DATETIME()
          ,tgt.dw_active_indicator = 'N'
WHEN NOT MATCHED THEN 
INSERT (production_order_uuid,
production_order_key,
order_number,
order_type,
material_number,
plant,
material_uuid,
plant_uuid,
customer_uuid,
material_key,
plant_key,
customer_key,
company_code,
created_on,
change_date_for_order_master,
maintenance_status,
plant_level_deletion_flag,
valuation_category,
batch_management_indicator,
plant_specific_material_status,
valid_from,
abc_indicator,
critical_part,
purchasing_group,
unit_of_issue,
mrp_profile,
mrp_type,
mrp_controller_buyer,
planned_deliv_time,
goods_receipt_processing_time,
period_indicator,
assembly_scrap,
lot_sizing_procedure,
procurement_type,
special_procurement_type,
dependent_requirements_indicator,
storage_costs_code,
selection_method,
discontinuation_indicator,
effective_out_date,
follow_up_material,
requirements_group,
mixed_mrp_indicator,
scheduling_margin_key,
automatic_fixing_planned_orders,
automatic_release,
backflush,
processing_time,
setup_time,
interoperation_time,
in_house_production,
maximum_storage_period,
time_unit,
withdrawal_production_bin,
rough_cut_planning,
overdelivery_tolerance_limit,
unlimited_overdelivery_allowed,
underdely_tolerance,
total_replenishment_lead_time,
replacement_part,
surcharge_factor_percent,
state_of_manufacture,
stock_type,
sample_percentage,
quarantine_period,
qm_control_key,
mean_inspection_duration,
inspection_plan_indicator,
documentation_required,
active_substance,
inspection_interval,
next_inspection,
loading_group,
batch_management_requirement,
quota_arrangement_usage,
service_level,
splitting_indicator,
plan_version,
object_type,
object_id,
availability_check,
fiscal_year_variant,
correction_factors,
shipping_setup_time,
shipping_processing_time,
delivery_cycle,
source_of_supply,
automatic_purchase_order,
source_list,
commodity_code,
country_of_origin,
region_of_origin,
commodity_code_unit,
intrastat_material_group,
planning_calendar,
repetitive_manufacturing,
planning_time_fence,
consumption_mode,
backward_consumption_period,
forward_consumption_period,
version_indicator,
alternative_bom,
bom_usage,
task_list_group,
group_counter,
special_procurement_costing,
production_unit,
production_storage_location,
mrp_group,
component_scrap,
certificate_type,
inspection_setup,
takt_time,
coverage_profile,
local_field_name,
physical_inventory_indicator,
variance_key,
serial_number_profile,
internal_object_number,
configurable_material,
repetitive_manufacturing_profile,
negative_stocks,
target_qm_system,
planning_cycle,
rounding_profile,
reference_material_for_consumption,
reference_plant_for_consumption,
date_of_material,
multiplier_for_reference_material,
reset_automatically,
customs_preference,
exemption_certificate,
exemption_certificate_number,
issue_date_certificate,
vendor_declaration_code,
vendor_declaration_date,
military_goods,
isr_service_level,
material_co_product,
planning_strategy_group,
material_internal_object_number,
storage_location_external_procurement,
bulk_material,
cc_indicator_fixed,
withdrawal_sequence_group,
qm_material_authorization,
adjustment_period,
task_list_type,
uom_group,
conversion_group,
air_bouyancy_factor,
production_scheduling_profile,
safety_time_indicator,
safety_time,
action_control,
batch_entry,
business_area,
controlling_area,
responsible_cost_center,
order_currency,
profit_center,
sales_order_number,
sales_order_item,
project_definition,
planner_group,
wbs_element,
mrp_controller,
order_priority,
created_by,
order_category,
location,
production_supervisor,
requesting_cost_center,
last_changed_by,
scheduling_type,
customer_number,
batch_number,
planning_plant,
production_version,
system_status,
status_object_confirmation,
status_object_delivered,
delivered,
actual_release_date,
planned_release_date,
scheduled_release_date,
actual_finish_date,
basic_finish_date,
scheduled_finish,
actual_start_date,
basic_start_date,
scheduled_start,
leading_order,
superior_order,
posting_date,
unit_execution_time,
unit_execution_time_exact,
planned_opening_date,
actual_scrap_quantity,
actual_execution_time,
actual_execution_time_exact,
actual_lead_time,
actual_lead_time_exact,
capacity_unit,
capacity_requirement,
actual_delivery_date,
planned_order_delivery_date,
base_unit_of_measure,
scrap_quantity,
planned_order_quantity,
planned_actual_scheduled_release_date,
planned_actual_scheduled_delivery_date,
scheduled_start_date,
planned_order,
order_item_number,
scrap_quantity_item,
order_item_quantity,
planned_target_release_deviation,
planned_target_delivery_deviation,
planned_target_start_deviation,
planned_lead_time,
target_actual_release_deviation,
target_actual_delivery_deviation,
target_actual_start_deviation,
planned_order_planned_start_date,
target_execution_time,
target_execution_time_exact,
target_lead_time,
target_lead_time_exact,
quantity_of_goods_received,
event,
leading_material,
input_last_update_date,
finalmd5key,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date)

-- generating uuid column for each record my combining the key colum and finalmd5key information to have unique value.

VALUES (TO_HEX(MD5(CONCAT(production_order_key,scr.finalmd5key))),
scr.production_order_key,
scr.order_number,
scr.order_type,
scr.material_number,
scr.plant,
scr.material_uuid,
scr.plant_uuid,
scr.customer_uuid,
scr.material_key,
scr.plant_key,
scr.customer_key,
scr.company_code,
scr.created_on,
scr.change_date_for_order_master,
scr.maintenance_status,
scr.plant_level_deletion_flag,
scr.valuation_category,
scr.batch_management_indicator,
scr.plant_specific_material_status,
scr.valid_from,
scr.abc_indicator,
scr.critical_part,
scr.purchasing_group,
scr.unit_of_issue,
scr.mrp_profile,
scr.mrp_type,
scr.mrp_controller_buyer,
scr.planned_deliv_time,
scr.goods_receipt_processing_time,
scr.period_indicator,
scr.assembly_scrap,
scr.lot_sizing_procedure,
scr.procurement_type,
scr.special_procurement_type,
scr.dependent_requirements_indicator,
scr.storage_costs_code,
scr.selection_method,
scr.discontinuation_indicator,
scr.effective_out_date,
scr.follow_up_material,
scr.requirements_group,
scr.mixed_mrp_indicator,
scr.scheduling_margin_key,
scr.automatic_fixing_planned_orders,
scr.automatic_release,
scr.backflush,
scr.processing_time,
scr.setup_time,
scr.interoperation_time,
scr.in_house_production,
scr.maximum_storage_period,
scr.time_unit,
scr.withdrawal_production_bin,
scr.rough_cut_planning,
scr.overdelivery_tolerance_limit,
scr.unlimited_overdelivery_allowed,
scr.underdely_tolerance,
scr.total_replenishment_lead_time,
scr.replacement_part,
scr.surcharge_factor_percent,
scr.state_of_manufacture,
scr.stock_type,
scr.sample_percentage,
scr.quarantine_period,
scr.qm_control_key,
scr.mean_inspection_duration,
scr.inspection_plan_indicator,
scr.documentation_required,
scr.active_substance,
scr.inspection_interval,
scr.next_inspection,
scr.loading_group,
scr.batch_management_requirement,
scr.quota_arrangement_usage,
scr.service_level,
scr.splitting_indicator,
scr.plan_version,
scr.object_type,
scr.object_id,
scr.availability_check,
scr.fiscal_year_variant,
scr.correction_factors,
scr.shipping_setup_time,
scr.shipping_processing_time,
scr.delivery_cycle,
scr.source_of_supply,
scr.automatic_purchase_order,
scr.source_list,
scr.commodity_code,
scr.country_of_origin,
scr.region_of_origin,
scr.commodity_code_unit,
scr.intrastat_material_group,
scr.planning_calendar,
scr.repetitive_manufacturing,
scr.planning_time_fence,
scr.consumption_mode,
scr.backward_consumption_period,
scr.forward_consumption_period,
scr.version_indicator,
scr.alternative_bom,
scr.bom_usage,
scr.task_list_group,
scr.group_counter,
scr.special_procurement_costing,
scr.production_unit,
scr.production_storage_location,
scr.mrp_group,
scr.component_scrap,
scr.certificate_type,
scr.inspection_setup,
scr.takt_time,
scr.coverage_profile,
scr.local_field_name,
scr.physical_inventory_indicator,
scr.variance_key,
scr.serial_number_profile,
scr.internal_object_number,
scr.configurable_material,
scr.repetitive_manufacturing_profile,
scr.negative_stocks,
scr.target_qm_system,
scr.planning_cycle,
scr.rounding_profile,
scr.reference_material_for_consumption,
scr.reference_plant_for_consumption,
scr.date_of_material,
scr.multiplier_for_reference_material,
scr.reset_automatically,
scr.customs_preference,
scr.exemption_certificate,
scr.exemption_certificate_number,
scr.issue_date_certificate,
scr.vendor_declaration_code,
scr.vendor_declaration_date,
scr.military_goods,
scr.isr_service_level,
scr.material_co_product,
scr.planning_strategy_group,
scr.material_internal_object_number,
scr.storage_location_external_procurement,
scr.bulk_material,
scr.cc_indicator_fixed,
scr.withdrawal_sequence_group,
scr.qm_material_authorization,
scr.adjustment_period,
scr.task_list_type,
scr.uom_group,
scr.conversion_group,
scr.air_bouyancy_factor,
scr.production_scheduling_profile,
scr.safety_time_indicator,
scr.safety_time,
scr.action_control,
scr.batch_entry,
scr.business_area,
scr.controlling_area,
scr.responsible_cost_center,
scr.order_currency,
scr.profit_center,
scr.sales_order_number,
scr.sales_order_item,
scr.project_definition,
scr.planner_group,
scr.wbs_element,
scr.mrp_controller,
scr.order_priority,
scr.created_by,
scr.order_category,
scr.location,
scr.production_supervisor,
scr.requesting_cost_center,
scr.last_changed_by,
scr.scheduling_type,
scr.customer_number,
scr.batch_number,
scr.planning_plant,
scr.production_version,
scr.system_status,
scr.status_object_confirmation,
scr.status_object_delivered,
scr.delivered,
scr.actual_release_date,
scr.planned_release_date,
scr.scheduled_release_date,
scr.actual_finish_date,
scr.basic_finish_date,
scr.scheduled_finish,
scr.actual_start_date,
scr.basic_start_date,
scr.scheduled_start,
scr.leading_order,
scr.superior_order,
scr.posting_date,
scr.unit_execution_time,
scr.unit_execution_time_exact,
scr.planned_opening_date,
scr.actual_scrap_quantity,
scr.actual_execution_time,
scr.actual_execution_time_exact,
scr.actual_lead_time,
scr.actual_lead_time_exact,
scr.capacity_unit,
scr.capacity_requirement,
scr.actual_delivery_date,
scr.planned_order_delivery_date,
scr.base_unit_of_measure,
scr.scrap_quantity,
scr.planned_order_quantity,
scr.planned_actual_scheduled_release_date,
scr.planned_actual_scheduled_delivery_date,
scr.scheduled_start_date,
scr.planned_order,
scr.order_item_number,
scr.scrap_quantity_item,
scr.order_item_quantity,
scr.planned_target_release_deviation,
scr.planned_target_delivery_deviation,
scr.planned_target_start_deviation,
scr.planned_lead_time,
scr.target_actual_release_deviation,
scr.target_actual_delivery_deviation,
scr.target_actual_start_deviation,
scr.planned_order_planned_start_date,
scr.target_execution_time,
scr.target_execution_time_exact,
scr.target_lead_time,
scr.target_lead_time_exact,
scr.quantity_of_goods_received,
scr.event,
scr.leading_material,
scr.input_last_update_date,
scr.finalmd5key,
scr.dw_active_indicator,
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME());

MERGE INTO 
`${ProjectID}.${StagingDatasetName}.layer1_audit_table` tgt
USING ( SELECT 

-- mention table name for which we are updating the record.

         'production_order_fact' as table_name

-- check the layer1_audit_table is having entry for the table. if not mark the flag as 'F'.

         ,CASE WHEN (select full_delta_indicator from `${ProjectID}.${StagingDatasetName}.layer1_audit_table` where table_name = 'production_order_fact') IS NULL
                    OR (select full_delta_indicator from `${ProjectID}.${StagingDatasetName}.layer1_audit_table` where table_name = 'production_order_fact') = 'F'
               THEN 'F'
               ELSE 'D'
          END AS full_delta_indicator

-- mention all the extractor names which are used as source

        ,'0PRODORDER_ATTR,0MAT_PLANT_ATTR' as extractors_names

-- default value '1900-01-01T00:00:00'

        ,CAST('1900-01-01T00:00:00' AS DATETIME) as full_load_datetime

-- get max input_last_udpate_date from the sales_order_fact 

        ,(select max(input_last_update_date) as delta_load_datatime from `${ProjectID}.${TargetDatasetNames2}.production_order_fact`) as delta_load_datetime

-- count of records base on the flag 'F' -- Full and 'D' -- Delta. If there is no entry in the table ,it treats it is a Full load and get entire count.

        ,(coalesce((select COUNT(*) AS inserted_record_count from `${ProjectID}.${TargetDatasetNames2}.delivery_fact` a 
          where a.dw_active_indicator = 'Y'  and a.dw_last_update_date > COALESCE((SELECT CASE WHEN b.full_delta_indicator = 'F' 
                                                              THEN b.full_load_datetime
                                                              WHEN b.full_delta_indicator <> 'F' THEN b.delta_load_datetime
                                                          END
                                                    from `${ProjectID}.${StagingDatasetName}.layer1_audit_table` b
                                        where b.table_name = 'production_order_fact'),CAST('1900-01-01T00:00:00' AS DATETIME))),(select count(*) as inserted_record_count from `${ProjectID}.${TargetDatasetNames2}.production_order_fact` where dw_active_indicator = 'Y')))  AS inserted_record_count

-- last update/insert date

        ,CURRENT_DATETIME() as last_update_date
) scr
on tgt.table_name = scr.table_name
WHEN MATCHED THEN 

-- Record exists update the information 

UPDATE set tgt.full_load_datetime ='1900-01-01T00:00:00'
          ,tgt.delta_load_datetime = scr.delta_load_datetime
          ,tgt.inserted_record_count = scr.inserted_record_count
          ,tgt.last_update_date = scr.last_update_date
WHEN NOT MATCHED THEN
INSERT (table_name,
        full_delta_indicator,
        extractors_names,
        full_load_datetime,
        delta_load_datetime,
        inserted_record_count,
        last_update_date)

-- No record then insert the new entry into the audit table

VALUES(scr.table_name,
       scr.full_delta_indicator,
       scr.extractors_names,
       scr.full_load_datetime,
       scr.delta_load_datetime,
       scr.inserted_record_count,
       scr.last_update_date);