CREATE OR REPLACE VIEW `${ProjectID}.${TargetDatasetNames3}.location_vw`
AS
SELECT
customer_uuid AS uuid,
'CUSTOMER' || '-' || customer_key AS location_uid,
'CUSTOMER' AS location_type,
customer_number AS location_id,
name_1 AS location_name,
name_2 AS location_name2,
street_and_house_number as house_number,
street_and_house_number as street,
city,
postal_code,
district,
region,
country_key as country,
CAST(NULL AS FLOAT64) as geo_lattitude,
CAST(NULL AS FLOAT64) as geo_longitude,
CAST(NULL AS STRING) as time_zone,
transportation_zone,
CAST(NULL AS STRING) as shipping_calendar,
CAST(NULL AS STRING) as receiving_calendar,
working_times as working_hour,
language_key,
CAST(NULL AS DATETIME) as valid_from_date,
CAST(NULL AS DATETIME) as valid_to_date,
CAST(NULL AS STRING) as active,
CAST(NULL AS STRING) as company_code,
CAST(NULL AS STRING) as valuation_area,
created_on as creation_date,
CAST(NULL AS DATE) as change_date
FROM `${ProjectID}.${TargetDatasetNames1}.customer_dimension`
where dw_active_indicator = 'Y'
UNION ALL 
SELECT 
supplier_uuid AS UUID,
'SUPPLIER' || '-' || supplier_key AS location_uid,
'SUPPLIER' AS location_type,
vendors_account_number AS location_id,
name_1 AS location_name,
name_2 AS location_name2,
street_and_house_number as house_number,
street_and_house_number as street,
city,
postal_code,
district,
region,
country_key as country,
CAST(NULL AS FLOAT64) as geo_lattitude,
CAST(NULL AS FLOAT64) as geo_longitude,
CAST(NULL AS STRING) as time_zone,
CAST(NULL AS STRING) as transportation_zone,
CAST(NULL AS STRING) as shipping_calendar,
CAST(NULL AS STRING) as receiving_calendar,
factory_calendar as working_hour,
language_key,
CAST(NULL AS DATETIME) as valid_from_date,
CAST(NULL AS DATETIME) as valid_to_date,
CAST(NULL AS STRING) as active,
CAST(NULL AS STRING) as company_code,
CAST(NULL AS STRING) as valuation_area,
created_on as creation_date,
CAST(NULL AS DATE) as change_date
FROM `${ProjectID}.${TargetDatasetNames1}.supplier_dimension`
where dw_active_indicator = 'Y'
UNION ALL 
SELECT 
plant_uuid AS UUID,
'PLANT' || '-' || plant_key AS location_uid,
'PLANT' AS location_type,
plant AS location_id,
name AS location_name,
name_2 AS location_name2,
street_house_number as house_number,
street_house_number as street,
city,
po_box,
city,
region,
country_key as country,
CAST(NULL AS FLOAT64) as geo_lattitude,
CAST(NULL AS FLOAT64) as geo_longitude,
CAST(NULL AS STRING) as time_zone,
CAST(NULL AS STRING) as transportation_zone,
CAST(NULL AS STRING) as shipping_calendar,
CAST(NULL AS STRING) as receiving_calendar,
factory_calendar as working_hour,
language_key,
CAST(NULL AS DATETIME) as valid_from_date,
CAST(NULL AS DATETIME) as valid_to_date,
CAST(NULL AS STRING) as active,
CAST(NULL AS STRING) as company_code,
CAST(NULL AS STRING) as valuation_area,
CAST(NULL AS DATE) as creation_date,
CAST(NULL AS DATE) as change_date
FROM `${ProjectID}.${TargetDatasetNames1}.plant_dimension`
where dw_active_indicator = 'Y';