MERGE INTO `sap-adapter.slt_staging.universal_journal_item` tgt
USING (
WITH acdoca as
(select RCLNT as client,
RLDNR as ledger,
RBUKRS as company_code,
GJAHR as fiscal_year,
BELNR as document_number,
DOCLN as line_item,
RYEAR as g_l_fiscal_year,
DOCNR_LD as ledger_spec_docno,
RRCTY as record_type,
RMVCT as transactn_type,
VORGN as activity_type,
VRGNG as bus_transaction,
BTTYPE as bustrans_type,
AWTYP as ref_procedure,
AWSYS as logical_system,
AWORG as refer_org_unit,
AWREF as reference_doc,
AWITEM as ref_doc_item,
AWITGRP as ref_item_group,
SUBTA as sub_transaction,
XREVERSING as is_reversing,
XREVERSED as is_reversed,
XTRUEREV as is_true_reversal,
AWTYP_REV as reversereftrans,
AWORG_REV as reversal_org,
AWREF_REV as reversal_ref,
SUBTA_REV as reversal_sub_trans,
XSETTLING as is_settling,
XSETTLED as is_settled,
PREC_AWTYP as precreftransact,
PREC_AWSYS as precreflogsys,
PREC_AWORG as precreforgunit,
PREC_AWREF as precrefdocument,
PREC_AWITEM as prec_ref_doc_item,
PREC_SUBTA as prec_sub_transactn,
PREC_AWMULT as multprecrefid,
PREC_BUKRS as precje_cocode,
PREC_GJAHR as precje_year,
PREC_BELNR as precje_docno,
PREC_DOCLN as precje_lineitem,
XSECONDARY as secondary_entry,
CLOSING_RUN_ID as closing_run_uuid,
SRC_AWTYP as scereftransact,
SRC_AWSYS as srcreflogsys,
SRC_AWORG as srcreforgunit,
SRC_AWREF as srcrefdocument,
SRC_AWITEM as src_ref_doc_item,
SRC_AWSUBIT as srcrefdoc_sub_item,
XCOMMITMENT as commitment,
OBS_REASON as obsoleteness_reason,
RTCUR as bal_transac_crcy,
RWCUR as transaction_currency,
RHCUR as companycode_currency,
RKCUR as global_currency,
ROCUR as free_defined_crcy_1,
RVCUR as free_defined_crcy_2,
RBCUR as free_defined_crcy_3,
RCCUR as free_defined_crcy_4,
RDCUR as free_defined_crcy_5,
RECUR as free_defined_crcy_6,
RFCUR as free_defined_crcy_7,
RGCUR as free_defined_crcy_8,
RCO_OCUR as co_object_currency,
RUNIT as base_unit,
RVUNIT as valuation_uom,
RRUNIT as reference_uom,
RIUNIT as inventory_uom,
QUNIT1 as add_unit_meas_1,
QUNIT2 as add_unit_meas_2,
QUNIT3 as add_unit_meas_3,
CO_MEINH as uom_covalqty,
RACCT as account_number,
RCNTR as cost_center,
PRCTR as profit_center,
RFAREA as functional_area,
RBUSA as business_area,
KOKRS as co_area,
SEGMENT as segment,
SCNTR as sender_cost_ctr,
PPRCTR as partner_pc,
SFAREA as partner_farea,
SBUSA as trdg_part_ba,
RASSC as trading_partner,
PSEGMENT as partner_segment,
TSL as amnt_in_bal_tr_crcy,
WSL as amnt_in_trans_crcy,
WSL2 as gv_amnt_in_transcrcy,
WSL3 as pcv_amnt_in_trnscrcy,
HSL as amnt_in_compcd_crcy,
KSL as amnt_in_gl_crcy,
OSL as amount_in_currency_1,
VSL as amount_in_currency_2,
BSL as amount_in_currency_3,
CSL as amount_in_currency_4,
DSL as amount_in_currency_5,
ESL as amount_in_currency_6,
FSL as amount_in_currency_7,
GSL as amount_in_currency_8,
KFSL as fixed_amnt_in_gc,
KFSL2 as gv_fixd_amt_glb_crcy,
KFSL3 as pcv_fixdamt_glb_crcy,
PSL as price_variance,
PSL2 as gval_tprice_varc_gc,
PSL3 as pcval_tprice_varc_gc,
PFSL as price_var_fxd,
PFSL2 as gval_fprice_varc_gc,
PFSL3 as pcval_fprice_varc_gc,
CO_OSL as amount_in_obj_crcy,
HSLALT as altvalue_lc,
KSLALT as altvalue_gc,
OSLALT as altvalue_in_crcy_1,
VSLALT as altvalue_in_crcy_2,
BSLALT as altvalue_in_crcy_3,
CSLALT as altvalue_in_crcy_4,
DSLALT as altvalue_in_crcy_5,
ESLALT as altvalue_in_crcy_6,
FSLALT as altvalue_in_crcy_7,
GSLALT as altvalue_in_crcy_8,
HSLEXT as extvalue_lc,
KSLEXT as extvalue_gc,
OSLEXT as extvalue_in_crcy_1,
VSLEXT as extvalue_in_crcy_2,
BSLEXT as extvalue_in_crcy_3,
CSLEXT as extvalue_in_crcy_4,
DSLEXT as extvalue_in_crcy_5,
ESLEXT as extvalue_in_crcy_6,
FSLEXT as extvalue_in_crcy_7,
GSLEXT as extvalue_in_crcy_8,
HVKWRT as value_sp_lcrcy,
MSL as quantity,
MFSL as fixed_quantity,
VMSL as val_quantity,
VMFSL as fixed_val_qty,
RMSL as ref_quantity,
QUANT1 as add_quantity_1,
QUANT2 as add_quantity_2,
QUANT3 as add_quantity_3,
CO_MEGBTR as covalqty,
CO_MEFBTR as covalqtyfix,
HSALK3 as invvalue_lcrcy,
KSALK3 as invvalue_gcrcy,
OSALK3 as invvalue_acrcy,
VSALK3 as invvalue_4crcy,
HSALKV as altinvvalue_lc,
KSALKV as altinvvalue_gc,
OSALKV as altinvvalue_ac,
VSALKV as altinvvalue_4c,
HPVPRS as map_lcrcy,
KPVPRS as map_gcrcy,
OPVPRS as map_acrcy,
VPVPRS as map_4crcy,
HSTPRS as stdprice_lcrcy,
KSTPRS as stdprice_gcrcy,
OSTPRS as stdprice_acrcy,
VSTPRS as stdprice_4crcy,
HVKSAL as invval_sp_lcrcy,
LBKUM as inv_quantity,
DRCRK as debit_credit,
POPER as posting_period,
PERIV as fi_year_variant,
FISCYEARPER as period_year,
BUDAT as posting_date,
BLDAT as document_date,
BLART as document_type,
BUZEI as line_item_1,
ZUONR as assignment_number,
BSCHL as posting_key,
BSTAT as document_status,
LINETYPE as item_category,
KTOSL as transaction_key,
SLALITTYPE as slalineitemtype,
XSPLITMOD as changed,
USNAM as user_name,
TIMESTAMP as time_stamp,
EPRCTR as elimination_prctr,
RHOART as origin_object,
GLACCOUNT_TYPE as g_l_account_type,
KTOPL as chart_of_accts,
LOKKT as altern_account,
KTOP2 as cntry_chrt_acts,
REBZG as invoice_ref,
REBZJ as fiscal_year_1,
REBZZ as line_item_2,
REBZT as follow_on_document_type,
RBEST as po_category,
EBELN as purchasing_doc,
EBELP as item,
ZEKKN as account_assgmt_no,
SGTXT as text,
KDAUF as sales_order,
KDPOS as sales_ord_item,
MATNR as material,
WERKS as plant,
LIFNR as vendor,
KUNNR as customer,
FBUDA as serv_rendered,
COCO_NUM as condition_contract,
WWERT as translation_dte,
KOART as account_type,
UMSKZ as special_g_l_ind,
MWSKZ as tax_code,
HBKID as house_bank,
HKTID as account_id,
XOPVW as oi_management,
AUGDT as clearing,
AUGBL as clrng_doc,
AUGGJ as clrg_fiscal_yr,
AFABE as depreciat_area,
ANLN1 as asset,
ANLN2 as sub_number,
BZDAT as asset_val_date,
ANBWA as ast_transaction_type,
MOVCAT as trans_type_cat,
DEPR_PERIOD as deprec_period,
ANLGR as group_asset,
ANLGR2 as subnumber,
SETTLEMENT_RULE as distr_rule_grp,
ANLKL as asset_class,
KTOGR as account_determ,
PANL1 as partner_asset,
PANL2 as partner_sub_no,
UBZDT_PN as orig_val_dat,
XVABG_PN as compl_retiremnt,
PROZS_PN as percentage_rate,
XMANPROPVAL_PN as man_proport_values,
KALNR as cost_estimateno,
VPRSV as price_control,
MLAST as price_determ,
KZBWS as valuation,
XOBEW as vendor_stk_val,
SOBKZ as special_stock,
VTSTAMP as valu_timestamp,
MAT_KDAUF as sd_doc_of_inv,
MAT_KDPOS as sd_item_of_inv,
MAT_PSPNR as wbselem_of_inv,
MAT_PS_POSID as wbselem_of_inv_1,
MAT_LIFNR as vendor_of_inv,
BWTAR as valuation_type,
BWKEY as valuation_area,
HPEINH as price_unit_lc,
KPEINH as price_unit_gc,
OPEINH as price_unit_ac,
VPEINH as price_unit_4c,
MLPTYP as orig_proc_cat,
MLCATEG as category,
QSBVALT as prcrmntalt_proc,
QSPROCESS as prod_proc_no,
PERART as period_type,
MLPOSNR as item_1,
INV_MOV_CATEG as inv_movement_categ,
BUKRS_SENDER as sender_cocode,
RACCT_SENDER as sender_gl_account,
ACCAS_SENDER as sender_acct_assgmt,
ACCASTY_SENDER as sndr_acctassgmt_type,
OBJNR as object_number,
HRKFT as co_subkey,
HKGRP as origin_group,
PAROB1 as partner_object,
PAROBSRC as parobj_source,
USPOB as source_object,
CO_BELKZ as dr_cr_ind_co,
CO_BEKNZ as dr_cr_origin,
BELTP as debit_type,
MUVFLG as qty_is_incomplete,
GKONT as offsetting_acct,
GKOAR as offst_acct_type,
ERLKZ as completion_ind,
PERNR as personnel_no,
PAOBJNR as profit_segment,
XPAOBJNR_CO_REL as paobj_is_co_relevant,
SCOPE as object_class,
LOGSYSO as logical_system_1,
PBUKRS as partner_cocode,
PSCOPE as partnerobjclass,
LOGSYSP as logical_system_2,
BWSTRAT as val_strategy,
OBJNR_HK as origin_object_1,
AUFNR_ORG as origin_order,
UKOSTL as origcctr,
ULSTAR as origact,
UPRZNR as sce_bproc,
UPRCTR as origin_profit_center,
ACCAS as account_assignment,
ACCASTY as object_type,
LSTAR as activity_type_1,
AUFNR as order_number,
AUTYP as order_category,
PS_PSP_PNR as wbs_element,
PS_POSID as wbs_element_1,
PS_PRJ_PNR as project_def,
PS_PSPID as project_def_1,
NPLNR as network,
NPLNR_VORGN as netwk_activity,
PRZNR as business_proc,
KSTRG as cost_object,
BEMOT as acctindicator,
RSRCE as resource,
QMNUM as notification,
SERVICE_DOC_TYPE as service_doc_type,
SERVICE_DOC_ID as service_document,
SERVICE_DOC_ITEM_ID as service_doc_item,
SERVICE_CONTRACT_TYPE as serv_contract_type,
SERVICE_CONTRACT_ID as service_contract,
SERVICE_CONTRACT_ITEM_ID as srv_contract_item,
ERKRS as operating_concern,
PACCAS as part_acct_assgmt,
PACCASTY as prt_object_type,
PLSTAR as paractvy,
PAUFNR as partner_order,
PAUTYP as prtnr_ord_cat,
PPS_PSP_PNR as partner_wbs_element,
PPS_POSID as partner_wbs_element_1,
PPS_PRJ_PNR as partner_project_def,
PPS_PSPID as part_proj_def,
PKDAUF as partner_salord,
PKDPOS as part_slsord_item,
PPAOBJNR as partnerprf_seg,
PNPLNR as part_proj_network,
PNPLNR_VORGN as part_proj_ntwk_acty,
PPRZNR as part_bus_process,
PKSTRG as partner_cost_object,
PSERVICE_DOC_TYPE as par_service_doctype,
PSERVICE_DOC_ID as partner_service_doc,
PSERVICE_DOC_ITEM_ID as par_service_docitem,
CO_ACCASTY_N1 as stat_acctass_type_1,
CO_ACCASTY_N2 as stat_acctass_type_2,
CO_ACCASTY_N3 as stat_acctass_type_3,
CO_ZLENR as item_2,
CO_BELNR as document_number_1,
CO_BUZEI as posting_row,
CO_BUZEI1 as co_postingrow_1,
CO_BUZEI2 as co_postingrow_2,
CO_BUZEI5 as co_postingrow_5,
CO_BUZEI6 as co_postingrow_6,
CO_BUZEI7 as co_postingrow_7,
CO_REFBZ as posting_row_1,
CO_REFBZ1 as refpostrow_1,
CO_REFBZ2 as refpostrow_2,
CO_REFBZ5 as refpostrow_5,
CO_REFBZ6 as refpostrow_6,
CO_REFBZ7 as refpostrow_7,
OVERTIMECAT as overtime_category,
WORK_ITEM_ID as work_item_id,
ARBID as object_id,
VORNR as activity,
AUFPS as order_item_no,
UVORN as suboperation,
EQUNR as equipment,
TPLNR as functional_loc,
ISTRU as assembly,
ILART as maintactivtype,
PLKNZ as orderplanind,
ARTPR as prioritytype,
PRIOK as priority,
MAUFNR as superior_order,
MATKL_MM as material_group,
PLANNED_PARTS_WORK as planned_parts_work,
FKART as billing_type,
VKORG as sales_org,
VTWEG as distr_channel,
SPART as division,
MATNR_COPA as product_sold,
MATKL as product_sold_group,
KDGRP as customer_group,
LAND1 as country,
BRSCH as industry,
BZIRK as sales_district,
KUNRE as bill_to_party,
KUNWE as ship_to_party,
KONZS as group_key,
ACDOC_COPA_EEW_DUMMY_PA as dummy_function_in_length_1,
DUMMY_MRKT_SGMNT_EEW_PS as dummy,
RE_BUKRS as company_code_1,
RE_ACCOUNT as ex_rv_a_c_in_cl,
FIKRS as fm_area,
FISTL as funds_center,
MEASURE as funded_program,
RFUND as fund,
RGRANT_NBR as grants,
RBUDGET_PD as budget_period,
SFUND as partner_fund,
SGRANT_NBR as partner_grant,
SBUDGET_PD as par_budper,
BDGT_ACCOUNT as budget_account,
BDGT_ACCOUNT_COCODE as budget_account_company_code,
BDGT_CNSMPN_DATE as budget_consumption_date,
BDGT_CNSMPN_PERIOD as cc_fiscal_period_for_budget_co,
BDGT_CNSMPN_YEAR as cc_fiscal_year_for_budget_cons,
BDGT_RELEVANT as budget_relevant_indicator,
BDGT_CNSMPN_TYPE as budget_consumption_type,
BDGT_CNSMPN_AMOUNT_TYPE as budget_consumption_amount_type,
VNAME as joint_venture,
EGRUP as equity_group,
RECID as recovery_indic,
VPTNR as partner,
BTYPE as billing_ind,
ETYPE as equity_type,
PRODPER as prod_month,
BILLM as billing_month,
POM as proc_oper_month,
CBRUNID as cutback_run_id_jva,
JVACTIVITY as jva_activity,
PVNAME as partner_venture_jva,
PEGRUP as partner_eg_jva,
S_RECIND as sender_rec_ind,
CBRACCT as cutback_account_jva,
CBOBJNR as cutback_co_jva,
SWENR as business_entity,
SGENR as building,
SGRNR as land,
SMENR as rental_object,
RECNNR as contract,
SNKSL as serv_charge_key,
SEMPSL as settlement_unit,
DABRZ as reference_date,
PSWENR as ptnr_bus_entity,
PSGENR as ptnr_building,
PSGRNR as partner_land,
PSMENR as ptnr_rent_unit,
PRECNNR as ptnr_contract_no,
PSNKSL as ptnr_srv_chrg_key,
PSEMPSL as ptnr_sett_unit,
PDABRZ as ptnr_reference_date,
ACROBJTYPE as accrual_object_type,
ACROBJ_ID as accrual_object,
ACRSOBJ_ID as accrual_subobject,
ACRITMTYPE as accrual_item_type,
ACRVALDAT as accrual_value_date,
VALOBJTYPE as type_of_fin_val_obj,
VALOBJ_ID as fin_valuation_object,
VALSOBJ_ID as fin_val_sub_object,
NETDT as due_on,
RISK_CLASS as risk_class,
ACDOC_EEW_DUMMY as dummy_1,
DUMMY_INCL_EEW_COBL as dummy_2,
FUP_ACTION as follow_up_action,
SDM_VERSION as sdm_versioning,
MIG_SOURCE as migr_source,
MIG_DOCLN as migr_line_item_id,
_DATAAGING as data_filter_value_for_data_agi,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct acdoca.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.acdoca` as acdoca
where acdoca._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'universal_journal_item'),0))
select client as client_key,
ledger as ledger_key,
company_code as company_code_key,
fiscal_year as fiscal_year_key,
document_number as document_number_key,
line_item as line_item_key,
*
From  acdoca
UNION ALL
select null as client_key,
null as ledger_key,
null as company_code_key,
null as fiscal_year_key,
null as document_number_key,
null as line_item_key,
acdoca.*
From acdoca as acdoca
INNER JOIN `sap-adapter.slt_staging.universal_journal_item` as uji
ON acdoca.client = uji.client
AND acdoca.ledger = uji.ledger
AND acdoca.company_code = uji.company_code
AND acdoca.fiscal_year = uji.fiscal_year
AND acdoca.document_number = uji.document_number
AND acdoca.line_item = uji.line_item
AND acdoca.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.ledger_key = tgt.ledger
AND src.company_code_key = tgt.company_code
AND src.fiscal_year_key = tgt.fiscal_year
AND src.document_number_key = tgt.document_number
AND src.line_item_key = tgt.line_item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
ledger,
company_code,
fiscal_year,
document_number,
line_item,
g_l_fiscal_year,
ledger_spec_docno,
record_type,
transactn_type,
activity_type,
bus_transaction,
bustrans_type,
ref_procedure,
logical_system,
refer_org_unit,
reference_doc,
ref_doc_item,
ref_item_group,
sub_transaction,
is_reversing,
is_reversed,
is_true_reversal,
reversereftrans,
reversal_org,
reversal_ref,
reversal_sub_trans,
is_settling,
is_settled,
precreftransact,
precreflogsys,
precreforgunit,
precrefdocument,
prec_ref_doc_item,
prec_sub_transactn,
multprecrefid,
precje_cocode,
precje_year,
precje_docno,
precje_lineitem,
secondary_entry,
closing_run_uuid,
scereftransact,
srcreflogsys,
srcreforgunit,
srcrefdocument,
src_ref_doc_item,
srcrefdoc_sub_item,
commitment,
obsoleteness_reason,
bal_transac_crcy,
transaction_currency,
companycode_currency,
global_currency,
free_defined_crcy_1,
free_defined_crcy_2,
free_defined_crcy_3,
free_defined_crcy_4,
free_defined_crcy_5,
free_defined_crcy_6,
free_defined_crcy_7,
free_defined_crcy_8,
co_object_currency,
base_unit,
valuation_uom,
reference_uom,
inventory_uom,
add_unit_meas_1,
add_unit_meas_2,
add_unit_meas_3,
uom_covalqty,
account_number,
cost_center,
profit_center,
functional_area,
business_area,
co_area,
segment,
sender_cost_ctr,
partner_pc,
partner_farea,
trdg_part_ba,
trading_partner,
partner_segment,
amnt_in_bal_tr_crcy,
amnt_in_trans_crcy,
gv_amnt_in_transcrcy,
pcv_amnt_in_trnscrcy,
amnt_in_compcd_crcy,
amnt_in_gl_crcy,
amount_in_currency_1,
amount_in_currency_2,
amount_in_currency_3,
amount_in_currency_4,
amount_in_currency_5,
amount_in_currency_6,
amount_in_currency_7,
amount_in_currency_8,
fixed_amnt_in_gc,
gv_fixd_amt_glb_crcy,
pcv_fixdamt_glb_crcy,
price_variance,
gval_tprice_varc_gc,
pcval_tprice_varc_gc,
price_var_fxd,
gval_fprice_varc_gc,
pcval_fprice_varc_gc,
amount_in_obj_crcy,
altvalue_lc,
altvalue_gc,
altvalue_in_crcy_1,
altvalue_in_crcy_2,
altvalue_in_crcy_3,
altvalue_in_crcy_4,
altvalue_in_crcy_5,
altvalue_in_crcy_6,
altvalue_in_crcy_7,
altvalue_in_crcy_8,
extvalue_lc,
extvalue_gc,
extvalue_in_crcy_1,
extvalue_in_crcy_2,
extvalue_in_crcy_3,
extvalue_in_crcy_4,
extvalue_in_crcy_5,
extvalue_in_crcy_6,
extvalue_in_crcy_7,
extvalue_in_crcy_8,
value_sp_lcrcy,
quantity,
fixed_quantity,
val_quantity,
fixed_val_qty,
ref_quantity,
add_quantity_1,
add_quantity_2,
add_quantity_3,
covalqty,
covalqtyfix,
invvalue_lcrcy,
invvalue_gcrcy,
invvalue_acrcy,
invvalue_4crcy,
altinvvalue_lc,
altinvvalue_gc,
altinvvalue_ac,
altinvvalue_4c,
map_lcrcy,
map_gcrcy,
map_acrcy,
map_4crcy,
stdprice_lcrcy,
stdprice_gcrcy,
stdprice_acrcy,
stdprice_4crcy,
invval_sp_lcrcy,
inv_quantity,
debit_credit,
posting_period,
fi_year_variant,
period_year,
posting_date,
document_date,
document_type,
line_item_1,
assignment_number,
posting_key,
document_status,
item_category,
transaction_key,
slalineitemtype,
changed,
user_name,
time_stamp,
elimination_prctr,
origin_object,
g_l_account_type,
chart_of_accts,
altern_account,
cntry_chrt_acts,
invoice_ref,
fiscal_year_1,
line_item_2,
follow_on_document_type,
po_category,
purchasing_doc,
item,
account_assgmt_no,
text,
sales_order,
sales_ord_item,
material,
plant,
vendor,
customer,
serv_rendered,
condition_contract,
translation_dte,
account_type,
special_g_l_ind,
tax_code,
house_bank,
account_id,
oi_management,
clearing,
clrng_doc,
clrg_fiscal_yr,
depreciat_area,
asset,
sub_number,
asset_val_date,
ast_transaction_type,
trans_type_cat,
deprec_period,
group_asset,
subnumber,
distr_rule_grp,
asset_class,
account_determ,
partner_asset,
partner_sub_no,
orig_val_dat,
compl_retiremnt,
percentage_rate,
man_proport_values,
cost_estimateno,
price_control,
price_determ,
valuation,
vendor_stk_val,
special_stock,
valu_timestamp,
sd_doc_of_inv,
sd_item_of_inv,
wbselem_of_inv,
wbselem_of_inv_1,
vendor_of_inv,
valuation_type,
valuation_area,
price_unit_lc,
price_unit_gc,
price_unit_ac,
price_unit_4c,
orig_proc_cat,
category,
prcrmntalt_proc,
prod_proc_no,
period_type,
item_1,
inv_movement_categ,
sender_cocode,
sender_gl_account,
sender_acct_assgmt,
sndr_acctassgmt_type,
object_number,
co_subkey,
origin_group,
partner_object,
parobj_source,
source_object,
dr_cr_ind_co,
dr_cr_origin,
debit_type,
qty_is_incomplete,
offsetting_acct,
offst_acct_type,
completion_ind,
personnel_no,
profit_segment,
paobj_is_co_relevant,
object_class,
logical_system_1,
partner_cocode,
partnerobjclass,
logical_system_2,
val_strategy,
origin_object_1,
origin_order,
origcctr,
origact,
sce_bproc,
origin_profit_center,
account_assignment,
object_type,
activity_type_1,
order_number,
order_category,
wbs_element,
wbs_element_1,
project_def,
project_def_1,
network,
netwk_activity,
business_proc,
cost_object,
acctindicator,
resource,
notification,
service_doc_type,
service_document,
service_doc_item,
serv_contract_type,
service_contract,
srv_contract_item,
operating_concern,
part_acct_assgmt,
prt_object_type,
paractvy,
partner_order,
prtnr_ord_cat,
partner_wbs_element,
partner_wbs_element_1,
partner_project_def,
part_proj_def,
partner_salord,
part_slsord_item,
partnerprf_seg,
part_proj_network,
part_proj_ntwk_acty,
part_bus_process,
partner_cost_object,
par_service_doctype,
partner_service_doc,
par_service_docitem,
stat_acctass_type_1,
stat_acctass_type_2,
stat_acctass_type_3,
item_2,
document_number_1,
posting_row,
co_postingrow_1,
co_postingrow_2,
co_postingrow_5,
co_postingrow_6,
co_postingrow_7,
posting_row_1,
refpostrow_1,
refpostrow_2,
refpostrow_5,
refpostrow_6,
refpostrow_7,
overtime_category,
work_item_id,
object_id,
activity,
order_item_no,
suboperation,
equipment,
functional_loc,
assembly,
maintactivtype,
orderplanind,
prioritytype,
priority,
superior_order,
material_group,
planned_parts_work,
billing_type,
sales_org,
distr_channel,
division,
product_sold,
product_sold_group,
customer_group,
country,
industry,
sales_district,
bill_to_party,
ship_to_party,
group_key,
dummy_function_in_length_1,
dummy,
company_code_1,
ex_rv_a_c_in_cl,
fm_area,
funds_center,
funded_program,
fund,
grants,
budget_period,
partner_fund,
partner_grant,
par_budper,
budget_account,
budget_account_company_code,
budget_consumption_date,
cc_fiscal_period_for_budget_co,
cc_fiscal_year_for_budget_cons,
budget_relevant_indicator,
budget_consumption_type,
budget_consumption_amount_type,
joint_venture,
equity_group,
recovery_indic,
partner,
billing_ind,
equity_type,
prod_month,
billing_month,
proc_oper_month,
cutback_run_id_jva,
jva_activity,
partner_venture_jva,
partner_eg_jva,
sender_rec_ind,
cutback_account_jva,
cutback_co_jva,
business_entity,
building,
land,
rental_object,
contract,
serv_charge_key,
settlement_unit,
reference_date,
ptnr_bus_entity,
ptnr_building,
partner_land,
ptnr_rent_unit,
ptnr_contract_no,
ptnr_srv_chrg_key,
ptnr_sett_unit,
ptnr_reference_date,
accrual_object_type,
accrual_object,
accrual_subobject,
accrual_item_type,
accrual_value_date,
type_of_fin_val_obj,
fin_valuation_object,
fin_val_sub_object,
due_on,
risk_class,
dummy_1,
dummy_2,
follow_up_action,
sdm_versioning,
migr_source,
migr_line_item_id,
data_filter_value_for_data_agi,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.ledger,
src.company_code,
src.fiscal_year,
src.document_number,
src.line_item,
src.g_l_fiscal_year,
src.ledger_spec_docno,
src.record_type,
src.transactn_type,
src.activity_type,
src.bus_transaction,
src.bustrans_type,
src.ref_procedure,
src.logical_system,
src.refer_org_unit,
src.reference_doc,
src.ref_doc_item,
src.ref_item_group,
src.sub_transaction,
src.is_reversing,
src.is_reversed,
src.is_true_reversal,
src.reversereftrans,
src.reversal_org,
src.reversal_ref,
src.reversal_sub_trans,
src.is_settling,
src.is_settled,
src.precreftransact,
src.precreflogsys,
src.precreforgunit,
src.precrefdocument,
src.prec_ref_doc_item,
src.prec_sub_transactn,
src.multprecrefid,
src.precje_cocode,
src.precje_year,
src.precje_docno,
src.precje_lineitem,
src.secondary_entry,
src.closing_run_uuid,
src.scereftransact,
src.srcreflogsys,
src.srcreforgunit,
src.srcrefdocument,
src.src_ref_doc_item,
src.srcrefdoc_sub_item,
src.commitment,
src.obsoleteness_reason,
src.bal_transac_crcy,
src.transaction_currency,
src.companycode_currency,
src.global_currency,
src.free_defined_crcy_1,
src.free_defined_crcy_2,
src.free_defined_crcy_3,
src.free_defined_crcy_4,
src.free_defined_crcy_5,
src.free_defined_crcy_6,
src.free_defined_crcy_7,
src.free_defined_crcy_8,
src.co_object_currency,
src.base_unit,
src.valuation_uom,
src.reference_uom,
src.inventory_uom,
src.add_unit_meas_1,
src.add_unit_meas_2,
src.add_unit_meas_3,
src.uom_covalqty,
src.account_number,
src.cost_center,
src.profit_center,
src.functional_area,
src.business_area,
src.co_area,
src.segment,
src.sender_cost_ctr,
src.partner_pc,
src.partner_farea,
src.trdg_part_ba,
src.trading_partner,
src.partner_segment,
src.amnt_in_bal_tr_crcy,
src.amnt_in_trans_crcy,
src.gv_amnt_in_transcrcy,
src.pcv_amnt_in_trnscrcy,
src.amnt_in_compcd_crcy,
src.amnt_in_gl_crcy,
src.amount_in_currency_1,
src.amount_in_currency_2,
src.amount_in_currency_3,
src.amount_in_currency_4,
src.amount_in_currency_5,
src.amount_in_currency_6,
src.amount_in_currency_7,
src.amount_in_currency_8,
src.fixed_amnt_in_gc,
src.gv_fixd_amt_glb_crcy,
src.pcv_fixdamt_glb_crcy,
src.price_variance,
src.gval_tprice_varc_gc,
src.pcval_tprice_varc_gc,
src.price_var_fxd,
src.gval_fprice_varc_gc,
src.pcval_fprice_varc_gc,
src.amount_in_obj_crcy,
src.altvalue_lc,
src.altvalue_gc,
src.altvalue_in_crcy_1,
src.altvalue_in_crcy_2,
src.altvalue_in_crcy_3,
src.altvalue_in_crcy_4,
src.altvalue_in_crcy_5,
src.altvalue_in_crcy_6,
src.altvalue_in_crcy_7,
src.altvalue_in_crcy_8,
src.extvalue_lc,
src.extvalue_gc,
src.extvalue_in_crcy_1,
src.extvalue_in_crcy_2,
src.extvalue_in_crcy_3,
src.extvalue_in_crcy_4,
src.extvalue_in_crcy_5,
src.extvalue_in_crcy_6,
src.extvalue_in_crcy_7,
src.extvalue_in_crcy_8,
src.value_sp_lcrcy,
src.quantity,
src.fixed_quantity,
src.val_quantity,
src.fixed_val_qty,
src.ref_quantity,
src.add_quantity_1,
src.add_quantity_2,
src.add_quantity_3,
src.covalqty,
src.covalqtyfix,
src.invvalue_lcrcy,
src.invvalue_gcrcy,
src.invvalue_acrcy,
src.invvalue_4crcy,
src.altinvvalue_lc,
src.altinvvalue_gc,
src.altinvvalue_ac,
src.altinvvalue_4c,
src.map_lcrcy,
src.map_gcrcy,
src.map_acrcy,
src.map_4crcy,
src.stdprice_lcrcy,
src.stdprice_gcrcy,
src.stdprice_acrcy,
src.stdprice_4crcy,
src.invval_sp_lcrcy,
src.inv_quantity,
src.debit_credit,
src.posting_period,
src.fi_year_variant,
src.period_year,
src.posting_date,
src.document_date,
src.document_type,
src.line_item_1,
src.assignment_number,
src.posting_key,
src.document_status,
src.item_category,
src.transaction_key,
src.slalineitemtype,
src.changed,
src.user_name,
src.time_stamp,
src.elimination_prctr,
src.origin_object,
src.g_l_account_type,
src.chart_of_accts,
src.altern_account,
src.cntry_chrt_acts,
src.invoice_ref,
src.fiscal_year_1,
src.line_item_2,
src.follow_on_document_type,
src.po_category,
src.purchasing_doc,
src.item,
src.account_assgmt_no,
src.text,
src.sales_order,
src.sales_ord_item,
src.material,
src.plant,
src.vendor,
src.customer,
src.serv_rendered,
src.condition_contract,
src.translation_dte,
src.account_type,
src.special_g_l_ind,
src.tax_code,
src.house_bank,
src.account_id,
src.oi_management,
src.clearing,
src.clrng_doc,
src.clrg_fiscal_yr,
src.depreciat_area,
src.asset,
src.sub_number,
src.asset_val_date,
src.ast_transaction_type,
src.trans_type_cat,
src.deprec_period,
src.group_asset,
src.subnumber,
src.distr_rule_grp,
src.asset_class,
src.account_determ,
src.partner_asset,
src.partner_sub_no,
src.orig_val_dat,
src.compl_retiremnt,
src.percentage_rate,
src.man_proport_values,
src.cost_estimateno,
src.price_control,
src.price_determ,
src.valuation,
src.vendor_stk_val,
src.special_stock,
src.valu_timestamp,
src.sd_doc_of_inv,
src.sd_item_of_inv,
src.wbselem_of_inv,
src.wbselem_of_inv_1,
src.vendor_of_inv,
src.valuation_type,
src.valuation_area,
src.price_unit_lc,
src.price_unit_gc,
src.price_unit_ac,
src.price_unit_4c,
src.orig_proc_cat,
src.category,
src.prcrmntalt_proc,
src.prod_proc_no,
src.period_type,
src.item_1,
src.inv_movement_categ,
src.sender_cocode,
src.sender_gl_account,
src.sender_acct_assgmt,
src.sndr_acctassgmt_type,
src.object_number,
src.co_subkey,
src.origin_group,
src.partner_object,
src.parobj_source,
src.source_object,
src.dr_cr_ind_co,
src.dr_cr_origin,
src.debit_type,
src.qty_is_incomplete,
src.offsetting_acct,
src.offst_acct_type,
src.completion_ind,
src.personnel_no,
src.profit_segment,
src.paobj_is_co_relevant,
src.object_class,
src.logical_system_1,
src.partner_cocode,
src.partnerobjclass,
src.logical_system_2,
src.val_strategy,
src.origin_object_1,
src.origin_order,
src.origcctr,
src.origact,
src.sce_bproc,
src.origin_profit_center,
src.account_assignment,
src.object_type,
src.activity_type_1,
src.order_number,
src.order_category,
src.wbs_element,
src.wbs_element_1,
src.project_def,
src.project_def_1,
src.network,
src.netwk_activity,
src.business_proc,
src.cost_object,
src.acctindicator,
src.resource,
src.notification,
src.service_doc_type,
src.service_document,
src.service_doc_item,
src.serv_contract_type,
src.service_contract,
src.srv_contract_item,
src.operating_concern,
src.part_acct_assgmt,
src.prt_object_type,
src.paractvy,
src.partner_order,
src.prtnr_ord_cat,
src.partner_wbs_element,
src.partner_wbs_element_1,
src.partner_project_def,
src.part_proj_def,
src.partner_salord,
src.part_slsord_item,
src.partnerprf_seg,
src.part_proj_network,
src.part_proj_ntwk_acty,
src.part_bus_process,
src.partner_cost_object,
src.par_service_doctype,
src.partner_service_doc,
src.par_service_docitem,
src.stat_acctass_type_1,
src.stat_acctass_type_2,
src.stat_acctass_type_3,
src.item_2,
src.document_number_1,
src.posting_row,
src.co_postingrow_1,
src.co_postingrow_2,
src.co_postingrow_5,
src.co_postingrow_6,
src.co_postingrow_7,
src.posting_row_1,
src.refpostrow_1,
src.refpostrow_2,
src.refpostrow_5,
src.refpostrow_6,
src.refpostrow_7,
src.overtime_category,
src.work_item_id,
src.object_id,
src.activity,
src.order_item_no,
src.suboperation,
src.equipment,
src.functional_loc,
src.assembly,
src.maintactivtype,
src.orderplanind,
src.prioritytype,
src.priority,
src.superior_order,
src.material_group,
src.planned_parts_work,
src.billing_type,
src.sales_org,
src.distr_channel,
src.division,
src.product_sold,
src.product_sold_group,
src.customer_group,
src.country,
src.industry,
src.sales_district,
src.bill_to_party,
src.ship_to_party,
src.group_key,
src.dummy_function_in_length_1,
src.dummy,
src.company_code_1,
src.ex_rv_a_c_in_cl,
src.fm_area,
src.funds_center,
src.funded_program,
src.fund,
src.grants,
src.budget_period,
src.partner_fund,
src.partner_grant,
src.par_budper,
src.budget_account,
src.budget_account_company_code,
src.budget_consumption_date,
src.cc_fiscal_period_for_budget_co,
src.cc_fiscal_year_for_budget_cons,
src.budget_relevant_indicator,
src.budget_consumption_type,
src.budget_consumption_amount_type,
src.joint_venture,
src.equity_group,
src.recovery_indic,
src.partner,
src.billing_ind,
src.equity_type,
src.prod_month,
src.billing_month,
src.proc_oper_month,
src.cutback_run_id_jva,
src.jva_activity,
src.partner_venture_jva,
src.partner_eg_jva,
src.sender_rec_ind,
src.cutback_account_jva,
src.cutback_co_jva,
src.business_entity,
src.building,
src.land,
src.rental_object,
src.contract,
src.serv_charge_key,
src.settlement_unit,
src.reference_date,
src.ptnr_bus_entity,
src.ptnr_building,
src.partner_land,
src.ptnr_rent_unit,
src.ptnr_contract_no,
src.ptnr_srv_chrg_key,
src.ptnr_sett_unit,
src.ptnr_reference_date,
src.accrual_object_type,
src.accrual_object,
src.accrual_subobject,
src.accrual_item_type,
src.accrual_value_date,
src.type_of_fin_val_obj,
src.fin_valuation_object,
src.fin_val_sub_object,
src.due_on,
src.risk_class,
src.dummy_1,
src.dummy_2,
src.follow_up_action,
src.sdm_versioning,
src.migr_source,
src.migr_line_item_id,
src.data_filter_value_for_data_agi,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'universal_journal_item' as table_name
    		,'acdoca' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'universal_journal_item') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'universal_journal_item') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.universal_journal_item`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.universal_journal_item` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'universal_journal_item'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.universal_journal_item`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    