MERGE INTO `sap-adapter.slt_staging.accounting_document_header_detail` tgt
USING (
WITH bkpf as
(select MANDT as client,
BUKRS as company_code,
BELNR as document_number,
GJAHR as fiscal_year,
BLART as document_type,
BLDAT as document_date,
BUDAT as posting_date,
MONAT as period,
CPUDT as entered_on,
CPUTM as entered_at,
AEDAT as changed_on,
UPDDT as last_update,
WWERT as translation_dte,
USNAM as user_name,
TCODE as transaction_code,
BVORG as cross_cc_number,
XBLNR as reference,
DBBLG as rec_entry_doc,
DBBLG_GJAHR as recentry_fyear,
DBBLG_BUKRS as recentry_cocode,
STBLG as reversed_with,
STJAH as year,
BKTXT as doc_header_text,
WAERS as currency,
KURSF as exchange_rate,
KZWRS as group_currency,
KZKRS as group_fx_rate,
BSTAT as document_status,
XNETB as net_document_type,
FRATH as unpl_del_costs,
XRUEB as back_posting,
GLVOR as bus_transaction,
GRPID as session_name,
DOKID as document_name_in_the_archive_s,
ARCID as extract_id,
IBLAR as internal_document_type_for_doc,
AWTYP as ref_procedure,
AWKEY as object_key,
FIKRS as fm_area,
HWAER as local_currency,
HWAE2 as local_curr_2,
HWAE3 as local_curr_3,
KURS2 as exchange_rate_2,
KURS3 as exchange_rate_3,
BASW2 as source_currency,
BASW3 as source_currency_1,
UMRD2 as trans_date,
UMRD3 as trans_date_1,
XSTOV as reversal_flag,
STODT as reversal_date,
XMWST as calculate_tax,
CURT2 as lc2_crcy_type,
CURT3 as lc3_crcy_type,
KUTY2 as exch_rate_type,
KUTY3 as exch_rate_type_1,
XSNET as net_entry,
AUSBK as source_cocode,
XUSVR as tax_details,
DUEFL as data_transfer_status,
AWSYS as logical_system,
TXKRS as rate_for_taxes,
CTXKRS as tax_rate_lc,
LOTKZ as request_number,
XWVOF as boe_bf_due_date,
STGRD as reversal_reason,
PPNAM as parked_by,
PPDAT as parked_on,
PPTME as parked_at,
PPTCOD as parked_with,
BRNCH as branch_number,
NUMPG as number_of_pages,
ADISC as discount_document,
XREF1_HD as ref_key_head_1,
XREF2_HD as ref_key_head_2,
XREVERSAL as reversal_ind,
REINDAT as inv_recpt_date,
RLDNR as ledger,
LDGRP as ledger_group,
PROPMANO as mandate,
XBLNR_ALT as alt_refer,
VATDATE as tax_reporting_date,
DOCCAT as doc_type,
XSPLIT as split_posting,
CASH_ALLOC as cash_flow_rel_doc,
FOLLOW_ON as follow_on,
XREORG as reorganized,
SUBSET as subset,
KURST as exch_rate_type_2,
KURSX as md_exchange_rate,
KUR2X as md_exch_rate_2,
KUR3X as md_exch_rate_3,
XMCA as doc_from_mca,
RESUBMISSION as resubmission_date,
LOGSYSTEM_SENDER as senderlogsystem,
BUKRS_SENDER as sender_cocode,
BELNR_SENDER as sender_doc_no,
GJAHR_SENDER as sender_fiscalyr,
INTSUBID as subid_for_awkey,
AWORG_REV as reversal_org,
AWREF_REV as reversal_ref,
XREVERSING as reversal_doc,
XREVERSED as reversed,
GLBTGRP as gl_bus_trans_grp,
CO_VRGNG as bus_transaction_1,
CO_REFBT as refdoctype,
CO_ALEBN as ale_org_docnr,
CO_VALDT as valuation_date,
CO_BELNR_SENDER as send_co_doc_no,
KOKRS_SENDER as sender_co_area,
ACC_PRINCIPLE as accounting_principle,
_DATAAGING as data_filter_value_for_data_agi,
TRAVA_PN as transfer_var,
LDGRPSPEC_PN as ldgrp_specific,
AFABESPEC_PN as area_specific,
XSECONDARY as secondary_entry,
REPROCESSING_STATUS_CODE as reproc_status_code,
TRR_PARTIAL_IND as partial_processing,
ITEM_REMOVAL_STATUS as item_removal_status,
PENRC as reason_f_delay,
GLO_REF1_HD as country_specific_reference_1_i,
GLO_DAT1_HD as country_specific_date_1_in_the,
GLO_REF2_HD as country_specific_reference_2_i,
GLO_DAT2_HD as country_specific_date_2_in_the,
GLO_REF3_HD as country_specific_reference_3_i,
GLO_DAT3_HD as country_specific_date_3_in_the,
GLO_REF4_HD as country_specific_reference_4_i,
GLO_DAT4_HD as country_specific_date_4_in_the,
GLO_REF5_HD as country_specific_reference_5_i,
GLO_DAT5_HD as country_specific_date_5_in_the,
GLO_BP1_HD as country_specific_business_part,
GLO_BP2_HD as country_specific_business_pa_1,
EV_POSTNG_CTRL as cntrentryview,
ANXTYPE as invoice_type,
ANXAMNT as annexation_amount,
ANXPERC as annexation_percen,
ZVAT_INDC as v_a_t_indicator,
__SAPF15__STATUS as document_status_1,
PSOTY as request_cat,
PSOAK as reason,
PSOKS as region,
PSOSG as reversal_reason_1,
PSOFN as file_number,
INTFORM as int_formula,
INTDATE as interest_calc_date,
PSOBT as posting_day,
PSOZL as actual,
PSODT as changed_on_1,
PSOTM as changed_at,
FM_UMART as transfer_type,
CCINS as card_type,
CCNUM as card_no,
SSBLK as sampling_block,
BATCH as lot_no,
SNAME as user_name_1,
SAMPLED as sampled_invoice,
EXCLUDE_FLAG as ppa_exclude,
BLIND as bl_indicator,
OFFSET_STATUS as offset_status,
OFFSET_REFER_DAT as date_referred,
KNUMV as doc_condition,
BLO as document_block,
CNT as contract_no,
PYBASTYP as payt_against,
PYBASNO as payt_ground_no,
PYBASDAT as payt_ground_date,
PYIBAN as iban,
INWARDNO_HD as incg_doc_nmbr,
INWARDDT_HD as incg_doc_date,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct bkpf.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.bkpf` as bkpf
where bkpf._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'accounting_document_header_detail'),0))
select client as client_key,
company_code as company_code_key,
document_number as document_number_key,
fiscal_year as fiscal_year_key,
*
From  bkpf
UNION ALL
select null as client_key,
null as company_code_key,
null as document_number_key,
null as fiscal_year_key,
bkpf.*
From bkpf as bkpf
INNER JOIN `sap-adapter.slt_staging.accounting_document_header_detail` as uji
ON bkpf.client = uji.client
AND bkpf.company_code = uji.company_code
AND bkpf.document_number = uji.document_number
AND bkpf.fiscal_year = uji.fiscal_year
AND bkpf.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.company_code_key = tgt.company_code
AND src.document_number_key = tgt.document_number
AND src.fiscal_year_key = tgt.fiscal_year
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
company_code,
document_number,
fiscal_year,
document_type,
document_date,
posting_date,
period,
entered_on,
entered_at,
changed_on,
last_update,
translation_dte,
user_name,
transaction_code,
cross_cc_number,
reference,
rec_entry_doc,
recentry_fyear,
recentry_cocode,
reversed_with,
year,
doc_header_text,
currency,
exchange_rate,
group_currency,
group_fx_rate,
document_status,
net_document_type,
unpl_del_costs,
back_posting,
bus_transaction,
session_name,
document_name_in_the_archive_s,
extract_id,
internal_document_type_for_doc,
ref_procedure,
object_key,
fm_area,
local_currency,
local_curr_2,
local_curr_3,
exchange_rate_2,
exchange_rate_3,
source_currency,
source_currency_1,
trans_date,
trans_date_1,
reversal_flag,
reversal_date,
calculate_tax,
lc2_crcy_type,
lc3_crcy_type,
exch_rate_type,
exch_rate_type_1,
net_entry,
source_cocode,
tax_details,
data_transfer_status,
logical_system,
rate_for_taxes,
tax_rate_lc,
request_number,
boe_bf_due_date,
reversal_reason,
parked_by,
parked_on,
parked_at,
parked_with,
branch_number,
number_of_pages,
discount_document,
ref_key_head_1,
ref_key_head_2,
reversal_ind,
inv_recpt_date,
ledger,
ledger_group,
mandate,
alt_refer,
tax_reporting_date,
doc_type,
split_posting,
cash_flow_rel_doc,
follow_on,
reorganized,
subset,
exch_rate_type_2,
md_exchange_rate,
md_exch_rate_2,
md_exch_rate_3,
doc_from_mca,
resubmission_date,
senderlogsystem,
sender_cocode,
sender_doc_no,
sender_fiscalyr,
subid_for_awkey,
reversal_org,
reversal_ref,
reversal_doc,
reversed,
gl_bus_trans_grp,
bus_transaction_1,
refdoctype,
ale_org_docnr,
valuation_date,
send_co_doc_no,
sender_co_area,
accounting_principle,
data_filter_value_for_data_agi,
transfer_var,
ldgrp_specific,
area_specific,
secondary_entry,
reproc_status_code,
partial_processing,
item_removal_status,
reason_f_delay,
country_specific_reference_1_i,
country_specific_date_1_in_the,
country_specific_reference_2_i,
country_specific_date_2_in_the,
country_specific_reference_3_i,
country_specific_date_3_in_the,
country_specific_reference_4_i,
country_specific_date_4_in_the,
country_specific_reference_5_i,
country_specific_date_5_in_the,
country_specific_business_part,
country_specific_business_pa_1,
cntrentryview,
invoice_type,
annexation_amount,
annexation_percen,
v_a_t_indicator,
document_status_1,
request_cat,
reason,
region,
reversal_reason_1,
file_number,
int_formula,
interest_calc_date,
posting_day,
actual,
changed_on_1,
changed_at,
transfer_type,
card_type,
card_no,
sampling_block,
lot_no,
user_name_1,
sampled_invoice,
ppa_exclude,
bl_indicator,
offset_status,
date_referred,
doc_condition,
document_block,
contract_no,
payt_against,
payt_ground_no,
payt_ground_date,
iban,
incg_doc_nmbr,
incg_doc_date,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.company_code,
src.document_number,
src.fiscal_year,
src.document_type,
src.document_date,
src.posting_date,
src.period,
src.entered_on,
src.entered_at,
src.changed_on,
src.last_update,
src.translation_dte,
src.user_name,
src.transaction_code,
src.cross_cc_number,
src.reference,
src.rec_entry_doc,
src.recentry_fyear,
src.recentry_cocode,
src.reversed_with,
src.year,
src.doc_header_text,
src.currency,
src.exchange_rate,
src.group_currency,
src.group_fx_rate,
src.document_status,
src.net_document_type,
src.unpl_del_costs,
src.back_posting,
src.bus_transaction,
src.session_name,
src.document_name_in_the_archive_s,
src.extract_id,
src.internal_document_type_for_doc,
src.ref_procedure,
src.object_key,
src.fm_area,
src.local_currency,
src.local_curr_2,
src.local_curr_3,
src.exchange_rate_2,
src.exchange_rate_3,
src.source_currency,
src.source_currency_1,
src.trans_date,
src.trans_date_1,
src.reversal_flag,
src.reversal_date,
src.calculate_tax,
src.lc2_crcy_type,
src.lc3_crcy_type,
src.exch_rate_type,
src.exch_rate_type_1,
src.net_entry,
src.source_cocode,
src.tax_details,
src.data_transfer_status,
src.logical_system,
src.rate_for_taxes,
src.tax_rate_lc,
src.request_number,
src.boe_bf_due_date,
src.reversal_reason,
src.parked_by,
src.parked_on,
src.parked_at,
src.parked_with,
src.branch_number,
src.number_of_pages,
src.discount_document,
src.ref_key_head_1,
src.ref_key_head_2,
src.reversal_ind,
src.inv_recpt_date,
src.ledger,
src.ledger_group,
src.mandate,
src.alt_refer,
src.tax_reporting_date,
src.doc_type,
src.split_posting,
src.cash_flow_rel_doc,
src.follow_on,
src.reorganized,
src.subset,
src.exch_rate_type_2,
src.md_exchange_rate,
src.md_exch_rate_2,
src.md_exch_rate_3,
src.doc_from_mca,
src.resubmission_date,
src.senderlogsystem,
src.sender_cocode,
src.sender_doc_no,
src.sender_fiscalyr,
src.subid_for_awkey,
src.reversal_org,
src.reversal_ref,
src.reversal_doc,
src.reversed,
src.gl_bus_trans_grp,
src.bus_transaction_1,
src.refdoctype,
src.ale_org_docnr,
src.valuation_date,
src.send_co_doc_no,
src.sender_co_area,
src.accounting_principle,
src.data_filter_value_for_data_agi,
src.transfer_var,
src.ldgrp_specific,
src.area_specific,
src.secondary_entry,
src.reproc_status_code,
src.partial_processing,
src.item_removal_status,
src.reason_f_delay,
src.country_specific_reference_1_i,
src.country_specific_date_1_in_the,
src.country_specific_reference_2_i,
src.country_specific_date_2_in_the,
src.country_specific_reference_3_i,
src.country_specific_date_3_in_the,
src.country_specific_reference_4_i,
src.country_specific_date_4_in_the,
src.country_specific_reference_5_i,
src.country_specific_date_5_in_the,
src.country_specific_business_part,
src.country_specific_business_pa_1,
src.cntrentryview,
src.invoice_type,
src.annexation_amount,
src.annexation_percen,
src.v_a_t_indicator,
src.document_status_1,
src.request_cat,
src.reason,
src.region,
src.reversal_reason_1,
src.file_number,
src.int_formula,
src.interest_calc_date,
src.posting_day,
src.actual,
src.changed_on_1,
src.changed_at,
src.transfer_type,
src.card_type,
src.card_no,
src.sampling_block,
src.lot_no,
src.user_name_1,
src.sampled_invoice,
src.ppa_exclude,
src.bl_indicator,
src.offset_status,
src.date_referred,
src.doc_condition,
src.document_block,
src.contract_no,
src.payt_against,
src.payt_ground_no,
src.payt_ground_date,
src.iban,
src.incg_doc_nmbr,
src.incg_doc_date,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'accounting_document_header_detail' as table_name
    		,'bkpf' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'accounting_document_header_detail') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'accounting_document_header_detail') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.accounting_document_header_detail`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.accounting_document_header_detail` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'accounting_document_header_detail'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.accounting_document_header_detail`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    