MERGE INTO `sap-adapter.slt_staging.account_document_customer_close_item` tgt
USING (
WITH bsad as
(select MANDT as client,
BUKRS as company_code,
KUNNR as customer,
UMSKS as transact_type,
UMSKZ as special_g_l_ind,
AUGDT as clearing,
AUGBL as clrng_doc,
ZUONR as assignment_number,
GJAHR as fiscal_year,
BELNR as document_number,
BUZEI as line_item,
BUDAT as posting_date,
BLDAT as document_date,
CPUDT as entered_on,
WAERS as currency,
XBLNR as reference,
BLART as document_type,
MONAT as period,
BSCHL as posting_key,
ZUMSK as trg_sp_g_l_ind,
SHKZG as debit_credit,
GSBER as business_area,
MWSKZ as tax_code,
TXDAT_FROM as tax_rate_valid_from,
DMBTR as amount_in_lc,
WRBTR as amount,
MWSTS as lc_tax,
WMWST as tax_amount,
BDIFF as valuation_diff,
BDIF2 as valuation_diff_2,
SGTXT as text,
PROJN as not_in_use,
AUFNR as order_number,
ANLN1 as asset,
ANLN2 as sub_number,
SAKNR as g_l_account,
HKONT as g_l_acct,
FKONT as fin_budget,
FILKD as branch,
ZFBDT as baseline_date,
ZTERM as payt_terms,
ZBD1T as days_1,
ZBD2T as days_2,
ZBD3T as days_net,
ZBD1P as disc_percent_1,
ZBD2P as disc_percent_2,
SKFBT as cd_base,
SKNTO as discount_amt,
WSKTO as cd_amount,
ZLSCH as pymt_meth,
ZLSPR as pmnt_block,
ZBFIX as fixed,
HBKID as house_bank,
BVTYP as part_bank_type,
REBZG as invoice_ref,
REBZJ as fiscal_year_1,
REBZZ as line_item_1,
SAMNR as collect_inv,
ANFBN as boe_payt_req,
ANFBJ as fiscal_year_of_the_bill_of_exc,
ANFBU as company_code_1,
ANFAE as return_bef,
MANSP as dunn_block,
MSCHL as dunning_key,
MADAT as last_dunned,
MANST as dunning_level,
MABER as dunning_area,
XNETB as net_document_type,
XANET as indicator_down_payment_in_net,
XCPDD as individ_set,
XINVE as invest_id,
XZAHL as payt_tran,
MWSK1 as tax_code_1,
TXDAT_FROM1 as tax_rate_valid_from_1,
DMBT1 as amount_1,
WRBT1 as amount_2,
MWSK2 as tax_code_2,
TXDAT_FROM2 as tax_rate_valid_from_2,
DMBT2 as amount_3,
WRBT2 as amount_4,
MWSK3 as tax_code_3,
TXDAT_FROM3 as tax_rate_valid_from_3,
DMBT3 as amount_5,
WRBT3 as amount_6,
BSTAT as document_status,
VBUND as trading_partner,
VBELN as billing_doc,
REBZT as follow_on_document_type,
INFAE as inv_due_date,
STCEG as vat_reg_no,
EGBLD as dest_country,
EGLLD as supplying_cntry,
RSTGR as reason_code,
XNOZA as indicator_account_is_not_coun,
VERTT as contract_type,
VERTN as contract_number,
VBEWA as flow_type,
WVERW as usage,
PROJK as wbs_element,
FIPOS as commitment_item,
NPLNR as network,
AUFPL as plan_no_f_oper,
APLZL as counter,
XEGDR as eu_triang_deal,
DMBE2 as lc2_amount,
DMBE3 as lc3_amount,
DMB21 as amount_7,
DMB22 as amount_8,
DMB23 as amount_9,
DMB31 as amount_10,
DMB32 as amount_11,
DMB33 as amount_12,
BDIF3 as valuation_diff_3,
XRAGL as indicator_clearing_was_revers,
UZAWE as pmt_meth_supl,
XSTOV as reversal_flag,
MWST2 as lc2_tax,
MWST3 as lc3_tax,
SKNT2 as cd_amt_lc2,
SKNT3 as cd_amt_lc3,
XREF1 as reference_key_1,
XREF2 as reference_key_2,
XARCH as archive,
PSWSL as g_l_currency,
PSWBT as g_l_amount,
LZBKZ as scb_ind,
LANDL as suppl_cntry,
IMKEY as real_estate_key,
VBEL2 as sales_document,
VPOS2 as number,
POSN2 as item,
ETEN2 as schedule_line,
FISTL as funds_center,
GEBER as fund,
DABRZ as reference_date,
XNEGP as negative_postg,
KOSTL as cost_center,
RFZEI as payt_card_item,
KKBER as cred_contr_area,
EMPFB as payer,
PRCTR as profit_center,
XREF3 as reference_key_3,
QSSKZ as wtax_code,
ZINKZ as interest_block,
DTWS1 as instruct_key_1,
DTWS2 as instruct_key_2,
DTWS3 as instruct_key_3,
DTWS4 as instruct_key_4,
XPYPR as payment_sent,
KIDNO as payment_ref,
ABSBT as hedged_amount,
CCBTC as settlement,
PYCUR as payment_cur,
PYAMT as pmnt_c_amnt,
BUPLA as business_place,
SECCO as section_code,
CESSION_KZ as ar_pledging_ind,
PPDIFF as diff_realized,
PPDIF2 as diff_realized_1,
PPDIF3 as diff_realized_2,
KBLNR as earmarked_funds,
KBLPOS as document_item,
GRANT_NBR as grants,
GMVKZ as execution,
SRTYPE as addit_receivab,
LOTKZ as request_number,
FKBER as functional_area,
INTRENO as re_code,
PPRCT as partner_pc,
BUZID as line_item_id,
AUGGJ as clrg_fiscal_yr,
HKTID as account_id,
BUDGET_PD as budget_period,
PAYS_PROV as psp,
PAYS_TRAN as psp_payment_ref,
MNDID as mandate_ref,
_DATAAGING as data_filter_value_for_data_agi,
KONTT as kontt,
KONTL as kontl,
UEBGDAT as uebgdat,
VNAME as joint_venture,
EGRUP as equity_group,
BTYPE as billing_ind,
PROPMANO as mandate,
GKONT as offsetting_acct,
GKART as offst_acct_type,
GHKON as g_l_offsetting_acct,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct bsad.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.bsad` as bsad
where bsad._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'account_document_customer_close_item'),0))
select client as client_key,
company_code as company_code_key,
customer as customer_key,
transact_type as transact_type_key,
special_g_l_ind as special_g_l_ind_key,
clearing as clearing_key,
clrng_doc as clrng_doc_key,
assignment_number as assignment_number_key,
fiscal_year as fiscal_year_key,
document_number as document_number_key,
line_item as line_item_key,
*
From  bsad
UNION ALL
select null as client_key,
null as company_code_key,
null as customer_key,
null as transact_type_key,
null as special_g_l_ind_key,
null as clearing_key,
null as clrng_doc_key,
null as assignment_number_key,
null as fiscal_year_key,
null as document_number_key,
null as line_item_key,
bsad.*
From bsad as bsad
INNER JOIN `sap-adapter.slt_staging.account_document_customer_close_item` as uji
ON bsad.client = uji.client
AND bsad.company_code = uji.company_code
AND bsad.customer = uji.customer
AND bsad.transact_type = uji.transact_type
AND bsad.special_g_l_ind = uji.special_g_l_ind
AND bsad.clearing = uji.clearing
AND bsad.clrng_doc = uji.clrng_doc
AND bsad.assignment_number = uji.assignment_number
AND bsad.fiscal_year = uji.fiscal_year
AND bsad.document_number = uji.document_number
AND bsad.line_item = uji.line_item
AND bsad.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.company_code_key = tgt.company_code
AND src.customer_key = tgt.customer
AND src.transact_type_key = tgt.transact_type
AND src.special_g_l_ind_key = tgt.special_g_l_ind
AND src.clearing_key = tgt.clearing
AND src.clrng_doc_key = tgt.clrng_doc
AND src.assignment_number_key = tgt.assignment_number
AND src.fiscal_year_key = tgt.fiscal_year
AND src.document_number_key = tgt.document_number
AND src.line_item_key = tgt.line_item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
company_code,
customer,
transact_type,
special_g_l_ind,
clearing,
clrng_doc,
assignment_number,
fiscal_year,
document_number,
line_item,
posting_date,
document_date,
entered_on,
currency,
reference,
document_type,
period,
posting_key,
trg_sp_g_l_ind,
debit_credit,
business_area,
tax_code,
tax_rate_valid_from,
amount_in_lc,
amount,
lc_tax,
tax_amount,
valuation_diff,
valuation_diff_2,
text,
not_in_use,
order_number,
asset,
sub_number,
g_l_account,
g_l_acct,
fin_budget,
branch,
baseline_date,
payt_terms,
days_1,
days_2,
days_net,
disc_percent_1,
disc_percent_2,
cd_base,
discount_amt,
cd_amount,
pymt_meth,
pmnt_block,
fixed,
house_bank,
part_bank_type,
invoice_ref,
fiscal_year_1,
line_item_1,
collect_inv,
boe_payt_req,
fiscal_year_of_the_bill_of_exc,
company_code_1,
return_bef,
dunn_block,
dunning_key,
last_dunned,
dunning_level,
dunning_area,
net_document_type,
indicator_down_payment_in_net,
individ_set,
invest_id,
payt_tran,
tax_code_1,
tax_rate_valid_from_1,
amount_1,
amount_2,
tax_code_2,
tax_rate_valid_from_2,
amount_3,
amount_4,
tax_code_3,
tax_rate_valid_from_3,
amount_5,
amount_6,
document_status,
trading_partner,
billing_doc,
follow_on_document_type,
inv_due_date,
vat_reg_no,
dest_country,
supplying_cntry,
reason_code,
indicator_account_is_not_coun,
contract_type,
contract_number,
flow_type,
usage,
wbs_element,
commitment_item,
network,
plan_no_f_oper,
counter,
eu_triang_deal,
lc2_amount,
lc3_amount,
amount_7,
amount_8,
amount_9,
amount_10,
amount_11,
amount_12,
valuation_diff_3,
indicator_clearing_was_revers,
pmt_meth_supl,
reversal_flag,
lc2_tax,
lc3_tax,
cd_amt_lc2,
cd_amt_lc3,
reference_key_1,
reference_key_2,
archive,
g_l_currency,
g_l_amount,
scb_ind,
suppl_cntry,
real_estate_key,
sales_document,
number,
item,
schedule_line,
funds_center,
fund,
reference_date,
negative_postg,
cost_center,
payt_card_item,
cred_contr_area,
payer,
profit_center,
reference_key_3,
wtax_code,
interest_block,
instruct_key_1,
instruct_key_2,
instruct_key_3,
instruct_key_4,
payment_sent,
payment_ref,
hedged_amount,
settlement,
payment_cur,
pmnt_c_amnt,
business_place,
section_code,
ar_pledging_ind,
diff_realized,
diff_realized_1,
diff_realized_2,
earmarked_funds,
document_item,
grants,
execution,
addit_receivab,
request_number,
functional_area,
re_code,
partner_pc,
line_item_id,
clrg_fiscal_yr,
account_id,
budget_period,
psp,
psp_payment_ref,
mandate_ref,
data_filter_value_for_data_agi,
kontt,
kontl,
uebgdat,
joint_venture,
equity_group,
billing_ind,
mandate,
offsetting_acct,
offst_acct_type,
g_l_offsetting_acct,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.company_code,
src.customer,
src.transact_type,
src.special_g_l_ind,
src.clearing,
src.clrng_doc,
src.assignment_number,
src.fiscal_year,
src.document_number,
src.line_item,
src.posting_date,
src.document_date,
src.entered_on,
src.currency,
src.reference,
src.document_type,
src.period,
src.posting_key,
src.trg_sp_g_l_ind,
src.debit_credit,
src.business_area,
src.tax_code,
src.tax_rate_valid_from,
src.amount_in_lc,
src.amount,
src.lc_tax,
src.tax_amount,
src.valuation_diff,
src.valuation_diff_2,
src.text,
src.not_in_use,
src.order_number,
src.asset,
src.sub_number,
src.g_l_account,
src.g_l_acct,
src.fin_budget,
src.branch,
src.baseline_date,
src.payt_terms,
src.days_1,
src.days_2,
src.days_net,
src.disc_percent_1,
src.disc_percent_2,
src.cd_base,
src.discount_amt,
src.cd_amount,
src.pymt_meth,
src.pmnt_block,
src.fixed,
src.house_bank,
src.part_bank_type,
src.invoice_ref,
src.fiscal_year_1,
src.line_item_1,
src.collect_inv,
src.boe_payt_req,
src.fiscal_year_of_the_bill_of_exc,
src.company_code_1,
src.return_bef,
src.dunn_block,
src.dunning_key,
src.last_dunned,
src.dunning_level,
src.dunning_area,
src.net_document_type,
src.indicator_down_payment_in_net,
src.individ_set,
src.invest_id,
src.payt_tran,
src.tax_code_1,
src.tax_rate_valid_from_1,
src.amount_1,
src.amount_2,
src.tax_code_2,
src.tax_rate_valid_from_2,
src.amount_3,
src.amount_4,
src.tax_code_3,
src.tax_rate_valid_from_3,
src.amount_5,
src.amount_6,
src.document_status,
src.trading_partner,
src.billing_doc,
src.follow_on_document_type,
src.inv_due_date,
src.vat_reg_no,
src.dest_country,
src.supplying_cntry,
src.reason_code,
src.indicator_account_is_not_coun,
src.contract_type,
src.contract_number,
src.flow_type,
src.usage,
src.wbs_element,
src.commitment_item,
src.network,
src.plan_no_f_oper,
src.counter,
src.eu_triang_deal,
src.lc2_amount,
src.lc3_amount,
src.amount_7,
src.amount_8,
src.amount_9,
src.amount_10,
src.amount_11,
src.amount_12,
src.valuation_diff_3,
src.indicator_clearing_was_revers,
src.pmt_meth_supl,
src.reversal_flag,
src.lc2_tax,
src.lc3_tax,
src.cd_amt_lc2,
src.cd_amt_lc3,
src.reference_key_1,
src.reference_key_2,
src.archive,
src.g_l_currency,
src.g_l_amount,
src.scb_ind,
src.suppl_cntry,
src.real_estate_key,
src.sales_document,
src.number,
src.item,
src.schedule_line,
src.funds_center,
src.fund,
src.reference_date,
src.negative_postg,
src.cost_center,
src.payt_card_item,
src.cred_contr_area,
src.payer,
src.profit_center,
src.reference_key_3,
src.wtax_code,
src.interest_block,
src.instruct_key_1,
src.instruct_key_2,
src.instruct_key_3,
src.instruct_key_4,
src.payment_sent,
src.payment_ref,
src.hedged_amount,
src.settlement,
src.payment_cur,
src.pmnt_c_amnt,
src.business_place,
src.section_code,
src.ar_pledging_ind,
src.diff_realized,
src.diff_realized_1,
src.diff_realized_2,
src.earmarked_funds,
src.document_item,
src.grants,
src.execution,
src.addit_receivab,
src.request_number,
src.functional_area,
src.re_code,
src.partner_pc,
src.line_item_id,
src.clrg_fiscal_yr,
src.account_id,
src.budget_period,
src.psp,
src.psp_payment_ref,
src.mandate_ref,
src.data_filter_value_for_data_agi,
src.kontt,
src.kontl,
src.uebgdat,
src.joint_venture,
src.equity_group,
src.billing_ind,
src.mandate,
src.offsetting_acct,
src.offst_acct_type,
src.g_l_offsetting_acct,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'account_document_customer_close_item' as table_name
    		,'bsad' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'account_document_customer_close_item') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'account_document_customer_close_item') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.account_document_customer_close_item`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.account_document_customer_close_item` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'account_document_customer_close_item'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.account_document_customer_close_item`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    