MERGE INTO `sap-adapter.slt_staging.company_codes` tgt
USING (
WITH t001 as
(select MANDT as client,
BUKRS as company_code,
BUTXT as company_name,
ORT01 as city,
LAND1 as country,
WAERS as currency,
SPRAS as language_key,
KTOPL as chart_of_accts,
WAABW as max_exch_rate_dev,
PERIV as fi_year_variant,
KOKFI as cocd_co_area,
RCOMP as company,
ADRNR as address,
STCEG as vat_reg_no,
FIKRS as fm_area,
XFMCO as project_cm_active,
XFMCB as cbm_active,
XFMCA as update_fm,
TXJCD as jurisdict_code,
FMHRDATE as fundsctr_in_hr,
XTEMPLT as template,
BUVAR as screen_variant,
FDBUK as cash_mgmnt_comp_code,
XFDIS as cm_activated,
XVALV as propose_value_date,
XSKFN as net_discount_base,
KKBER as cred_contr_area,
XMWSN as net_tax_base,
MREGL as sample_acct_rules,
XGSBE as business_area_fs,
XGJRV as propose_fiscal_year,
XKDFT as indicator_post_translations_f,
XPROD as productive,
XEINK as purchase_acct,
XJVAA as jva_active,
XVVWA as fin_asset_man_active,
XSLTA as indicator_no_exchange_rate_di,
XFDMM as update_mm_in_cmf,
XFDSD as update_sd_in_cmf,
XEXTB as external_cocode,
EBUKR as original_key,
KTOP2 as cntry_chrt_acts,
UMKRS as tax_group,
BUKRS_GLOB as global_cocde,
FSTVA as fld_stat_var,
OPVAR as pstg_per_var,
XCOVR as hedgereq_active,
TXKRS as tx_crcy_transl,
WFVAR as workflow_var,
XBBBF as inventory_mgmt,
XBBBE as po_sched_agmt,
XBBBA as requisition,
XBBKO as contract,
XSTDT as indicator_document_date_as_th,
MWSKV as input_tax_code,
MWSKA as output_tax_code,
IMPDA as imp_data_in_po,
XNEGP as indicator_negative_postings_p,
XKKBI as enter_control_area,
WT_NEWWT as extended_wtax_active,
PP_PDATE as parking_pst_date,
INFMT as method,
FSTVARE as fldstatusvar,
KOPIM as copying_ctrl_gr,
DKWEG as import_data_gr,
OFFSACCT as offsetting_acct,
BAPOVAR as ba_variant,
XCOS as cos_status,
XCESSION as accts_recble_pledg,
XSPLT as amount_split_to,
SURCCM as surcharges,
DTPROV as doc_type,
DTAMTC as doc_type_1,
DTTAXC as document_type,
DTTDSP as rc_doc_type,
DTAXR as def_tax_rule,
XVATDATE as tax_date,
PST_PER_VAR as manage_postg_period,
XBBSC as shopping_cart,
F_OBSOLETE as hide_entry,
FM_DERIVE_ACC as activ_aadrivton,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct t001.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.t001` as t001
where t001._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'company_codes'),0))
select client as client_key,
company_code as company_code_key,
*
From  t001
UNION ALL
select null as client_key,
null as company_code_key,
t001.*
From t001 as t001
INNER JOIN `sap-adapter.slt_staging.company_codes` as uji
ON t001.client = uji.client
AND t001.company_code = uji.company_code
AND t001.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.company_code_key = tgt.company_code
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
company_code,
company_name,
city,
country,
currency,
language_key,
chart_of_accts,
max_exch_rate_dev,
fi_year_variant,
cocd_co_area,
company,
address,
vat_reg_no,
fm_area,
project_cm_active,
cbm_active,
update_fm,
jurisdict_code,
fundsctr_in_hr,
template,
screen_variant,
cash_mgmnt_comp_code,
cm_activated,
propose_value_date,
net_discount_base,
cred_contr_area,
net_tax_base,
sample_acct_rules,
business_area_fs,
propose_fiscal_year,
indicator_post_translations_f,
productive,
purchase_acct,
jva_active,
fin_asset_man_active,
indicator_no_exchange_rate_di,
update_mm_in_cmf,
update_sd_in_cmf,
external_cocode,
original_key,
cntry_chrt_acts,
tax_group,
global_cocde,
fld_stat_var,
pstg_per_var,
hedgereq_active,
tx_crcy_transl,
workflow_var,
inventory_mgmt,
po_sched_agmt,
requisition,
contract,
indicator_document_date_as_th,
input_tax_code,
output_tax_code,
imp_data_in_po,
indicator_negative_postings_p,
enter_control_area,
extended_wtax_active,
parking_pst_date,
method,
fldstatusvar,
copying_ctrl_gr,
import_data_gr,
offsetting_acct,
ba_variant,
cos_status,
accts_recble_pledg,
amount_split_to,
surcharges,
doc_type,
doc_type_1,
document_type,
rc_doc_type,
def_tax_rule,
tax_date,
manage_postg_period,
shopping_cart,
hide_entry,
activ_aadrivton,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.company_code,
src.company_name,
src.city,
src.country,
src.currency,
src.language_key,
src.chart_of_accts,
src.max_exch_rate_dev,
src.fi_year_variant,
src.cocd_co_area,
src.company,
src.address,
src.vat_reg_no,
src.fm_area,
src.project_cm_active,
src.cbm_active,
src.update_fm,
src.jurisdict_code,
src.fundsctr_in_hr,
src.template,
src.screen_variant,
src.cash_mgmnt_comp_code,
src.cm_activated,
src.propose_value_date,
src.net_discount_base,
src.cred_contr_area,
src.net_tax_base,
src.sample_acct_rules,
src.business_area_fs,
src.propose_fiscal_year,
src.indicator_post_translations_f,
src.productive,
src.purchase_acct,
src.jva_active,
src.fin_asset_man_active,
src.indicator_no_exchange_rate_di,
src.update_mm_in_cmf,
src.update_sd_in_cmf,
src.external_cocode,
src.original_key,
src.cntry_chrt_acts,
src.tax_group,
src.global_cocde,
src.fld_stat_var,
src.pstg_per_var,
src.hedgereq_active,
src.tx_crcy_transl,
src.workflow_var,
src.inventory_mgmt,
src.po_sched_agmt,
src.requisition,
src.contract,
src.indicator_document_date_as_th,
src.input_tax_code,
src.output_tax_code,
src.imp_data_in_po,
src.indicator_negative_postings_p,
src.enter_control_area,
src.extended_wtax_active,
src.parking_pst_date,
src.method,
src.fldstatusvar,
src.copying_ctrl_gr,
src.import_data_gr,
src.offsetting_acct,
src.ba_variant,
src.cos_status,
src.accts_recble_pledg,
src.amount_split_to,
src.surcharges,
src.doc_type,
src.doc_type_1,
src.document_type,
src.rc_doc_type,
src.def_tax_rule,
src.tax_date,
src.manage_postg_period,
src.shopping_cart,
src.hide_entry,
src.activ_aadrivton,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'company_codes' as table_name
    		,'t001' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'company_codes') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'company_codes') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.company_codes`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.company_codes` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'company_codes'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.company_codes`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    