MERGE INTO `sap-adapter.slt_staging.sales_document_header_status` tgt
USING (
WITH vbuk as
(select MANDT as client,
VBELN as sales_document,
RFSTK as ref_status,
RFGSK as total_refstatus,
BESTK as confirmed,
LFSTK as delivery_status,
LFGSK as ovrl_delvry_sts,
WBSTK as ovrlgdsmvtstat,
FKSTK as billing_status,
FKSAK as bill_stat_order,
BUCHK as posting_status,
ABSTK as rejection_sts,
GBSTK as overall_status,
KOSTK as ovr_pick_status,
LVSTK as overallwmstatus,
UVALS as item_data,
UVVLS as item_deliv_data,
UVFAS as item_bill_data,
UVALL as header_data,
UVVLK as header_dlv_data,
UVFAK as header_bill_dat,
UVPRS as pricing,
VBTYP as document_cat,
VBOBJ as document_object,
AEDAT as changed_on,
FKIVK as totals_status,
RELIK as inv_list_status,
UVK01 as hdr_reserves_1,
UVK02 as hdr_reserves_2,
UVK03 as hdr_reserves_3,
UVK04 as hdr_reserves_4,
UVK05 as hdr_reserves_5,
UVS01 as total_reserves1,
UVS02 as totalreserves2,
UVS03 as total_reserves3,
UVS04 as total_reserves4,
UVS05 as total_reserves5,
PKSTK as packing_status,
CMPSA as static_check,
CMPSB as dynamic_check,
CMPSC as value,
CMPSD as termsofpayment,
CMPSE as customer_date,
CMPSF as open_items,
CMPSG as oldest_item,
CMPSH as max_dunn_level,
CMPSI as financial_doc,
CMPSJ as exptcreditinsur,
CMPSK as payment_card,
CMPSL as reserve,
CMPS0 as reserve_1,
CMPS1 as reserve_2,
CMPS2 as reserve_3,
CMGST as overallcredstat,
TRSTA as trns_plan_stat,
KOQUK as confirmation,
COSTA as confirm_status,
SAPRL as sap_release,
UVPAS as it_data_packag,
UVPIS as it_data_pck_putaway,
UVWAS as item_data_gm,
UVPAK as head_data_pckg,
UVPIK as head_data_pck_putawy,
UVWAK as head_data_gm,
UVGEK as head_data_dan_gds,
CMPSM as data_obsolete,
DCSTK as delay_status,
VESTK as hu_in_stock,
VLSTK as statdecntrlwhse,
RRSTA as rev_det_status,
BLOCK as indicator_document_preselecte,
FSSTK as ov_b_blk_stat,
LSSTK as dlv_blk_status,
SPSTG as overall_blk_st,
PDSTK as pod_status,
FMSTK as status_funds_mgmt,
MANEK as manual_completion,
SPE_TMPID as temporary_inbound_delivery,
HDALL as hold,
HDALS as phold,
CMPS_CM as sap_cred_mgmt,
CMPS_TE as crma_te_status,
VBTYP_EXT as cat_ext_obsol,
__SAPMP__LBASK as dtucsta,
FSH_AR_STAT_HDR as arun_status_at_hdr,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct vbuk.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.vbuk` as vbuk
where vbuk._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'sales_document_header_status'),0))
select client as client_key,
sales_document as sales_document_key,
*
From  vbuk
UNION ALL
select null as client_key,
null as sales_document_key,
vbuk.*
From vbuk as vbuk
INNER JOIN `sap-adapter.slt_staging.sales_document_header_status` as uji
ON vbuk.client = uji.client
AND vbuk.sales_document = uji.sales_document
AND vbuk.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.sales_document_key = tgt.sales_document
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
sales_document,
ref_status,
total_refstatus,
confirmed,
delivery_status,
ovrl_delvry_sts,
ovrlgdsmvtstat,
billing_status,
bill_stat_order,
posting_status,
rejection_sts,
overall_status,
ovr_pick_status,
overallwmstatus,
item_data,
item_deliv_data,
item_bill_data,
header_data,
header_dlv_data,
header_bill_dat,
pricing,
document_cat,
document_object,
changed_on,
totals_status,
inv_list_status,
hdr_reserves_1,
hdr_reserves_2,
hdr_reserves_3,
hdr_reserves_4,
hdr_reserves_5,
total_reserves1,
totalreserves2,
total_reserves3,
total_reserves4,
total_reserves5,
packing_status,
static_check,
dynamic_check,
value,
termsofpayment,
customer_date,
open_items,
oldest_item,
max_dunn_level,
financial_doc,
exptcreditinsur,
payment_card,
reserve,
reserve_1,
reserve_2,
reserve_3,
overallcredstat,
trns_plan_stat,
confirmation,
confirm_status,
sap_release,
it_data_packag,
it_data_pck_putaway,
item_data_gm,
head_data_pckg,
head_data_pck_putawy,
head_data_gm,
head_data_dan_gds,
data_obsolete,
delay_status,
hu_in_stock,
statdecntrlwhse,
rev_det_status,
indicator_document_preselecte,
ov_b_blk_stat,
dlv_blk_status,
overall_blk_st,
pod_status,
status_funds_mgmt,
manual_completion,
temporary_inbound_delivery,
hold,
phold,
sap_cred_mgmt,
crma_te_status,
cat_ext_obsol,
dtucsta,
arun_status_at_hdr,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.sales_document,
src.ref_status,
src.total_refstatus,
src.confirmed,
src.delivery_status,
src.ovrl_delvry_sts,
src.ovrlgdsmvtstat,
src.billing_status,
src.bill_stat_order,
src.posting_status,
src.rejection_sts,
src.overall_status,
src.ovr_pick_status,
src.overallwmstatus,
src.item_data,
src.item_deliv_data,
src.item_bill_data,
src.header_data,
src.header_dlv_data,
src.header_bill_dat,
src.pricing,
src.document_cat,
src.document_object,
src.changed_on,
src.totals_status,
src.inv_list_status,
src.hdr_reserves_1,
src.hdr_reserves_2,
src.hdr_reserves_3,
src.hdr_reserves_4,
src.hdr_reserves_5,
src.total_reserves1,
src.totalreserves2,
src.total_reserves3,
src.total_reserves4,
src.total_reserves5,
src.packing_status,
src.static_check,
src.dynamic_check,
src.value,
src.termsofpayment,
src.customer_date,
src.open_items,
src.oldest_item,
src.max_dunn_level,
src.financial_doc,
src.exptcreditinsur,
src.payment_card,
src.reserve,
src.reserve_1,
src.reserve_2,
src.reserve_3,
src.overallcredstat,
src.trns_plan_stat,
src.confirmation,
src.confirm_status,
src.sap_release,
src.it_data_packag,
src.it_data_pck_putaway,
src.item_data_gm,
src.head_data_pckg,
src.head_data_pck_putawy,
src.head_data_gm,
src.head_data_dan_gds,
src.data_obsolete,
src.delay_status,
src.hu_in_stock,
src.statdecntrlwhse,
src.rev_det_status,
src.indicator_document_preselecte,
src.ov_b_blk_stat,
src.dlv_blk_status,
src.overall_blk_st,
src.pod_status,
src.status_funds_mgmt,
src.manual_completion,
src.temporary_inbound_delivery,
src.hold,
src.phold,
src.sap_cred_mgmt,
src.crma_te_status,
src.cat_ext_obsol,
src.dtucsta,
src.arun_status_at_hdr,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'sales_document_header_status' as table_name
    		,'vbuk' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'sales_document_header_status') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'sales_document_header_status') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.sales_document_header_status`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.sales_document_header_status` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'sales_document_header_status'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.sales_document_header_status`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    