MERGE INTO `sap-adapter.slt_staging.invoice_receipt_header_detail` tgt
USING (
WITH rbkp as
(select MANDT as client,
BELNR as inv_doc_no,
GJAHR as fiscal_year,
BLART as document_type,
BLDAT as document_date,
BUDAT as posting_date,
USNAM as user_name,
TCODE as transaction_code,
CPUDT as entered_on,
CPUTM as entered_at,
VGART as transactn_type,
XBLNR as reference,
BUKRS as company_code,
LIFNR as invoicing_party,
WAERS as currency,
KURSF as exchange_rate,
RMWWR as gross_inv_amnt,
BEZNK as unpl_del_csts,
TXDAT as tax_date,
TXDAT_FROM as tax_rate_valid_from,
WMWST1 as value_added_tax,
MWSKZ1 as tax_code,
WMWST2 as not_in_use,
MWSKZ2 as not_in_use_1,
ZTERM as payt_terms,
ZBD1T as days_1,
ZBD1P as disc_percent_1,
ZBD2T as days_2,
ZBD2P as disc_percent_2,
ZBD3T as days_net,
WSKTO as cd_amount,
XRECH as invoice,
BKTXT as doc_header_text,
SAPRL as sap_release,
LOGSYS as logical_system,
XMWST as calculate_tax,
STBLG as reversed_by,
STJAH as year,
MWSKZ_BNK as tax_code_1,
TXJCD_BNK as tax_jur,
IVTYP as iv_category,
XRBTX as sev_tax_codes,
REPART as inv_ver_type,
RBSTAT as inv_status,
KNUMVE as doc_condition,
KNUMVL as supplier_cond,
ARKUEN as inv_reduction,
ARKUEMW as tax_inv_red,
MAKZN as manaccpdnetamnt,
MAKZMW as tax_accptd_man,
LIEFFN as supp_error_net,
LIEFFMW as tax_supp_error,
XAUTAKZ as auto_accepted,
ESRNR as isr_number,
ESRPZ as check_digit,
ESRRE as isr_qr_ref,
QSSHB as wtax_base,
QSFBT as wtax_exempt,
QSSKZ as wtax_code,
DIEKZ as service_ind,
LANDL as suppl_cntry,
LZBKZ as scb_ind,
TXKRS as rate_for_taxes,
CTXKRS as tax_rate_lc,
EMPFB as payer,
BVTYP as part_bank_type,
HBKID as house_bank,
ZUONR as assignment_number,
ZLSPR as pmnt_block,
ZLSCH as pymt_meth,
ZFBDT as baseline_date,
KIDNO as payment_ref,
REBZG as inr_ref_no,
REBZJ as fiscal_year_1,
XINVE as invest_id,
EGMLD as reporting_cntry,
XEGDR as eu_triang_deal,
VATDATE as tax_reporting_date,
HKONT as g_l_acct,
MONAT as period,
J_1BNFTYPE as nf_type,
BRNCH as branch_number,
ERFPR as entry_profile,
SECCO as section_code,
NAME1 as name,
NAME2 as name_2,
NAME3 as name_3,
NAME4 as name_4,
PSTLZ as postal_code,
ORT01 as city,
LAND1 as country,
STRAS as street,
PFACH as po_box,
PSTL2 as po_box_pcode,
PSKTO as post_bank_no,
BANKN as bank_account,
BANKL as bank_number,
BANKS as bank_country,
STCD1 as tax_number_1,
STCD2 as tax_number_2,
STKZU as liable_for_vat,
STKZA as equalizatn_tax,
REGIO as region,
BKONT as control_key,
DTAWS as instruction_key,
DTAMS as dme_indicator,
SPRAS as char1,
XCPDK as one_time_acct,
EMPFG as pmnt_recipient,
FITYP as tax_type,
STCDT as tax_number_type,
STKZN as natural_person,
STCD3 as tax_number_3,
STCD4 as tax_number_4,
BKREF as reference_1,
J_1KFREPRE as rep_s_name,
J_1KFTBUS as type_of_business,
J_1KFTIND as type_of_industry,
ANRED as title,
STCEG as vat_reg_no,
STCD5 as tax_number_5,
INTAD as clrk_s_internet,
ERNAME as created_by,
REINDAT as inv_recpt_date,
UZAWE as pmt_meth_supl,
FDLEV as planning_level,
FDTAG as planning_date,
ZBFIX as fixed,
FRGKZ as release_ind,
ERFNAM as entered_by,
BUPLA as business_place,
FILKD as branch,
GSBER as business_area,
LOTKZ as lot_no,
SGTXT as text,
INV_TRAN as transaction,
PREPAY_STATUS as prepayment_status,
PREPAY_AWKEY as invoice_number,
ASSIGN_STATUS as assignm_test,
ASSIGN_NEXT_DATE as next_assignment,
ASSIGN_END_DATE as assignment_end,
COPY_BY_BELNR as original_invoice,
COPY_BY_YEAR as fiscal_year_2,
COPY_TO_BELNR as copied_invoice,
COPY_TO_YEAR as fyear_inv_copy,
COPY_USER as creator_of_copy,
KURSX as md_exchange_rate,
WWERT as translation_dte,
XREF3 as reference_key_3,
DUMMY_MMIV_SI_S_HEADER_EEW_PS as dummy,
BUSINESS_NETWORK_ORIGIN as bus_network_origin,
ISEOPBLOCKED as business_purp_compl,
LASTCHANGEDATETIME as time_stamp,
GLO_REF1_HD as country_specific_reference_1_i,
GLO_DAT1_HD as country_specific_date_1_in_the,
GLO_REF2_HD as country_specific_reference_2_i,
GLO_DAT2_HD as country_specific_date_2_in_the,
GLO_REF3_HD as country_specific_reference_3_i,
GLO_DAT3_HD as country_specific_date_3_in_the,
GLO_REF4_HD as country_specific_reference_4_i,
GLO_DAT4_HD as country_specific_date_4_in_the,
GLO_REF5_HD as country_specific_reference_5_i,
GLO_DAT5_HD as country_specific_date_5_in_the,
GLO_BP1_HD as country_specific_business_part,
GLO_BP2_HD as country_specific_business_pa_1,
CIM_REPLICATIONTIMESTAMP as time_stamp_1,
NODE_KEY as guid,
PARENT_KEY as guid_1,
ROOT_KEY as guid_2,
J_1TPBUPL as branch_code,
LOGMX_UUID as mexico_uuid,
ANXTYPE as invoice_type,
ANXAMNT as annexation_amount,
ANXPERC as annexation_percen,
ZVAT_INDC as v_a_t_indicator,
__ILE__PARK as select_0,
__ILE__HOLD as select_1,
__ILE__BAPI_SAVE as select_2,
GST_PART as gst_partner,
PLC_SUP as place_of_supply,
PYBASTYP as payt_against,
PYBASNO as payt_ground_no,
PYBASDAT as payt_ground_date,
PYIBAN as iban,
INWARDNO_HD as incg_doc_nmbr,
INWARDDT_HD as incg_doc_date,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct rbkp.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.rbkp` as rbkp
where rbkp._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'invoice_receipt_header_detail'),0))
select client as client_key,
inv_doc_no as inv_doc_no_key,
fiscal_year as fiscal_year_key,
*
From  rbkp
UNION ALL
select null as client_key,
null as inv_doc_no_key,
null as fiscal_year_key,
rbkp.*
From rbkp as rbkp
INNER JOIN `sap-adapter.slt_staging.invoice_receipt_header_detail` as uji
ON rbkp.client = uji.client
AND rbkp.inv_doc_no = uji.inv_doc_no
AND rbkp.fiscal_year = uji.fiscal_year
AND rbkp.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.inv_doc_no_key = tgt.inv_doc_no
AND src.fiscal_year_key = tgt.fiscal_year
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
inv_doc_no,
fiscal_year,
document_type,
document_date,
posting_date,
user_name,
transaction_code,
entered_on,
entered_at,
transactn_type,
reference,
company_code,
invoicing_party,
currency,
exchange_rate,
gross_inv_amnt,
unpl_del_csts,
tax_date,
tax_rate_valid_from,
value_added_tax,
tax_code,
not_in_use,
not_in_use_1,
payt_terms,
days_1,
disc_percent_1,
days_2,
disc_percent_2,
days_net,
cd_amount,
invoice,
doc_header_text,
sap_release,
logical_system,
calculate_tax,
reversed_by,
year,
tax_code_1,
tax_jur,
iv_category,
sev_tax_codes,
inv_ver_type,
inv_status,
doc_condition,
supplier_cond,
inv_reduction,
tax_inv_red,
manaccpdnetamnt,
tax_accptd_man,
supp_error_net,
tax_supp_error,
auto_accepted,
isr_number,
check_digit,
isr_qr_ref,
wtax_base,
wtax_exempt,
wtax_code,
service_ind,
suppl_cntry,
scb_ind,
rate_for_taxes,
tax_rate_lc,
payer,
part_bank_type,
house_bank,
assignment_number,
pmnt_block,
pymt_meth,
baseline_date,
payment_ref,
inr_ref_no,
fiscal_year_1,
invest_id,
reporting_cntry,
eu_triang_deal,
tax_reporting_date,
g_l_acct,
period,
nf_type,
branch_number,
entry_profile,
section_code,
name,
name_2,
name_3,
name_4,
postal_code,
city,
country,
street,
po_box,
po_box_pcode,
post_bank_no,
bank_account,
bank_number,
bank_country,
tax_number_1,
tax_number_2,
liable_for_vat,
equalizatn_tax,
region,
control_key,
instruction_key,
dme_indicator,
char1,
one_time_acct,
pmnt_recipient,
tax_type,
tax_number_type,
natural_person,
tax_number_3,
tax_number_4,
reference_1,
rep_s_name,
type_of_business,
type_of_industry,
title,
vat_reg_no,
tax_number_5,
clrk_s_internet,
created_by,
inv_recpt_date,
pmt_meth_supl,
planning_level,
planning_date,
fixed,
release_ind,
entered_by,
business_place,
branch,
business_area,
lot_no,
text,
transaction,
prepayment_status,
invoice_number,
assignm_test,
next_assignment,
assignment_end,
original_invoice,
fiscal_year_2,
copied_invoice,
fyear_inv_copy,
creator_of_copy,
md_exchange_rate,
translation_dte,
reference_key_3,
dummy,
bus_network_origin,
business_purp_compl,
time_stamp,
country_specific_reference_1_i,
country_specific_date_1_in_the,
country_specific_reference_2_i,
country_specific_date_2_in_the,
country_specific_reference_3_i,
country_specific_date_3_in_the,
country_specific_reference_4_i,
country_specific_date_4_in_the,
country_specific_reference_5_i,
country_specific_date_5_in_the,
country_specific_business_part,
country_specific_business_pa_1,
time_stamp_1,
guid,
guid_1,
guid_2,
branch_code,
mexico_uuid,
invoice_type,
annexation_amount,
annexation_percen,
v_a_t_indicator,
select_0,
select_1,
select_2,
gst_partner,
place_of_supply,
payt_against,
payt_ground_no,
payt_ground_date,
iban,
incg_doc_nmbr,
incg_doc_date,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.inv_doc_no,
src.fiscal_year,
src.document_type,
src.document_date,
src.posting_date,
src.user_name,
src.transaction_code,
src.entered_on,
src.entered_at,
src.transactn_type,
src.reference,
src.company_code,
src.invoicing_party,
src.currency,
src.exchange_rate,
src.gross_inv_amnt,
src.unpl_del_csts,
src.tax_date,
src.tax_rate_valid_from,
src.value_added_tax,
src.tax_code,
src.not_in_use,
src.not_in_use_1,
src.payt_terms,
src.days_1,
src.disc_percent_1,
src.days_2,
src.disc_percent_2,
src.days_net,
src.cd_amount,
src.invoice,
src.doc_header_text,
src.sap_release,
src.logical_system,
src.calculate_tax,
src.reversed_by,
src.year,
src.tax_code_1,
src.tax_jur,
src.iv_category,
src.sev_tax_codes,
src.inv_ver_type,
src.inv_status,
src.doc_condition,
src.supplier_cond,
src.inv_reduction,
src.tax_inv_red,
src.manaccpdnetamnt,
src.tax_accptd_man,
src.supp_error_net,
src.tax_supp_error,
src.auto_accepted,
src.isr_number,
src.check_digit,
src.isr_qr_ref,
src.wtax_base,
src.wtax_exempt,
src.wtax_code,
src.service_ind,
src.suppl_cntry,
src.scb_ind,
src.rate_for_taxes,
src.tax_rate_lc,
src.payer,
src.part_bank_type,
src.house_bank,
src.assignment_number,
src.pmnt_block,
src.pymt_meth,
src.baseline_date,
src.payment_ref,
src.inr_ref_no,
src.fiscal_year_1,
src.invest_id,
src.reporting_cntry,
src.eu_triang_deal,
src.tax_reporting_date,
src.g_l_acct,
src.period,
src.nf_type,
src.branch_number,
src.entry_profile,
src.section_code,
src.name,
src.name_2,
src.name_3,
src.name_4,
src.postal_code,
src.city,
src.country,
src.street,
src.po_box,
src.po_box_pcode,
src.post_bank_no,
src.bank_account,
src.bank_number,
src.bank_country,
src.tax_number_1,
src.tax_number_2,
src.liable_for_vat,
src.equalizatn_tax,
src.region,
src.control_key,
src.instruction_key,
src.dme_indicator,
src.char1,
src.one_time_acct,
src.pmnt_recipient,
src.tax_type,
src.tax_number_type,
src.natural_person,
src.tax_number_3,
src.tax_number_4,
src.reference_1,
src.rep_s_name,
src.type_of_business,
src.type_of_industry,
src.title,
src.vat_reg_no,
src.tax_number_5,
src.clrk_s_internet,
src.created_by,
src.inv_recpt_date,
src.pmt_meth_supl,
src.planning_level,
src.planning_date,
src.fixed,
src.release_ind,
src.entered_by,
src.business_place,
src.branch,
src.business_area,
src.lot_no,
src.text,
src.transaction,
src.prepayment_status,
src.invoice_number,
src.assignm_test,
src.next_assignment,
src.assignment_end,
src.original_invoice,
src.fiscal_year_2,
src.copied_invoice,
src.fyear_inv_copy,
src.creator_of_copy,
src.md_exchange_rate,
src.translation_dte,
src.reference_key_3,
src.dummy,
src.bus_network_origin,
src.business_purp_compl,
src.time_stamp,
src.country_specific_reference_1_i,
src.country_specific_date_1_in_the,
src.country_specific_reference_2_i,
src.country_specific_date_2_in_the,
src.country_specific_reference_3_i,
src.country_specific_date_3_in_the,
src.country_specific_reference_4_i,
src.country_specific_date_4_in_the,
src.country_specific_reference_5_i,
src.country_specific_date_5_in_the,
src.country_specific_business_part,
src.country_specific_business_pa_1,
src.time_stamp_1,
src.guid,
src.guid_1,
src.guid_2,
src.branch_code,
src.mexico_uuid,
src.invoice_type,
src.annexation_amount,
src.annexation_percen,
src.v_a_t_indicator,
src.select_0,
src.select_1,
src.select_2,
src.gst_partner,
src.place_of_supply,
src.payt_against,
src.payt_ground_no,
src.payt_ground_date,
src.iban,
src.incg_doc_nmbr,
src.incg_doc_date,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'invoice_receipt_header_detail' as table_name
    		,'rbkp' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'invoice_receipt_header_detail') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'invoice_receipt_header_detail') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.invoice_receipt_header_detail`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.invoice_receipt_header_detail` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'invoice_receipt_header_detail'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.invoice_receipt_header_detail`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    