MERGE INTO `sap-adapter.slt_staging.sales_document_header` tgt
USING (
WITH vbak as
(select MANDT as client,
VBELN as sales_document,
ERDAT as created_on,
ERZET as entry_time,
ERNAM as created_by,
ANGDT as valid_from,
BNDDT as valid_to,
AUDAT as document_date,
VBTYP as document_cat,
TRVOG as transact_group,
AUART as sales_doc_type,
AUGRU as order_reason,
GWLDT as begin_guarantee,
SUBMI as collective_no,
LIFSK as delivery_block,
FAKSK as billing_block,
NETWR as net_value,
WAERK as doc_currency,
VKORG as sales_org,
VTWEG as distr_channel,
SPART as division,
VKGRP as sales_group,
VKBUR as sales_office,
GSBER as business_area,
GSKST as business_area_1,
GUEBG as valid_from_1,
GUEEN as valid_to_1,
KNUMV as doc_condition,
VDATU as reqd_deliv_date,
VPRGR as prop_date_type,
AUTLF as complete_dlv,
VBKLA as original_system,
VBKLT as indicator,
KALSM as pric_procedure,
VSBED as shp_cond,
FKARA as ord_rel_bill_ty,
AWAHR as probability,
KTEXT as description,
BSTNK as cust_reference,
BSARK as pur_ord_type,
BSTDK as cust_ref_date,
BSTZD as supplement,
IHREZ as your_reference,
BNAME as name,
TELF1 as telephone,
MAHZA as no_of_contacts,
MAHDT as last_contact_dt,
KUNNR as sold_to_party,
KOSTL as cost_center,
STAFO as update_group,
STWAE as stats_currency,
AEDAT as changed_on,
KVGR1 as customer_grp_1,
KVGR2 as customer_grp_2,
KVGR3 as customer_grp_3,
KVGR4 as customer_grp_4,
KVGR5 as customer_grp_5,
KNUMA as agreement,
KOKRS as co_area,
PS_PSP_PNR as wbs_element,
KURST as exch_rate_type,
KKBER as cred_contr_area,
KNKLI as credit_account,
GRUPP as cust_cred_group,
SBGRP as cred_rep_grp,
CTLPC as risk_category,
CMWAE as currency,
CMFRE as release_date,
CMNUP as next_check,
CMNGV as next_date,
AMTBL as credit_value,
HITYP_PR as hiertypepricing,
ABRVW as usage,
ABDIS as mrp_for_ds_type,
VGBEL as reference_doc,
OBJNR as object_no_hdr,
BUKRS_VF as ccodetobebilled,
TAXK1 as alt_tax_class,
TAXK2 as taxclass2_cust,
TAXK3 as taxclass3_cust,
TAXK4 as taxclass4_cust,
TAXK5 as taxclass5_cust,
TAXK6 as taxclass6_cust,
TAXK7 as taxclass7_cust,
TAXK8 as taxclass8_cust,
TAXK9 as taxclass9_cust,
XBLNR as reference,
ZUONR as assignment_number,
VGTYP as prec_doc_categ,
KALSM_CH as search_proced,
AGRZR as accrual_period,
AUFNR as order_number,
QMNUM as notification,
VBELN_GRP as master_contract,
SCHEME_GRP as ref_procedure,
ABRUF_PART as check_partner,
ABHOD as pick_up_date,
ABHOV as pick_up_time,
ABHOB as pick_up_time_1,
RPLNR as paym_ca_pl_no,
VZEIT as req_dely_time,
STCEG_L as tax_dest_cntry,
LANDTX as tax_depart_cty,
XEGDR as eu_triang_deal,
ENQUEUE_GRP as block_master_contr_until_all,
DAT_FZAU as cmlqtydate,
FMBDAT as mat_avail_date,
VSNMR_V as version,
HANDLE as int_id,
PROLI as dg_mgmt_profile,
CONT_DG as contains_dg,
CRM_GUID as char_70,
UPD_TMSTMP as time_stamp,
MSR_ID as process_id_no,
TM_CTRL_KEY as control_key,
OIPBL as location_id,
LAST_CHANGED_BY_USER as last_changed_by,
HANDOVERLOC as handover_location,
EXT_BUS_SYST_ID as ext_bus_syst_id,
EXT_REF_DOC_ID as external_document_id,
EXT_REV_TMSTMP as external_revision,
APM_APPROVAL_STATUS as approval_status,
APM_APPROVAL_REASON as apprvl_req_rsn_id,
APM_REJECTION_REASON as apprvl_req_rjcn_rsn,
_DATAAGING as data_filter_value_for_data_agi,
ABSTK as rejection_sts,
BESTK as confirmed,
CMPSC as value,
CMPSD as termsofpayment,
CMPSI as financial_doc,
CMPSJ as exptcreditinsur,
CMPSK as payment_card,
CMPS_CM as sap_cred_mgmt,
CMPS_TE as crma_te_status,
CMGST as overallcredstat,
COSTA as confirm_status,
DCSTK as delay_status,
FKSAK as bill_stat_order,
FMSTK as status_funds_mgmt,
FSSTK as ov_b_blk_stat,
GBSTK as overall_status,
LFGSK as ovrl_delvry_sts,
LFSTK as delivery_status,
LSSTK as dlv_blk_status,
MANEK as manual_completion,
RFGSK as total_refstatus,
RFSTK as ref_status,
SPSTG as overall_blk_st,
TRSTA as trns_plan_stat,
UVALL as header_data,
UVALS as item_data,
UVFAK as header_bill_dat,
UVFAS as item_bill_data,
UVPRS as pricing,
UVVLK as header_dlv_data,
UVVLS as item_deliv_data,
UVK01 as hdr_reserves_1,
UVK02 as hdr_reserves_2,
UVK03 as hdr_reserves_3,
UVK04 as hdr_reserves_4,
UVK05 as hdr_reserves_5,
UVS01 as total_reserves1,
UVS02 as totalreserves2,
UVS03 as total_reserves3,
UVS04 as total_reserves4,
UVS05 as total_reserves5,
WBSTK as ovrlgdsmvtstat,
TOTAL_EMCST as embargo_status,
TOTAL_SLCST as wls_sts,
TOTAL_LCCST as total_legal_status,
TOTAL_PCSTA as prod_marktablty_sts,
TOTAL_DGSTA as dangerous_goods_sts,
TOTAL_SDSSTA as sfty_data_sheet_sts,
DP_CLEAR_STA_HDR as down_payment_status,
DUMMY_SALESDOC_INCL_EEW_PS as dummy_function_in_length_1,
ZAPCGKH as annexing_package,
APCGK_EXTENDH as ann_package_extend,
ZABDATH as annexing_base_date,
AD01FAREG as a_d_bill_rule,
AD01BASDOC as initial_doc,
LASTVCHR as last_voucher,
PSM_BUDAT as posting_date,
FSH_KVGR6 as customer_grp_6,
FSH_KVGR7 as customer_grp_7,
FSH_KVGR8 as customer_grp_8,
FSH_KVGR9 as customer_grp_5_1,
FSH_KVGR10 as customer_grp_10,
FSH_REREG as release_rule,
FSH_CQ_CHECK as rqmt_relevant,
FSH_VRSN_STATUS as snap_status,
FSH_TRANSACTION as transaction_number,
FSH_VAS_CG as vas_cust_group,
FSH_CANDATE as cancel_date,
FSH_SS as sched_strat,
FSH_OS_STG_CHANGE as changed_manually,
J_3GKBAUL as etm_rel_ind,
MILL_APPL_ID as application_id,
TAS as treasury_account_sym,
BETC as business_evt_typ_cd,
MOD_ALLOW as modification_allowed,
CANCEL_ALLOW as cancellation_allowed,
PAY_METHOD as payment_methods,
BPN as business_partner_no,
REP_FREQ as reporting_frequency,
LOGSYSB as logical_system,
KALCD as proc_camp_det,
MULTI as multiple_promotions,
SPPAYM as paymmethod,
WTYSC_CLM_HDR as claim_header,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct vbak.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.vbak` as vbak
where vbak._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'sales_document_header'),0))
select client as client_key,
sales_document as sales_document_key,
*
From  vbak
UNION ALL
select null as client_key,
null as sales_document_key,
vbak.*
From vbak as vbak
INNER JOIN `sap-adapter.slt_staging.sales_document_header` as uji
ON vbak.client = uji.client
AND vbak.sales_document = uji.sales_document
AND vbak.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.sales_document_key = tgt.sales_document
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
sales_document,
created_on,
entry_time,
created_by,
valid_from,
valid_to,
document_date,
document_cat,
transact_group,
sales_doc_type,
order_reason,
begin_guarantee,
collective_no,
delivery_block,
billing_block,
net_value,
doc_currency,
sales_org,
distr_channel,
division,
sales_group,
sales_office,
business_area,
business_area_1,
valid_from_1,
valid_to_1,
doc_condition,
reqd_deliv_date,
prop_date_type,
complete_dlv,
original_system,
indicator,
pric_procedure,
shp_cond,
ord_rel_bill_ty,
probability,
description,
cust_reference,
pur_ord_type,
cust_ref_date,
supplement,
your_reference,
name,
telephone,
no_of_contacts,
last_contact_dt,
sold_to_party,
cost_center,
update_group,
stats_currency,
changed_on,
customer_grp_1,
customer_grp_2,
customer_grp_3,
customer_grp_4,
customer_grp_5,
agreement,
co_area,
wbs_element,
exch_rate_type,
cred_contr_area,
credit_account,
cust_cred_group,
cred_rep_grp,
risk_category,
currency,
release_date,
next_check,
next_date,
credit_value,
hiertypepricing,
usage,
mrp_for_ds_type,
reference_doc,
object_no_hdr,
ccodetobebilled,
alt_tax_class,
taxclass2_cust,
taxclass3_cust,
taxclass4_cust,
taxclass5_cust,
taxclass6_cust,
taxclass7_cust,
taxclass8_cust,
taxclass9_cust,
reference,
assignment_number,
prec_doc_categ,
search_proced,
accrual_period,
order_number,
notification,
master_contract,
ref_procedure,
check_partner,
pick_up_date,
pick_up_time,
pick_up_time_1,
paym_ca_pl_no,
req_dely_time,
tax_dest_cntry,
tax_depart_cty,
eu_triang_deal,
block_master_contr_until_all,
cmlqtydate,
mat_avail_date,
version,
int_id,
dg_mgmt_profile,
contains_dg,
char_70,
time_stamp,
process_id_no,
control_key,
location_id,
last_changed_by,
handover_location,
ext_bus_syst_id,
external_document_id,
external_revision,
approval_status,
apprvl_req_rsn_id,
apprvl_req_rjcn_rsn,
data_filter_value_for_data_agi,
rejection_sts,
confirmed,
value,
termsofpayment,
financial_doc,
exptcreditinsur,
payment_card,
sap_cred_mgmt,
crma_te_status,
overallcredstat,
confirm_status,
delay_status,
bill_stat_order,
status_funds_mgmt,
ov_b_blk_stat,
overall_status,
ovrl_delvry_sts,
delivery_status,
dlv_blk_status,
manual_completion,
total_refstatus,
ref_status,
overall_blk_st,
trns_plan_stat,
header_data,
item_data,
header_bill_dat,
item_bill_data,
pricing,
header_dlv_data,
item_deliv_data,
hdr_reserves_1,
hdr_reserves_2,
hdr_reserves_3,
hdr_reserves_4,
hdr_reserves_5,
total_reserves1,
totalreserves2,
total_reserves3,
total_reserves4,
total_reserves5,
ovrlgdsmvtstat,
embargo_status,
wls_sts,
total_legal_status,
prod_marktablty_sts,
dangerous_goods_sts,
sfty_data_sheet_sts,
down_payment_status,
dummy_function_in_length_1,
annexing_package,
ann_package_extend,
annexing_base_date,
a_d_bill_rule,
initial_doc,
last_voucher,
posting_date,
customer_grp_6,
customer_grp_7,
customer_grp_8,
customer_grp_5_1,
customer_grp_10,
release_rule,
rqmt_relevant,
snap_status,
transaction_number,
vas_cust_group,
cancel_date,
sched_strat,
changed_manually,
etm_rel_ind,
application_id,
treasury_account_sym,
business_evt_typ_cd,
modification_allowed,
cancellation_allowed,
payment_methods,
business_partner_no,
reporting_frequency,
logical_system,
proc_camp_det,
multiple_promotions,
paymmethod,
claim_header,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.sales_document,
src.created_on,
src.entry_time,
src.created_by,
src.valid_from,
src.valid_to,
src.document_date,
src.document_cat,
src.transact_group,
src.sales_doc_type,
src.order_reason,
src.begin_guarantee,
src.collective_no,
src.delivery_block,
src.billing_block,
src.net_value,
src.doc_currency,
src.sales_org,
src.distr_channel,
src.division,
src.sales_group,
src.sales_office,
src.business_area,
src.business_area_1,
src.valid_from_1,
src.valid_to_1,
src.doc_condition,
src.reqd_deliv_date,
src.prop_date_type,
src.complete_dlv,
src.original_system,
src.indicator,
src.pric_procedure,
src.shp_cond,
src.ord_rel_bill_ty,
src.probability,
src.description,
src.cust_reference,
src.pur_ord_type,
src.cust_ref_date,
src.supplement,
src.your_reference,
src.name,
src.telephone,
src.no_of_contacts,
src.last_contact_dt,
src.sold_to_party,
src.cost_center,
src.update_group,
src.stats_currency,
src.changed_on,
src.customer_grp_1,
src.customer_grp_2,
src.customer_grp_3,
src.customer_grp_4,
src.customer_grp_5,
src.agreement,
src.co_area,
src.wbs_element,
src.exch_rate_type,
src.cred_contr_area,
src.credit_account,
src.cust_cred_group,
src.cred_rep_grp,
src.risk_category,
src.currency,
src.release_date,
src.next_check,
src.next_date,
src.credit_value,
src.hiertypepricing,
src.usage,
src.mrp_for_ds_type,
src.reference_doc,
src.object_no_hdr,
src.ccodetobebilled,
src.alt_tax_class,
src.taxclass2_cust,
src.taxclass3_cust,
src.taxclass4_cust,
src.taxclass5_cust,
src.taxclass6_cust,
src.taxclass7_cust,
src.taxclass8_cust,
src.taxclass9_cust,
src.reference,
src.assignment_number,
src.prec_doc_categ,
src.search_proced,
src.accrual_period,
src.order_number,
src.notification,
src.master_contract,
src.ref_procedure,
src.check_partner,
src.pick_up_date,
src.pick_up_time,
src.pick_up_time_1,
src.paym_ca_pl_no,
src.req_dely_time,
src.tax_dest_cntry,
src.tax_depart_cty,
src.eu_triang_deal,
src.block_master_contr_until_all,
src.cmlqtydate,
src.mat_avail_date,
src.version,
src.int_id,
src.dg_mgmt_profile,
src.contains_dg,
src.char_70,
src.time_stamp,
src.process_id_no,
src.control_key,
src.location_id,
src.last_changed_by,
src.handover_location,
src.ext_bus_syst_id,
src.external_document_id,
src.external_revision,
src.approval_status,
src.apprvl_req_rsn_id,
src.apprvl_req_rjcn_rsn,
src.data_filter_value_for_data_agi,
src.rejection_sts,
src.confirmed,
src.value,
src.termsofpayment,
src.financial_doc,
src.exptcreditinsur,
src.payment_card,
src.sap_cred_mgmt,
src.crma_te_status,
src.overallcredstat,
src.confirm_status,
src.delay_status,
src.bill_stat_order,
src.status_funds_mgmt,
src.ov_b_blk_stat,
src.overall_status,
src.ovrl_delvry_sts,
src.delivery_status,
src.dlv_blk_status,
src.manual_completion,
src.total_refstatus,
src.ref_status,
src.overall_blk_st,
src.trns_plan_stat,
src.header_data,
src.item_data,
src.header_bill_dat,
src.item_bill_data,
src.pricing,
src.header_dlv_data,
src.item_deliv_data,
src.hdr_reserves_1,
src.hdr_reserves_2,
src.hdr_reserves_3,
src.hdr_reserves_4,
src.hdr_reserves_5,
src.total_reserves1,
src.totalreserves2,
src.total_reserves3,
src.total_reserves4,
src.total_reserves5,
src.ovrlgdsmvtstat,
src.embargo_status,
src.wls_sts,
src.total_legal_status,
src.prod_marktablty_sts,
src.dangerous_goods_sts,
src.sfty_data_sheet_sts,
src.down_payment_status,
src.dummy_function_in_length_1,
src.annexing_package,
src.ann_package_extend,
src.annexing_base_date,
src.a_d_bill_rule,
src.initial_doc,
src.last_voucher,
src.posting_date,
src.customer_grp_6,
src.customer_grp_7,
src.customer_grp_8,
src.customer_grp_5_1,
src.customer_grp_10,
src.release_rule,
src.rqmt_relevant,
src.snap_status,
src.transaction_number,
src.vas_cust_group,
src.cancel_date,
src.sched_strat,
src.changed_manually,
src.etm_rel_ind,
src.application_id,
src.treasury_account_sym,
src.business_evt_typ_cd,
src.modification_allowed,
src.cancellation_allowed,
src.payment_methods,
src.business_partner_no,
src.reporting_frequency,
src.logical_system,
src.proc_camp_det,
src.multiple_promotions,
src.paymmethod,
src.claim_header,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'sales_document_header' as table_name
    		,'vbak' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'sales_document_header') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'sales_document_header') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.sales_document_header`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.sales_document_header` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'sales_document_header'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.sales_document_header`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    