MERGE INTO `sap-adapter.slt_staging.production_order_confirmation_details` tgt
USING (
WITH afru as
(select MANDT as client,
RUECK as confirmation,
RMZHL as counter,
ERSDA as entry_date,
ERNAM as entered_by_user,
LAEDA as last_change,
AENAM as changed_by,
BUDAT as posting_date,
ARBID as object_id,
WERKS as plant,
LTXA1 as confirm_text,
TXTSP as language_key,
ISERH as conf_break_time,
ZEIER as break_time_unit,
ILE01 as unit_activity,
ISM01 as acty_to_confirm,
ILE02 as unit_activity_1,
ISM02 as acty_to_confirm_1,
ILE03 as unit_activity_2,
ISM03 as acty_to_confirm_2,
ILE04 as unit_activity_3,
ISM04 as acty_to_confirm_3,
ILE05 as unit_activity_4,
ISM05 as acty_to_confirm_4,
ILE06 as unit_activity_5,
ISM06 as acty_to_confirm_5,
ABARB as processing,
ISMNW as actual_work,
ISMNE as unit_for_work,
LEARR as activity_type,
IDAUR as actual_duration,
IDAUE as un_actual_dur,
ZCODE as std_value_code,
LOART as wage_type,
QUALF as suitability,
ANZMA as no_employees,
LOGRP as wage_group,
GMNGA as confd_yield_quantity,
LMNGA as yield_quantity,
XMNGA as scrap_quantity,
GMEIN as base_unit,
MEINH as confirmation_unit,
GRUND as reason,
PERNR as personnel_no,
ISDD as start_execution,
ISDZ as act_start_time,
IERD as finish_setup,
IERZ as finish_setup_1,
ISBD as start_of_proc,
ISBZ as start_of_proc_1,
IEBD as fin_processing,
IEBZ as fin_processing_1,
ISAD as start_teardown,
ISAZ as start_teardown_1,
IEDD as finish_execut,
IEDZ as actual_finish,
PEDD as forecast_finish,
PEDZ as forecast_end,
WABLNR as material_doc,
WEBLNR as doc_gds_mvt_err,
AUERU as final_confirmtn,
AUSOR as clear_open_res,
STNDR as standard_conf,
MANUR as type_confirm,
MEILR as milestone_conf,
AUFPL as plan_no_f_oper,
APLZL as counter_1,
AUFNR as order_number,
APLFL as sequence,
VORNR as activity,
SUMNR as sup_op_node,
OFM01 as forecast_value,
OFE01 as std_value_unit,
LEK01 as no_remain_act,
OFM02 as forecast_value_1,
OFE02 as std_value_unit_1,
LEK02 as no_remain_act_1,
OFM03 as forecast_value_2,
OFE03 as std_value_unit_2,
LEK03 as no_remain_act_2,
OFM04 as forecast_value_3,
OFE04 as std_value_unit_3,
LEK04 as no_remain_act_3,
OFM05 as forecast_value_4,
OFE05 as std_value_unit_4,
LEK05 as no_remain_act_4,
OFM06 as forecast_value_5,
OFE06 as std_value_unit_5,
LEK06 as no_remain_act_5,
OFMNW as remaining_work,
OFMNE as unit_remng_work,
LEKNW as no_remain_work,
ODAUR as remaining_dur,
ODAUE as unit_remaining,
STOKZ as reversed,
STZHL as cancelled_conf,
SMENG as operation_qty,
RUECK_MST as confirmation_1,
RMZHL_MST as counter_2,
PDSNR as number,
KAPID as capacity_id,
SPLIT as split_number,
ZAUSW as time_rec_id_no,
ORIND as application,
ORIGF as origin,
CANUM as counters_for_cap_rqmts_recor,
BELNR_IST as document_number,
BELNR_UMB as document_number_1,
RMNGA as rework_quantity,
CATSBELNR as document_no,
SATZA as record_type,
ERZET as entry_time,
CATSPRICE as price,
CATSTCURR as trans_currency,
CATSPEINH as price_unit,
BEMOT as acctindicator,
IPRZ1 as process_qty,
IPRE1 as process_unit,
IPRK1 as no_remain_act_6,
EXNAM as created_by,
EXERD as created_on,
EXERZ as external_time,
PRZ01 as business_proc,
OPRZ1 as remaining_proc,
OPRE1 as remainproc_unit,
SKOKRS as co_area,
SKOSTL as send_cctr,
NODAT as no_date_update,
ISMNU as unit_for_work_1,
OFMNU as unit_for_work_2,
PACKNO as package_number,
EXTID as external_key,
SCHGRUP as shift_grouping,
KAPTPROG as shift_definition,
EEW_AFRU_PS_DUMMY as dummy_function_in_length_1,
OBMAT as orig_batch_matl,
OBCHA as original_batch,
LICHA as supplier_batch,
MYEAR as mat_doc_year,
ME_SFCID as mes_sfc_id,
ME_2ND_CONF_QTY as rework_me,
NO_GOODSMOVEMENT_VIA_API as no_goods_movement,
ROLE_ID as role,
UCMAT as pb_material,
UCCHA as process_batch,
WTY_IND as warranty,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct afru.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.afru` as afru
where afru._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'production_order_confirmation_details'),0))
select client as client_key,
confirmation as confirmation_key,
counter as counter_key,
*
From  afru
UNION ALL
select null as client_key,
null as confirmation_key,
null as counter_key,
afru.*
From afru as afru
INNER JOIN `sap-adapter.slt_staging.production_order_confirmation_details` as uji
ON afru.client = uji.client
AND afru.confirmation = uji.confirmation
AND afru.counter = uji.counter
AND afru.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.confirmation_key = tgt.confirmation
AND src.counter_key = tgt.counter
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
confirmation,
counter,
entry_date,
entered_by_user,
last_change,
changed_by,
posting_date,
object_id,
plant,
confirm_text,
language_key,
conf_break_time,
break_time_unit,
unit_activity,
acty_to_confirm,
unit_activity_1,
acty_to_confirm_1,
unit_activity_2,
acty_to_confirm_2,
unit_activity_3,
acty_to_confirm_3,
unit_activity_4,
acty_to_confirm_4,
unit_activity_5,
acty_to_confirm_5,
processing,
actual_work,
unit_for_work,
activity_type,
actual_duration,
un_actual_dur,
std_value_code,
wage_type,
suitability,
no_employees,
wage_group,
confd_yield_quantity,
yield_quantity,
scrap_quantity,
base_unit,
confirmation_unit,
reason,
personnel_no,
start_execution,
act_start_time,
finish_setup,
finish_setup_1,
start_of_proc,
start_of_proc_1,
fin_processing,
fin_processing_1,
start_teardown,
start_teardown_1,
finish_execut,
actual_finish,
forecast_finish,
forecast_end,
material_doc,
doc_gds_mvt_err,
final_confirmtn,
clear_open_res,
standard_conf,
type_confirm,
milestone_conf,
plan_no_f_oper,
counter_1,
order_number,
sequence,
activity,
sup_op_node,
forecast_value,
std_value_unit,
no_remain_act,
forecast_value_1,
std_value_unit_1,
no_remain_act_1,
forecast_value_2,
std_value_unit_2,
no_remain_act_2,
forecast_value_3,
std_value_unit_3,
no_remain_act_3,
forecast_value_4,
std_value_unit_4,
no_remain_act_4,
forecast_value_5,
std_value_unit_5,
no_remain_act_5,
remaining_work,
unit_remng_work,
no_remain_work,
remaining_dur,
unit_remaining,
reversed,
cancelled_conf,
operation_qty,
confirmation_1,
counter_2,
number,
capacity_id,
split_number,
time_rec_id_no,
application,
origin,
counters_for_cap_rqmts_recor,
document_number,
document_number_1,
rework_quantity,
document_no,
record_type,
entry_time,
price,
trans_currency,
price_unit,
acctindicator,
process_qty,
process_unit,
no_remain_act_6,
created_by,
created_on,
external_time,
business_proc,
remaining_proc,
remainproc_unit,
co_area,
send_cctr,
no_date_update,
unit_for_work_1,
unit_for_work_2,
package_number,
external_key,
shift_grouping,
shift_definition,
dummy_function_in_length_1,
orig_batch_matl,
original_batch,
supplier_batch,
mat_doc_year,
mes_sfc_id,
rework_me,
no_goods_movement,
role,
pb_material,
process_batch,
warranty,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.confirmation,
src.counter,
src.entry_date,
src.entered_by_user,
src.last_change,
src.changed_by,
src.posting_date,
src.object_id,
src.plant,
src.confirm_text,
src.language_key,
src.conf_break_time,
src.break_time_unit,
src.unit_activity,
src.acty_to_confirm,
src.unit_activity_1,
src.acty_to_confirm_1,
src.unit_activity_2,
src.acty_to_confirm_2,
src.unit_activity_3,
src.acty_to_confirm_3,
src.unit_activity_4,
src.acty_to_confirm_4,
src.unit_activity_5,
src.acty_to_confirm_5,
src.processing,
src.actual_work,
src.unit_for_work,
src.activity_type,
src.actual_duration,
src.un_actual_dur,
src.std_value_code,
src.wage_type,
src.suitability,
src.no_employees,
src.wage_group,
src.confd_yield_quantity,
src.yield_quantity,
src.scrap_quantity,
src.base_unit,
src.confirmation_unit,
src.reason,
src.personnel_no,
src.start_execution,
src.act_start_time,
src.finish_setup,
src.finish_setup_1,
src.start_of_proc,
src.start_of_proc_1,
src.fin_processing,
src.fin_processing_1,
src.start_teardown,
src.start_teardown_1,
src.finish_execut,
src.actual_finish,
src.forecast_finish,
src.forecast_end,
src.material_doc,
src.doc_gds_mvt_err,
src.final_confirmtn,
src.clear_open_res,
src.standard_conf,
src.type_confirm,
src.milestone_conf,
src.plan_no_f_oper,
src.counter_1,
src.order_number,
src.sequence,
src.activity,
src.sup_op_node,
src.forecast_value,
src.std_value_unit,
src.no_remain_act,
src.forecast_value_1,
src.std_value_unit_1,
src.no_remain_act_1,
src.forecast_value_2,
src.std_value_unit_2,
src.no_remain_act_2,
src.forecast_value_3,
src.std_value_unit_3,
src.no_remain_act_3,
src.forecast_value_4,
src.std_value_unit_4,
src.no_remain_act_4,
src.forecast_value_5,
src.std_value_unit_5,
src.no_remain_act_5,
src.remaining_work,
src.unit_remng_work,
src.no_remain_work,
src.remaining_dur,
src.unit_remaining,
src.reversed,
src.cancelled_conf,
src.operation_qty,
src.confirmation_1,
src.counter_2,
src.number,
src.capacity_id,
src.split_number,
src.time_rec_id_no,
src.application,
src.origin,
src.counters_for_cap_rqmts_recor,
src.document_number,
src.document_number_1,
src.rework_quantity,
src.document_no,
src.record_type,
src.entry_time,
src.price,
src.trans_currency,
src.price_unit,
src.acctindicator,
src.process_qty,
src.process_unit,
src.no_remain_act_6,
src.created_by,
src.created_on,
src.external_time,
src.business_proc,
src.remaining_proc,
src.remainproc_unit,
src.co_area,
src.send_cctr,
src.no_date_update,
src.unit_for_work_1,
src.unit_for_work_2,
src.package_number,
src.external_key,
src.shift_grouping,
src.shift_definition,
src.dummy_function_in_length_1,
src.orig_batch_matl,
src.original_batch,
src.supplier_batch,
src.mat_doc_year,
src.mes_sfc_id,
src.rework_me,
src.no_goods_movement,
src.role,
src.pb_material,
src.process_batch,
src.warranty,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'production_order_confirmation_details' as table_name
    		,'afru' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'production_order_confirmation_details') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'production_order_confirmation_details') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.production_order_confirmation_details`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.production_order_confirmation_details` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'production_order_confirmation_details'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.production_order_confirmation_details`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    