MERGE INTO `sap-adapter.slt_staging.supplier_master_address_details` tgt
USING (
WITH adrc as
(select CLIENT as client,
ADDRNUMBER as address_number,
DATE_FROM as valid_from,
NATION as address_version,
DATE_TO as valid_to,
TITLE as title,
NAME1 as name,
NAME2 as name_2,
NAME3 as name_3,
NAME4 as name_4,
NAME_TEXT as conv_name,
NAME_CO as co_name,
CITY1 as city,
CITY2 as district,
CITY_CODE as city_code,
CITYP_CODE as district_1,
HOME_CITY as different_city,
CITYH_CODE as city_code_1,
CHCKSTATUS as check_status,
REGIOGROUP as structure_group,
POST_CODE1 as postal_code,
POST_CODE2 as po_box_post_cde,
POST_CODE3 as company_post_cd,
PCODE1_EXT as postal_code_ext,
PCODE2_EXT as postal_code_ext_1,
PCODE3_EXT as postal_code_ext_2,
PO_BOX as po_box,
DONT_USE_P as undeliverable,
PO_BOX_NUM as po_box_w_o_no,
PO_BOX_LOC as po_box_city,
CITY_CODE2 as city_code_2,
PO_BOX_REG as po_region,
PO_BOX_CTY as po_box_country,
POSTALAREA as delivery_dist,
TRANSPZONE as transport_zone,
STREET as street,
DONT_USE_S as undeliverable_1,
STREETCODE as street_code,
STREETABBR as street_abbrev,
HOUSE_NUM1 as house_number,
HOUSE_NUM2 as supplement,
HOUSE_NUM3 as number_range,
STR_SUPPL1 as street_2,
STR_SUPPL2 as street_3,
STR_SUPPL3 as street_4,
LOCATION as street_5,
BUILDING as building_code,
FLOOR as floor_in_building,
ROOMNUMBER as room_number,
COUNTRY as country,
LANGU as language_key,
REGION as region,
ADDR_GROUP as address_group,
FLAGGROUPS as flag_there_are_more_address_g,
PERS_ADDR as pers_address,
SORT1 as search_term_1,
SORT2 as search_term_2,
SORT_PHN as phonet_sort,
DEFLT_COMM as comm_method,
TEL_NUMBER as telephone,
TEL_EXTENS as extension,
FAX_NUMBER as fax,
FAX_EXTENS as extension_1,
FLAGCOMM2 as telephone_1,
FLAGCOMM3 as fax_1,
FLAGCOMM4 as teletex,
FLAGCOMM5 as telex,
FLAGCOMM6 as e_mail_defined,
FLAGCOMM7 as r_mail,
FLAGCOMM8 as x_400,
FLAGCOMM9 as rfc,
FLAGCOMM10 as printer,
FLAGCOMM11 as ssf,
FLAGCOMM12 as uri_ftp,
FLAGCOMM13 as pager,
ADDRORIGIN as address_source,
MC_NAME1 as name_1,
MC_CITY1 as city_1,
MC_STREET as street_1,
EXTENSION1 as data_line,
EXTENSION2 as telebox,
TIME_ZONE as time_zone,
TAXJURCODE as tax_jurisdiction,
ADDRESS_ID as address_id,
LANGU_CREA as creation_lang,
ADRC_UUID as address_uuid,
UUID_BELATED as subsequent_uuid,
ID_CATEGORY as id_category,
ADRC_ERR_STATUS as error_status,
PO_BOX_LOBBY as po_box_lobby,
DELI_SERV_TYPE as delvry_serv_type,
DELI_SERV_NUMBER as delivery_service_no,
COUNTY_CODE as county_code,
COUNTY as county,
TOWNSHIP_CODE as township_code,
TOWNSHIP as township,
MC_COUNTY as county_1,
MC_TOWNSHIP as township_1,
XPCPT as purposecomplete_flag,
_DATAAGING as data_filter_value_for_data_agi,
DUNS as duns_number,
DUNSP4 as duns_4,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct adrc.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.adrc` as adrc
where adrc._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'supplier_master_address_details'),0))
select client as client_key,
address_number as address_number_key,
valid_from as valid_from_key,
address_version as address_version_key,
*
From  adrc
UNION ALL
select null as client_key,
null as address_number_key,
null as valid_from_key,
null as address_version_key,
adrc.*
From adrc as adrc
INNER JOIN `sap-adapter.slt_staging.supplier_master_address_details` as uji
ON adrc.client = uji.client
AND adrc.address_number = uji.address_number
AND adrc.valid_from = uji.valid_from
AND adrc.address_version = uji.address_version
AND adrc.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.address_number_key = tgt.address_number
AND src.valid_from_key = tgt.valid_from
AND src.address_version_key = tgt.address_version
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
address_number,
valid_from,
address_version,
valid_to,
title,
name,
name_2,
name_3,
name_4,
conv_name,
co_name,
city,
district,
city_code,
district_1,
different_city,
city_code_1,
check_status,
structure_group,
postal_code,
po_box_post_cde,
company_post_cd,
postal_code_ext,
postal_code_ext_1,
postal_code_ext_2,
po_box,
undeliverable,
po_box_w_o_no,
po_box_city,
city_code_2,
po_region,
po_box_country,
delivery_dist,
transport_zone,
street,
undeliverable_1,
street_code,
street_abbrev,
house_number,
supplement,
number_range,
street_2,
street_3,
street_4,
street_5,
building_code,
floor_in_building,
room_number,
country,
language_key,
region,
address_group,
flag_there_are_more_address_g,
pers_address,
search_term_1,
search_term_2,
phonet_sort,
comm_method,
telephone,
extension,
fax,
extension_1,
telephone_1,
fax_1,
teletex,
telex,
e_mail_defined,
r_mail,
x_400,
rfc,
printer,
ssf,
uri_ftp,
pager,
address_source,
name_1,
city_1,
street_1,
data_line,
telebox,
time_zone,
tax_jurisdiction,
address_id,
creation_lang,
address_uuid,
subsequent_uuid,
id_category,
error_status,
po_box_lobby,
delvry_serv_type,
delivery_service_no,
county_code,
county,
township_code,
township,
county_1,
township_1,
purposecomplete_flag,
data_filter_value_for_data_agi,
duns_number,
duns_4,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.address_number,
src.valid_from,
src.address_version,
src.valid_to,
src.title,
src.name,
src.name_2,
src.name_3,
src.name_4,
src.conv_name,
src.co_name,
src.city,
src.district,
src.city_code,
src.district_1,
src.different_city,
src.city_code_1,
src.check_status,
src.structure_group,
src.postal_code,
src.po_box_post_cde,
src.company_post_cd,
src.postal_code_ext,
src.postal_code_ext_1,
src.postal_code_ext_2,
src.po_box,
src.undeliverable,
src.po_box_w_o_no,
src.po_box_city,
src.city_code_2,
src.po_region,
src.po_box_country,
src.delivery_dist,
src.transport_zone,
src.street,
src.undeliverable_1,
src.street_code,
src.street_abbrev,
src.house_number,
src.supplement,
src.number_range,
src.street_2,
src.street_3,
src.street_4,
src.street_5,
src.building_code,
src.floor_in_building,
src.room_number,
src.country,
src.language_key,
src.region,
src.address_group,
src.flag_there_are_more_address_g,
src.pers_address,
src.search_term_1,
src.search_term_2,
src.phonet_sort,
src.comm_method,
src.telephone,
src.extension,
src.fax,
src.extension_1,
src.telephone_1,
src.fax_1,
src.teletex,
src.telex,
src.e_mail_defined,
src.r_mail,
src.x_400,
src.rfc,
src.printer,
src.ssf,
src.uri_ftp,
src.pager,
src.address_source,
src.name_1,
src.city_1,
src.street_1,
src.data_line,
src.telebox,
src.time_zone,
src.tax_jurisdiction,
src.address_id,
src.creation_lang,
src.address_uuid,
src.subsequent_uuid,
src.id_category,
src.error_status,
src.po_box_lobby,
src.delvry_serv_type,
src.delivery_service_no,
src.county_code,
src.county,
src.township_code,
src.township,
src.county_1,
src.township_1,
src.purposecomplete_flag,
src.data_filter_value_for_data_agi,
src.duns_number,
src.duns_4,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'supplier_master_address_details' as table_name
    		,'adrc' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'supplier_master_address_details') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'supplier_master_address_details') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.supplier_master_address_details`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.supplier_master_address_details` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'supplier_master_address_details'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.supplier_master_address_details`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    