MERGE INTO `sap-adapter.slt_staging.plant_data` tgt
USING (
WITH marc as
(select MANDT as client,
MATNR as material,
WERKS as plant,
PSTAT as maint_status,
LVORM as df_plant_level,
BWTTY as valuation_cat,
XCHAR as batches,
MMSTA as p_s_matl_status,
MMSTD as valid_from,
MAABC as abc_indicator,
KZKRI as critical_part,
EKGRP as purch_group,
AUSME as unit_of_issue,
DISPR as mrp_profile,
DISMM as mrp_type,
DISPO as mrp_controller,
KZDIE as mrpctrllr_buyer,
PLIFZ as pl_deliv_time,
WEBAZ as gr_proc_time,
PERKZ as period_ind,
AUSSS as assembly_scrap,
DISLS as lot_sizing_procedure,
BESKZ as procurement,
SOBSL as specprocurement,
MINBE as reorder_point,
EISBE as safety_stock,
BSTMI as min_lot_size,
BSTMA as max_lot_size,
BSTFE as fixed_lot_size,
BSTRF as rounding_value,
MABST as max_stock_level,
LOSFX as lsi_costs,
SBDKZ as indiv_coll,
LAGPR as storage_costs,
ALTSL as selectionmethod,
KZAUS as discontin_ind,
AUSDT as eff_out_date,
NFMAT as follow_up_matl,
KZBED as reqmts_grouping,
MISKZ as mixed_mrp,
FHORI as schedmargin_key,
PFREI as autom_fix_pl_ords,
FFREI as autom_release,
RGEKZ as backflush,
FEVOR as prodn_supervisor,
BEARZ as processing_time,
RUEZT as setup_time,
TRANZ as interoperation,
BASMG as base_quantity,
DZEIT as inhseprodtime,
MAXLZ as max_storage,
LZEIH as time_unit,
KZPRO as withd_fm_pr_bin,
GPMKZ as rough_cut_plng,
UEETO as overdely_tol,
UEETK as unlimited,
UNETO as underdely_tol,
WZEIT as total_rl_time,
ATPKZ as replacemt_part,
VZUSL as surcharge,
HERBL as state_of_manufac,
INSMK as post_to_insp_stk,
SPROZ as sample,
QUAZT as quarantine,
SSQSS as qm_control_key,
MPDAU as mean_insp_dur,
KZPPV as insp_plan_ind,
KZDKZ as doc_required,
WSTGH as active_subst,
PRFRQ as insp_interval,
NKMPR as next_inspection,
UMLMC as stock_in_tfr,
LADGR as loading_group,
XCHPF as batch_mgmt_rqt_plnt,
USEQU as quota_arr_usage,
LGRAD as service_level,
AUFTL as splitting_ind,
PLVAR as plan_version,
OTYPE as object_type,
OBJID as object_id,
MTVFP as avail_check,
PERIV as fi_year_variant,
KZKFK as corr_factors,
VRVEZ as setup_time_1,
VBAMG as base_quantity_1,
VBEAZ as processing_time_1,
LIZYK as deactivated,
BWSCL as supply_source,
KAUTB as autom_po,
KORDB as source_list,
STAWN as commodity_code,
HERKL as ctry_of_origin,
HERKR as reg_of_origin,
EXPME as comm_code_unit,
MTVER as intrastat_group,
PRCTR as profit_center,
TRAME as stk_in_transit,
MRPPP as plng_calendar,
SAUFT as repetitive_mfg,
FXHOR as plng_time_fence,
VRMOD as consmption_mode,
VINT1 as bwd_cons_per,
VINT2 as fwd_cons_period,
VERKZ as version,
STLAL as alternative,
STLAN as usage,
PLNNR as group_key_list,
APLAL as group_counter,
LOSGR as cstg_lot_size,
SOBSK as specproctype,
FRTME as production_unit,
LGPRO as prod_stor_loc,
DISGR as mrp_group,
KAUSF as component_scrap,
QZGTP as certificatetype,
QMATV as insp_setup,
TAKZT as takt_time,
RWPRO as coverage_prof,
COPAM as field_name,
ABCIN as cc_phys_inv,
AWSLS as variance_key,
SERNP as serialnoprofile,
CUOBJ as int_object_no,
STDPD as confble_matl,
SFEPR as rem_profile,
XMCNG as neg_stocks,
QSSYS as target_qm_sys,
LFRHY as planning_cycle,
RDPRF as rnding_profile,
VRBMT as ref_matl_cons,
VRBWK as ref_plant_cons,
VRBDT as date_to,
VRBFK as multiplier,
AUTRU as autom_reset,
PREFE as cus_preference,
PRENC as exemption_cert,
PRENO as exempt_cert_no,
PREND as iss_date_of_crt,
PRENE as vendor_decl,
PRENG as vdr_decl_date,
ITARK as military_goods,
SERVG as service_level_1,
KZKUP as co_product,
STRGR as strategy_group,
CUOBV as int_object_no_1,
LGFSB as stor_loc_ep,
SCHGT as bulk_material,
CCFIX as cc_ind_fixed,
EPRIO as stock_det_grp,
QMATA as qm_mat_auth,
RESVP as adjustmt_period,
PLNTY as task_list_type,
UOMGR as uom_group,
UMRSL as conv_group,
ABFAC as air_buoy_fact,
SFCPF as prod_sched_profile,
SHFLG as safety_time_ind,
SHZET as safety_time,
MDACH as action_control,
KZECH as enter_batch,
MEGRU as uom_group_1,
MFRGR as mat_freight_grp,
PROFIL as backfl_profile,
VKUMC as stk_transfer_sv,
VKTRW as st_in_trans_sp,
KZAGL as smth_prom_cons,
FVIDK as prod_version,
FXPRU as fixed_price_co_prod,
LOGGR as logistics_group,
FPRFM as dist_prof,
GLGMG as tied_empties,
VKGLG as slsval_tiedempt,
INDUS as mat_category,
MOWNR as eu_prod_list_no,
MOGRU as cap_prod_group,
CASNR as cas_no_pharm,
GPNUM as prodcom_no,
STEUC as control_code,
FABKZ as jit_indicator,
MATGR as mat_grouping,
VSPVB as proposed_s_area,
DPLFS as fair_share_rule,
DPLPU as push_distribution,
DPLHO as deploymnt_hrzn,
MINLS as min_lot_size_1,
MAXLS as max_lot_size_1,
FIXLS as fix_lot_size,
LTINC as lot_size_incr,
COMPL as this_field_is_no_longer_used,
CONVT as conv_type,
SHPRO as st_per_profile,
AHDIS as mrp_dep_reqmts,
DIBER as mrp_area_exists,
KZPSP as cross_project,
OCMPF as overall_profile,
APOKZ as relevant_to_apo,
MCRUE as mardh_rec_already_exists_for,
LFMON as current_period,
LFGJA as year_cur_period,
EISLO as min_safetystock,
NCOST as do_not_cost,
ROTATION_DATE as putaway_stkrmvl,
UCHKZ as ob_management,
UCMAT as ob_ref_matrial,
EXCISE_TAX_RLVNCE as excise_tax_relevance_indicator,
BWESB as val_gr_blocked_stck,
SGT_COVS as seg_strategy,
SGT_STATC as seg_status_mrp,
SGT_SCOPE as seg_scope,
SGT_MRPSI as sort_stk_method,
SGT_PRCM as cons_prio,
SGT_CHINT as discr_batch_no,
SGT_STK_PRT as stk_prot,
SGT_DEFSC as def_segment,
SGT_MRP_ATP_STATUS as atp_mrp_status,
SGT_MMSTD as valid_from_1,
FSH_MG_ARUN_REQ as arun,
FSH_SEAIM as season_act_im,
FSH_VAR_GROUP as variant_group,
FSH_KZECH as batch_assignment,
FSH_CALENDAR_GROUP as calendar_group,
ARUN_FIX_BATCH as assign_batches,
PPSKZ as advanced_planning,
CONS_PROCG as consign_control,
GI_PR_TIME as gi_proc_time,
MULTIPLE_EKGRP as across_purch_group,
REF_SCHEMA as deter_schema,
MIN_TROC as minimum_target_range,
MAX_TROC as maximum_target_range,
TARGET_STOCK as target_stock,
NF_FLAG as nf_metals,
__CWM__UMLMC as stock_in_tfr_1,
__CWM__TRAME as stk_in_transit_1,
__CWM__BWESB as val_gr_blocked_stck_1,
SCM_MATLOCID_GUID16 as product,
SCM_MATLOCID_GUID22 as loc_prod_id,
SCM_GRPRT as gr_processng_time,
SCM_GIPRT as gi_processng_time,
SCM_SCOST as prod_stor_costs,
SCM_RELDT as repl_lead_time,
SCM_RRP_TYPE as pp_plng_proced,
SCM_HEUR_ID as heuristic,
SCM_PACKAGE_ID as plan_package,
SCM_SSPEN as safety_stk_pen,
SCM_GET_ALERTS as product_alerts,
SCM_RES_NET_NAME as network_name,
SCM_CONHAP as gr_handlg_cap_cons,
SCM_HUNIT as uom_handlcap_gr,
SCM_CONHAP_OUT as gi_handlg_cap_cons,
SCM_HUNIT_OUT as uom_handlcap_gi,
SCM_SHELF_LIFE_LOC as shelf_life_loc,
SCM_SHELF_LIFE_DUR as loc_shelf_life,
SCM_MATURITY_DUR as loc_matur_time,
SCM_SHLF_LFE_REQ_MIN as min_shelf_life,
SCM_SHLF_LFE_REQ_MAX as max_shelf_life,
SCM_LSUOM as lot_size_unit,
SCM_REORD_DUR as reorder_ds,
SCM_TARGET_DUR as trgt_days_sup,
SCM_TSTRID as per_ls_plng_cal,
SCM_STRA1 as requirement_str,
SCM_PEG_PAST_ALERT as pegg_alertback,
SCM_PEG_FUTURE_ALERT as pegg_alert,
SCM_PEG_STRATEGY as peggng_strategy,
SCM_PEG_WO_ALERT_FST as avoid_alerts,
SCM_FIXPEG_PROD_SET as fixed_pegging,
SCM_WHATBOM as plan_explosion,
SCM_RRP_SEL_GROUP as planning_group,
SCM_INTSRC_PROF as profile,
SCM_PRIO as priority,
SCM_MIN_PASS_AMOUNT as min_passing_amt,
SCM_PROFID as conversion_rule,
SCM_GES_MNG_USE as entire_receipt,
SCM_GES_BST_USE as entire_stock,
SCM_THRUPUT_TIME as throughput_time,
SCM_TPOP as tpop,
SCM_SAFTY_V as safety_stock_for_vcl,
SCM_PPSAFTYSTK as sft_parent_location,
SCM_PPSAFTYSTK_V as sft_parent_loc_vcl,
SCM_REPSAFTY as rep_safety_st,
SCM_REPSAFTY_V as rep_sft_f_vcl,
SCM_REORD_V as reord_point_vcl,
SCM_MAXSTOCK_V as maximum_stock_vcl,
SCM_SCOST_PRCNT as holding_cost_factor,
SCM_PROC_COST as procuremt_costs,
SCM_NDCOSTWE as gr_costs,
SCM_NDCOSTWA as gi_costs,
DUMMY_PLNT_INCL_EEW_PS as md_product_plant_extensible_fi,
__SAPMP__TOLPRPL as tolerance_plus,
__SAPMP__TOLPRMI as tol_minus,
__STTPEC__SERVALID as serialized_from,
__VSO__R_PKGRP as packing_group,
__VSO__R_LANE_NUM as picking_line,
__VSO__R_PAL_VEND as matno_pkm_ve,
__VSO__R_FORK_DIR as pick_pkm_length,
IUID_RELEVANT as iuid_relevant,
IUID_TYPE as iuid_type,
UID_IEA as ext_allocation,
DPCBT as su_btch_default_val,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct marc.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.marc` as marc
where marc._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'plant_data'),0))
select client as client_key,
material as material_key,
plant as plant_key,
*
From  marc
UNION ALL
select null as client_key,
null as material_key,
null as plant_key,
marc.*
From marc as marc
INNER JOIN `sap-adapter.slt_staging.plant_data` as uji
ON marc.client = uji.client
AND marc.material = uji.material
AND marc.plant = uji.plant
AND marc.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.material_key = tgt.material
AND src.plant_key = tgt.plant
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
material,
plant,
maint_status,
df_plant_level,
valuation_cat,
batches,
p_s_matl_status,
valid_from,
abc_indicator,
critical_part,
purch_group,
unit_of_issue,
mrp_profile,
mrp_type,
mrp_controller,
mrpctrllr_buyer,
pl_deliv_time,
gr_proc_time,
period_ind,
assembly_scrap,
lot_sizing_procedure,
procurement,
specprocurement,
reorder_point,
safety_stock,
min_lot_size,
max_lot_size,
fixed_lot_size,
rounding_value,
max_stock_level,
lsi_costs,
indiv_coll,
storage_costs,
selectionmethod,
discontin_ind,
eff_out_date,
follow_up_matl,
reqmts_grouping,
mixed_mrp,
schedmargin_key,
autom_fix_pl_ords,
autom_release,
backflush,
prodn_supervisor,
processing_time,
setup_time,
interoperation,
base_quantity,
inhseprodtime,
max_storage,
time_unit,
withd_fm_pr_bin,
rough_cut_plng,
overdely_tol,
unlimited,
underdely_tol,
total_rl_time,
replacemt_part,
surcharge,
state_of_manufac,
post_to_insp_stk,
sample,
quarantine,
qm_control_key,
mean_insp_dur,
insp_plan_ind,
doc_required,
active_subst,
insp_interval,
next_inspection,
stock_in_tfr,
loading_group,
batch_mgmt_rqt_plnt,
quota_arr_usage,
service_level,
splitting_ind,
plan_version,
object_type,
object_id,
avail_check,
fi_year_variant,
corr_factors,
setup_time_1,
base_quantity_1,
processing_time_1,
deactivated,
supply_source,
autom_po,
source_list,
commodity_code,
ctry_of_origin,
reg_of_origin,
comm_code_unit,
intrastat_group,
profit_center,
stk_in_transit,
plng_calendar,
repetitive_mfg,
plng_time_fence,
consmption_mode,
bwd_cons_per,
fwd_cons_period,
version,
alternative,
usage,
group_key_list,
group_counter,
cstg_lot_size,
specproctype,
production_unit,
prod_stor_loc,
mrp_group,
component_scrap,
certificatetype,
insp_setup,
takt_time,
coverage_prof,
field_name,
cc_phys_inv,
variance_key,
serialnoprofile,
int_object_no,
confble_matl,
rem_profile,
neg_stocks,
target_qm_sys,
planning_cycle,
rnding_profile,
ref_matl_cons,
ref_plant_cons,
date_to,
multiplier,
autom_reset,
cus_preference,
exemption_cert,
exempt_cert_no,
iss_date_of_crt,
vendor_decl,
vdr_decl_date,
military_goods,
service_level_1,
co_product,
strategy_group,
int_object_no_1,
stor_loc_ep,
bulk_material,
cc_ind_fixed,
stock_det_grp,
qm_mat_auth,
adjustmt_period,
task_list_type,
uom_group,
conv_group,
air_buoy_fact,
prod_sched_profile,
safety_time_ind,
safety_time,
action_control,
enter_batch,
uom_group_1,
mat_freight_grp,
backfl_profile,
stk_transfer_sv,
st_in_trans_sp,
smth_prom_cons,
prod_version,
fixed_price_co_prod,
logistics_group,
dist_prof,
tied_empties,
slsval_tiedempt,
mat_category,
eu_prod_list_no,
cap_prod_group,
cas_no_pharm,
prodcom_no,
control_code,
jit_indicator,
mat_grouping,
proposed_s_area,
fair_share_rule,
push_distribution,
deploymnt_hrzn,
min_lot_size_1,
max_lot_size_1,
fix_lot_size,
lot_size_incr,
this_field_is_no_longer_used,
conv_type,
st_per_profile,
mrp_dep_reqmts,
mrp_area_exists,
cross_project,
overall_profile,
relevant_to_apo,
mardh_rec_already_exists_for,
current_period,
year_cur_period,
min_safetystock,
do_not_cost,
putaway_stkrmvl,
ob_management,
ob_ref_matrial,
excise_tax_relevance_indicator,
val_gr_blocked_stck,
seg_strategy,
seg_status_mrp,
seg_scope,
sort_stk_method,
cons_prio,
discr_batch_no,
stk_prot,
def_segment,
atp_mrp_status,
valid_from_1,
arun,
season_act_im,
variant_group,
batch_assignment,
calendar_group,
assign_batches,
advanced_planning,
consign_control,
gi_proc_time,
across_purch_group,
deter_schema,
minimum_target_range,
maximum_target_range,
target_stock,
nf_metals,
stock_in_tfr_1,
stk_in_transit_1,
val_gr_blocked_stck_1,
product,
loc_prod_id,
gr_processng_time,
gi_processng_time,
prod_stor_costs,
repl_lead_time,
pp_plng_proced,
heuristic,
plan_package,
safety_stk_pen,
product_alerts,
network_name,
gr_handlg_cap_cons,
uom_handlcap_gr,
gi_handlg_cap_cons,
uom_handlcap_gi,
shelf_life_loc,
loc_shelf_life,
loc_matur_time,
min_shelf_life,
max_shelf_life,
lot_size_unit,
reorder_ds,
trgt_days_sup,
per_ls_plng_cal,
requirement_str,
pegg_alertback,
pegg_alert,
peggng_strategy,
avoid_alerts,
fixed_pegging,
plan_explosion,
planning_group,
profile,
priority,
min_passing_amt,
conversion_rule,
entire_receipt,
entire_stock,
throughput_time,
tpop,
safety_stock_for_vcl,
sft_parent_location,
sft_parent_loc_vcl,
rep_safety_st,
rep_sft_f_vcl,
reord_point_vcl,
maximum_stock_vcl,
holding_cost_factor,
procuremt_costs,
gr_costs,
gi_costs,
md_product_plant_extensible_fi,
tolerance_plus,
tol_minus,
serialized_from,
packing_group,
picking_line,
matno_pkm_ve,
pick_pkm_length,
iuid_relevant,
iuid_type,
ext_allocation,
su_btch_default_val,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.material,
src.plant,
src.maint_status,
src.df_plant_level,
src.valuation_cat,
src.batches,
src.p_s_matl_status,
src.valid_from,
src.abc_indicator,
src.critical_part,
src.purch_group,
src.unit_of_issue,
src.mrp_profile,
src.mrp_type,
src.mrp_controller,
src.mrpctrllr_buyer,
src.pl_deliv_time,
src.gr_proc_time,
src.period_ind,
src.assembly_scrap,
src.lot_sizing_procedure,
src.procurement,
src.specprocurement,
src.reorder_point,
src.safety_stock,
src.min_lot_size,
src.max_lot_size,
src.fixed_lot_size,
src.rounding_value,
src.max_stock_level,
src.lsi_costs,
src.indiv_coll,
src.storage_costs,
src.selectionmethod,
src.discontin_ind,
src.eff_out_date,
src.follow_up_matl,
src.reqmts_grouping,
src.mixed_mrp,
src.schedmargin_key,
src.autom_fix_pl_ords,
src.autom_release,
src.backflush,
src.prodn_supervisor,
src.processing_time,
src.setup_time,
src.interoperation,
src.base_quantity,
src.inhseprodtime,
src.max_storage,
src.time_unit,
src.withd_fm_pr_bin,
src.rough_cut_plng,
src.overdely_tol,
src.unlimited,
src.underdely_tol,
src.total_rl_time,
src.replacemt_part,
src.surcharge,
src.state_of_manufac,
src.post_to_insp_stk,
src.sample,
src.quarantine,
src.qm_control_key,
src.mean_insp_dur,
src.insp_plan_ind,
src.doc_required,
src.active_subst,
src.insp_interval,
src.next_inspection,
src.stock_in_tfr,
src.loading_group,
src.batch_mgmt_rqt_plnt,
src.quota_arr_usage,
src.service_level,
src.splitting_ind,
src.plan_version,
src.object_type,
src.object_id,
src.avail_check,
src.fi_year_variant,
src.corr_factors,
src.setup_time_1,
src.base_quantity_1,
src.processing_time_1,
src.deactivated,
src.supply_source,
src.autom_po,
src.source_list,
src.commodity_code,
src.ctry_of_origin,
src.reg_of_origin,
src.comm_code_unit,
src.intrastat_group,
src.profit_center,
src.stk_in_transit,
src.plng_calendar,
src.repetitive_mfg,
src.plng_time_fence,
src.consmption_mode,
src.bwd_cons_per,
src.fwd_cons_period,
src.version,
src.alternative,
src.usage,
src.group_key_list,
src.group_counter,
src.cstg_lot_size,
src.specproctype,
src.production_unit,
src.prod_stor_loc,
src.mrp_group,
src.component_scrap,
src.certificatetype,
src.insp_setup,
src.takt_time,
src.coverage_prof,
src.field_name,
src.cc_phys_inv,
src.variance_key,
src.serialnoprofile,
src.int_object_no,
src.confble_matl,
src.rem_profile,
src.neg_stocks,
src.target_qm_sys,
src.planning_cycle,
src.rnding_profile,
src.ref_matl_cons,
src.ref_plant_cons,
src.date_to,
src.multiplier,
src.autom_reset,
src.cus_preference,
src.exemption_cert,
src.exempt_cert_no,
src.iss_date_of_crt,
src.vendor_decl,
src.vdr_decl_date,
src.military_goods,
src.service_level_1,
src.co_product,
src.strategy_group,
src.int_object_no_1,
src.stor_loc_ep,
src.bulk_material,
src.cc_ind_fixed,
src.stock_det_grp,
src.qm_mat_auth,
src.adjustmt_period,
src.task_list_type,
src.uom_group,
src.conv_group,
src.air_buoy_fact,
src.prod_sched_profile,
src.safety_time_ind,
src.safety_time,
src.action_control,
src.enter_batch,
src.uom_group_1,
src.mat_freight_grp,
src.backfl_profile,
src.stk_transfer_sv,
src.st_in_trans_sp,
src.smth_prom_cons,
src.prod_version,
src.fixed_price_co_prod,
src.logistics_group,
src.dist_prof,
src.tied_empties,
src.slsval_tiedempt,
src.mat_category,
src.eu_prod_list_no,
src.cap_prod_group,
src.cas_no_pharm,
src.prodcom_no,
src.control_code,
src.jit_indicator,
src.mat_grouping,
src.proposed_s_area,
src.fair_share_rule,
src.push_distribution,
src.deploymnt_hrzn,
src.min_lot_size_1,
src.max_lot_size_1,
src.fix_lot_size,
src.lot_size_incr,
src.this_field_is_no_longer_used,
src.conv_type,
src.st_per_profile,
src.mrp_dep_reqmts,
src.mrp_area_exists,
src.cross_project,
src.overall_profile,
src.relevant_to_apo,
src.mardh_rec_already_exists_for,
src.current_period,
src.year_cur_period,
src.min_safetystock,
src.do_not_cost,
src.putaway_stkrmvl,
src.ob_management,
src.ob_ref_matrial,
src.excise_tax_relevance_indicator,
src.val_gr_blocked_stck,
src.seg_strategy,
src.seg_status_mrp,
src.seg_scope,
src.sort_stk_method,
src.cons_prio,
src.discr_batch_no,
src.stk_prot,
src.def_segment,
src.atp_mrp_status,
src.valid_from_1,
src.arun,
src.season_act_im,
src.variant_group,
src.batch_assignment,
src.calendar_group,
src.assign_batches,
src.advanced_planning,
src.consign_control,
src.gi_proc_time,
src.across_purch_group,
src.deter_schema,
src.minimum_target_range,
src.maximum_target_range,
src.target_stock,
src.nf_metals,
src.stock_in_tfr_1,
src.stk_in_transit_1,
src.val_gr_blocked_stck_1,
src.product,
src.loc_prod_id,
src.gr_processng_time,
src.gi_processng_time,
src.prod_stor_costs,
src.repl_lead_time,
src.pp_plng_proced,
src.heuristic,
src.plan_package,
src.safety_stk_pen,
src.product_alerts,
src.network_name,
src.gr_handlg_cap_cons,
src.uom_handlcap_gr,
src.gi_handlg_cap_cons,
src.uom_handlcap_gi,
src.shelf_life_loc,
src.loc_shelf_life,
src.loc_matur_time,
src.min_shelf_life,
src.max_shelf_life,
src.lot_size_unit,
src.reorder_ds,
src.trgt_days_sup,
src.per_ls_plng_cal,
src.requirement_str,
src.pegg_alertback,
src.pegg_alert,
src.peggng_strategy,
src.avoid_alerts,
src.fixed_pegging,
src.plan_explosion,
src.planning_group,
src.profile,
src.priority,
src.min_passing_amt,
src.conversion_rule,
src.entire_receipt,
src.entire_stock,
src.throughput_time,
src.tpop,
src.safety_stock_for_vcl,
src.sft_parent_location,
src.sft_parent_loc_vcl,
src.rep_safety_st,
src.rep_sft_f_vcl,
src.reord_point_vcl,
src.maximum_stock_vcl,
src.holding_cost_factor,
src.procuremt_costs,
src.gr_costs,
src.gi_costs,
src.md_product_plant_extensible_fi,
src.tolerance_plus,
src.tol_minus,
src.serialized_from,
src.packing_group,
src.picking_line,
src.matno_pkm_ve,
src.pick_pkm_length,
src.iuid_relevant,
src.iuid_type,
src.ext_allocation,
src.su_btch_default_val,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'plant_data' as table_name
    		,'marc' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'plant_data') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'plant_data') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.plant_data`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.plant_data` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'plant_data'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.plant_data`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    