MERGE INTO `sap-adapter.slt_staging.material_master` tgt
USING (
WITH mara as
(select MANDT as client,
MATNR as material,
ERSDA as created_on,
CREATED_AT_TIME as created_time,
ERNAM as created_by,
LAEDA as last_change,
AENAM as changed_by,
VPSTA as complete_status,
PSTAT as maint_status,
LVORM as df_client_level,
MTART as material_type,
MBRSH as industry_sector,
MATKL as material_group,
BISMT as old_matl_number,
MEINS as base_unit,
BSTME as order_unit,
ZEINR as document,
ZEIAR as document_type,
ZEIVR as doc_version,
ZEIFO as page_format,
AESZN as doc_change_no,
BLATT as page_number,
BLANZ as no_of_sheets,
FERTH as prod_insp_memo,
FORMT as page_format_1,
GROES as size_dimensions,
WRKST as basic_material,
NORMT as ind_std_desc,
LABOR as lab_office,
EKWSL as purch_value_key,
BRGEW as gross_weight,
NTGEW as net_weight,
GEWEI as weight_unit,
VOLUM as volume,
VOLEH as volume_unit,
BEHVO as container,
RAUBE as stor_conditions,
TEMPB as temperature,
DISST as low_level_code,
TRAGR as trans_group,
STOFF as haz_matl_no,
SPART as division,
KUNNR as competitor,
EANNR as ean_number,
WESCH as gr_slips_quantity,
BWVOR as procure_rule,
BWSCL as supply_source,
SAISO as season,
ETIAR as label_type,
ETIFO as label_form,
ENTAR as field_deact,
EAN11 as ean_upc,
NUMTP as ean_category,
LAENG as length_obj,
BREIT as width,
HOEHE as height,
MEABM as unit,
PRDHA as prod_hierarchy,
AEKLK as net_change_cstg,
CADKZ as cad_indicator,
QMPUR as qm_procurement,
ERGEW as allowed_pkg_wt,
ERGEI as unit_of_weight,
ERVOL as allowed_volume,
ERVOE as volume_unit_1,
GEWTO as excess_wt_tolerance,
VOLTO as excess_volume_tol,
VABME as var_order_unit,
KZREV as revision_level,
KZKFG as configurable,
XCHPF as batch_mgmt_rqt,
VHART as packag_mat_type,
FUELG as maximum_level,
STFAK as stacking_factor,
MAGRV as matl_grp_pckmat,
BEGRU as authorizgroup,
DATAB as valid_from,
LIQDT as valid_to,
SAISJ as season_year,
PLGTP as price_band_cat,
MLGUT as w_empties_bom,
EXTWG as ext_matl_group,
SATNR as cross_plant_cm,
ATTYP as matl_category,
KZKUP as co_product,
KZNFM as follow_up_matl,
PMATA as pr_ref_matl,
MSTAE as x_plant_status,
MSTAV as x_dchain_status,
MSTDE as valid_from_1,
MSTDV as valid_from_2,
TAKLV as tax_class,
RBNRM as catalog_profile,
MHDRZ as rem_shelf_life,
MHDHB as tot_shelf_life,
MHDLP as storage,
INHME as content_unit,
INHAL as net_contents,
VPREH as comp_price_unit,
ETIAG as label_matl_grpg,
INHBR as gross_contents,
CMETH as conv_method,
CUOBF as int_object_no,
KZUMW as envt_relevant,
KOSCH as prod_allocation,
SPROF as pricing_profile,
NRFHG as disc_in_kind,
MFRPN as mfr_part_number,
MFRNR as manufacturer,
BMATN as int_material_no,
MPROF as mfr_part_profile,
KZWSM as units_meas_use,
SAITY as rollout,
PROFL as dgindprofile,
IHIVI as highly_viscous,
ILOOS as in_bulk_liquid,
SERLV as serializlevel,
KZGVH as closed,
XGCHP as batch_rec_req,
KZEFF as assign_eff_vals,
COMPL as comp_level,
IPRKZ as period_ind,
RDMHD as rounding_rule,
PRZUS as prodcomposition,
MTPOS_MARA as genitemcatgroup,
BFLME as log_variants,
MATFI as material_locked,
CMREL as cm_relevant,
BBTYP as astmt_list_type,
SLED_BBD as expiration_date,
GTIN_VARIANT as ean_variant,
GENNR as genericmaterial,
RMATP as ref_mat_for_pckg,
GDS_RELEVANT as gds_relevant,
WEORA as origin_accept,
HUTYP_DFLT as stand_hu_type,
PILFERABLE as pilferable,
WHSTC as wh_stor_cond,
WHMATGR as wh_mat_grp,
HNDLCODE as handling_ind,
HAZMAT as haz_sub,
HUTYP as hutyp,
TARE_VAR as variable_tw,
MAXC as max_capacity,
MAXC_TOL as overcapac_tol,
MAXL as max_length,
MAXB as max_pack_width,
MAXH as max_height,
MAXDIM_UOM as unit_of_measure,
HERKL as ctry_of_origin,
MFRGR as mat_freight_grp,
QQTIME as quarant_per,
QQTIMEUOM as time_unit,
QGRP as qual_insp_grp,
SERIAL as serial_no_prf,
PS_SMARTFORM as form_name,
LOGUNIT as logistics_uom,
CWQREL as cw_relevant,
CWQPROC as cw_profile,
CWQTOLGR as catch_wt_tol_grp,
ADPROF as adjust_profile,
IPMIPPRODUCT as intel_property,
ALLOW_PMAT_IGNO as var_price_allowed,
MEDIUM as medium,
COMMODITY as commodity,
ANIMAL_ORIGIN as animal_origin,
TEXTILE_COMP_IND as texcompactive,
LAST_CHANGED_TIME as last_chgd_time,
MATNR_EXTERNAL as material_1,
CHML_CMPLNC_RLVNCE_IND as chemical_compliance_relevance,
LOGISTICAL_MAT_CATEGORY as logl_material_cat,
SALES_MATERIAL as sales_material_no,
IDENTIFICATION_TAG_TYPE as tag_type,
SGT_CSGR as seg_structure,
SGT_COVSA as seg_strategy,
SGT_STAT as seg_status,
SGT_SCOPE as seg_scope,
SGT_REL as seg_relevant,
ANP as anp_code,
PSM_CODE as psm_code,
FSH_MG_AT1 as fsh_attribute1,
FSH_MG_AT2 as fsh_attribute2,
FSH_MG_AT3 as fsh_attribute3,
FSH_SEALV as season_usage,
FSH_SEAIM as season_act_im,
FSH_SC_MID as mat_conv_id,
DUMMY_PRD_INCL_EEW_PS as dummy_field,
SCM_MATID_GUID16 as product,
SCM_MATID_GUID22 as product_id,
SCM_MATURITY_DUR as maturation_time,
SCM_SHLF_LFE_REQ_MIN as req_min_sh_life,
SCM_SHLF_LFE_REQ_MAX as req_max_sh_life,
SCM_PUOM as preferred_uom,
RMATP_PB as reference_product,
PROD_SHAPE as product_shape,
MO_PROFILE_ID as prod_orient_prof,
OVERHANG_TRESH as overhang_threshold,
BRIDGE_TRESH as bridge_threshold,
BRIDGE_MAX_SLOPE as maximum_slope,
HEIGHT_NONFLAT as abs_height_thresh,
HEIGHT_NONFLAT_UOM as abs_height_thresh_1,
SCM_KITCOMP as product_for_kito,
SCM_PROD_PAOOPT as procure_to_order,
SCM_BOD_DEPLVL as push_depl_fr_supp,
SCM_RESTRICT_INVBAL as no_inv_balancing,
SCM_DRP_GL_STOCK as glb_stk_entry_loc,
SCM_EXCL_EXPEDITE as no_express_shipment,
__CWM__XCWMAT as cw_material,
__CWM__VALUM as valuation_uom,
__CWM__TOLGR as tolerance_group,
__CWM__TARA as fixed_tare,
__CWM__TARUM as tare_calc,
__BEV1__LULEINH as loading_units,
__BEV1__LULDEGRP as loading_unit_group,
__BEV1__NESTRUCCAT as struct_category,
__DSD__SL_TOLTYP as tolerance_type,
__DSD__SV_CNT_GRP as counting_group,
__DSD__VC_GROUP as dsd_grouping,
__SAPMP__KADU as cable_diameter,
__SAPMP__ABMEIN as unit_for_dimensions,
__SAPMP__KADP as cabdia_allow,
__SAPMP__BRAD as bending_factor,
__SAPMP__SPBI as inner_width,
__SAPMP__TRAD as outer_diameter,
__SAPMP__KEDU as core_diameter,
__SAPMP__SPTR as load_capacity,
__SAPMP__FBDK as r_o_flange_thick,
__SAPMP__FBHK as r_o_flange_height,
__SAPMP__RILI as coil_delivery,
__SAPMP__FBAK as run_out_flange,
__SAPMP__AHO as no_vert_layers,
__SAPMP__MIFRR as clearance,
__STTPEC__SERTYPE as serialization_type,
__STTPEC__SYNCACT as sync_active,
__STTPEC__SYNCTIME as last_synchronized,
__STTPEC__SYNCCHG as changed_since_int,
__STTPEC__COUNTRY_REF as prof_rel_country,
__STTPEC__PRDCAT as product_category,
__VSO__R_TILT_IND as tilting_allowed,
__VSO__R_STACK_IND as no_stacking,
__VSO__R_BOT_IND as bottom_layer,
__VSO__R_TOP_IND as top_layer,
__VSO__R_STACK_NO as stacking_factor_1,
__VSO__R_PAL_IND as load_w_o_pkm,
__VSO__R_PAL_OVR_D as overhang_depth,
__VSO__R_PAL_OVR_W as overhang_width,
__VSO__R_PAL_B_HT as max_stack_hght,
__VSO__R_PAL_MIN_H as min_stack_hght,
__VSO__R_TOL_B_HT as stackh_toleran,
__VSO__R_NO_P_GVH as no_mat_pkm,
__VSO__R_QUAN_UNIT as uom_vso,
__VSO__R_KZGVH_IND as closed_pkm_req,
PACKCODE as packaging_code,
DG_PACK_STATUS as dg_pckg_status,
SRV_DURA as work_duration,
SRV_DURA_UOM as unit_1,
SRV_SERWI as service_profile,
SRV_ESCAL as response_prof,
SOM_CYCLE as billing_cycle,
SOM_CYCLE_RULE as billing_cycle_determ,
SOM_TC_SCHEMA as assignment_schema,
MCOND as condition_mgmt,
RETDELC as return_code,
LOGLEV_RETO as return_to_log_level,
NSNID as nsn,
ICFA as ammunition_code,
RIC_ID as ric_id,
OVLPN as overlength_part_num,
ADSPC_SPC as spare_prt_class_code,
VARID as var_obj_id,
MSBOOKPARTNO as ms_book_part_no,
DPCBT as su_btch_default_val,
XGRDT as sng_un_bch_rcp,
IMATN as fff_class,
PICNUM as chain_no,
BSTAT as creation_status,
COLOR_ATINN as internal_char,
SIZE1_ATINN as internal_char_1,
SIZE2_ATINN as internal_char_2,
COLOR as color,
SIZE1 as main_size,
SIZE2 as second_size,
FREE_CHAR as char_value,
CARE_CODE as care_code,
BRAND_ID as brand,
FIBER_CODE1 as component_1,
FIBER_PART1 as perc_share_1,
FIBER_CODE2 as component_2,
FIBER_PART2 as perc_share_2,
FIBER_CODE3 as component_3,
FIBER_PART3 as perc_share_3,
FIBER_CODE4 as component_4,
FIBER_PART4 as perc_share_4,
FIBER_CODE5 as component_5,
FIBER_PART5 as perc_share_5,
FASHGRD as fashion_grade,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct mara.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.mara` as mara
where mara._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'material_master'),0))
select client as client_key,
material as material_key,
*
From  mara
UNION ALL
select null as client_key,
null as material_key,
mara.*
From mara as mara
INNER JOIN `sap-adapter.slt_staging.material_master` as uji
ON mara.client = uji.client
AND mara.material = uji.material
AND mara.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.material_key = tgt.material
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
material,
created_on,
created_time,
created_by,
last_change,
changed_by,
complete_status,
maint_status,
df_client_level,
material_type,
industry_sector,
material_group,
old_matl_number,
base_unit,
order_unit,
document,
document_type,
doc_version,
page_format,
doc_change_no,
page_number,
no_of_sheets,
prod_insp_memo,
page_format_1,
size_dimensions,
basic_material,
ind_std_desc,
lab_office,
purch_value_key,
gross_weight,
net_weight,
weight_unit,
volume,
volume_unit,
container,
stor_conditions,
temperature,
low_level_code,
trans_group,
haz_matl_no,
division,
competitor,
ean_number,
gr_slips_quantity,
procure_rule,
supply_source,
season,
label_type,
label_form,
field_deact,
ean_upc,
ean_category,
length_obj,
width,
height,
unit,
prod_hierarchy,
net_change_cstg,
cad_indicator,
qm_procurement,
allowed_pkg_wt,
unit_of_weight,
allowed_volume,
volume_unit_1,
excess_wt_tolerance,
excess_volume_tol,
var_order_unit,
revision_level,
configurable,
batch_mgmt_rqt,
packag_mat_type,
maximum_level,
stacking_factor,
matl_grp_pckmat,
authorizgroup,
valid_from,
valid_to,
season_year,
price_band_cat,
w_empties_bom,
ext_matl_group,
cross_plant_cm,
matl_category,
co_product,
follow_up_matl,
pr_ref_matl,
x_plant_status,
x_dchain_status,
valid_from_1,
valid_from_2,
tax_class,
catalog_profile,
rem_shelf_life,
tot_shelf_life,
storage,
content_unit,
net_contents,
comp_price_unit,
label_matl_grpg,
gross_contents,
conv_method,
int_object_no,
envt_relevant,
prod_allocation,
pricing_profile,
disc_in_kind,
mfr_part_number,
manufacturer,
int_material_no,
mfr_part_profile,
units_meas_use,
rollout,
dgindprofile,
highly_viscous,
in_bulk_liquid,
serializlevel,
closed,
batch_rec_req,
assign_eff_vals,
comp_level,
period_ind,
rounding_rule,
prodcomposition,
genitemcatgroup,
log_variants,
material_locked,
cm_relevant,
astmt_list_type,
expiration_date,
ean_variant,
genericmaterial,
ref_mat_for_pckg,
gds_relevant,
origin_accept,
stand_hu_type,
pilferable,
wh_stor_cond,
wh_mat_grp,
handling_ind,
haz_sub,
hutyp,
variable_tw,
max_capacity,
overcapac_tol,
max_length,
max_pack_width,
max_height,
unit_of_measure,
ctry_of_origin,
mat_freight_grp,
quarant_per,
time_unit,
qual_insp_grp,
serial_no_prf,
form_name,
logistics_uom,
cw_relevant,
cw_profile,
catch_wt_tol_grp,
adjust_profile,
intel_property,
var_price_allowed,
medium,
commodity,
animal_origin,
texcompactive,
last_chgd_time,
material_1,
chemical_compliance_relevance,
logl_material_cat,
sales_material_no,
tag_type,
seg_structure,
seg_strategy,
seg_status,
seg_scope,
seg_relevant,
anp_code,
psm_code,
fsh_attribute1,
fsh_attribute2,
fsh_attribute3,
season_usage,
season_act_im,
mat_conv_id,
dummy_field,
product,
product_id,
maturation_time,
req_min_sh_life,
req_max_sh_life,
preferred_uom,
reference_product,
product_shape,
prod_orient_prof,
overhang_threshold,
bridge_threshold,
maximum_slope,
abs_height_thresh,
abs_height_thresh_1,
product_for_kito,
procure_to_order,
push_depl_fr_supp,
no_inv_balancing,
glb_stk_entry_loc,
no_express_shipment,
cw_material,
valuation_uom,
tolerance_group,
fixed_tare,
tare_calc,
loading_units,
loading_unit_group,
struct_category,
tolerance_type,
counting_group,
dsd_grouping,
cable_diameter,
unit_for_dimensions,
cabdia_allow,
bending_factor,
inner_width,
outer_diameter,
core_diameter,
load_capacity,
r_o_flange_thick,
r_o_flange_height,
coil_delivery,
run_out_flange,
no_vert_layers,
clearance,
serialization_type,
sync_active,
last_synchronized,
changed_since_int,
prof_rel_country,
product_category,
tilting_allowed,
no_stacking,
bottom_layer,
top_layer,
stacking_factor_1,
load_w_o_pkm,
overhang_depth,
overhang_width,
max_stack_hght,
min_stack_hght,
stackh_toleran,
no_mat_pkm,
uom_vso,
closed_pkm_req,
packaging_code,
dg_pckg_status,
work_duration,
unit_1,
service_profile,
response_prof,
billing_cycle,
billing_cycle_determ,
assignment_schema,
condition_mgmt,
return_code,
return_to_log_level,
nsn,
ammunition_code,
ric_id,
overlength_part_num,
spare_prt_class_code,
var_obj_id,
ms_book_part_no,
su_btch_default_val,
sng_un_bch_rcp,
fff_class,
chain_no,
creation_status,
internal_char,
internal_char_1,
internal_char_2,
color,
main_size,
second_size,
char_value,
care_code,
brand,
component_1,
perc_share_1,
component_2,
perc_share_2,
component_3,
perc_share_3,
component_4,
perc_share_4,
component_5,
perc_share_5,
fashion_grade,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.material,
src.created_on,
src.created_time,
src.created_by,
src.last_change,
src.changed_by,
src.complete_status,
src.maint_status,
src.df_client_level,
src.material_type,
src.industry_sector,
src.material_group,
src.old_matl_number,
src.base_unit,
src.order_unit,
src.document,
src.document_type,
src.doc_version,
src.page_format,
src.doc_change_no,
src.page_number,
src.no_of_sheets,
src.prod_insp_memo,
src.page_format_1,
src.size_dimensions,
src.basic_material,
src.ind_std_desc,
src.lab_office,
src.purch_value_key,
src.gross_weight,
src.net_weight,
src.weight_unit,
src.volume,
src.volume_unit,
src.container,
src.stor_conditions,
src.temperature,
src.low_level_code,
src.trans_group,
src.haz_matl_no,
src.division,
src.competitor,
src.ean_number,
src.gr_slips_quantity,
src.procure_rule,
src.supply_source,
src.season,
src.label_type,
src.label_form,
src.field_deact,
src.ean_upc,
src.ean_category,
src.length_obj,
src.width,
src.height,
src.unit,
src.prod_hierarchy,
src.net_change_cstg,
src.cad_indicator,
src.qm_procurement,
src.allowed_pkg_wt,
src.unit_of_weight,
src.allowed_volume,
src.volume_unit_1,
src.excess_wt_tolerance,
src.excess_volume_tol,
src.var_order_unit,
src.revision_level,
src.configurable,
src.batch_mgmt_rqt,
src.packag_mat_type,
src.maximum_level,
src.stacking_factor,
src.matl_grp_pckmat,
src.authorizgroup,
src.valid_from,
src.valid_to,
src.season_year,
src.price_band_cat,
src.w_empties_bom,
src.ext_matl_group,
src.cross_plant_cm,
src.matl_category,
src.co_product,
src.follow_up_matl,
src.pr_ref_matl,
src.x_plant_status,
src.x_dchain_status,
src.valid_from_1,
src.valid_from_2,
src.tax_class,
src.catalog_profile,
src.rem_shelf_life,
src.tot_shelf_life,
src.storage,
src.content_unit,
src.net_contents,
src.comp_price_unit,
src.label_matl_grpg,
src.gross_contents,
src.conv_method,
src.int_object_no,
src.envt_relevant,
src.prod_allocation,
src.pricing_profile,
src.disc_in_kind,
src.mfr_part_number,
src.manufacturer,
src.int_material_no,
src.mfr_part_profile,
src.units_meas_use,
src.rollout,
src.dgindprofile,
src.highly_viscous,
src.in_bulk_liquid,
src.serializlevel,
src.closed,
src.batch_rec_req,
src.assign_eff_vals,
src.comp_level,
src.period_ind,
src.rounding_rule,
src.prodcomposition,
src.genitemcatgroup,
src.log_variants,
src.material_locked,
src.cm_relevant,
src.astmt_list_type,
src.expiration_date,
src.ean_variant,
src.genericmaterial,
src.ref_mat_for_pckg,
src.gds_relevant,
src.origin_accept,
src.stand_hu_type,
src.pilferable,
src.wh_stor_cond,
src.wh_mat_grp,
src.handling_ind,
src.haz_sub,
src.hutyp,
src.variable_tw,
src.max_capacity,
src.overcapac_tol,
src.max_length,
src.max_pack_width,
src.max_height,
src.unit_of_measure,
src.ctry_of_origin,
src.mat_freight_grp,
src.quarant_per,
src.time_unit,
src.qual_insp_grp,
src.serial_no_prf,
src.form_name,
src.logistics_uom,
src.cw_relevant,
src.cw_profile,
src.catch_wt_tol_grp,
src.adjust_profile,
src.intel_property,
src.var_price_allowed,
src.medium,
src.commodity,
src.animal_origin,
src.texcompactive,
src.last_chgd_time,
src.material_1,
src.chemical_compliance_relevance,
src.logl_material_cat,
src.sales_material_no,
src.tag_type,
src.seg_structure,
src.seg_strategy,
src.seg_status,
src.seg_scope,
src.seg_relevant,
src.anp_code,
src.psm_code,
src.fsh_attribute1,
src.fsh_attribute2,
src.fsh_attribute3,
src.season_usage,
src.season_act_im,
src.mat_conv_id,
src.dummy_field,
src.product,
src.product_id,
src.maturation_time,
src.req_min_sh_life,
src.req_max_sh_life,
src.preferred_uom,
src.reference_product,
src.product_shape,
src.prod_orient_prof,
src.overhang_threshold,
src.bridge_threshold,
src.maximum_slope,
src.abs_height_thresh,
src.abs_height_thresh_1,
src.product_for_kito,
src.procure_to_order,
src.push_depl_fr_supp,
src.no_inv_balancing,
src.glb_stk_entry_loc,
src.no_express_shipment,
src.cw_material,
src.valuation_uom,
src.tolerance_group,
src.fixed_tare,
src.tare_calc,
src.loading_units,
src.loading_unit_group,
src.struct_category,
src.tolerance_type,
src.counting_group,
src.dsd_grouping,
src.cable_diameter,
src.unit_for_dimensions,
src.cabdia_allow,
src.bending_factor,
src.inner_width,
src.outer_diameter,
src.core_diameter,
src.load_capacity,
src.r_o_flange_thick,
src.r_o_flange_height,
src.coil_delivery,
src.run_out_flange,
src.no_vert_layers,
src.clearance,
src.serialization_type,
src.sync_active,
src.last_synchronized,
src.changed_since_int,
src.prof_rel_country,
src.product_category,
src.tilting_allowed,
src.no_stacking,
src.bottom_layer,
src.top_layer,
src.stacking_factor_1,
src.load_w_o_pkm,
src.overhang_depth,
src.overhang_width,
src.max_stack_hght,
src.min_stack_hght,
src.stackh_toleran,
src.no_mat_pkm,
src.uom_vso,
src.closed_pkm_req,
src.packaging_code,
src.dg_pckg_status,
src.work_duration,
src.unit_1,
src.service_profile,
src.response_prof,
src.billing_cycle,
src.billing_cycle_determ,
src.assignment_schema,
src.condition_mgmt,
src.return_code,
src.return_to_log_level,
src.nsn,
src.ammunition_code,
src.ric_id,
src.overlength_part_num,
src.spare_prt_class_code,
src.var_obj_id,
src.ms_book_part_no,
src.su_btch_default_val,
src.sng_un_bch_rcp,
src.fff_class,
src.chain_no,
src.creation_status,
src.internal_char,
src.internal_char_1,
src.internal_char_2,
src.color,
src.main_size,
src.second_size,
src.char_value,
src.care_code,
src.brand,
src.component_1,
src.perc_share_1,
src.component_2,
src.perc_share_2,
src.component_3,
src.perc_share_3,
src.component_4,
src.perc_share_4,
src.component_5,
src.perc_share_5,
src.fashion_grade,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'material_master' as table_name
    		,'mara' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'material_master') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'material_master') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.material_master`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.material_master` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'material_master'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.material_master`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    