MERGE INTO `sap-adapter.slt_staging.shipment_header_details` tgt
USING (
WITH vttk as
(select MANDT as client,
TKNUM as shipment_number,
VBTYP as document_cat,
SHTYP as shipment_type,
TPLST as transportplanpt,
ERNAM as created_by,
ERDAT as created_on,
ERZET as entry_time,
AENAM as changed_by,
AEDAT as changed_on,
AEZET as time_of_change,
STERM as determine_legs,
ABFER as shpmtcompltype,
ABWST as processcontrol,
BFART as service_level,
VSART as shipping_type,
VSAVL as shtypeprelimleg,
VSANL as subseqlegshtype,
LAUFK as leg_indicator,
VSBED as shp_cond,
ROUTE as shipment_route,
SIGNI as container_id,
EXTI1 as external_id_1,
EXTI2 as external_id_2,
TPBEZ as description,
STDIS as planned,
DTDIS as planning_end,
UZDIS as scheduling_end,
STREG as check_in,
DPREG as plancheckindate,
UPREG as plannedtimechin,
DAREG as act_date_chkin,
UAREG as currenttmechkin,
STLBG as loading_start,
DPLBG as planloadstart,
UPLBG as planloadsttime,
DALBG as curr_load_start,
UALBG as actloadstrttime,
STLAD as loading_end,
DPLEN as planloadingend,
UPLEN as planloadendtime,
DALEN as act_load_end,
UALEN as actloadendtime,
STABF as shpmt_compl,
DPABF as planshpcmpldte,
UPABF as pl_time_proc,
DTABF as dateshpmntcmpl,
UZABF as timetrspprocess,
STTBG as shipment_start,
DPTBG as planshipstart,
UPTBG as plantranssttime,
DATBG as currshipmtstart,
UATBG as acttranspstrttm,
STTEN as shipment_end,
DPTEN as planshipmentend,
UPTEN as plantransendtim,
DATEN as act_shipmentend,
UATEN as actshipmtendtim,
STTRG as overall_status,
TDLNR as service_agent,
TERNR as order_number,
PKSTK as handling_units,
DTMEG as weight_unit,
DTMEV as volume_unit,
DISTZ as distance,
MEDST as uom_distance,
FAHZT as travel_time,
GESZT as total_time,
MEIZT as trav_times,
STAFO as update_group,
FBSTA as shipm_csts_cal,
FBGST as ovsts_shcostcal,
ARSTA as shpmt_costs_set,
ARGST as tot_shp_cst_stm,
STERM_DONE as legs_determined,
VSE_FRK as ship_units_shpcostd,
KKALSM as pricing_procedure,
SDABW as spec_processing,
FRKRL as shpmntcostsrel,
GESZTD as planned_total_time,
FAHZTD as planned_act_durat,
GESZTDA as actual_total_time,
FAHZTDA as actual_duration,
ROCPY_DONE as route_from_del,
HANDLE as handle,
TSEGFL as tsegment_exists,
TSEGTP as template,
ADD01 as suppl_1,
ADD02 as suppl_2,
ADD03 as suppl_3,
ADD04 as suppl_4,
TEXT1 as addit_text_1,
TEXT2 as addit_text_2,
TEXT3 as addit_text_3,
TEXT4 as addit_text_4,
PROLI as dg_mgmt_profile,
DGTLOCK as block_ind_dg,
DGMDDAT as selection_date,
CONT_DG as contains_dg,
WARZTD as planned_waiting_time,
WARZTDA as curr_waiting_time,
AULWE as route_schedule,
TNDRST as tender_status,
TNDRRC as acccnd_rjctrsn,
TNDR_TEXT as tendering_text,
TNDRDAT as date_tender_st,
TNDRZET as time_tender,
TNDR_MAXP as maximum_price,
TNDR_MAXC as currency,
TNDR_ACTP as actual_costs,
TNDR_ACTC as currency_1,
TNDR_CARR as from_fdwg_agent,
TNDR_CRNM as name_of_carrier,
TNDR_TRKID as fa_tracking_id,
TNDR_EXPD as valid_to,
TNDR_EXPT as to_time,
TNDR_ERPD as earlypickupdate,
TNDR_ERPT as pickup_time,
TNDR_LTPD as latest_pickup,
TNDR_LTPT as time_1,
TNDR_ERDD as earl_del_date,
TNDR_ERDT as time_2,
TNDR_LTDD as latest_del_date,
TNDR_LTDT as time_3,
TNDR_LDLG as lgthloadingpltf,
TNDR_LDLU as uom_load_length,
KZHULFR as hus_di_relevant,
ALLOWED_TWGT as allow_tot_wght,
VLSTK as statdecntrlwhse,
VERURSYS as original_system,
CM_IDENT as identification,
CM_SEQUENCE as sequence,
EXT_FREIGHT_ORD as frg_ord_id,
EXT_TM_SYS as business_system,
__BEV1__RPFAR1 as driver_1,
__BEV1__RPFAR2 as driver_2,
__BEV1__RPMOWA as vehicle,
__BEV1__RPANHAE as trailer,
__BEV1__RPFLGNR as sequence_number,
__VSO__R_STATUS as vso_status,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct vttk.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.vttk` as vttk
where vttk._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'shipment_header_details'),0))
select client as client_key,
shipment_number as shipment_number_key,
*
From  vttk
UNION ALL
select null as client_key,
null as shipment_number_key,
vttk.*
From vttk as vttk
INNER JOIN `sap-adapter.slt_staging.shipment_header_details` as uji
ON vttk.client = uji.client
AND vttk.shipment_number = uji.shipment_number
AND vttk.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.shipment_number_key = tgt.shipment_number
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
shipment_number,
document_cat,
shipment_type,
transportplanpt,
created_by,
created_on,
entry_time,
changed_by,
changed_on,
time_of_change,
determine_legs,
shpmtcompltype,
processcontrol,
service_level,
shipping_type,
shtypeprelimleg,
subseqlegshtype,
leg_indicator,
shp_cond,
shipment_route,
container_id,
external_id_1,
external_id_2,
description,
planned,
planning_end,
scheduling_end,
check_in,
plancheckindate,
plannedtimechin,
act_date_chkin,
currenttmechkin,
loading_start,
planloadstart,
planloadsttime,
curr_load_start,
actloadstrttime,
loading_end,
planloadingend,
planloadendtime,
act_load_end,
actloadendtime,
shpmt_compl,
planshpcmpldte,
pl_time_proc,
dateshpmntcmpl,
timetrspprocess,
shipment_start,
planshipstart,
plantranssttime,
currshipmtstart,
acttranspstrttm,
shipment_end,
planshipmentend,
plantransendtim,
act_shipmentend,
actshipmtendtim,
overall_status,
service_agent,
order_number,
handling_units,
weight_unit,
volume_unit,
distance,
uom_distance,
travel_time,
total_time,
trav_times,
update_group,
shipm_csts_cal,
ovsts_shcostcal,
shpmt_costs_set,
tot_shp_cst_stm,
legs_determined,
ship_units_shpcostd,
pricing_procedure,
spec_processing,
shpmntcostsrel,
planned_total_time,
planned_act_durat,
actual_total_time,
actual_duration,
route_from_del,
handle,
tsegment_exists,
template,
suppl_1,
suppl_2,
suppl_3,
suppl_4,
addit_text_1,
addit_text_2,
addit_text_3,
addit_text_4,
dg_mgmt_profile,
block_ind_dg,
selection_date,
contains_dg,
planned_waiting_time,
curr_waiting_time,
route_schedule,
tender_status,
acccnd_rjctrsn,
tendering_text,
date_tender_st,
time_tender,
maximum_price,
currency,
actual_costs,
currency_1,
from_fdwg_agent,
name_of_carrier,
fa_tracking_id,
valid_to,
to_time,
earlypickupdate,
pickup_time,
latest_pickup,
time_1,
earl_del_date,
time_2,
latest_del_date,
time_3,
lgthloadingpltf,
uom_load_length,
hus_di_relevant,
allow_tot_wght,
statdecntrlwhse,
original_system,
identification,
sequence,
frg_ord_id,
business_system,
driver_1,
driver_2,
vehicle,
trailer,
sequence_number,
vso_status,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.shipment_number,
src.document_cat,
src.shipment_type,
src.transportplanpt,
src.created_by,
src.created_on,
src.entry_time,
src.changed_by,
src.changed_on,
src.time_of_change,
src.determine_legs,
src.shpmtcompltype,
src.processcontrol,
src.service_level,
src.shipping_type,
src.shtypeprelimleg,
src.subseqlegshtype,
src.leg_indicator,
src.shp_cond,
src.shipment_route,
src.container_id,
src.external_id_1,
src.external_id_2,
src.description,
src.planned,
src.planning_end,
src.scheduling_end,
src.check_in,
src.plancheckindate,
src.plannedtimechin,
src.act_date_chkin,
src.currenttmechkin,
src.loading_start,
src.planloadstart,
src.planloadsttime,
src.curr_load_start,
src.actloadstrttime,
src.loading_end,
src.planloadingend,
src.planloadendtime,
src.act_load_end,
src.actloadendtime,
src.shpmt_compl,
src.planshpcmpldte,
src.pl_time_proc,
src.dateshpmntcmpl,
src.timetrspprocess,
src.shipment_start,
src.planshipstart,
src.plantranssttime,
src.currshipmtstart,
src.acttranspstrttm,
src.shipment_end,
src.planshipmentend,
src.plantransendtim,
src.act_shipmentend,
src.actshipmtendtim,
src.overall_status,
src.service_agent,
src.order_number,
src.handling_units,
src.weight_unit,
src.volume_unit,
src.distance,
src.uom_distance,
src.travel_time,
src.total_time,
src.trav_times,
src.update_group,
src.shipm_csts_cal,
src.ovsts_shcostcal,
src.shpmt_costs_set,
src.tot_shp_cst_stm,
src.legs_determined,
src.ship_units_shpcostd,
src.pricing_procedure,
src.spec_processing,
src.shpmntcostsrel,
src.planned_total_time,
src.planned_act_durat,
src.actual_total_time,
src.actual_duration,
src.route_from_del,
src.handle,
src.tsegment_exists,
src.template,
src.suppl_1,
src.suppl_2,
src.suppl_3,
src.suppl_4,
src.addit_text_1,
src.addit_text_2,
src.addit_text_3,
src.addit_text_4,
src.dg_mgmt_profile,
src.block_ind_dg,
src.selection_date,
src.contains_dg,
src.planned_waiting_time,
src.curr_waiting_time,
src.route_schedule,
src.tender_status,
src.acccnd_rjctrsn,
src.tendering_text,
src.date_tender_st,
src.time_tender,
src.maximum_price,
src.currency,
src.actual_costs,
src.currency_1,
src.from_fdwg_agent,
src.name_of_carrier,
src.fa_tracking_id,
src.valid_to,
src.to_time,
src.earlypickupdate,
src.pickup_time,
src.latest_pickup,
src.time_1,
src.earl_del_date,
src.time_2,
src.latest_del_date,
src.time_3,
src.lgthloadingpltf,
src.uom_load_length,
src.hus_di_relevant,
src.allow_tot_wght,
src.statdecntrlwhse,
src.original_system,
src.identification,
src.sequence,
src.frg_ord_id,
src.business_system,
src.driver_1,
src.driver_2,
src.vehicle,
src.trailer,
src.sequence_number,
src.vso_status,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'shipment_header_details' as table_name
    		,'vttk' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'shipment_header_details') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'shipment_header_details') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.shipment_header_details`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.shipment_header_details` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'shipment_header_details'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.shipment_header_details`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    