MERGE INTO `sap-adapter.slt_staging.production_order_item_details` tgt
USING (
WITH afpo as
(select MANDT as client,
AUFNR as order_number,
POSNR as order_item_no,
PSOBS as spec_procuremt,
QUNUM as quota_arr,
QUPOS as quota_arr_item,
PROJN as wbs_element,
PLNUM as planned_order,
STRMP as plnd_start_date,
ETRMP as plnd_open_date,
KDAUF as sales_order,
KDPOS as sales_ord_item,
KDEIN as sorder_schedule,
BESKZ as procurement,
PSAMG as planned_scrap,
PSMNG as total_quantity,
WEMNG as gr_quantity,
IAMNG as expectvarrecipt,
AMEIN as order_un,
MEINS as base_unit,
MATNR as material,
PAMNG as scrap_quantity,
PGMNG as order_quantity,
KNTTP as acct_assgmt_cat,
TPAUF as partial_convrs,
LTRMI as delivery_date,
LTRMP as planned_delivery,
KALNR as cost_estimateno,
UEBTO as overdeliv_tol,
UEBTK as unlimited,
UNTTO as underdel_tol,
INSMK as stock_type,
WEPOS as goods_receipt,
BWTAR as valuation_type,
BWTTY as valuation_cat,
PWERK as planning_plant,
LGORT as stor_loc,
UMREZ as counter,
UMREN as denominator,
WEBAZ as gr_proc_time,
ELIKZ as deliv_compl,
SAFNR as rs_header,
VERID as prod_version,
SERNR as bom_expl_number,
TECHS as standardvariant,
DWERK as plant,
DAUTY as order_category,
DAUAT as order_type,
DGLTP as basic_fin_date,
DGLTS as sched_finish,
DFREI as release_ind,
DNREL as not_relevant,
VERTO as distribution,
SOBKZ as special_stock,
KZVBR as consumption,
WEWRT as gr_value,
WEUNB as gr_non_valuated,
ABLAD as unloading_point,
WEMPF as recipient,
CHARG as batch,
GSBER as business_area,
WEAED as gr_can_change,
CUOBJ as int_object_no,
KBNKZ as kanban_indicat,
ARSNR as settle_reser_no,
ARSPS as settle_item_no,
KRSNR as reservation_number,
KRSPS as item_no,
KCKEY as cost_collector,
RTP01 as repetitive_mfg,
RTP02 as kanban,
RTP03 as sales_ord_stock,
RTP04 as external_ppc,
KSVON as valid_from,
KSBIS as valid_to,
OBJNP as object_number,
NDISR as not_relevant_1,
VFMNG as committed,
GSBTR as commitment_date,
KZAVC as type_avail_chck,
KZBWS as valuation,
XLOEK as deletion_flag,
SERNP as serialnoprofile,
ANZSN as no_serial_no,
OBJTYPE as changeind,
CH_PROC as changeproctype,
FXPRU as fixed_price_co_prod,
CUOBJ_ROOT as int_object_no_1,
BERID as mrp_area,
TECHS_COPY as standardvariant_1,
SGT_SCAT as stock_segment,
KUNNR2 as customer,
FSH_SEASON_YEAR as season_year,
FSH_SEASON as season,
FSH_COLLECTION as collection,
FSH_THEME as theme,
FSH_SALLOC_QTY as allocated_stock,
MILL_OC_AUFNR_U as original_order,
MILL_OC_RUMNG as confirmed_qty,
MILL_OC_SORT as sequence,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct afpo.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.afpo` as afpo
where afpo._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'production_order_item_details'),0))
select client as client_key,
order_number as order_number_key,
order_item_no as order_item_no_key,
*
From  afpo
UNION ALL
select null as client_key,
null as order_number_key,
null as order_item_no_key,
afpo.*
From afpo as afpo
INNER JOIN `sap-adapter.slt_staging.production_order_item_details` as uji
ON afpo.client = uji.client
AND afpo.order_number = uji.order_number
AND afpo.order_item_no = uji.order_item_no
AND afpo.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.order_number_key = tgt.order_number
AND src.order_item_no_key = tgt.order_item_no
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
order_number,
order_item_no,
spec_procuremt,
quota_arr,
quota_arr_item,
wbs_element,
planned_order,
plnd_start_date,
plnd_open_date,
sales_order,
sales_ord_item,
sorder_schedule,
procurement,
planned_scrap,
total_quantity,
gr_quantity,
expectvarrecipt,
order_un,
base_unit,
material,
scrap_quantity,
order_quantity,
acct_assgmt_cat,
partial_convrs,
delivery_date,
planned_delivery,
cost_estimateno,
overdeliv_tol,
unlimited,
underdel_tol,
stock_type,
goods_receipt,
valuation_type,
valuation_cat,
planning_plant,
stor_loc,
counter,
denominator,
gr_proc_time,
deliv_compl,
rs_header,
prod_version,
bom_expl_number,
standardvariant,
plant,
order_category,
order_type,
basic_fin_date,
sched_finish,
release_ind,
not_relevant,
distribution,
special_stock,
consumption,
gr_value,
gr_non_valuated,
unloading_point,
recipient,
batch,
business_area,
gr_can_change,
int_object_no,
kanban_indicat,
settle_reser_no,
settle_item_no,
reservation_number,
item_no,
cost_collector,
repetitive_mfg,
kanban,
sales_ord_stock,
external_ppc,
valid_from,
valid_to,
object_number,
not_relevant_1,
committed,
commitment_date,
type_avail_chck,
valuation,
deletion_flag,
serialnoprofile,
no_serial_no,
changeind,
changeproctype,
fixed_price_co_prod,
int_object_no_1,
mrp_area,
standardvariant_1,
stock_segment,
customer,
season_year,
season,
collection,
theme,
allocated_stock,
original_order,
confirmed_qty,
sequence,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.order_number,
src.order_item_no,
src.spec_procuremt,
src.quota_arr,
src.quota_arr_item,
src.wbs_element,
src.planned_order,
src.plnd_start_date,
src.plnd_open_date,
src.sales_order,
src.sales_ord_item,
src.sorder_schedule,
src.procurement,
src.planned_scrap,
src.total_quantity,
src.gr_quantity,
src.expectvarrecipt,
src.order_un,
src.base_unit,
src.material,
src.scrap_quantity,
src.order_quantity,
src.acct_assgmt_cat,
src.partial_convrs,
src.delivery_date,
src.planned_delivery,
src.cost_estimateno,
src.overdeliv_tol,
src.unlimited,
src.underdel_tol,
src.stock_type,
src.goods_receipt,
src.valuation_type,
src.valuation_cat,
src.planning_plant,
src.stor_loc,
src.counter,
src.denominator,
src.gr_proc_time,
src.deliv_compl,
src.rs_header,
src.prod_version,
src.bom_expl_number,
src.standardvariant,
src.plant,
src.order_category,
src.order_type,
src.basic_fin_date,
src.sched_finish,
src.release_ind,
src.not_relevant,
src.distribution,
src.special_stock,
src.consumption,
src.gr_value,
src.gr_non_valuated,
src.unloading_point,
src.recipient,
src.batch,
src.business_area,
src.gr_can_change,
src.int_object_no,
src.kanban_indicat,
src.settle_reser_no,
src.settle_item_no,
src.reservation_number,
src.item_no,
src.cost_collector,
src.repetitive_mfg,
src.kanban,
src.sales_ord_stock,
src.external_ppc,
src.valid_from,
src.valid_to,
src.object_number,
src.not_relevant_1,
src.committed,
src.commitment_date,
src.type_avail_chck,
src.valuation,
src.deletion_flag,
src.serialnoprofile,
src.no_serial_no,
src.changeind,
src.changeproctype,
src.fixed_price_co_prod,
src.int_object_no_1,
src.mrp_area,
src.standardvariant_1,
src.stock_segment,
src.customer,
src.season_year,
src.season,
src.collection,
src.theme,
src.allocated_stock,
src.original_order,
src.confirmed_qty,
src.sequence,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'production_order_item_details' as table_name
    		,'afpo' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'production_order_item_details') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'production_order_item_details') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.production_order_item_details`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.production_order_item_details` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'production_order_item_details'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.production_order_item_details`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    