MERGE INTO `sap-adapter.slt_staging.delivery_item` tgt
USING (
WITH lips as
(select MANDT as client,
VBELN as delivery,
POSNR as item,
PSTYV as item_category,
ERNAM as created_by,
ERZET as entry_time,
ERDAT as created_on,
MATNR as material,
MATWA as materialentered,
MATKL as material_group,
WERKS as plant,
LGORT as stor_loc,
CHARG as batch,
LICHN as supplier_batch,
KDMAT as customer_mat,
PRODH as prod_hierarchy,
LFIMG as delivery_qty,
MEINS as base_unit,
VRKME as sales_unit,
UMVKZ as numerator,
UMVKN as denominat,
NTGEW as net_weight,
BRGEW as gross_weight,
GEWEI as weight_unit,
VOLUM as volume,
VOLEH as volume_unit,
KZTLF as part_dlv_item,
UEBTK as unlimited,
UEBTO as overdeliv_tol,
UNTTO as underdel_tol,
CHSPL as batch_split,
FAKSP as billing_block,
MBDAT as mat_avail_date,
LGMNG as qty_stckp_unt,
ARKTX as item_descr,
LGPBE as storage_bin,
VBELV as originating_doc,
POSNV as item_1,
VBTYV as document_cat,
VGSYS as prdoclogsys,
VGBEL as reference_doc,
VGPOS as reference_item,
UPFLU as update_doc_flow,
UEPOS as higher_lev_item,
FKREL as relev_for_bill,
LADGR as loading_group,
TRAGR as trans_group,
KOMKZ as picking_id,
LGNUM as warehouse_no,
LISPL as whse_no_split,
LGTYP as storage_type,
LGPLA as storage_bin_1,
BWTEX as separate_val,
BWART as movement_type,
BWLVS as movement_type_1,
KZDLG as ind_dynamic_bin,
BDART as requirementtype,
PLART as planning_type,
MTART as material_type,
XCHPF as batch_mgmt_rqt,
XCHAR as batches,
VGREF as preced_with_ref,
POSAR as item_type,
BWTAR as valuation_type,
SUMBD as req_mt_totals,
MTVFP as avail_check,
EANNR as ean_number,
GSBER as business_area,
VKBUR as sales_office,
VKGRP as sales_group,
VTWEG as distr_channel,
SPART as division,
GRKOR as delivery_group,
FMENG as qty_is_fixed,
ANTLF as max_part_deliv,
VBEAF as fixed_proc_time,
VBEAV as var_proc_time,
STAFO as update_group,
WAVWR as cost,
KZWI1 as subtotal_1,
KZWI2 as subtotal_2,
KZWI3 as subtotal_3,
KZWI4 as subtotal_4,
KZWI5 as subtotal_5,
KZWI6 as subtotal_6,
SOBKZ as special_stock,
AEDAT as changed_on,
EAN11 as ean_upc,
KVGR1 as customer_grp_1,
KVGR2 as customer_grp_2,
KVGR3 as customer_grp_3,
KVGR4 as customer_grp_4,
KVGR5 as customer_grp_5,
MVGR1 as materialgroup_1,
MVGR2 as materialgroup_2,
MVGR3 as materialgroup_3,
MVGR4 as materialgroup_4,
MVGR5 as materialgroup_5,
VPZUO as allocation_ind,
VGTYP as prec_doc_categ,
RFVGTYP as preceddoccentrl,
KOSTL as cost_center,
KOKRS as co_area,
PAOBJNR as profit_segment,
PRCTR as profit_center,
PS_PSP_PNR as wbs_element,
AUFNR as order_number,
POSNR_PP as order_item_no,
KDAUF as sales_order,
KDPOS as sales_ord_item,
VPMAT as plng_material,
VPWRK as planning_plant,
PRBME as prod_grp_unit,
UMREF as conversion,
KNTTP as acct_assgmt_cat,
KZVBR as consumption,
FIPOS as commitment_item,
FISTL as funds_center,
GEBER as fund,
PCKPF as packing_control,
BEDAR_LF as reqmts_class,
CMPNT as credit_active,
KCMENG as cumul_batch_qty,
KCBRGEW as cum_gross_wght,
KCNTGEW as cumul_net_wght,
KCVOLUM as cumul_volume,
UECHA as hghlevitmbatch,
CUOBJ as configuration,
CUOBJ_CH as int_object_no,
ANZSN as no_serial_no,
SERAIL as serialnoprofile,
KCGEWEI as weight_unit_1,
KCVOLEH as volume_unit_1,
SERNR as bom_expl_number,
ABRLI as int_dlv_scd_no,
ABART as release_type,
ABRVW as usage,
QPLOS as inspection_lot,
QTLOS as partial_lot,
NACHL as no_gr_posted,
MAGRV as matl_grp_pckmat,
OBJKO as object_no_hdr,
OBJPO as objno_item,
AESKD as engin_change,
SHKZG as returns_item,
PROSA as matdetermactive,
UEPVW as usage_hl_item,
EMPST as recv_point,
ABTNR as department,
KOQUI as confirmation,
STADAT as statistics_date,
AKTNR as promotion,
KNUMH_CH as nocondrec_batch,
PREFE as cus_preference,
EXART as bus_trans_type,
CLINT as int_class_no,
CHMVS as qty_proposal,
ABELN as alloc_table,
ABELP as item_2,
LFIMG_FLO as internal_field_do_not_use,
LGMNG_FLO as internal_field_do_not_use_1,
KCMENG_FLO as internal_field_do_not_use_2,
KZUMW as envt_relevant,
KMPMG as quantity,
AUREL as at_relevant,
KPEIN as pricing_unit,
KMEIN as unit_of_measure,
NETPR as net_price,
NETWR as net_value,
KOWRR as stat_value,
KZBEW as movement_ind,
MFRGR as mat_freight_grp,
CHHPV as pack_acc_batch,
ABFOR as paytguarantform,
ABGES as guaranteed,
MBUHR as matl_staging_tme,
WKTNR as value_contract_no,
WKTPS as val_cont_item,
J_1BCFOP as cfop,
J_1BTAXLW1 as icms_law,
J_1BTAXLW2 as ipi_law,
J_1BTXSDC as tax_code,
SITUA as situation,
RSNUM as reservation_number,
RSPOS as item_no,
RSART as record_type,
KANNR as sequence_number,
KZFME as leading_uom,
PROFL as dgindprofile,
KCMENGVME as cumul_batch_qty_1,
KCMENGVMEF as cumulated_batch_split_quantity,
KZBWS as valuation,
PSPNR as project_def,
EPRIO as withdr_seq_grp,
RULES as stk_determ_rule,
KZBEF as inv_mgmt_active,
MPROF as mfr_part_profile,
EMATN as mpn_material,
LGBZO as staging_area,
HANDLE as key,
VERURPOS as orig_item,
LIFEXPOS as ext_item,
NOATP as no_avail_check,
NOPCK as not_rel_picking,
RBLVS as refmvttype_wm,
BERID as mrp_area,
BESTQ as stock_category,
UMBSQ as stock_category_1,
UMMAT as receiving_mat,
UMWRK as receiving_plant,
UMLGO as receiving_sloc,
UMCHA as receiving_batch,
UMBAR as val_type_tfr,
UMSOK as sp_ind_st_tfr,
SONUM as spec_stock_no,
USONU as spec_stock_no_1,
AKKUR as lettofcredrate,
AKMNG as current_qty,
VKGRU as class_of_items,
SHKZG_UM as main_posting_id,
INSMK as stock_type,
KZECH as enter_batch,
FLGWM as indicator_copy_dest_storage,
BERKZ as staging_ind,
HUPOS as indicator_delivery_item_is_a,
NOWAB as no_gds_movement,
KONTO as g_l_account,
KZEAR as final_issue,
HSDAT as date_of_manuf,
VFDAT as sled_bbd,
LFGJA as year_cur_period,
LFBNR as reference_doc_1,
LFPOS as ref_doc_item,
GRUND as reason_for_mvt,
FOBWA as sub_movmnt_type,
DLVTP as delivery_cat,
EXBWR as ext_amount_lc,
BPMNG as qty_in_opun,
EXVKW as sales_value,
CMPRE_FLT as credit_price,
KZPOD as pod_indicator,
LFDEZ as not_wms_relevnt,
UMREV as conversionfactr,
PODREL as pod_rel_rc_sc,
KZUML as st_tfr_tfr_pst,
FKBER as functional_area,
GRANT_NBR as grants,
KZWSO as units_meas_use,
GMCONTROL as gds_mvmt_contrl,
POSTING_CHANGE as wbwkz,
UM_PS_PSP_PNR as trsfr_wbs_elmnt,
PRE_VL_ETENS as sequential_no,
SPE_GEN_ELIKZ as deliv_compl,
SPE_SCRAP_IND as scrap_indicator,
SPE_AUTH_NUMBER as rma_number,
SPE_INSPOUT_GUID as inspection_guid,
SPE_FOLLOW_UP as follow_up_code,
SPE_EXP_DATE_EXT as end_validity_period,
SPE_EXP_DATE_INT as end_internal_val,
SPE_AUTH_COMPLET as rma_no_completed,
ORMNG as delivery_qty_1,
SPE_ATP_TMSTMP as atp_time_stamp,
SPE_ORIG_SYS as original_system_type,
SPE_LIEFFZ as cq_vendor,
SPE_IMWRK as in_plant,
SPE_LIFEXPOS2 as ext_ident,
SPE_EXCEPT_CODE as except_code_wh,
SPE_KEEP_QTY as retention_qty,
SPE_ALTERNATE as alt_prodnr,
SPE_MAT_SUBST as reasn,
SPE_STRUC as structure,
SPE_APO_QNTYFAC as numerator_1,
SPE_APO_QNTYDIV as denominator,
SPE_HERKL as ctry_of_origin,
SPE_BXP_DATE_EXT as begin_valid_period,
SPE_VERSION as deliveryvsn,
SPE_COMPL_MVT as gm_completion,
J_1BTAXLW4 as cofins_law,
J_1BTAXLW5 as pis_law,
J_1BTAXLW3 as iss_law,
BUDGET_PD as budget_period,
KBNKZ as kanban_indicat,
FARR_RELTYPE as type,
SITKZ as spec_iss_val_sit,
SGT_RCAT as reqmnt_segment,
SGT_SCAT as stock_segment,
BESTA as confirmed,
CMPPI as financial_doc,
CMPPJ as exptcreditinsur,
FKIVP as interco_billst,
FKSTA as billing_status,
GBSTA as overall_status,
HDALL as dlyitemnotcomp,
KOQUA as confirmation_1,
KOSTA as picking_status,
LVSTA as wm_activ_status,
PDSTA as pod_status,
PKSTA as packing_status,
UVALL as item_3,
UVFAK as item_bill_data,
UVPAK as it_data_pckgng,
UVPIK as item_data_pck_putawy,
UVVLK as item_deliv_data,
UVWAK as item_data_gm,
VLSTP as decentr_whse,
WBSTA as goodsmovementst,
UVP01 as item_reserves_1,
UVP02 as item_reserves_2,
UVP03 as item_reserves_3,
UVP04 as item_reserves_4,
UVP05 as item_reserves_5,
EMCST as embargo_status,
SLCST as wls_status,
LCCST as ovr_status,
PCSTA as prod_marktablty_sts,
DGSTA as prod_marktablty_sts_1,
SDSSTA as sfty_data_sheet_sts,
__SAPMP__LBASP as dtucsta,
_DATAAGING as data_filter_value_for_data_agi,
__CWM__LFIMG as deliv_qty_puom,
__CWM__LFIME as cwm_duom,
__CWM__PIKMG as picked_qty_puom,
__CWM__PIKME as puom_qty_picked,
__CWM__XENTER as pq_entered,
__CWM__XTAENTER as to_entry,
__CWM__KCMENG as cum_cw_batch_qty,
__CWM__EBUMG as qty_to_post_in_puom,
DUMMY_DELITM_INCL_EEW_PS as dummy_function_in_length_1,
__KJEDM__INVERTED as inverted,
__SAPMP__LBA_NO as dtuc,
__SAPMP__ALT_CONV as prov_conv_fact,
LGTOR as door_for_whse,
FSH_SEASON_YEAR as season_year,
FSH_SEASON as season,
FSH_COLLECTION as collection,
FSH_THEME as theme,
FSH_KVGR6 as customer_grp_6,
FSH_KVGR7 as customer_grp_7,
FSH_KVGR8 as customer_grp_8,
FSH_KVGR9 as customer_grp_5_1,
FSH_KVGR10 as customer_grp_10,
FSH_VAS_REL as vas_relevant,
FSH_VAS_PRNT_ID as item_4,
FSH_TRANSACTION as transaction_number,
FSH_ITEM_GROUP as item_group,
FSH_ITEM as item_number,
FSH_RSNUM as reservation_1,
FSH_RSPOS as item_no_1,
MILL_UCDET as ob_purity,
CONS_ORDER as consignment,
WRF_CHARSTC1 as characteristic_1,
WRF_CHARSTC2 as characteristic_2,
WRF_CHARSTC3 as characteristic_3,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct lips.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.lips` as lips
where lips._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'delivery_item'),0))
select client as client_key,
delivery as delivery_key,
item as item_key,
*
From  lips
UNION ALL
select null as client_key,
null as delivery_key,
null as item_key,
lips.*
From lips as lips
INNER JOIN `sap-adapter.slt_staging.delivery_item` as uji
ON lips.client = uji.client
AND lips.delivery = uji.delivery
AND lips.item = uji.item
AND lips.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.delivery_key = tgt.delivery
AND src.item_key = tgt.item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
delivery,
item,
item_category,
created_by,
entry_time,
created_on,
material,
materialentered,
material_group,
plant,
stor_loc,
batch,
supplier_batch,
customer_mat,
prod_hierarchy,
delivery_qty,
base_unit,
sales_unit,
numerator,
denominat,
net_weight,
gross_weight,
weight_unit,
volume,
volume_unit,
part_dlv_item,
unlimited,
overdeliv_tol,
underdel_tol,
batch_split,
billing_block,
mat_avail_date,
qty_stckp_unt,
item_descr,
storage_bin,
originating_doc,
item_1,
document_cat,
prdoclogsys,
reference_doc,
reference_item,
update_doc_flow,
higher_lev_item,
relev_for_bill,
loading_group,
trans_group,
picking_id,
warehouse_no,
whse_no_split,
storage_type,
storage_bin_1,
separate_val,
movement_type,
movement_type_1,
ind_dynamic_bin,
requirementtype,
planning_type,
material_type,
batch_mgmt_rqt,
batches,
preced_with_ref,
item_type,
valuation_type,
req_mt_totals,
avail_check,
ean_number,
business_area,
sales_office,
sales_group,
distr_channel,
division,
delivery_group,
qty_is_fixed,
max_part_deliv,
fixed_proc_time,
var_proc_time,
update_group,
cost,
subtotal_1,
subtotal_2,
subtotal_3,
subtotal_4,
subtotal_5,
subtotal_6,
special_stock,
changed_on,
ean_upc,
customer_grp_1,
customer_grp_2,
customer_grp_3,
customer_grp_4,
customer_grp_5,
materialgroup_1,
materialgroup_2,
materialgroup_3,
materialgroup_4,
materialgroup_5,
allocation_ind,
prec_doc_categ,
preceddoccentrl,
cost_center,
co_area,
profit_segment,
profit_center,
wbs_element,
order_number,
order_item_no,
sales_order,
sales_ord_item,
plng_material,
planning_plant,
prod_grp_unit,
conversion,
acct_assgmt_cat,
consumption,
commitment_item,
funds_center,
fund,
packing_control,
reqmts_class,
credit_active,
cumul_batch_qty,
cum_gross_wght,
cumul_net_wght,
cumul_volume,
hghlevitmbatch,
configuration,
int_object_no,
no_serial_no,
serialnoprofile,
weight_unit_1,
volume_unit_1,
bom_expl_number,
int_dlv_scd_no,
release_type,
usage,
inspection_lot,
partial_lot,
no_gr_posted,
matl_grp_pckmat,
object_no_hdr,
objno_item,
engin_change,
returns_item,
matdetermactive,
usage_hl_item,
recv_point,
department,
confirmation,
statistics_date,
promotion,
nocondrec_batch,
cus_preference,
bus_trans_type,
int_class_no,
qty_proposal,
alloc_table,
item_2,
internal_field_do_not_use,
internal_field_do_not_use_1,
internal_field_do_not_use_2,
envt_relevant,
quantity,
at_relevant,
pricing_unit,
unit_of_measure,
net_price,
net_value,
stat_value,
movement_ind,
mat_freight_grp,
pack_acc_batch,
paytguarantform,
guaranteed,
matl_staging_tme,
value_contract_no,
val_cont_item,
cfop,
icms_law,
ipi_law,
tax_code,
situation,
reservation_number,
item_no,
record_type,
sequence_number,
leading_uom,
dgindprofile,
cumul_batch_qty_1,
cumulated_batch_split_quantity,
valuation,
project_def,
withdr_seq_grp,
stk_determ_rule,
inv_mgmt_active,
mfr_part_profile,
mpn_material,
staging_area,
key,
orig_item,
ext_item,
no_avail_check,
not_rel_picking,
refmvttype_wm,
mrp_area,
stock_category,
stock_category_1,
receiving_mat,
receiving_plant,
receiving_sloc,
receiving_batch,
val_type_tfr,
sp_ind_st_tfr,
spec_stock_no,
spec_stock_no_1,
lettofcredrate,
current_qty,
class_of_items,
main_posting_id,
stock_type,
enter_batch,
indicator_copy_dest_storage,
staging_ind,
indicator_delivery_item_is_a,
no_gds_movement,
g_l_account,
final_issue,
date_of_manuf,
sled_bbd,
year_cur_period,
reference_doc_1,
ref_doc_item,
reason_for_mvt,
sub_movmnt_type,
delivery_cat,
ext_amount_lc,
qty_in_opun,
sales_value,
credit_price,
pod_indicator,
not_wms_relevnt,
conversionfactr,
pod_rel_rc_sc,
st_tfr_tfr_pst,
functional_area,
grants,
units_meas_use,
gds_mvmt_contrl,
wbwkz,
trsfr_wbs_elmnt,
sequential_no,
deliv_compl,
scrap_indicator,
rma_number,
inspection_guid,
follow_up_code,
end_validity_period,
end_internal_val,
rma_no_completed,
delivery_qty_1,
atp_time_stamp,
original_system_type,
cq_vendor,
in_plant,
ext_ident,
except_code_wh,
retention_qty,
alt_prodnr,
reasn,
structure,
numerator_1,
denominator,
ctry_of_origin,
begin_valid_period,
deliveryvsn,
gm_completion,
cofins_law,
pis_law,
iss_law,
budget_period,
kanban_indicat,
type,
spec_iss_val_sit,
reqmnt_segment,
stock_segment,
confirmed,
financial_doc,
exptcreditinsur,
interco_billst,
billing_status,
overall_status,
dlyitemnotcomp,
confirmation_1,
picking_status,
wm_activ_status,
pod_status,
packing_status,
item_3,
item_bill_data,
it_data_pckgng,
item_data_pck_putawy,
item_deliv_data,
item_data_gm,
decentr_whse,
goodsmovementst,
item_reserves_1,
item_reserves_2,
item_reserves_3,
item_reserves_4,
item_reserves_5,
embargo_status,
wls_status,
ovr_status,
prod_marktablty_sts,
prod_marktablty_sts_1,
sfty_data_sheet_sts,
dtucsta,
data_filter_value_for_data_agi,
deliv_qty_puom,
cwm_duom,
picked_qty_puom,
puom_qty_picked,
pq_entered,
to_entry,
cum_cw_batch_qty,
qty_to_post_in_puom,
dummy_function_in_length_1,
inverted,
dtuc,
prov_conv_fact,
door_for_whse,
season_year,
season,
collection,
theme,
customer_grp_6,
customer_grp_7,
customer_grp_8,
customer_grp_5_1,
customer_grp_10,
vas_relevant,
item_4,
transaction_number,
item_group,
item_number,
reservation_1,
item_no_1,
ob_purity,
consignment,
characteristic_1,
characteristic_2,
characteristic_3,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.delivery,
src.item,
src.item_category,
src.created_by,
src.entry_time,
src.created_on,
src.material,
src.materialentered,
src.material_group,
src.plant,
src.stor_loc,
src.batch,
src.supplier_batch,
src.customer_mat,
src.prod_hierarchy,
src.delivery_qty,
src.base_unit,
src.sales_unit,
src.numerator,
src.denominat,
src.net_weight,
src.gross_weight,
src.weight_unit,
src.volume,
src.volume_unit,
src.part_dlv_item,
src.unlimited,
src.overdeliv_tol,
src.underdel_tol,
src.batch_split,
src.billing_block,
src.mat_avail_date,
src.qty_stckp_unt,
src.item_descr,
src.storage_bin,
src.originating_doc,
src.item_1,
src.document_cat,
src.prdoclogsys,
src.reference_doc,
src.reference_item,
src.update_doc_flow,
src.higher_lev_item,
src.relev_for_bill,
src.loading_group,
src.trans_group,
src.picking_id,
src.warehouse_no,
src.whse_no_split,
src.storage_type,
src.storage_bin_1,
src.separate_val,
src.movement_type,
src.movement_type_1,
src.ind_dynamic_bin,
src.requirementtype,
src.planning_type,
src.material_type,
src.batch_mgmt_rqt,
src.batches,
src.preced_with_ref,
src.item_type,
src.valuation_type,
src.req_mt_totals,
src.avail_check,
src.ean_number,
src.business_area,
src.sales_office,
src.sales_group,
src.distr_channel,
src.division,
src.delivery_group,
src.qty_is_fixed,
src.max_part_deliv,
src.fixed_proc_time,
src.var_proc_time,
src.update_group,
src.cost,
src.subtotal_1,
src.subtotal_2,
src.subtotal_3,
src.subtotal_4,
src.subtotal_5,
src.subtotal_6,
src.special_stock,
src.changed_on,
src.ean_upc,
src.customer_grp_1,
src.customer_grp_2,
src.customer_grp_3,
src.customer_grp_4,
src.customer_grp_5,
src.materialgroup_1,
src.materialgroup_2,
src.materialgroup_3,
src.materialgroup_4,
src.materialgroup_5,
src.allocation_ind,
src.prec_doc_categ,
src.preceddoccentrl,
src.cost_center,
src.co_area,
src.profit_segment,
src.profit_center,
src.wbs_element,
src.order_number,
src.order_item_no,
src.sales_order,
src.sales_ord_item,
src.plng_material,
src.planning_plant,
src.prod_grp_unit,
src.conversion,
src.acct_assgmt_cat,
src.consumption,
src.commitment_item,
src.funds_center,
src.fund,
src.packing_control,
src.reqmts_class,
src.credit_active,
src.cumul_batch_qty,
src.cum_gross_wght,
src.cumul_net_wght,
src.cumul_volume,
src.hghlevitmbatch,
src.configuration,
src.int_object_no,
src.no_serial_no,
src.serialnoprofile,
src.weight_unit_1,
src.volume_unit_1,
src.bom_expl_number,
src.int_dlv_scd_no,
src.release_type,
src.usage,
src.inspection_lot,
src.partial_lot,
src.no_gr_posted,
src.matl_grp_pckmat,
src.object_no_hdr,
src.objno_item,
src.engin_change,
src.returns_item,
src.matdetermactive,
src.usage_hl_item,
src.recv_point,
src.department,
src.confirmation,
src.statistics_date,
src.promotion,
src.nocondrec_batch,
src.cus_preference,
src.bus_trans_type,
src.int_class_no,
src.qty_proposal,
src.alloc_table,
src.item_2,
src.internal_field_do_not_use,
src.internal_field_do_not_use_1,
src.internal_field_do_not_use_2,
src.envt_relevant,
src.quantity,
src.at_relevant,
src.pricing_unit,
src.unit_of_measure,
src.net_price,
src.net_value,
src.stat_value,
src.movement_ind,
src.mat_freight_grp,
src.pack_acc_batch,
src.paytguarantform,
src.guaranteed,
src.matl_staging_tme,
src.value_contract_no,
src.val_cont_item,
src.cfop,
src.icms_law,
src.ipi_law,
src.tax_code,
src.situation,
src.reservation_number,
src.item_no,
src.record_type,
src.sequence_number,
src.leading_uom,
src.dgindprofile,
src.cumul_batch_qty_1,
src.cumulated_batch_split_quantity,
src.valuation,
src.project_def,
src.withdr_seq_grp,
src.stk_determ_rule,
src.inv_mgmt_active,
src.mfr_part_profile,
src.mpn_material,
src.staging_area,
src.key,
src.orig_item,
src.ext_item,
src.no_avail_check,
src.not_rel_picking,
src.refmvttype_wm,
src.mrp_area,
src.stock_category,
src.stock_category_1,
src.receiving_mat,
src.receiving_plant,
src.receiving_sloc,
src.receiving_batch,
src.val_type_tfr,
src.sp_ind_st_tfr,
src.spec_stock_no,
src.spec_stock_no_1,
src.lettofcredrate,
src.current_qty,
src.class_of_items,
src.main_posting_id,
src.stock_type,
src.enter_batch,
src.indicator_copy_dest_storage,
src.staging_ind,
src.indicator_delivery_item_is_a,
src.no_gds_movement,
src.g_l_account,
src.final_issue,
src.date_of_manuf,
src.sled_bbd,
src.year_cur_period,
src.reference_doc_1,
src.ref_doc_item,
src.reason_for_mvt,
src.sub_movmnt_type,
src.delivery_cat,
src.ext_amount_lc,
src.qty_in_opun,
src.sales_value,
src.credit_price,
src.pod_indicator,
src.not_wms_relevnt,
src.conversionfactr,
src.pod_rel_rc_sc,
src.st_tfr_tfr_pst,
src.functional_area,
src.grants,
src.units_meas_use,
src.gds_mvmt_contrl,
src.wbwkz,
src.trsfr_wbs_elmnt,
src.sequential_no,
src.deliv_compl,
src.scrap_indicator,
src.rma_number,
src.inspection_guid,
src.follow_up_code,
src.end_validity_period,
src.end_internal_val,
src.rma_no_completed,
src.delivery_qty_1,
src.atp_time_stamp,
src.original_system_type,
src.cq_vendor,
src.in_plant,
src.ext_ident,
src.except_code_wh,
src.retention_qty,
src.alt_prodnr,
src.reasn,
src.structure,
src.numerator_1,
src.denominator,
src.ctry_of_origin,
src.begin_valid_period,
src.deliveryvsn,
src.gm_completion,
src.cofins_law,
src.pis_law,
src.iss_law,
src.budget_period,
src.kanban_indicat,
src.type,
src.spec_iss_val_sit,
src.reqmnt_segment,
src.stock_segment,
src.confirmed,
src.financial_doc,
src.exptcreditinsur,
src.interco_billst,
src.billing_status,
src.overall_status,
src.dlyitemnotcomp,
src.confirmation_1,
src.picking_status,
src.wm_activ_status,
src.pod_status,
src.packing_status,
src.item_3,
src.item_bill_data,
src.it_data_pckgng,
src.item_data_pck_putawy,
src.item_deliv_data,
src.item_data_gm,
src.decentr_whse,
src.goodsmovementst,
src.item_reserves_1,
src.item_reserves_2,
src.item_reserves_3,
src.item_reserves_4,
src.item_reserves_5,
src.embargo_status,
src.wls_status,
src.ovr_status,
src.prod_marktablty_sts,
src.prod_marktablty_sts_1,
src.sfty_data_sheet_sts,
src.dtucsta,
src.data_filter_value_for_data_agi,
src.deliv_qty_puom,
src.cwm_duom,
src.picked_qty_puom,
src.puom_qty_picked,
src.pq_entered,
src.to_entry,
src.cum_cw_batch_qty,
src.qty_to_post_in_puom,
src.dummy_function_in_length_1,
src.inverted,
src.dtuc,
src.prov_conv_fact,
src.door_for_whse,
src.season_year,
src.season,
src.collection,
src.theme,
src.customer_grp_6,
src.customer_grp_7,
src.customer_grp_8,
src.customer_grp_5_1,
src.customer_grp_10,
src.vas_relevant,
src.item_4,
src.transaction_number,
src.item_group,
src.item_number,
src.reservation_1,
src.item_no_1,
src.ob_purity,
src.consignment,
src.characteristic_1,
src.characteristic_2,
src.characteristic_3,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'delivery_item' as table_name
    		,'lips' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'delivery_item') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'delivery_item') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.delivery_item`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.delivery_item` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'delivery_item'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.delivery_item`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    