MERGE INTO `sap-adapter.slt_staging.sales_document_business_data` tgt
USING (
WITH vbkd as
(select MANDT as client,
VBELN as sales_document,
POSNR as item,
KONDA as custprice_group,
KDGRP as customer_group,
BZIRK as sales_district,
PLTYP as price_list_tp,
INCO1 as incoterms,
INCO2 as incoterms_2,
KZAZU as order_combinat,
PERFK as invoicing_dates,
PERRL as inv_list_sched,
MRNKZ as man_inv_maint,
KURRF as exch_rate_acct,
VALTG as add_value_days,
VALDT as fixed_val_date,
ZTERM as payt_terms,
ZLSCH as payt_method,
KTGRD as accassmtgrpcust,
KURSK as exchange_rate,
PRSDT as pricing_date,
FKDAT as billing_date,
FBUDA as serv_rendered,
GJAHR as fiscal_year,
POPER as posting_period,
STCUR as exch_rate_stats,
MSCHL as dunning_key,
MANSP as dunn_block,
FPLNR as billing_plan_no,
WAKTION as promotion,
ABSSC as paym_guar_proc,
LCNUM as financ_doc_no,
J_1AFITP as tax_type,
J_1ARFZ as reason_for_zero_vat,
J_1AREGIO as region,
J_1AGICD as activity_code,
J_1ADTYP as distr_type,
J_1ATXREL as tax_rel_class,
ABTNR as department,
EMPST as recv_point,
BSTKD as cust_reference,
BSTDK as cust_ref_date,
BSARK as pur_ord_type,
IHREZ as your_reference,
BSTKD_E as po_number,
BSTDK_E as purchorderdate,
BSARK_E as pur_ord_type_1,
IHREZ_E as your_reference_1,
POSEX_E as po_item,
KURSK_DAT as translation_dte,
KURRF_DAT as translation_dte_1,
KDKG1 as condition_grp_1,
KDKG2 as condition_grp_2,
KDKG3 as condition_grp_3,
KDKG4 as condition_grp_4,
KDKG5 as condition_grp_5,
WKWAE as currency,
WKKUR as exchange_rate_1,
AKWAE as lettofcredcrcy,
AKKUR as lettofcredrate,
AKPRZ as depreciation,
J_1AINDXP as inflation_index,
J_1AIDATEP as index_base_date,
BSTKD_M as po_number_1,
DELCO as delivery_time,
FFPRF as dip_profile,
BEMOT as acctindicator,
FAKTF as billing_form,
RRREL as rev_recognition,
ACDATV as acc_period_start,
VSART as shipping_type,
TRATY as mnsoftrns_type,
TRMTYP as meanstransp,
SDABW as spec_processing,
WMINR as catalog,
FKBER as functional_area,
PODKZ as pod_relevant,
CAMPAIGN as cgpl_guid,
VKONT as contract_acct,
DPBP_REF_FPLNR as billing_plan_no_1,
DPBP_REF_FPLTR as item_1,
REVSP as revenue_dist,
REVEVTYP as revenue_event,
FARR_RELTYPE as type,
VTREF as contract,
_DATAAGING as data_filter_value_for_data_agi,
J_1TPBUPL as branch_code,
INCOV as inco_version,
INCO2_L as inco_location1,
INCO3_L as inco_location2,
PACKNO as package_number,
PEROP_BEG as per_of_perf_start,
PEROP_END as per_of_perf_end,
STCODE as lst_cst_code,
FORMC1 as form_type,
FORMC2 as form_type_1,
STEUC as control_code,
COMPREAS as abbreviation,
MNDID as mandate_ref,
PAY_TYPE as payment_type,
SEPON as sepa_relevant,
MNDVG as sepa_relevant_1,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct vbkd.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.vbkd` as vbkd
where vbkd._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'sales_document_business_data'),0))
select client as client_key,
sales_document as sales_document_key,
item as item_key,
*
From  vbkd
UNION ALL
select null as client_key,
null as sales_document_key,
null as item_key,
vbkd.*
From vbkd as vbkd
INNER JOIN `sap-adapter.slt_staging.sales_document_business_data` as uji
ON vbkd.client = uji.client
AND vbkd.sales_document = uji.sales_document
AND vbkd.item = uji.item
AND vbkd.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.sales_document_key = tgt.sales_document
AND src.item_key = tgt.item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
sales_document,
item,
custprice_group,
customer_group,
sales_district,
price_list_tp,
incoterms,
incoterms_2,
order_combinat,
invoicing_dates,
inv_list_sched,
man_inv_maint,
exch_rate_acct,
add_value_days,
fixed_val_date,
payt_terms,
payt_method,
accassmtgrpcust,
exchange_rate,
pricing_date,
billing_date,
serv_rendered,
fiscal_year,
posting_period,
exch_rate_stats,
dunning_key,
dunn_block,
billing_plan_no,
promotion,
paym_guar_proc,
financ_doc_no,
tax_type,
reason_for_zero_vat,
region,
activity_code,
distr_type,
tax_rel_class,
department,
recv_point,
cust_reference,
cust_ref_date,
pur_ord_type,
your_reference,
po_number,
purchorderdate,
pur_ord_type_1,
your_reference_1,
po_item,
translation_dte,
translation_dte_1,
condition_grp_1,
condition_grp_2,
condition_grp_3,
condition_grp_4,
condition_grp_5,
currency,
exchange_rate_1,
lettofcredcrcy,
lettofcredrate,
depreciation,
inflation_index,
index_base_date,
po_number_1,
delivery_time,
dip_profile,
acctindicator,
billing_form,
rev_recognition,
acc_period_start,
shipping_type,
mnsoftrns_type,
meanstransp,
spec_processing,
catalog,
functional_area,
pod_relevant,
cgpl_guid,
contract_acct,
billing_plan_no_1,
item_1,
revenue_dist,
revenue_event,
type,
contract,
data_filter_value_for_data_agi,
branch_code,
inco_version,
inco_location1,
inco_location2,
package_number,
per_of_perf_start,
per_of_perf_end,
lst_cst_code,
form_type,
form_type_1,
control_code,
abbreviation,
mandate_ref,
payment_type,
sepa_relevant,
sepa_relevant_1,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.sales_document,
src.item,
src.custprice_group,
src.customer_group,
src.sales_district,
src.price_list_tp,
src.incoterms,
src.incoterms_2,
src.order_combinat,
src.invoicing_dates,
src.inv_list_sched,
src.man_inv_maint,
src.exch_rate_acct,
src.add_value_days,
src.fixed_val_date,
src.payt_terms,
src.payt_method,
src.accassmtgrpcust,
src.exchange_rate,
src.pricing_date,
src.billing_date,
src.serv_rendered,
src.fiscal_year,
src.posting_period,
src.exch_rate_stats,
src.dunning_key,
src.dunn_block,
src.billing_plan_no,
src.promotion,
src.paym_guar_proc,
src.financ_doc_no,
src.tax_type,
src.reason_for_zero_vat,
src.region,
src.activity_code,
src.distr_type,
src.tax_rel_class,
src.department,
src.recv_point,
src.cust_reference,
src.cust_ref_date,
src.pur_ord_type,
src.your_reference,
src.po_number,
src.purchorderdate,
src.pur_ord_type_1,
src.your_reference_1,
src.po_item,
src.translation_dte,
src.translation_dte_1,
src.condition_grp_1,
src.condition_grp_2,
src.condition_grp_3,
src.condition_grp_4,
src.condition_grp_5,
src.currency,
src.exchange_rate_1,
src.lettofcredcrcy,
src.lettofcredrate,
src.depreciation,
src.inflation_index,
src.index_base_date,
src.po_number_1,
src.delivery_time,
src.dip_profile,
src.acctindicator,
src.billing_form,
src.rev_recognition,
src.acc_period_start,
src.shipping_type,
src.mnsoftrns_type,
src.meanstransp,
src.spec_processing,
src.catalog,
src.functional_area,
src.pod_relevant,
src.cgpl_guid,
src.contract_acct,
src.billing_plan_no_1,
src.item_1,
src.revenue_dist,
src.revenue_event,
src.type,
src.contract,
src.data_filter_value_for_data_agi,
src.branch_code,
src.inco_version,
src.inco_location1,
src.inco_location2,
src.package_number,
src.per_of_perf_start,
src.per_of_perf_end,
src.lst_cst_code,
src.form_type,
src.form_type_1,
src.control_code,
src.abbreviation,
src.mandate_ref,
src.payment_type,
src.sepa_relevant,
src.sepa_relevant_1,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'sales_document_business_data' as table_name
    		,'vbkd' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'sales_document_business_data') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'sales_document_business_data') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.sales_document_business_data`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.sales_document_business_data` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'sales_document_business_data'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.sales_document_business_data`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    