MERGE INTO `sap-adapter.slt_staging.purchase_order_item_detail` tgt
USING (
WITH ekpo as
(select MANDT as client,
EBELN as purchasing_doc,
EBELP as item,
UNIQUEID as document_item,
LOEKZ as deletion_ind,
STATU as rfq_status,
AEDAT as changed_on,
TXZ01 as short_text,
MATNR as material,
EMATN as material_1,
BUKRS as company_code,
WERKS as plant,
LGORT as stor_loc,
BEDNR as tracking_number,
MATKL as material_group,
INFNR as info_record,
IDNLF as supp_mat_no,
KTMNG as target_quantity,
MENGE as po_quantity,
MEINS as order_unit,
BPRME as order_price_un,
BPUMZ as qty_conversion,
BPUMN as qty_conversion_1,
UMREZ as equal_to,
UMREN as denominator,
NETPR as net_price,
PEINH as price_unit,
NETWR as net_value,
BRTWR as gross_value,
AGDAT as quot_deadline,
WEBAZ as gr_proc_time,
MWSKZ as tax_code,
TXDAT_FROM as tax_rate_valid_from,
TXDAT as tax_date,
BONUS as sett_group_1,
INSMK as stock_type,
SPINF as infoupdate,
PRSDR as print_price,
SCHPR as estimated_price,
MAHNZ as no_rem_exp,
MAHN1 as st_rem_exped,
MAHN2 as nd_rem_exped,
MAHN3 as rd_rem_exped,
UEBTO as overdeliv_tol,
UEBTK as unlimited,
UNTTO as underdel_tol,
BWTAR as valuation_type,
BWTTY as valuation_cat,
ABSKZ as rejection_ind,
AGMEM as quot_comment,
ELIKZ as deliv_compl,
EREKZ as final_invoice,
PSTYP as item_category,
KNTTP as acct_assgmt_cat,
KZVBR as consumption,
VRTKZ as distribution,
TWRKZ as partial_invoice,
WEPOS as goods_receipt,
WEUNB as gr_non_valuated,
REPOS as invoice_receipt,
WEBRE as gr_based_iv,
KZABS as acknowl_reqd,
LABNR as order_acknowl,
KONNR as agreement,
KTPNR as agreement_item,
ABDAT as reconcil_date,
ABFTZ as agr_cum_qty,
ETFZ1 as firm_zone,
ETFZ2 as trade_off_zone,
KZSTU as binding_on_mrp,
NOTKZ as exclusion,
LMEIN as base_unit,
EVERS as shipping_instr,
ZWERT as target_value,
NAVNW as non_deductible,
ABMNG as rel_order_qty,
PRDAT as price_date,
BSTYP as doc_category,
EFFWR as effective_value,
XOBLR as commitments,
KUNNR as customer,
ADRNR as address,
EKKOL as condition_group,
SKTOF as no_cash_disc,
STAFO as update_group,
PLIFZ as pl_deliv_time,
NTGEW as net_weight,
GEWEI as unit_of_weight,
TXJCD as tax_jur,
ETDRK as print_relevant,
SOBKZ as special_stock,
ARSNR as settle_reser_no,
ARSPS as settle_item_no,
INSNC as not_changeable,
SSQSS as qm_control_key,
ZGTYP as certificatetype,
EAN11 as ean_upc,
BSTAE as conf_control,
REVLV as revision_level,
GEBER as fund,
FISTL as funds_center,
FIPOS as commitment_item,
KO_GSBER as bus_area_prtner,
KO_PARGB as ptr_s_assum_ba,
KO_PRCTR as profit_center,
KO_PPRCTR as partner_pc,
MEPRF as pr_date_cat,
BRGEW as gross_weight,
VOLUM as volume,
VOLEH as volume_unit,
INCO1 as incoterms,
INCO2 as incoterms_2,
VORAB as advance_proc,
KOLIF as prior_supplier,
LTSNR as suppl_subrange,
PACKNO as package_number,
FPLNR as invoicing_plan,
GNETWR as net_value_1,
STAPO as statistical,
UEBPO as h_lev_item,
LEWED as latest_gr_date,
EMLIF as supplier,
LBLKZ as sc_supplier,
SATNR as cross_plant_cm,
ATTYP as matl_category,
VSART as shipping_type,
HANDOVERLOC as handover_location,
KANBA as kanban_indicat,
ADRN2 as address_1,
CUOBJ as int_object_no,
XERSY as ers,
EILDT as gr_b_sett_from,
DRDAT as last_transm,
DRUHR as time_of_transmission,
DRUNR as sequential_number,
AKTNR as promotion,
ABELN as alloc_table,
ABELP as item_1,
ANZPU as points,
PUNEI as points_unit,
SAISO as season,
SAISJ as season_year,
EBON2 as sett_group_2,
EBON3 as sett_group_3,
EBONF as settlement,
MLMAA as ml_act,
MHDRZ as rem_shelf_life,
ANFNR as rfq,
ANFPS as item_2,
KZKFG as origin_of_config,
USEQU as quota_arr_usage,
UMSOK as sp_ind_st_tfr,
BANFN as purchase_req,
BNFPO as requisn_item,
MTART as material_type,
UPTYP as subitem_cat,
UPVOR as sub_items,
KZWI1 as subtotal_1,
KZWI2 as subtotal_2,
KZWI3 as subtotal_3,
KZWI4 as subtotal_4,
KZWI5 as subtotal_5,
KZWI6 as subtotal_6,
SIKGR as key,
MFZHI as max_cmg_qty,
FFZHI as maximum_cpgq,
RETPO as returns_item,
AUREL as at_relevant,
BSGRU as reason_for_ord,
LFRET as del_type_rtns,
MFRGR as mat_freight_grp,
NRFHG as disc_in_kind,
J_1BNBM as ncm_code,
J_1BMATUSE as material_usage,
J_1BMATORG as material_origin,
J_1BOWNPRO as prod_in_house,
J_1BINDUST as mat_category,
ABUEB as creation_profile,
NLABD as next_frc_sched,
NFABD as next_jit_sched,
KZBWS as valuation,
BONBA as rebate_basis,
FABKZ as jit_indicator,
J_1AINDXP as inflation_index,
J_1AIDATEP as index_date,
MPROF as mfr_part_profile,
EGLKZ as final_delivery,
KZTLF as part_del_item,
KZFME as units_meas_use,
RDPRF as rnding_profile,
TECHS as standardvariant,
CHG_SRV as configuration_changed,
CHG_FPLNR as no_invoice_for_this_item_altho,
MFRPN as mfr_part_number,
MFRNR as manufacturer,
EMNFR as external_manuf,
NOVET as shipping_block,
AFNAM as requisitioner,
TZONRC as rec_time_zone,
IPRKZ as period_ind,
LEBRE as srv_based_inv_ver,
BERID as mrp_area,
XCONDITIONS as conditions_for_item_although_n,
APOMS as ext_planning,
CCOMP as stock_transf_cat,
GRANT_NBR as grants,
FKBER as functional_area,
STATUS as item_status,
RESLO as iss_stor_loc,
KBLNR as earmarked_funds,
KBLPOS as document_item_1,
PS_PSP_PNR as wbs_element,
KOSTL as cost_center,
SAKTO as g_l_account,
WEORA as origin_accept,
SRV_BAS_COM as service_based_comm,
PRIO_URG as reqmt_urgency,
PRIO_REQ as reqmt_priority,
EMPST as recv_point,
DIFF_INVOICE as diff_invoicing,
TRMRISK_RELEVANT as risk_relevancy,
CREATIONDATE as creation_date,
CREATIONTIME as creation_time,
SPE_ABGRU as rejectionreason,
SPE_CRM_SO as crm_sales_order,
SPE_CRM_SO_ITEM as crm_item_no,
SPE_CRM_REF_SO as crm_ref_order,
SPE_CRM_REF_ITEM as crm_rf_item_no,
SPE_CRM_FKREL as bill_relevance,
SPE_CHNG_SYS as changer_s_sys_type,
SPE_INSMK_SRC as source_stock_type,
SPE_CQ_CTRLTYPE as control_type,
SPE_CQ_NOCQ as no_cq_transmission,
REASON_CODE as reason_code,
CQU_SAR as cumulative_grs,
ANZSN as no_serial_no,
SPE_EWM_DTC as ewm_del_tol_chk,
EXLIN as configurable_itemno,
EXSNR as external_sort_no,
EHTYP as ext_hierarchy_cat,
RETPC as retention,
DPTYP as down_payment,
DPPCT as down_payment_1,
DPAMT as down_payment_amt,
DPDAT as due_date_for_dp,
FLS_RSTO as enh_store_ret,
EXT_RFX_NUMBER as external_document,
EXT_RFX_ITEM as external_item,
EXT_RFX_SYSTEM as logical_system,
SRM_CONTRACT_ID as central_contract,
SRM_CONTRACT_ITM as cent_contract_item,
BLK_REASON_ID as block_reason_id,
BLK_REASON_TXT as block_reas_text,
ITCONS as rt_consumption,
FIXMG as fixed_date,
WABWE as gi_based_gr,
CMPL_DLV_ITM as complete_deliv,
INCO2_L as inco_location1,
INCO3_L as inco_location2,
STAWN as commodity_code,
ISVCO as intrastat_srvc_code,
GRWRT as statist_value,
SERVICEPERFORMER as service_performer,
PRODUCTTYPE as product_type_group,
REQUESTFORQUOTATION as rfq_1,
REQUESTFORQUOTATIONITEM as item_number_for_rfq,
EXTMATERIALFORPURG as material_2,
TARGET_VALUE as item_target_value,
EXTERNALREFERENCEID as ext_reference_id,
TC_AUT_DET as tc_auto_det,
MANUAL_TC_REASON as man_tc_reason,
FISCAL_INCENTIVE as tax_incent_type,
TAX_SUBJECT_ST as tax_subj_to_st,
FISCAL_INCENTIVE_ID as incentive_id,
SF_TXJCD as origjurcod,
DUMMY_EKPO_INCL_EEW_PS as ext_include,
EXPECTED_VALUE as expected_value,
LIMIT_AMOUNT as overall_limit,
ENH_DATE1 as wka_start_date,
ENH_DATE2 as wka_end_date,
ENH_PERCENT as percentage,
ENH_NUMC1 as wrk_time_hours,
_DATAAGING as data_filter_value_for_data_agi,
__BEV1__NEGEN_ITEM as item_generated,
__BEV1__NEDEPFREE as dependent_free,
__BEV1__NESTRUCCAT as struct_category,
ADVCODE as advice_code,
BUDGET_PD as budget_period,
EXCPE as acceptance_period,
FMFGUS_KEY as us_govt,
IUID_RELEVANT as iuid_relevant,
MRPIND as mrpind,
SGT_SCAT as stock_segment,
SGT_RCAT as reqmnt_segment,
TMS_REF_UUID as guid_of_sap_tm,
TMS_SRC_LOC_KEY as location,
TMS_DES_LOC_KEY as location_1,
WRF_CHARSTC1 as characteristic_1,
WRF_CHARSTC2 as characteristic_2,
WRF_CHARSTC3 as characteristic_3,
REFSITE as purchasing_ref_site,
ZAPCGK as annexing_package,
APCGK_EXTEND as ann_package_extend,
ZBAS_DATE as base_date,
ZADATTYP as annexing_date_type,
ZSTART_DAT as annexing_start_date,
Z_DEV as deviation_percen,
ZINDANX as annexed_ind,
ZLIMIT_DAT as limit_date,
NUMERATOR as char20,
HASHCAL_BDAT as new_base_date,
HASHCAL as accountant_gen_mth,
NEGATIVE as no_negative_annexing,
HASHCAL_EXISTS as purchasing_org,
KNOWN_INDEX as known_index_indic,
__SAPMP__GPOSE as global_item_no,
ANGPN as quotation_item,
ADMOI as model_id_code,
ADPRI as order_priority,
LPRIO as delivery_prior,
ADACN as aircraftreg_no,
AFPNR as item_3,
BSARK as conf_type,
AUDAT as document_date,
ANGNR as quotation,
PNSTAT as s1pnstat_message,
ADDNS as donotsub,
SERRU as subcon_type,
SERNP as serialnoprofile,
DISUB_SOBKZ as sp_stock,
DISUB_PSPNR as wbs_element_1,
DISUB_KUNNR as customer_1,
DISUB_VBELN as sales_document,
DISUB_POSNR as item_4,
DISUB_OWNER as owner_of_stock,
FSH_SEASON_YEAR as season_year_1,
FSH_SEASON as season_1,
FSH_COLLECTION as collection,
FSH_THEME as theme,
FSH_ATP_DATE as start_date_atp,
FSH_VAS_REL as vas_relevant,
FSH_VAS_PRNT_ID as item_5,
FSH_TRANSACTION as transaction_number,
FSH_ITEM_GROUP as item_group,
FSH_ITEM as item_number,
FSH_SS as sched_strat,
FSH_GRID_COND_REC as record_num,
FSH_PSM_PFM_SPLIT as split_id,
CNFM_QTY as committed_qty,
FSH_PQR_UEPOS as higher_lev_item_pqr,
RFM_DIVERSION as diversion_status,
RFM_SCC_INDICATOR as season_comp_ind,
STPAC as activate_stop,
LGBZO as auto_unloadpt,
LGBZO_B as auto_unloadpt_1,
ADDRNUM as address_number,
CONSNUM as sequence_number,
BORGR_MISS as info_at_reg,
DEP_ID as department,
BELNR as earmarked_funds_1,
KBLPOS_CAB as document_item_2,
KBLNR_COMP as commitment_doc,
KBLPOS_COMP as commitment_item_1,
WBS_ELEMENT as wbs_element_2,
RFM_PSST_RULE as psst_grouping_rule,
RFM_PSST_GROUP as psst_group,
RFM_REF_DOC as reference_document,
RFM_REF_ITEM as reference_item,
RFM_REF_ACTION as reference_action,
RFM_REF_SLITEM as reference_schedule_line_item_n,
REF_ITEM as reference_item_1,
SOURCE_ID as origin_profile,
SOURCE_KEY as source_system_key,
PUT_BACK as put_back_id,
POL_ID as order_list_item_no,
CONS_ORDER as consignment,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct ekpo.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.ekpo` as ekpo
where ekpo._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'purchase_order_item_detail'),0))
select client as client_key,
purchasing_doc as purchasing_doc_key,
item as item_key,
*
From  ekpo
UNION ALL
select null as client_key,
null as purchasing_doc_key,
null as item_key,
ekpo.*
From ekpo as ekpo
INNER JOIN `sap-adapter.slt_staging.purchase_order_item_detail` as uji
ON ekpo.client = uji.client
AND ekpo.purchasing_doc = uji.purchasing_doc
AND ekpo.item = uji.item
AND ekpo.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.purchasing_doc_key = tgt.purchasing_doc
AND src.item_key = tgt.item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
purchasing_doc,
item,
document_item,
deletion_ind,
rfq_status,
changed_on,
short_text,
material,
material_1,
company_code,
plant,
stor_loc,
tracking_number,
material_group,
info_record,
supp_mat_no,
target_quantity,
po_quantity,
order_unit,
order_price_un,
qty_conversion,
qty_conversion_1,
equal_to,
denominator,
net_price,
price_unit,
net_value,
gross_value,
quot_deadline,
gr_proc_time,
tax_code,
tax_rate_valid_from,
tax_date,
sett_group_1,
stock_type,
infoupdate,
print_price,
estimated_price,
no_rem_exp,
st_rem_exped,
nd_rem_exped,
rd_rem_exped,
overdeliv_tol,
unlimited,
underdel_tol,
valuation_type,
valuation_cat,
rejection_ind,
quot_comment,
deliv_compl,
final_invoice,
item_category,
acct_assgmt_cat,
consumption,
distribution,
partial_invoice,
goods_receipt,
gr_non_valuated,
invoice_receipt,
gr_based_iv,
acknowl_reqd,
order_acknowl,
agreement,
agreement_item,
reconcil_date,
agr_cum_qty,
firm_zone,
trade_off_zone,
binding_on_mrp,
exclusion,
base_unit,
shipping_instr,
target_value,
non_deductible,
rel_order_qty,
price_date,
doc_category,
effective_value,
commitments,
customer,
address,
condition_group,
no_cash_disc,
update_group,
pl_deliv_time,
net_weight,
unit_of_weight,
tax_jur,
print_relevant,
special_stock,
settle_reser_no,
settle_item_no,
not_changeable,
qm_control_key,
certificatetype,
ean_upc,
conf_control,
revision_level,
fund,
funds_center,
commitment_item,
bus_area_prtner,
ptr_s_assum_ba,
profit_center,
partner_pc,
pr_date_cat,
gross_weight,
volume,
volume_unit,
incoterms,
incoterms_2,
advance_proc,
prior_supplier,
suppl_subrange,
package_number,
invoicing_plan,
net_value_1,
statistical,
h_lev_item,
latest_gr_date,
supplier,
sc_supplier,
cross_plant_cm,
matl_category,
shipping_type,
handover_location,
kanban_indicat,
address_1,
int_object_no,
ers,
gr_b_sett_from,
last_transm,
time_of_transmission,
sequential_number,
promotion,
alloc_table,
item_1,
points,
points_unit,
season,
season_year,
sett_group_2,
sett_group_3,
settlement,
ml_act,
rem_shelf_life,
rfq,
item_2,
origin_of_config,
quota_arr_usage,
sp_ind_st_tfr,
purchase_req,
requisn_item,
material_type,
subitem_cat,
sub_items,
subtotal_1,
subtotal_2,
subtotal_3,
subtotal_4,
subtotal_5,
subtotal_6,
key,
max_cmg_qty,
maximum_cpgq,
returns_item,
at_relevant,
reason_for_ord,
del_type_rtns,
mat_freight_grp,
disc_in_kind,
ncm_code,
material_usage,
material_origin,
prod_in_house,
mat_category,
creation_profile,
next_frc_sched,
next_jit_sched,
valuation,
rebate_basis,
jit_indicator,
inflation_index,
index_date,
mfr_part_profile,
final_delivery,
part_del_item,
units_meas_use,
rnding_profile,
standardvariant,
configuration_changed,
no_invoice_for_this_item_altho,
mfr_part_number,
manufacturer,
external_manuf,
shipping_block,
requisitioner,
rec_time_zone,
period_ind,
srv_based_inv_ver,
mrp_area,
conditions_for_item_although_n,
ext_planning,
stock_transf_cat,
grants,
functional_area,
item_status,
iss_stor_loc,
earmarked_funds,
document_item_1,
wbs_element,
cost_center,
g_l_account,
origin_accept,
service_based_comm,
reqmt_urgency,
reqmt_priority,
recv_point,
diff_invoicing,
risk_relevancy,
creation_date,
creation_time,
rejectionreason,
crm_sales_order,
crm_item_no,
crm_ref_order,
crm_rf_item_no,
bill_relevance,
changer_s_sys_type,
source_stock_type,
control_type,
no_cq_transmission,
reason_code,
cumulative_grs,
no_serial_no,
ewm_del_tol_chk,
configurable_itemno,
external_sort_no,
ext_hierarchy_cat,
retention,
down_payment,
down_payment_1,
down_payment_amt,
due_date_for_dp,
enh_store_ret,
external_document,
external_item,
logical_system,
central_contract,
cent_contract_item,
block_reason_id,
block_reas_text,
rt_consumption,
fixed_date,
gi_based_gr,
complete_deliv,
inco_location1,
inco_location2,
commodity_code,
intrastat_srvc_code,
statist_value,
service_performer,
product_type_group,
rfq_1,
item_number_for_rfq,
material_2,
item_target_value,
ext_reference_id,
tc_auto_det,
man_tc_reason,
tax_incent_type,
tax_subj_to_st,
incentive_id,
origjurcod,
ext_include,
expected_value,
overall_limit,
wka_start_date,
wka_end_date,
percentage,
wrk_time_hours,
data_filter_value_for_data_agi,
item_generated,
dependent_free,
struct_category,
advice_code,
budget_period,
acceptance_period,
us_govt,
iuid_relevant,
mrpind,
stock_segment,
reqmnt_segment,
guid_of_sap_tm,
location,
location_1,
characteristic_1,
characteristic_2,
characteristic_3,
purchasing_ref_site,
annexing_package,
ann_package_extend,
base_date,
annexing_date_type,
annexing_start_date,
deviation_percen,
annexed_ind,
limit_date,
char20,
new_base_date,
accountant_gen_mth,
no_negative_annexing,
purchasing_org,
known_index_indic,
global_item_no,
quotation_item,
model_id_code,
order_priority,
delivery_prior,
aircraftreg_no,
item_3,
conf_type,
document_date,
quotation,
s1pnstat_message,
donotsub,
subcon_type,
serialnoprofile,
sp_stock,
wbs_element_1,
customer_1,
sales_document,
item_4,
owner_of_stock,
season_year_1,
season_1,
collection,
theme,
start_date_atp,
vas_relevant,
item_5,
transaction_number,
item_group,
item_number,
sched_strat,
record_num,
split_id,
committed_qty,
higher_lev_item_pqr,
diversion_status,
season_comp_ind,
activate_stop,
auto_unloadpt,
auto_unloadpt_1,
address_number,
sequence_number,
info_at_reg,
department,
earmarked_funds_1,
document_item_2,
commitment_doc,
commitment_item_1,
wbs_element_2,
psst_grouping_rule,
psst_group,
reference_document,
reference_item,
reference_action,
reference_schedule_line_item_n,
reference_item_1,
origin_profile,
source_system_key,
put_back_id,
order_list_item_no,
consignment,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.purchasing_doc,
src.item,
src.document_item,
src.deletion_ind,
src.rfq_status,
src.changed_on,
src.short_text,
src.material,
src.material_1,
src.company_code,
src.plant,
src.stor_loc,
src.tracking_number,
src.material_group,
src.info_record,
src.supp_mat_no,
src.target_quantity,
src.po_quantity,
src.order_unit,
src.order_price_un,
src.qty_conversion,
src.qty_conversion_1,
src.equal_to,
src.denominator,
src.net_price,
src.price_unit,
src.net_value,
src.gross_value,
src.quot_deadline,
src.gr_proc_time,
src.tax_code,
src.tax_rate_valid_from,
src.tax_date,
src.sett_group_1,
src.stock_type,
src.infoupdate,
src.print_price,
src.estimated_price,
src.no_rem_exp,
src.st_rem_exped,
src.nd_rem_exped,
src.rd_rem_exped,
src.overdeliv_tol,
src.unlimited,
src.underdel_tol,
src.valuation_type,
src.valuation_cat,
src.rejection_ind,
src.quot_comment,
src.deliv_compl,
src.final_invoice,
src.item_category,
src.acct_assgmt_cat,
src.consumption,
src.distribution,
src.partial_invoice,
src.goods_receipt,
src.gr_non_valuated,
src.invoice_receipt,
src.gr_based_iv,
src.acknowl_reqd,
src.order_acknowl,
src.agreement,
src.agreement_item,
src.reconcil_date,
src.agr_cum_qty,
src.firm_zone,
src.trade_off_zone,
src.binding_on_mrp,
src.exclusion,
src.base_unit,
src.shipping_instr,
src.target_value,
src.non_deductible,
src.rel_order_qty,
src.price_date,
src.doc_category,
src.effective_value,
src.commitments,
src.customer,
src.address,
src.condition_group,
src.no_cash_disc,
src.update_group,
src.pl_deliv_time,
src.net_weight,
src.unit_of_weight,
src.tax_jur,
src.print_relevant,
src.special_stock,
src.settle_reser_no,
src.settle_item_no,
src.not_changeable,
src.qm_control_key,
src.certificatetype,
src.ean_upc,
src.conf_control,
src.revision_level,
src.fund,
src.funds_center,
src.commitment_item,
src.bus_area_prtner,
src.ptr_s_assum_ba,
src.profit_center,
src.partner_pc,
src.pr_date_cat,
src.gross_weight,
src.volume,
src.volume_unit,
src.incoterms,
src.incoterms_2,
src.advance_proc,
src.prior_supplier,
src.suppl_subrange,
src.package_number,
src.invoicing_plan,
src.net_value_1,
src.statistical,
src.h_lev_item,
src.latest_gr_date,
src.supplier,
src.sc_supplier,
src.cross_plant_cm,
src.matl_category,
src.shipping_type,
src.handover_location,
src.kanban_indicat,
src.address_1,
src.int_object_no,
src.ers,
src.gr_b_sett_from,
src.last_transm,
src.time_of_transmission,
src.sequential_number,
src.promotion,
src.alloc_table,
src.item_1,
src.points,
src.points_unit,
src.season,
src.season_year,
src.sett_group_2,
src.sett_group_3,
src.settlement,
src.ml_act,
src.rem_shelf_life,
src.rfq,
src.item_2,
src.origin_of_config,
src.quota_arr_usage,
src.sp_ind_st_tfr,
src.purchase_req,
src.requisn_item,
src.material_type,
src.subitem_cat,
src.sub_items,
src.subtotal_1,
src.subtotal_2,
src.subtotal_3,
src.subtotal_4,
src.subtotal_5,
src.subtotal_6,
src.key,
src.max_cmg_qty,
src.maximum_cpgq,
src.returns_item,
src.at_relevant,
src.reason_for_ord,
src.del_type_rtns,
src.mat_freight_grp,
src.disc_in_kind,
src.ncm_code,
src.material_usage,
src.material_origin,
src.prod_in_house,
src.mat_category,
src.creation_profile,
src.next_frc_sched,
src.next_jit_sched,
src.valuation,
src.rebate_basis,
src.jit_indicator,
src.inflation_index,
src.index_date,
src.mfr_part_profile,
src.final_delivery,
src.part_del_item,
src.units_meas_use,
src.rnding_profile,
src.standardvariant,
src.configuration_changed,
src.no_invoice_for_this_item_altho,
src.mfr_part_number,
src.manufacturer,
src.external_manuf,
src.shipping_block,
src.requisitioner,
src.rec_time_zone,
src.period_ind,
src.srv_based_inv_ver,
src.mrp_area,
src.conditions_for_item_although_n,
src.ext_planning,
src.stock_transf_cat,
src.grants,
src.functional_area,
src.item_status,
src.iss_stor_loc,
src.earmarked_funds,
src.document_item_1,
src.wbs_element,
src.cost_center,
src.g_l_account,
src.origin_accept,
src.service_based_comm,
src.reqmt_urgency,
src.reqmt_priority,
src.recv_point,
src.diff_invoicing,
src.risk_relevancy,
src.creation_date,
src.creation_time,
src.rejectionreason,
src.crm_sales_order,
src.crm_item_no,
src.crm_ref_order,
src.crm_rf_item_no,
src.bill_relevance,
src.changer_s_sys_type,
src.source_stock_type,
src.control_type,
src.no_cq_transmission,
src.reason_code,
src.cumulative_grs,
src.no_serial_no,
src.ewm_del_tol_chk,
src.configurable_itemno,
src.external_sort_no,
src.ext_hierarchy_cat,
src.retention,
src.down_payment,
src.down_payment_1,
src.down_payment_amt,
src.due_date_for_dp,
src.enh_store_ret,
src.external_document,
src.external_item,
src.logical_system,
src.central_contract,
src.cent_contract_item,
src.block_reason_id,
src.block_reas_text,
src.rt_consumption,
src.fixed_date,
src.gi_based_gr,
src.complete_deliv,
src.inco_location1,
src.inco_location2,
src.commodity_code,
src.intrastat_srvc_code,
src.statist_value,
src.service_performer,
src.product_type_group,
src.rfq_1,
src.item_number_for_rfq,
src.material_2,
src.item_target_value,
src.ext_reference_id,
src.tc_auto_det,
src.man_tc_reason,
src.tax_incent_type,
src.tax_subj_to_st,
src.incentive_id,
src.origjurcod,
src.ext_include,
src.expected_value,
src.overall_limit,
src.wka_start_date,
src.wka_end_date,
src.percentage,
src.wrk_time_hours,
src.data_filter_value_for_data_agi,
src.item_generated,
src.dependent_free,
src.struct_category,
src.advice_code,
src.budget_period,
src.acceptance_period,
src.us_govt,
src.iuid_relevant,
src.mrpind,
src.stock_segment,
src.reqmnt_segment,
src.guid_of_sap_tm,
src.location,
src.location_1,
src.characteristic_1,
src.characteristic_2,
src.characteristic_3,
src.purchasing_ref_site,
src.annexing_package,
src.ann_package_extend,
src.base_date,
src.annexing_date_type,
src.annexing_start_date,
src.deviation_percen,
src.annexed_ind,
src.limit_date,
src.char20,
src.new_base_date,
src.accountant_gen_mth,
src.no_negative_annexing,
src.purchasing_org,
src.known_index_indic,
src.global_item_no,
src.quotation_item,
src.model_id_code,
src.order_priority,
src.delivery_prior,
src.aircraftreg_no,
src.item_3,
src.conf_type,
src.document_date,
src.quotation,
src.s1pnstat_message,
src.donotsub,
src.subcon_type,
src.serialnoprofile,
src.sp_stock,
src.wbs_element_1,
src.customer_1,
src.sales_document,
src.item_4,
src.owner_of_stock,
src.season_year_1,
src.season_1,
src.collection,
src.theme,
src.start_date_atp,
src.vas_relevant,
src.item_5,
src.transaction_number,
src.item_group,
src.item_number,
src.sched_strat,
src.record_num,
src.split_id,
src.committed_qty,
src.higher_lev_item_pqr,
src.diversion_status,
src.season_comp_ind,
src.activate_stop,
src.auto_unloadpt,
src.auto_unloadpt_1,
src.address_number,
src.sequence_number,
src.info_at_reg,
src.department,
src.earmarked_funds_1,
src.document_item_2,
src.commitment_doc,
src.commitment_item_1,
src.wbs_element_2,
src.psst_grouping_rule,
src.psst_group,
src.reference_document,
src.reference_item,
src.reference_action,
src.reference_schedule_line_item_n,
src.reference_item_1,
src.origin_profile,
src.source_system_key,
src.put_back_id,
src.order_list_item_no,
src.consignment,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'purchase_order_item_detail' as table_name
    		,'ekpo' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'purchase_order_item_detail') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'purchase_order_item_detail') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.purchase_order_item_detail`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.purchase_order_item_detail` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'purchase_order_item_detail'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.purchase_order_item_detail`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    