MERGE INTO `sap-adapter.slt_staging.material_movement_item_detail` tgt
USING (
WITH mseg as
(select MANDT as client,
MBLNR as material_doc,
MJAHR as mat_doc_year,
ZEILE as mat_doc_item,
LINE_ID as line_id,
PARENT_ID as parent_id,
LINE_DEPTH as level,
MAA_URZEI as orig_line_itm,
BWART as movement_type,
XAUTO as auto_created,
MATNR as material,
WERKS as plant,
LGORT as stor_loc,
CHARG as batch,
INSMK as stock_type,
ZUSCH as status_key,
ZUSTD as batch_restr,
SOBKZ as special_stock,
LIFNR as vendor,
KUNNR as customer,
KDAUF as sales_order,
KDPOS as sales_ord_item,
KDEIN as sorder_schedule,
PLPLA as distribution,
SHKZG as debit_credit,
WAERS as currency,
DMBTR as amount_in_lc,
BNBTR as delivery_costs,
BUALT as amount,
SHKUM as d_c_ind_reval,
DMBUM as revaluation,
BWTAR as valuation_type,
MENGE as quantity,
MEINS as base_unit,
ERFMG as quantity_in_une,
ERFME as unit_of_entry,
BPMNG as qty_in_opun,
BPRME as order_price_un,
EBELN as purchase_order,
EBELP as item,
LFBJA as fisc_yr_ref_doc,
LFBNR as reference_doc,
LFPOS as ref_doc_item,
SJAHR as mat_doc_year_1,
SMBLN as material_doc_1,
SMBLP as mat_doc_item_1,
ELIKZ as deliv_compl,
SGTXT as text,
EQUNR as equipment,
WEMPF as recipient,
ABLAD as unloading_point,
GSBER as business_area,
KOKRS as co_area,
PARGB as trdg_part_ba,
PARBU as clearing_cocode,
KOSTL as cost_center,
PROJN as not_in_use,
AUFNR as order_number,
ANLN1 as asset,
ANLN2 as sub_number,
XSKST as cctposting_stat,
XSAUF as ord_post_stat,
XSPRO as projpost_stat,
XSERG as pa_post_stat,
GJAHR as fiscal_year,
XRUEM as post_prev_per,
XRUEJ as pst_to_pr_year,
BUKRS as company_code,
BELNR as document_number,
BUZEI as line_item,
BELUM as document_number_1,
BUZUM as line_item_1,
RSNUM as reservation_number,
RSPOS as item_no,
KZEAR as final_issue,
PBAMG as quantity_1,
KZSTR as stat_relevant,
UMMAT as receiving_mat,
UMWRK as receiving_plant,
UMLGO as receiving_sloc,
UMCHA as receiving_batch,
UMZST as restricted_use,
UMZUS as stkeytferbatch,
UMBAR as val_type_tfr,
UMSOK as sp_ind_st_tfr,
KZBEW as movement_ind,
KZVBR as consumption,
KZZUG as receipt_ind,
WEUNB as gr_non_valuated,
PALAN as no_of_pallets,
LGNUM as warehouse_no,
LGTYP as storage_type,
LGPLA as storage_bin,
BESTQ as stock_category,
BWLVS as movement_type_1,
TBNUM as tr_number,
TBPOS as tr_item,
XBLVS as posting_in_wm,
VSCHN as int_st_pst_src,
NSCHN as inter_post_dest,
DYPLA as dynamic_bin,
UBNUM as posting_chge_no,
TBPRI as trnsfr_priority,
TANUM as to_number,
WEANZ as no_of_gr_slips,
GRUND as reason_for_mvmt,
EVERS as shipping_instr,
EVERE as compliance,
IMKEY as real_estate_key,
KSTRG as cost_object,
PAOBJNR as profit_segment,
PRCTR as profit_center,
PS_PSP_PNR as wbs_element,
NPLNR as network,
AUFPL as plan_no_f_oper,
APLZL as counter,
AUFPS as order_item_no,
VPTNR as partner,
FIPOS as commitment_item,
SAKTO as g_l_account,
BSTMG as qty_in_oun,
BSTME as order_unit,
XWSBR as revgr_desp_ir,
EMLIF as supplier,
DUMMY_INCL_EEW_COBL as dummy,
EXBWR as ext_amount_lc,
VKWRT as salval_inc_vat,
AKTNR as promotion,
ZEKKN as account_assgmt_no,
VFDAT as sled_bbd,
CUOBJ_CH as int_object_no,
EXVKW as sales_value,
PPRCTR as partner_pc,
RSART as record_type,
GEBER as fund,
FISTL as funds_center,
MATBF as stock_mat,
UMMAB as receiving_mat_1,
BUSTM as quantity_string,
BUSTW as value_string,
MENGU as qty_updating,
WERTU as value_updating,
LBKUM as valuated_stock,
SALK3 as total_value,
VPRSV as price_control,
FKBER as functional_area,
DABRBZ as reference_date,
VKWRA as salval_w_o_vat,
DABRZ as reference_date_1,
XBEAU as automatic_po,
LSMNG as del_note_qty,
LSMEH as del_note_unit,
KZBWS as valuation,
QINSPST as status_gr_doc,
URZEI as orig_line_itm_1,
J_1BEXBASE as alt_base_amnt,
MWSKZ as tax_code,
TXJCD as tax_jur,
EMATN as mpn_material,
J_1AGIRUPD as gi_reval_o_k,
VKMWS as tax_code_1,
HSDAT as date_of_manuf,
BERKZ as staging_ind,
MAT_KDAUF as sales_order_1,
MAT_KDPOS as sales_ord_item_1,
MAT_PSPNR as wbs_element_1,
XWOFF as calcn_of_val_open,
BEMOT as acctindicator,
PRZNR as business_proc,
LLIEF as goods_supplier,
LSTAR as activity_type,
XOBEW as vendor_stk_val,
GRANT_NBR as grants,
ZUSTD_T156M as stock_type_mod,
SPE_GTS_STOCK_TY as gts_stock_type,
KBLNR as earmarked_funds,
KBLPOS as document_item,
XMACC as multi_acct_assgt,
VGART_MKPF as trans_ev_type,
BUDAT_MKPF as posting_date,
CPUDT_MKPF as entered_on,
CPUTM_MKPF as entered_at,
USNAM_MKPF as user_name,
XBLNR_MKPF as reference,
TCODE2_MKPF as transaction_code,
VBELN_IM as delivery,
VBELP_IM as item_1,
SGT_SCAT as stock_segment,
SGT_UMSCAT as rec_stock_seg,
SGT_RCAT as reqmnt_segment,
SERVICEPERFORMER as service_performer,
PERNR as personnel_no,
KNTTP_GR as acct_assgmt_cat,
WORK_ITEM_ID as work_item_id,
FBUDA as serv_rendered,
XPRINT as print_active,
__CWM__MENGE as qty_in_puom,
__CWM__MEINS as parallel_uom,
__CWM__ERFMG as puom_euom_qty,
__CWM__ERFME as puom_entry_uom,
SERVICE_DOC_TYPE as service_doc_type,
SERVICE_DOC_ID as service_document,
SERVICE_DOC_ITEM_ID as service_doc_item,
EWM_LGNUM as warehouse_no_1,
EWM_GMDOC as gm_document,
DISUB_OWNER as owner_of_stock,
FSH_SEASON_YEAR as season_year,
FSH_SEASON as season,
FSH_COLLECTION as collection,
FSH_THEME as theme,
FSH_UMSEA_YR as season_year_1,
FSH_UMSEA as issuing_season,
FSH_UMCOLL as issuing_collection,
FSH_UMTHEME as issuing_theme,
SGT_CHINT as discr_batch_no,
COMPL_MARK as compl_ind,
FZGLS_MARK as do_not_adj_crq,
ETANP_MARK as adjust_item,
POPUP_MARK as dialog_box,
OINAVNW as non_deductible,
OICONDCOD as condkey,
CONDI as condkey_1,
WRF_CHARSTC1 as characteristic_1,
WRF_CHARSTC2 as characteristic_2,
WRF_CHARSTC3 as characteristic_3,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct mseg.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.mseg` as mseg
where mseg._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'material_movement_item_detail'),0))
select client as client_key,
material_doc as material_doc_key,
mat_doc_year as mat_doc_year_key,
mat_doc_item as mat_doc_item_key,
*
From  mseg
UNION ALL
select null as client_key,
null as material_doc_key,
null as mat_doc_year_key,
null as mat_doc_item_key,
mseg.*
From mseg as mseg
INNER JOIN `sap-adapter.slt_staging.material_movement_item_detail` as uji
ON mseg.client = uji.client
AND mseg.material_doc = uji.material_doc
AND mseg.mat_doc_year = uji.mat_doc_year
AND mseg.mat_doc_item = uji.mat_doc_item
AND mseg.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.material_doc_key = tgt.material_doc
AND src.mat_doc_year_key = tgt.mat_doc_year
AND src.mat_doc_item_key = tgt.mat_doc_item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
material_doc,
mat_doc_year,
mat_doc_item,
line_id,
parent_id,
level,
orig_line_itm,
movement_type,
auto_created,
material,
plant,
stor_loc,
batch,
stock_type,
status_key,
batch_restr,
special_stock,
vendor,
customer,
sales_order,
sales_ord_item,
sorder_schedule,
distribution,
debit_credit,
currency,
amount_in_lc,
delivery_costs,
amount,
d_c_ind_reval,
revaluation,
valuation_type,
quantity,
base_unit,
quantity_in_une,
unit_of_entry,
qty_in_opun,
order_price_un,
purchase_order,
item,
fisc_yr_ref_doc,
reference_doc,
ref_doc_item,
mat_doc_year_1,
material_doc_1,
mat_doc_item_1,
deliv_compl,
text,
equipment,
recipient,
unloading_point,
business_area,
co_area,
trdg_part_ba,
clearing_cocode,
cost_center,
not_in_use,
order_number,
asset,
sub_number,
cctposting_stat,
ord_post_stat,
projpost_stat,
pa_post_stat,
fiscal_year,
post_prev_per,
pst_to_pr_year,
company_code,
document_number,
line_item,
document_number_1,
line_item_1,
reservation_number,
item_no,
final_issue,
quantity_1,
stat_relevant,
receiving_mat,
receiving_plant,
receiving_sloc,
receiving_batch,
restricted_use,
stkeytferbatch,
val_type_tfr,
sp_ind_st_tfr,
movement_ind,
consumption,
receipt_ind,
gr_non_valuated,
no_of_pallets,
warehouse_no,
storage_type,
storage_bin,
stock_category,
movement_type_1,
tr_number,
tr_item,
posting_in_wm,
int_st_pst_src,
inter_post_dest,
dynamic_bin,
posting_chge_no,
trnsfr_priority,
to_number,
no_of_gr_slips,
reason_for_mvmt,
shipping_instr,
compliance,
real_estate_key,
cost_object,
profit_segment,
profit_center,
wbs_element,
network,
plan_no_f_oper,
counter,
order_item_no,
partner,
commitment_item,
g_l_account,
qty_in_oun,
order_unit,
revgr_desp_ir,
supplier,
dummy,
ext_amount_lc,
salval_inc_vat,
promotion,
account_assgmt_no,
sled_bbd,
int_object_no,
sales_value,
partner_pc,
record_type,
fund,
funds_center,
stock_mat,
receiving_mat_1,
quantity_string,
value_string,
qty_updating,
value_updating,
valuated_stock,
total_value,
price_control,
functional_area,
reference_date,
salval_w_o_vat,
reference_date_1,
automatic_po,
del_note_qty,
del_note_unit,
valuation,
status_gr_doc,
orig_line_itm_1,
alt_base_amnt,
tax_code,
tax_jur,
mpn_material,
gi_reval_o_k,
tax_code_1,
date_of_manuf,
staging_ind,
sales_order_1,
sales_ord_item_1,
wbs_element_1,
calcn_of_val_open,
acctindicator,
business_proc,
goods_supplier,
activity_type,
vendor_stk_val,
grants,
stock_type_mod,
gts_stock_type,
earmarked_funds,
document_item,
multi_acct_assgt,
trans_ev_type,
posting_date,
entered_on,
entered_at,
user_name,
reference,
transaction_code,
delivery,
item_1,
stock_segment,
rec_stock_seg,
reqmnt_segment,
service_performer,
personnel_no,
acct_assgmt_cat,
work_item_id,
serv_rendered,
print_active,
qty_in_puom,
parallel_uom,
puom_euom_qty,
puom_entry_uom,
service_doc_type,
service_document,
service_doc_item,
warehouse_no_1,
gm_document,
owner_of_stock,
season_year,
season,
collection,
theme,
season_year_1,
issuing_season,
issuing_collection,
issuing_theme,
discr_batch_no,
compl_ind,
do_not_adj_crq,
adjust_item,
dialog_box,
non_deductible,
condkey,
condkey_1,
characteristic_1,
characteristic_2,
characteristic_3,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.material_doc,
src.mat_doc_year,
src.mat_doc_item,
src.line_id,
src.parent_id,
src.level,
src.orig_line_itm,
src.movement_type,
src.auto_created,
src.material,
src.plant,
src.stor_loc,
src.batch,
src.stock_type,
src.status_key,
src.batch_restr,
src.special_stock,
src.vendor,
src.customer,
src.sales_order,
src.sales_ord_item,
src.sorder_schedule,
src.distribution,
src.debit_credit,
src.currency,
src.amount_in_lc,
src.delivery_costs,
src.amount,
src.d_c_ind_reval,
src.revaluation,
src.valuation_type,
src.quantity,
src.base_unit,
src.quantity_in_une,
src.unit_of_entry,
src.qty_in_opun,
src.order_price_un,
src.purchase_order,
src.item,
src.fisc_yr_ref_doc,
src.reference_doc,
src.ref_doc_item,
src.mat_doc_year_1,
src.material_doc_1,
src.mat_doc_item_1,
src.deliv_compl,
src.text,
src.equipment,
src.recipient,
src.unloading_point,
src.business_area,
src.co_area,
src.trdg_part_ba,
src.clearing_cocode,
src.cost_center,
src.not_in_use,
src.order_number,
src.asset,
src.sub_number,
src.cctposting_stat,
src.ord_post_stat,
src.projpost_stat,
src.pa_post_stat,
src.fiscal_year,
src.post_prev_per,
src.pst_to_pr_year,
src.company_code,
src.document_number,
src.line_item,
src.document_number_1,
src.line_item_1,
src.reservation_number,
src.item_no,
src.final_issue,
src.quantity_1,
src.stat_relevant,
src.receiving_mat,
src.receiving_plant,
src.receiving_sloc,
src.receiving_batch,
src.restricted_use,
src.stkeytferbatch,
src.val_type_tfr,
src.sp_ind_st_tfr,
src.movement_ind,
src.consumption,
src.receipt_ind,
src.gr_non_valuated,
src.no_of_pallets,
src.warehouse_no,
src.storage_type,
src.storage_bin,
src.stock_category,
src.movement_type_1,
src.tr_number,
src.tr_item,
src.posting_in_wm,
src.int_st_pst_src,
src.inter_post_dest,
src.dynamic_bin,
src.posting_chge_no,
src.trnsfr_priority,
src.to_number,
src.no_of_gr_slips,
src.reason_for_mvmt,
src.shipping_instr,
src.compliance,
src.real_estate_key,
src.cost_object,
src.profit_segment,
src.profit_center,
src.wbs_element,
src.network,
src.plan_no_f_oper,
src.counter,
src.order_item_no,
src.partner,
src.commitment_item,
src.g_l_account,
src.qty_in_oun,
src.order_unit,
src.revgr_desp_ir,
src.supplier,
src.dummy,
src.ext_amount_lc,
src.salval_inc_vat,
src.promotion,
src.account_assgmt_no,
src.sled_bbd,
src.int_object_no,
src.sales_value,
src.partner_pc,
src.record_type,
src.fund,
src.funds_center,
src.stock_mat,
src.receiving_mat_1,
src.quantity_string,
src.value_string,
src.qty_updating,
src.value_updating,
src.valuated_stock,
src.total_value,
src.price_control,
src.functional_area,
src.reference_date,
src.salval_w_o_vat,
src.reference_date_1,
src.automatic_po,
src.del_note_qty,
src.del_note_unit,
src.valuation,
src.status_gr_doc,
src.orig_line_itm_1,
src.alt_base_amnt,
src.tax_code,
src.tax_jur,
src.mpn_material,
src.gi_reval_o_k,
src.tax_code_1,
src.date_of_manuf,
src.staging_ind,
src.sales_order_1,
src.sales_ord_item_1,
src.wbs_element_1,
src.calcn_of_val_open,
src.acctindicator,
src.business_proc,
src.goods_supplier,
src.activity_type,
src.vendor_stk_val,
src.grants,
src.stock_type_mod,
src.gts_stock_type,
src.earmarked_funds,
src.document_item,
src.multi_acct_assgt,
src.trans_ev_type,
src.posting_date,
src.entered_on,
src.entered_at,
src.user_name,
src.reference,
src.transaction_code,
src.delivery,
src.item_1,
src.stock_segment,
src.rec_stock_seg,
src.reqmnt_segment,
src.service_performer,
src.personnel_no,
src.acct_assgmt_cat,
src.work_item_id,
src.serv_rendered,
src.print_active,
src.qty_in_puom,
src.parallel_uom,
src.puom_euom_qty,
src.puom_entry_uom,
src.service_doc_type,
src.service_document,
src.service_doc_item,
src.warehouse_no_1,
src.gm_document,
src.owner_of_stock,
src.season_year,
src.season,
src.collection,
src.theme,
src.season_year_1,
src.issuing_season,
src.issuing_collection,
src.issuing_theme,
src.discr_batch_no,
src.compl_ind,
src.do_not_adj_crq,
src.adjust_item,
src.dialog_box,
src.non_deductible,
src.condkey,
src.condkey_1,
src.characteristic_1,
src.characteristic_2,
src.characteristic_3,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'material_movement_item_detail' as table_name
    		,'mseg' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'material_movement_item_detail') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'material_movement_item_detail') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.material_movement_item_detail`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.material_movement_item_detail` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'material_movement_item_detail'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.material_movement_item_detail`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    