MERGE INTO `sap-adapter.slt_staging.business_partner_general_data_details` tgt
USING (
WITH but000 as
(select CLIENT as client,
PARTNER as businesspartner,
TYPE as partn_cat,
BPKIND as partner_type,
BU_GROUP as partner_grouping,
BPEXT as external_number,
BU_SORT1 as search_term_1,
BU_SORT2 as search_term_2,
SOURCE as data_origin,
TITLE as title,
XDELE as archiving_flag,
XBLCK as central_block,
AUGRP as authorization_group,
TITLE_LET as salutation,
BU_LOGSYS as logical_system,
CONTACT as contact,
NOT_RELEASED as not_released,
NOT_LG_COMPETENT as not_legally_competnt,
PRINT_MODE as print_format,
BP_EEW_DUMMY as dummy_function_in_length_1,
RATE as cost_rev_rate,
NAME_ORG1 as name_1,
NAME_ORG2 as name_2,
NAME_ORG3 as name_3,
NAME_ORG4 as name_4,
LEGAL_ENTY as legal_form,
IND_SECTOR as industry_sector,
LEGAL_ORG as legal_entity,
FOUND_DAT as date_founded,
LIQUID_DAT as liquidation,
LOCATION_1 as location_no_1,
LOCATION_2 as location_no_2,
LOCATION_3 as check_digit,
NAME_LAST as last_name,
NAME_FIRST as first_name,
NAME_LST2 as other_last_name,
NAME_LAST2 as name_at_birth,
NAMEMIDDLE as middle_name,
TITLE_ACA1 as academic_title,
TITLE_ACA2 as nd_academic,
TITLE_ROYL as name_supplement,
PREFIX1 as prefix,
PREFIX2 as nd_prefix,
NAME1_TEXT as full_name,
NICKNAME as known_as,
INITIALS as initials,
NAMEFORMAT as name_format,
NAMCOUNTRY as format_country,
LANGU_CORR as correspondence_lang,
XSEXM as male,
XSEXF as female,
BIRTHPL as birthplace,
MARST as marital_status,
EMPLO as employer,
JOBGR as occupation,
NATIO as nationality,
CNTAX as obsolete_field,
CNDSC as country_of_orig,
PERSNUMBER as person_number,
XSEXU as unknown,
XUBNAME as user_name,
BU_LANGU as business_partner_language,
GENDER as sex,
BIRTHDT as date_of_birth,
DEATHDT as death_date,
PERNO as personnel_no,
CHILDREN as obsolete_field_1,
MEM_HOUSE as obsolete_field_2,
BIRTHDT_STATUS as birth_date_status,
PARTGRPTYP as group_type,
NAME_GRP1 as name_1_1,
NAME_GRP2 as name_2_1,
MC_NAME1 as name_1_last_nm,
MC_NAME2 as name2_first_nme,
CRUSR as created_by,
CRDAT as created_on,
CRTIM as created_at,
CHUSR as changed_by,
CHDAT as changed_on,
CHTIM as changed_at,
PARTNER_GUID as bp_guid,
ADDRCOMM as address_number,
TD_SWITCH as partner_converted,
IS_ORG_CENTRE as is_org_center,
DB_KEY as uuid_in_x_form_binary,
VALID_FROM as valid_from,
VALID_TO as valid_to,
XPCPT as purpose_completed,
NATPERS as natural_person,
MILVE as military_use,
NUC_SEC as nuclear_sector,
PAR_REL as release_indic,
BP_SORT as phonet_sort_fld,
KBANKS as bank_country,
KBANKL as bank_key,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct but000.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.but000` as but000
where but000._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'business_partner_general_data_details'),0))
select client as client_key,
businesspartner as businesspartner_key,
*
From  but000
UNION ALL
select null as client_key,
null as businesspartner_key,
but000.*
From but000 as but000
INNER JOIN `sap-adapter.slt_staging.business_partner_general_data_details` as uji
ON but000.client = uji.client
AND but000.businesspartner = uji.businesspartner
AND but000.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.businesspartner_key = tgt.businesspartner
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
businesspartner,
partn_cat,
partner_type,
partner_grouping,
external_number,
search_term_1,
search_term_2,
data_origin,
title,
archiving_flag,
central_block,
authorization_group,
salutation,
logical_system,
contact,
not_released,
not_legally_competnt,
print_format,
dummy_function_in_length_1,
cost_rev_rate,
name_1,
name_2,
name_3,
name_4,
legal_form,
industry_sector,
legal_entity,
date_founded,
liquidation,
location_no_1,
location_no_2,
check_digit,
last_name,
first_name,
other_last_name,
name_at_birth,
middle_name,
academic_title,
nd_academic,
name_supplement,
prefix,
nd_prefix,
full_name,
known_as,
initials,
name_format,
format_country,
correspondence_lang,
male,
female,
birthplace,
marital_status,
employer,
occupation,
nationality,
obsolete_field,
country_of_orig,
person_number,
unknown,
user_name,
business_partner_language,
sex,
date_of_birth,
death_date,
personnel_no,
obsolete_field_1,
obsolete_field_2,
birth_date_status,
group_type,
name_1_1,
name_2_1,
name_1_last_nm,
name2_first_nme,
created_by,
created_on,
created_at,
changed_by,
changed_on,
changed_at,
bp_guid,
address_number,
partner_converted,
is_org_center,
uuid_in_x_form_binary,
valid_from,
valid_to,
purpose_completed,
natural_person,
military_use,
nuclear_sector,
release_indic,
phonet_sort_fld,
bank_country,
bank_key,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.businesspartner,
src.partn_cat,
src.partner_type,
src.partner_grouping,
src.external_number,
src.search_term_1,
src.search_term_2,
src.data_origin,
src.title,
src.archiving_flag,
src.central_block,
src.authorization_group,
src.salutation,
src.logical_system,
src.contact,
src.not_released,
src.not_legally_competnt,
src.print_format,
src.dummy_function_in_length_1,
src.cost_rev_rate,
src.name_1,
src.name_2,
src.name_3,
src.name_4,
src.legal_form,
src.industry_sector,
src.legal_entity,
src.date_founded,
src.liquidation,
src.location_no_1,
src.location_no_2,
src.check_digit,
src.last_name,
src.first_name,
src.other_last_name,
src.name_at_birth,
src.middle_name,
src.academic_title,
src.nd_academic,
src.name_supplement,
src.prefix,
src.nd_prefix,
src.full_name,
src.known_as,
src.initials,
src.name_format,
src.format_country,
src.correspondence_lang,
src.male,
src.female,
src.birthplace,
src.marital_status,
src.employer,
src.occupation,
src.nationality,
src.obsolete_field,
src.country_of_orig,
src.person_number,
src.unknown,
src.user_name,
src.business_partner_language,
src.sex,
src.date_of_birth,
src.death_date,
src.personnel_no,
src.obsolete_field_1,
src.obsolete_field_2,
src.birth_date_status,
src.group_type,
src.name_1_1,
src.name_2_1,
src.name_1_last_nm,
src.name2_first_nme,
src.created_by,
src.created_on,
src.created_at,
src.changed_by,
src.changed_on,
src.changed_at,
src.bp_guid,
src.address_number,
src.partner_converted,
src.is_org_center,
src.uuid_in_x_form_binary,
src.valid_from,
src.valid_to,
src.purpose_completed,
src.natural_person,
src.military_use,
src.nuclear_sector,
src.release_indic,
src.phonet_sort_fld,
src.bank_country,
src.bank_key,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'business_partner_general_data_details' as table_name
    		,'but000' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'business_partner_general_data_details') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'business_partner_general_data_details') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.business_partner_general_data_details`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.business_partner_general_data_details` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'business_partner_general_data_details'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.business_partner_general_data_details`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    