MERGE INTO `sap-adapter.slt_staging.delivery_header` tgt
USING (
WITH likp as
(select MANDT as client,
VBELN as delivery,
ERNAM as created_by,
ERZET as entry_time,
ERDAT as created_on,
BZIRK as sales_district,
VSTEL as shipping_point,
VKORG as sales_org,
LFART as delivery_type,
AUTLF as complete_dlv,
KZAZU as order_combinat,
WADAT as planned_gds_mvmt,
LDDAT as loading_date,
TDDAT as transpplngdate,
LFDAT as delivery_date,
KODAT as pick_date,
ABLAD as unloading_point,
INCO1 as incoterms,
INCO2 as incoterms_2,
EXPKZ as export_indicator,
ROUTE as route,
FAKSK as billing_block,
LIFSK as delivery_block,
VBTYP as document_cat,
KNFAK as factorycalendar,
TPQUA as means_transp_qual,
TPGRP as means_of_transp_grp,
LPRIO as delivery_prior,
VSBED as shp_cond,
KUNNR as ship_to_party,
KUNAG as sold_to_party,
KDGRP as customer_group,
STZKL as wait_time_class,
STZZU as wait_time_surcharge,
BTGEW as total_weight,
NTGEW as net_weight,
GEWEI as weight_unit,
VOLUM as volume,
VOLEH as volume_unit,
ANZPK as no_of_packages,
BEROT as pickeditmlocat,
LFUHR as timeofdelivery,
GRULG as weight_group,
LSTEL as loading_point,
TRAGR as trans_group,
FKARV as dlvbillingtype,
FKDAT as billing_date,
PERFK as invoicing_dates,
ROUTA as route_1,
STAFO as update_group,
KALSM as procedure_pricing,
KNUMV as doc_condition,
WAERK as doc_currency,
VKBUR as sales_office,
VBEAK as total_proc_time,
ZUKRL as comb_criteria,
VERUR as original_doc,
COMMN as communicationno,
STWAE as stats_currency,
STCUR as exch_rate_stats,
EXNUM as foreign_trade_datanr,
AENAM as changed_by,
AEDAT as changed_on,
LGNUM as warehouse_no,
LISPL as id_delivery_split,
VKOIV as sales_org_icb,
VTWIV as distrib_channel,
SPAIV as div_iv,
FKAIV as intercobilltype,
PIOIV as billing_date_1,
FKDIV as billing_date_2,
KUNIV as cust_inter_co,
KKBER as cred_contr_area,
KNKLI as credit_account,
GRUPP as cust_cred_group,
SBGRP as cred_rep_grp,
CTLPC as risk_category,
CMWAE as currency,
AMTBL as credit_value,
BOLNR as bill_of_lading,
LIFNR as vendor,
TRATY as mnsoftrns_type,
TRAID as mns_of_trans_id,
CMFRE as release_date,
CMNGV as next_date,
XABLN as gr_gi_slip_no,
BLDAT as document_date,
WADAT_IST as actual_gi_date,
TRSPG as shpmtblreason,
TPSID as id_transp_syst,
LIFEX as ext_delivery,
TERNR as order_number,
KALSM_CH as search_proced,
KLIEF as corr_delivery,
KALSP as procedure_1,
KNUMP as doc_condition_1,
NETWR as net_value,
AULWE as route_schedule,
WERKS as receiving_plant,
LCNUM as financ_doc_no,
ABSSC as paym_guar_proc,
KOUHR as picking_time,
TDUHR as tr_plan_time,
LDUHR as loading_time,
WAUHR as gi_time,
LGTOR as door_for_whse,
LGBZO as staging_area,
AKWAE as lettofcredcrcy,
AKKUR as lettofcredrate,
AKPRZ as depreciation,
PROLI as dg_mgmt_profile,
XBLNR as reference,
HANDLE as key,
TSEGFL as tsegment_exists,
TSEGTP as template,
TZONIS as del_loc_tzone,
TZONRC as rec_time_zone,
CONT_DG as contains_dg,
VERURSYS as original_system,
KZWAB as ind_gds_mvmnt,
TCODE as transaction_code,
VSART as shipping_type,
TRMTYP as meanstransp,
SDABW as spec_processing,
VBUND as company_id,
XWOFF as calcn_of_val_open,
DIRTA as immed_to,
PRVBE as supply_area,
FOLAR as delivery_type_1,
PODAT as pod_date,
POTIM as confirm_time,
VGANZ as no_itms_pred_sys,
IMWRK as in_plant,
SPE_LOEKZ as doc_delet_id,
SPE_LOC_SEQ as location_seq,
SPE_ACC_APP_STS as del_conf_stat,
SPE_SHP_INF_STS as ship_info_stat,
SPE_RET_CANC as ret_asn_canc,
SPE_WAUHR_IST as gi_time_1,
SPE_WAZONE_IST as time_zone,
SPE_REV_VLSTK as statdecntrlwhse,
SPE_LE_SCENARIO as scenario_logistic_ex,
SPE_ORIG_SYS as original_system_type,
SPE_CHNG_SYS as changer_s_sys_type,
SPE_GEOROUTE as georoute,
SPE_GEOROUTEIND as chg_ind_route,
SPE_CARRIER_IND as change_ind,
SPE_GTS_REL as gds_traffic_ty,
SPE_GTS_RT_CDE as gtsroutecode,
SPE_REL_TMSTMP as rls_time_stamp,
SPE_UNIT_SYSTEM as msrmnt_unit_sys,
SPE_INV_BFR_GI as inv_bf_gi,
SPE_QI_STATUS as qi_status,
SPE_RED_IND as redirected,
SAKES as storage_status,
SPE_LIFEX_TYPE as type_ext_ident,
SPE_TTYPE as means_of_trans,
SPE_PRO_NUMBER as pro_number,
LOC_GUID as akkreditiv,
SPE_BILLING_IND as billing_indicator,
PRINTER_PROFILE as print_profile,
MSR_ACTIVE as adv_returns,
PRTNR as document_log,
STGE_LOC_CHANGE as stor_loc_change,
TM_CTRL_KEY as control_key,
DLV_SPLIT_INITIA as spl_iinitiator,
DLV_VERSION as dlv_version,
_DATAAGING as data_filter_value_for_data_agi,
GTS_VORPA as type_of_previous_doc,
GTS_VORNU as no_of_previous_doc,
GTS_EXPVZ as mode_of_trans,
GTS_PORTI as port_airport,
ITM_EXPVZ as mode_of_transport,
ITM_STGBE as ctry_meanstr_border,
ITM_KZGBE as id_means_transp_bord,
ITM_VYGID as conveyancerefidn,
ITM_IEVER as mode_transp_inland,
ITM_STABE as ctry_meanstr_inland,
ITM_KZABE as id_means_transp_inl,
HANDOVERLOC as handover_location,
HANDOVERDATE as handover_date,
HANDOVERTIME as handover_time,
HANDOVERTZONE as handoverloc_timezone,
BESTK as confirmed,
CMPSC as value,
CMPSD as termsofpayment,
CMPSI as financial_doc,
CMPSJ as exptcreditinsur,
CMPSK as payment_card,
CMPS_CM as sap_cred_mgmt,
CMPS_TE as crma_te_status,
CMGST as overallcredstat,
FKIVK as totals_status,
FKSTK as billing_status,
GBSTK as overall_status,
HDALL as hold,
HDALS as phold,
KOQUK as confirmation,
KOSTK as ovr_pick_status,
LVSTK as overallwmstatus,
PDSTK as pod_status,
PKSTK as packing_status,
SPE_TMPID as temporary_inbound_delivery,
SPSTG as overall_blk_st,
TRSTA as trns_plan_stat,
UVALL as header_data,
UVALS as item_data,
UVFAK as header_bill_dat,
UVFAS as item_bill_data,
UVPAK as head_data_pckg,
UVPAS as it_data_packag,
UVPIK as head_data_pck_putawy,
UVPIS as it_data_pck_putaway,
UVVLK as header_dlv_data,
UVVLS as item_deliv_data,
UVWAK as head_data_gm,
UVWAS as item_data_gm,
VESTK as hu_in_stock,
VLSTK as statdecntrlwhse_1,
WBSTK as ovrlgdsmvtstat,
UVK01 as hdr_reserves_1,
UVK02 as hdr_reserves_2,
UVK03 as hdr_reserves_3,
UVK04 as hdr_reserves_4,
UVK05 as hdr_reserves_5,
UVS01 as total_reserves1,
UVS02 as totalreserves2,
UVS03 as total_reserves3,
UVS04 as total_reserves4,
UVS05 as total_reserves5,
TOTAL_PCSTA as prod_marktablty_sts,
TOTAL_DGSTA as dangerous_goods_sts,
TOTAL_SDSSTA as sfty_data_sheet_sts,
__SAPMP__LBASK as dtucsta,
INCOV as inco_version,
INCO2_L as inco_location1,
INCO3_L as inco_location2,
OID_EXTBOL as extern_bol_no,
OID_MISCDL as miscell_del_no,
EXT_BUS_SYST_ID as ext_bus_syst_id,
SITKZ_DB as spec_iss_val_sit,
DUMMY_DELIVERY_INCL_EEW_PS as dummy_function_in_length_1,
__BEV1__LULEINH as loading_units,
__BEV1__RPFAESS as no_cat_1,
__BEV1__RPKIST as no_cat_2,
__BEV1__RPCONT as no_cat_3,
__BEV1__RPSONST as no_cat_4,
__BEV1__RPFLGNR as sequence_number,
IDT_CUR_EVTLOC as current_point,
IDT_CUR_EVTQUA as arrival_departure,
IDT_CUR_EVTTST as curr_tme_stamp,
IDT_CUR_ESTLOC as base_point,
IDT_CUR_ESTQUA as arrival_departure_1,
IDT_CUR_ESTTST as time_estim_stamp,
IDT_CUR_WRKQUA as event_estimation,
IDT_PRE_EVTLOC as prior_point,
IDT_PRE_EVTQUA as arrival_departure_2,
IDT_PRE_EVTTST as prior_tme_stamp,
IDT_PRE_ESTLOC as prior_base_pt,
IDT_PRE_ESTQUA as arrival_departure_3,
IDT_PRE_ESTTST as time_estim_stamp_1,
IDT_PRE_WRKQUA as event_estimation_1,
IDT_REF_ESTLOC as base_point_1,
IDT_REF_ESTQUA as arrival_departure_4,
IDT_REF_ESTTST as time_estim_stamp_2,
IDT_FIRM_LFDAT as delivery_date_fixed,
IDT_DOCNUM as idoc_number,
BORGR_GRP as inb_dly_group,
KBNKZ as kanban_indicat,
FSH_TRANSACTION as transaction_number,
FSH_VAS_LAST_ITEM as last_vas_item_number,
FSH_VAS_CG as vas_cust_group,
RFM_PSST_GROUP as psst_group,
JIT_RLVNT as jit_relevant,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct likp.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.likp` as likp
where likp._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'delivery_header'),0))
select client as client_key,
delivery as delivery_key,
*
From  likp
UNION ALL
select null as client_key,
null as delivery_key,
likp.*
From likp as likp
INNER JOIN `sap-adapter.slt_staging.delivery_header` as uji
ON likp.client = uji.client
AND likp.delivery = uji.delivery
AND likp.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.delivery_key = tgt.delivery
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
delivery,
created_by,
entry_time,
created_on,
sales_district,
shipping_point,
sales_org,
delivery_type,
complete_dlv,
order_combinat,
planned_gds_mvmt,
loading_date,
transpplngdate,
delivery_date,
pick_date,
unloading_point,
incoterms,
incoterms_2,
export_indicator,
route,
billing_block,
delivery_block,
document_cat,
factorycalendar,
means_transp_qual,
means_of_transp_grp,
delivery_prior,
shp_cond,
ship_to_party,
sold_to_party,
customer_group,
wait_time_class,
wait_time_surcharge,
total_weight,
net_weight,
weight_unit,
volume,
volume_unit,
no_of_packages,
pickeditmlocat,
timeofdelivery,
weight_group,
loading_point,
trans_group,
dlvbillingtype,
billing_date,
invoicing_dates,
route_1,
update_group,
procedure_pricing,
doc_condition,
doc_currency,
sales_office,
total_proc_time,
comb_criteria,
original_doc,
communicationno,
stats_currency,
exch_rate_stats,
foreign_trade_datanr,
changed_by,
changed_on,
warehouse_no,
id_delivery_split,
sales_org_icb,
distrib_channel,
div_iv,
intercobilltype,
billing_date_1,
billing_date_2,
cust_inter_co,
cred_contr_area,
credit_account,
cust_cred_group,
cred_rep_grp,
risk_category,
currency,
credit_value,
bill_of_lading,
vendor,
mnsoftrns_type,
mns_of_trans_id,
release_date,
next_date,
gr_gi_slip_no,
document_date,
actual_gi_date,
shpmtblreason,
id_transp_syst,
ext_delivery,
order_number,
search_proced,
corr_delivery,
procedure_1,
doc_condition_1,
net_value,
route_schedule,
receiving_plant,
financ_doc_no,
paym_guar_proc,
picking_time,
tr_plan_time,
loading_time,
gi_time,
door_for_whse,
staging_area,
lettofcredcrcy,
lettofcredrate,
depreciation,
dg_mgmt_profile,
reference,
key,
tsegment_exists,
template,
del_loc_tzone,
rec_time_zone,
contains_dg,
original_system,
ind_gds_mvmnt,
transaction_code,
shipping_type,
meanstransp,
spec_processing,
company_id,
calcn_of_val_open,
immed_to,
supply_area,
delivery_type_1,
pod_date,
confirm_time,
no_itms_pred_sys,
in_plant,
doc_delet_id,
location_seq,
del_conf_stat,
ship_info_stat,
ret_asn_canc,
gi_time_1,
time_zone,
statdecntrlwhse,
scenario_logistic_ex,
original_system_type,
changer_s_sys_type,
georoute,
chg_ind_route,
change_ind,
gds_traffic_ty,
gtsroutecode,
rls_time_stamp,
msrmnt_unit_sys,
inv_bf_gi,
qi_status,
redirected,
storage_status,
type_ext_ident,
means_of_trans,
pro_number,
akkreditiv,
billing_indicator,
print_profile,
adv_returns,
document_log,
stor_loc_change,
control_key,
spl_iinitiator,
dlv_version,
data_filter_value_for_data_agi,
type_of_previous_doc,
no_of_previous_doc,
mode_of_trans,
port_airport,
mode_of_transport,
ctry_meanstr_border,
id_means_transp_bord,
conveyancerefidn,
mode_transp_inland,
ctry_meanstr_inland,
id_means_transp_inl,
handover_location,
handover_date,
handover_time,
handoverloc_timezone,
confirmed,
value,
termsofpayment,
financial_doc,
exptcreditinsur,
payment_card,
sap_cred_mgmt,
crma_te_status,
overallcredstat,
totals_status,
billing_status,
overall_status,
hold,
phold,
confirmation,
ovr_pick_status,
overallwmstatus,
pod_status,
packing_status,
temporary_inbound_delivery,
overall_blk_st,
trns_plan_stat,
header_data,
item_data,
header_bill_dat,
item_bill_data,
head_data_pckg,
it_data_packag,
head_data_pck_putawy,
it_data_pck_putaway,
header_dlv_data,
item_deliv_data,
head_data_gm,
item_data_gm,
hu_in_stock,
statdecntrlwhse_1,
ovrlgdsmvtstat,
hdr_reserves_1,
hdr_reserves_2,
hdr_reserves_3,
hdr_reserves_4,
hdr_reserves_5,
total_reserves1,
totalreserves2,
total_reserves3,
total_reserves4,
total_reserves5,
prod_marktablty_sts,
dangerous_goods_sts,
sfty_data_sheet_sts,
dtucsta,
inco_version,
inco_location1,
inco_location2,
extern_bol_no,
miscell_del_no,
ext_bus_syst_id,
spec_iss_val_sit,
dummy_function_in_length_1,
loading_units,
no_cat_1,
no_cat_2,
no_cat_3,
no_cat_4,
sequence_number,
current_point,
arrival_departure,
curr_tme_stamp,
base_point,
arrival_departure_1,
time_estim_stamp,
event_estimation,
prior_point,
arrival_departure_2,
prior_tme_stamp,
prior_base_pt,
arrival_departure_3,
time_estim_stamp_1,
event_estimation_1,
base_point_1,
arrival_departure_4,
time_estim_stamp_2,
delivery_date_fixed,
idoc_number,
inb_dly_group,
kanban_indicat,
transaction_number,
last_vas_item_number,
vas_cust_group,
psst_group,
jit_relevant,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.delivery,
src.created_by,
src.entry_time,
src.created_on,
src.sales_district,
src.shipping_point,
src.sales_org,
src.delivery_type,
src.complete_dlv,
src.order_combinat,
src.planned_gds_mvmt,
src.loading_date,
src.transpplngdate,
src.delivery_date,
src.pick_date,
src.unloading_point,
src.incoterms,
src.incoterms_2,
src.export_indicator,
src.route,
src.billing_block,
src.delivery_block,
src.document_cat,
src.factorycalendar,
src.means_transp_qual,
src.means_of_transp_grp,
src.delivery_prior,
src.shp_cond,
src.ship_to_party,
src.sold_to_party,
src.customer_group,
src.wait_time_class,
src.wait_time_surcharge,
src.total_weight,
src.net_weight,
src.weight_unit,
src.volume,
src.volume_unit,
src.no_of_packages,
src.pickeditmlocat,
src.timeofdelivery,
src.weight_group,
src.loading_point,
src.trans_group,
src.dlvbillingtype,
src.billing_date,
src.invoicing_dates,
src.route_1,
src.update_group,
src.procedure_pricing,
src.doc_condition,
src.doc_currency,
src.sales_office,
src.total_proc_time,
src.comb_criteria,
src.original_doc,
src.communicationno,
src.stats_currency,
src.exch_rate_stats,
src.foreign_trade_datanr,
src.changed_by,
src.changed_on,
src.warehouse_no,
src.id_delivery_split,
src.sales_org_icb,
src.distrib_channel,
src.div_iv,
src.intercobilltype,
src.billing_date_1,
src.billing_date_2,
src.cust_inter_co,
src.cred_contr_area,
src.credit_account,
src.cust_cred_group,
src.cred_rep_grp,
src.risk_category,
src.currency,
src.credit_value,
src.bill_of_lading,
src.vendor,
src.mnsoftrns_type,
src.mns_of_trans_id,
src.release_date,
src.next_date,
src.gr_gi_slip_no,
src.document_date,
src.actual_gi_date,
src.shpmtblreason,
src.id_transp_syst,
src.ext_delivery,
src.order_number,
src.search_proced,
src.corr_delivery,
src.procedure_1,
src.doc_condition_1,
src.net_value,
src.route_schedule,
src.receiving_plant,
src.financ_doc_no,
src.paym_guar_proc,
src.picking_time,
src.tr_plan_time,
src.loading_time,
src.gi_time,
src.door_for_whse,
src.staging_area,
src.lettofcredcrcy,
src.lettofcredrate,
src.depreciation,
src.dg_mgmt_profile,
src.reference,
src.key,
src.tsegment_exists,
src.template,
src.del_loc_tzone,
src.rec_time_zone,
src.contains_dg,
src.original_system,
src.ind_gds_mvmnt,
src.transaction_code,
src.shipping_type,
src.meanstransp,
src.spec_processing,
src.company_id,
src.calcn_of_val_open,
src.immed_to,
src.supply_area,
src.delivery_type_1,
src.pod_date,
src.confirm_time,
src.no_itms_pred_sys,
src.in_plant,
src.doc_delet_id,
src.location_seq,
src.del_conf_stat,
src.ship_info_stat,
src.ret_asn_canc,
src.gi_time_1,
src.time_zone,
src.statdecntrlwhse,
src.scenario_logistic_ex,
src.original_system_type,
src.changer_s_sys_type,
src.georoute,
src.chg_ind_route,
src.change_ind,
src.gds_traffic_ty,
src.gtsroutecode,
src.rls_time_stamp,
src.msrmnt_unit_sys,
src.inv_bf_gi,
src.qi_status,
src.redirected,
src.storage_status,
src.type_ext_ident,
src.means_of_trans,
src.pro_number,
src.akkreditiv,
src.billing_indicator,
src.print_profile,
src.adv_returns,
src.document_log,
src.stor_loc_change,
src.control_key,
src.spl_iinitiator,
src.dlv_version,
src.data_filter_value_for_data_agi,
src.type_of_previous_doc,
src.no_of_previous_doc,
src.mode_of_trans,
src.port_airport,
src.mode_of_transport,
src.ctry_meanstr_border,
src.id_means_transp_bord,
src.conveyancerefidn,
src.mode_transp_inland,
src.ctry_meanstr_inland,
src.id_means_transp_inl,
src.handover_location,
src.handover_date,
src.handover_time,
src.handoverloc_timezone,
src.confirmed,
src.value,
src.termsofpayment,
src.financial_doc,
src.exptcreditinsur,
src.payment_card,
src.sap_cred_mgmt,
src.crma_te_status,
src.overallcredstat,
src.totals_status,
src.billing_status,
src.overall_status,
src.hold,
src.phold,
src.confirmation,
src.ovr_pick_status,
src.overallwmstatus,
src.pod_status,
src.packing_status,
src.temporary_inbound_delivery,
src.overall_blk_st,
src.trns_plan_stat,
src.header_data,
src.item_data,
src.header_bill_dat,
src.item_bill_data,
src.head_data_pckg,
src.it_data_packag,
src.head_data_pck_putawy,
src.it_data_pck_putaway,
src.header_dlv_data,
src.item_deliv_data,
src.head_data_gm,
src.item_data_gm,
src.hu_in_stock,
src.statdecntrlwhse_1,
src.ovrlgdsmvtstat,
src.hdr_reserves_1,
src.hdr_reserves_2,
src.hdr_reserves_3,
src.hdr_reserves_4,
src.hdr_reserves_5,
src.total_reserves1,
src.totalreserves2,
src.total_reserves3,
src.total_reserves4,
src.total_reserves5,
src.prod_marktablty_sts,
src.dangerous_goods_sts,
src.sfty_data_sheet_sts,
src.dtucsta,
src.inco_version,
src.inco_location1,
src.inco_location2,
src.extern_bol_no,
src.miscell_del_no,
src.ext_bus_syst_id,
src.spec_iss_val_sit,
src.dummy_function_in_length_1,
src.loading_units,
src.no_cat_1,
src.no_cat_2,
src.no_cat_3,
src.no_cat_4,
src.sequence_number,
src.current_point,
src.arrival_departure,
src.curr_tme_stamp,
src.base_point,
src.arrival_departure_1,
src.time_estim_stamp,
src.event_estimation,
src.prior_point,
src.arrival_departure_2,
src.prior_tme_stamp,
src.prior_base_pt,
src.arrival_departure_3,
src.time_estim_stamp_1,
src.event_estimation_1,
src.base_point_1,
src.arrival_departure_4,
src.time_estim_stamp_2,
src.delivery_date_fixed,
src.idoc_number,
src.inb_dly_group,
src.kanban_indicat,
src.transaction_number,
src.last_vas_item_number,
src.vas_cust_group,
src.psst_group,
src.jit_relevant,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'delivery_header' as table_name
    		,'likp' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'delivery_header') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'delivery_header') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.delivery_header`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.delivery_header` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'delivery_header'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.delivery_header`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    