MERGE INTO `sap-adapter.slt_staging.supplier_master_compnay_code_details` tgt
USING (
WITH lfb1 as
(select MANDT as client,
LIFNR as vendor,
BUKRS as company_code,
PERNR as personnel_no,
ERDAT as created_on,
ERNAM as created_by,
SPERR as co_code_post_block,
LOEVM as co_cde_deletion_flag,
ZUAWA as sort_key,
AKONT as recon_account,
BEGRU as authorization,
VZSKZ as interest_indic,
ZWELS as payment_methods,
XVERR as clrg_with_cust,
ZAHLS as payment_block,
ZTERM as payt_terms,
EIKTO as acct_w_vendor,
ZSABE as clerk_at_vendor,
KVERM as account_memo,
FDGRV as planning_group,
BUSAB as clerk_abbrev,
LNRZE as head_office,
LNRZB as alternat_payee,
ZINDT as last_key_date,
ZINRT as int_calc_freq,
DATLZ as last_int_calc,
XDEZV as local_process,
WEBTR as bill_ex_limit,
KULTG as chk_cashng_time,
REPRF as chk_double_inv,
TOGRU as tolerance_group,
HBKID as house_bank,
XPORE as individual_payt,
QSZNR as exemption_no,
QSZDT as valid_until,
QSSKZ as wtax_code,
BLNKZ as subs_ind,
MINDK as minority_indic,
ALTKN as prev_acct_no,
ZGRUP as grouping_key,
MGRUP as grouping_key_1,
UZAWE as pmt_meth_supl,
QSREC as recipient_type,
QSBGR as exmpt_authority,
QLAND as wtax_country,
XEDIP as pmt_adv_by_edi,
FRGRP as release_group,
TOGRR as tolerance_grp,
TLFXS as clerk_s_fax,
INTAD as clrk_s_internet,
XLFZB as alt_payee_doc,
GUZTE as cr_memo_terms,
GRICD as activity_code,
GRIDT as distr_type,
XAUSZ as acct_statement,
CERDT as certifictn_date,
CONFS as confirmst_ccd,
UPDAT as confirm_date,
UPTIM as confirm_time,
NODEL as cocd_del_block,
TLFNS as act_clk_tel_no,
AVSND as pmtadv_xml,
AD_HASH as e_mail_for_avis,
CVP_XBLCK_B as purposecomplete_flag,
CIIUCODE as main_economic_act,
LFB1_EEW_CC as dataelement_for_the_extension,
ZBOKD as ledger_exp_date,
ZQSSKZ as future_w_tax_code,
ZQSZDT as valid_until_1,
ZQSZNR as f_exemption_no,
ZMINDAT as cer_date_min_wage,
J_SC_SUBCONTYPE as subcontractor_type,
J_SC_COMPDATE as completion_date,
J_SC_OFFSM as offset_method,
J_SC_OFFSR as offset_percentage,
BASIS_PNT as basis_points,
GMVKZK as execution,
BRSCH as industry,
WRBTR as amount_for_pmt_progr,
WAERS as currency,
FORGN as foreign_shareholder,
SHARE_IN_FOREIGN as foreign_share,
NOTES as notes,
ACTIVE as shr_is_active,
PREPAY_RELEVANT as prepayment_relevant,
ASSIGN_TEST as assignm_test_group,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct lfb1.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.lfb1` as lfb1
where lfb1._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'supplier_master_compnay_code_details'),0))
select client as client_key,
vendor as vendor_key,
company_code as company_code_key,
*
From  lfb1
UNION ALL
select null as client_key,
null as vendor_key,
null as company_code_key,
lfb1.*
From lfb1 as lfb1
INNER JOIN `sap-adapter.slt_staging.supplier_master_compnay_code_details` as uji
ON lfb1.client = uji.client
AND lfb1.vendor = uji.vendor
AND lfb1.company_code = uji.company_code
AND lfb1.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.vendor_key = tgt.vendor
AND src.company_code_key = tgt.company_code
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
vendor,
company_code,
personnel_no,
created_on,
created_by,
co_code_post_block,
co_cde_deletion_flag,
sort_key,
recon_account,
authorization,
interest_indic,
payment_methods,
clrg_with_cust,
payment_block,
payt_terms,
acct_w_vendor,
clerk_at_vendor,
account_memo,
planning_group,
clerk_abbrev,
head_office,
alternat_payee,
last_key_date,
int_calc_freq,
last_int_calc,
local_process,
bill_ex_limit,
chk_cashng_time,
chk_double_inv,
tolerance_group,
house_bank,
individual_payt,
exemption_no,
valid_until,
wtax_code,
subs_ind,
minority_indic,
prev_acct_no,
grouping_key,
grouping_key_1,
pmt_meth_supl,
recipient_type,
exmpt_authority,
wtax_country,
pmt_adv_by_edi,
release_group,
tolerance_grp,
clerk_s_fax,
clrk_s_internet,
alt_payee_doc,
cr_memo_terms,
activity_code,
distr_type,
acct_statement,
certifictn_date,
confirmst_ccd,
confirm_date,
confirm_time,
cocd_del_block,
act_clk_tel_no,
pmtadv_xml,
e_mail_for_avis,
purposecomplete_flag,
main_economic_act,
dataelement_for_the_extension,
ledger_exp_date,
future_w_tax_code,
valid_until_1,
f_exemption_no,
cer_date_min_wage,
subcontractor_type,
completion_date,
offset_method,
offset_percentage,
basis_points,
execution,
industry,
amount_for_pmt_progr,
currency,
foreign_shareholder,
foreign_share,
notes,
shr_is_active,
prepayment_relevant,
assignm_test_group,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.vendor,
src.company_code,
src.personnel_no,
src.created_on,
src.created_by,
src.co_code_post_block,
src.co_cde_deletion_flag,
src.sort_key,
src.recon_account,
src.authorization,
src.interest_indic,
src.payment_methods,
src.clrg_with_cust,
src.payment_block,
src.payt_terms,
src.acct_w_vendor,
src.clerk_at_vendor,
src.account_memo,
src.planning_group,
src.clerk_abbrev,
src.head_office,
src.alternat_payee,
src.last_key_date,
src.int_calc_freq,
src.last_int_calc,
src.local_process,
src.bill_ex_limit,
src.chk_cashng_time,
src.chk_double_inv,
src.tolerance_group,
src.house_bank,
src.individual_payt,
src.exemption_no,
src.valid_until,
src.wtax_code,
src.subs_ind,
src.minority_indic,
src.prev_acct_no,
src.grouping_key,
src.grouping_key_1,
src.pmt_meth_supl,
src.recipient_type,
src.exmpt_authority,
src.wtax_country,
src.pmt_adv_by_edi,
src.release_group,
src.tolerance_grp,
src.clerk_s_fax,
src.clrk_s_internet,
src.alt_payee_doc,
src.cr_memo_terms,
src.activity_code,
src.distr_type,
src.acct_statement,
src.certifictn_date,
src.confirmst_ccd,
src.confirm_date,
src.confirm_time,
src.cocd_del_block,
src.act_clk_tel_no,
src.pmtadv_xml,
src.e_mail_for_avis,
src.purposecomplete_flag,
src.main_economic_act,
src.dataelement_for_the_extension,
src.ledger_exp_date,
src.future_w_tax_code,
src.valid_until_1,
src.f_exemption_no,
src.cer_date_min_wage,
src.subcontractor_type,
src.completion_date,
src.offset_method,
src.offset_percentage,
src.basis_points,
src.execution,
src.industry,
src.amount_for_pmt_progr,
src.currency,
src.foreign_shareholder,
src.foreign_share,
src.notes,
src.shr_is_active,
src.prepayment_relevant,
src.assignm_test_group,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'supplier_master_compnay_code_details' as table_name
    		,'lfb1' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'supplier_master_compnay_code_details') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'supplier_master_compnay_code_details') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.supplier_master_compnay_code_details`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.supplier_master_compnay_code_details` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'supplier_master_compnay_code_details'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.supplier_master_compnay_code_details`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    