MERGE INTO `sap-adapter.slt_staging.customer_master` tgt
USING (
WITH kna1 as
(select MANDT as client,
KUNNR as customer,
LAND1 as country,
NAME1 as name,
NAME2 as name_2,
ORT01 as city,
PSTLZ as postal_code,
REGIO as region,
SORTL as search_term,
STRAS as street,
TELF1 as telephone_1,
TELFX as fax_number,
XCPDK as one_time_acct,
ADRNR as address,
MCOD1 as name_1,
MCOD2 as name_2_1,
MCOD3 as city_1,
ANRED as title,
AUFSD as order_block,
BAHNE as express_station,
BAHNS as train_station,
BBBNR as location_no_1,
BBSNR as location_no_2,
BEGRU as authorization,
BRSCH as industry,
BUBKZ as check_digit,
DATLT as data_line,
ERDAT as created_on,
ERNAM as created_by,
EXABL as unloading_pts,
FAKSD as billing_block,
FISKN as fiscal_address,
KNAZK as working_times,
KNRZA as alternat_payer,
KONZS as group_key,
KTOKD as account_group,
KUKLA as customer_class,
LIFNR as vendor,
LIFSD as delivery_block,
LOCCO as location_code,
LOEVM as deletion_flag,
NAME3 as name_3,
NAME4 as name_4,
NIELS as nielsen_id,
ORT02 as district,
PFACH as po_box,
PSTL2 as po_box_pcode,
COUNC as county_code,
CITYC as city_code,
RPMKR as regional_market,
SPERR as posting_block,
SPRAS as language_key,
STCD1 as tax_number_1,
STCD2 as tax_number_2,
STKZA as equalizatn_tax,
STKZU as liable_for_vat,
TELBX as telebox,
TELF2 as telephone_2,
TELTX as teletex,
TELX1 as telex,
LZONE as transport_zone,
XZEMP as al_payer_in_doc,
VBUND as trading_partner,
STCEG as vat_reg_no,
DEAR1 as competitors,
DEAR2 as sales_partner,
DEAR3 as prospect,
DEAR4 as cust_type_4,
DEAR5 as default_sp,
GFORM as legal_status,
BRAN1 as industry_code_1,
BRAN2 as industry_code_2,
BRAN3 as industry_code_3,
BRAN4 as industry_code_4,
BRAN5 as industry_code_5,
EKONT as initial_contact,
UMSAT as annual_sales,
UMJAH as sales_year,
UWAER as currency,
JMZAH as employee,
JMJAH as year,
KATR1 as attribute_1,
KATR2 as attribute_2,
KATR3 as attribute_3,
KATR4 as attribute_4,
KATR5 as attribute_5,
KATR6 as attribute_6,
KATR7 as attribute_7,
KATR8 as attribute_8,
KATR9 as attribute_9,
KATR10 as attribute_10,
STKZN as natural_person,
UMSA1 as annual_sales_1,
TXJCD as tax_jur,
PERIV as fi_year_variant,
ABRVW as usage,
INSPBYDEBI as by_customer,
INSPATDEBI as after_delivery,
KTOCD as ref_acct_group,
PFORT as p_o_box_city,
WERKS as plant,
DTAMS as dme_indicator,
DTAWS as instruction_key,
DUEFL as data_transfer_status,
HZUOR as hier_assignment,
SPERZ as payment_block,
ETIKG as lab_cust_group,
CIVVE as non_milit_use,
MILVE as military_use,
KDKG1 as condition_grp_1,
KDKG2 as condition_grp_2,
KDKG3 as condition_grp_3,
KDKG4 as condition_grp_4,
KDKG5 as condition_grp_5,
XKNZA as alt_payer_doc,
FITYP as tax_type,
STCDT as tax_number_type,
STCD3 as tax_number_3,
STCD4 as tax_number_4,
STCD5 as tax_number_5,
XICMS as icms_exempt,
XXIPI as ipi_exempt,
XSUBT as subtrib_group,
CFOPC as cfop_category,
TXLW1 as icms_law,
TXLW2 as ipi_law,
CCC01 as biochem_warfare,
CCC02 as nucl_nonprolif,
CCC03 as natl_security,
CCC04 as missile_techn,
BONDED_AREA_CONFIRM as bonded_area_confirm,
DONATE_MARK as donate_mark,
CASSD as sales_block,
KNURL as url,
J_1KFREPRE as rep_s_name,
J_1KFTBUS as type_of_business,
J_1KFTIND as type_of_industry,
CONFS as confirm_status,
UPDAT as confirm_date,
UPTIM as confirm_time,
NODEL as deletion_block,
DEAR6 as consumer,
CVP_XBLCK as purposecomplete_flag,
SUFRAMA as suframa_code,
RG as rg_number,
EXP as issued_by,
UF as state,
RGDATE as rg_issuing_date,
RIC as ric_number,
RNE as foreign_national_reg,
RNEDATE as rne_issuing_date,
CNAE as cnae,
LEGALNAT as legal_nature,
CRTN as crt_number,
ICMSTAXPAY as icms_taxpayer,
INDTYP as industry_main_type,
TDT as tax_declaration_type,
COMSIZE as company_size,
DECREGPC as decl_reg_pis_cofi,
KNA1_EEW_CUST as data_element_for_customer,
RULE_EXCLUSION as account_excluded,
__VSO__R_PALHGT as max_stack_hght,
__VSO__R_PAL_UL as pkm_length_unit,
__VSO__R_PK_MAT as customerrelated,
__VSO__R_MATPAL as pkm_of_custom,
__VSO__R_I_NO_LYR as no_layers_inpal,
__VSO__R_ONE_MAT as material_spec,
__VSO__R_ONE_SORT as pack_pcktype,
__VSO__R_ULD_SIDE as side_preference,
__VSO__R_LOAD_PREF as f_b_preference,
__VSO__R_DPOINT as collunloadpoint,
ALC as agency_loc_cd,
PMT_OFFICE as payment_office,
FEE_SCHEDULE as fee_schedule,
DUNS as duns_number,
DUNS4 as duns_4,
PSOFG as processor_group,
PSOIS as slaprepr_proced,
PSON1 as name_5,
PSON2 as name_2_2,
PSON3 as name_3_1,
PSOVN as first_name,
PSOTL as title_1,
PSOHS as house_number,
PSOST as street_1,
PSOO1 as description,
PSOO2 as description_1,
PSOO3 as description_2,
PSOO4 as description_3,
PSOO5 as description_4,
J_1IEXCD as ecc_no,
J_1IEXRN as excise_reg_no,
J_1IEXRG as excise_range,
J_1IEXDI as excise_division,
J_1IEXCO as commissionerate,
J_1ICSTNO as cst_no,
J_1ILSTNO as lst_no,
J_1IPANNO as pan,
J_1IEXCICU as exc_ind_cust,
AEDAT as changed_on,
USNAM as changed_by,
J_1ISERN as service_tax_regn_no,
J_1IPANREF as pan_reference,
J_3GETYP as recipient_type,
J_3GREFTYP as reference_type,
PSPNR as wbs_element,
COAUFNR as order_number,
J_3GAGEXT as ext_sold_to_party,
J_3GAGINT as cust_int_settl,
J_3GAGDUMI as dummy_recipient,
J_3GAGSTDI as std_recipient,
LGORT as stor_loc,
KOKRS as co_area,
KOSTL as cost_center,
J_3GABGLG as retiredate_pbe,
J_3GABGVG as retiredate_tbe,
J_3GABRART as settl_type,
J_3GSTDMON as hours_per_month,
J_3GSTDTAG as hours_days,
J_3GTAGMON as days_month,
J_3GZUGTAG as acqdate_pbe,
J_3GMASCHB as pbe_document,
J_3GMEINSA as mltpl_usg_per,
J_3GKEINSA as short_op,
J_3GBLSPER as blckinddocentry,
J_3GKLEIVO as pbe_as_tbe,
J_3GCALID as calendar_id,
J_3GVMONAT as complete_month,
J_3GABRKEN as settlmnt_ind,
J_3GLABRECH as last_settlement,
J_3GAABRECH as current_settl,
J_3GZUTVHLG as with_acq_date,
J_3GNEGMEN as negqtyallowed,
J_3GFRISTLO as dlinelogic,
J_3GEMINBE as minusprd_rsctd,
J_3GFMGUE as relnotallunrusg,
J_3GZUSCHUE as srchrgeunrstuse,
J_3GSCHPRS as shift_price,
J_3GINVSTA as inv_status_cs,
__SAPCEM__DBER as planning_area,
__SAPCEM__KVMEQ as settlqtyequirel,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct kna1.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.kna1` as kna1
where kna1._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'customer_master'),0))
select client as client_key,
customer as customer_key,
*
From  kna1
UNION ALL
select null as client_key,
null as customer_key,
kna1.*
From kna1 as kna1
INNER JOIN `sap-adapter.slt_staging.customer_master` as uji
ON kna1.client = uji.client
AND kna1.customer = uji.customer
AND kna1.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.customer_key = tgt.customer
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
customer,
country,
name,
name_2,
city,
postal_code,
region,
search_term,
street,
telephone_1,
fax_number,
one_time_acct,
address,
name_1,
name_2_1,
city_1,
title,
order_block,
express_station,
train_station,
location_no_1,
location_no_2,
authorization,
industry,
check_digit,
data_line,
created_on,
created_by,
unloading_pts,
billing_block,
fiscal_address,
working_times,
alternat_payer,
group_key,
account_group,
customer_class,
vendor,
delivery_block,
location_code,
deletion_flag,
name_3,
name_4,
nielsen_id,
district,
po_box,
po_box_pcode,
county_code,
city_code,
regional_market,
posting_block,
language_key,
tax_number_1,
tax_number_2,
equalizatn_tax,
liable_for_vat,
telebox,
telephone_2,
teletex,
telex,
transport_zone,
al_payer_in_doc,
trading_partner,
vat_reg_no,
competitors,
sales_partner,
prospect,
cust_type_4,
default_sp,
legal_status,
industry_code_1,
industry_code_2,
industry_code_3,
industry_code_4,
industry_code_5,
initial_contact,
annual_sales,
sales_year,
currency,
employee,
year,
attribute_1,
attribute_2,
attribute_3,
attribute_4,
attribute_5,
attribute_6,
attribute_7,
attribute_8,
attribute_9,
attribute_10,
natural_person,
annual_sales_1,
tax_jur,
fi_year_variant,
usage,
by_customer,
after_delivery,
ref_acct_group,
p_o_box_city,
plant,
dme_indicator,
instruction_key,
data_transfer_status,
hier_assignment,
payment_block,
lab_cust_group,
non_milit_use,
military_use,
condition_grp_1,
condition_grp_2,
condition_grp_3,
condition_grp_4,
condition_grp_5,
alt_payer_doc,
tax_type,
tax_number_type,
tax_number_3,
tax_number_4,
tax_number_5,
icms_exempt,
ipi_exempt,
subtrib_group,
cfop_category,
icms_law,
ipi_law,
biochem_warfare,
nucl_nonprolif,
natl_security,
missile_techn,
bonded_area_confirm,
donate_mark,
sales_block,
url,
rep_s_name,
type_of_business,
type_of_industry,
confirm_status,
confirm_date,
confirm_time,
deletion_block,
consumer,
purposecomplete_flag,
suframa_code,
rg_number,
issued_by,
state,
rg_issuing_date,
ric_number,
foreign_national_reg,
rne_issuing_date,
cnae,
legal_nature,
crt_number,
icms_taxpayer,
industry_main_type,
tax_declaration_type,
company_size,
decl_reg_pis_cofi,
data_element_for_customer,
account_excluded,
max_stack_hght,
pkm_length_unit,
customerrelated,
pkm_of_custom,
no_layers_inpal,
material_spec,
pack_pcktype,
side_preference,
f_b_preference,
collunloadpoint,
agency_loc_cd,
payment_office,
fee_schedule,
duns_number,
duns_4,
processor_group,
slaprepr_proced,
name_5,
name_2_2,
name_3_1,
first_name,
title_1,
house_number,
street_1,
description,
description_1,
description_2,
description_3,
description_4,
ecc_no,
excise_reg_no,
excise_range,
excise_division,
commissionerate,
cst_no,
lst_no,
pan,
exc_ind_cust,
changed_on,
changed_by,
service_tax_regn_no,
pan_reference,
recipient_type,
reference_type,
wbs_element,
order_number,
ext_sold_to_party,
cust_int_settl,
dummy_recipient,
std_recipient,
stor_loc,
co_area,
cost_center,
retiredate_pbe,
retiredate_tbe,
settl_type,
hours_per_month,
hours_days,
days_month,
acqdate_pbe,
pbe_document,
mltpl_usg_per,
short_op,
blckinddocentry,
pbe_as_tbe,
calendar_id,
complete_month,
settlmnt_ind,
last_settlement,
current_settl,
with_acq_date,
negqtyallowed,
dlinelogic,
minusprd_rsctd,
relnotallunrusg,
srchrgeunrstuse,
shift_price,
inv_status_cs,
planning_area,
settlqtyequirel,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.customer,
src.country,
src.name,
src.name_2,
src.city,
src.postal_code,
src.region,
src.search_term,
src.street,
src.telephone_1,
src.fax_number,
src.one_time_acct,
src.address,
src.name_1,
src.name_2_1,
src.city_1,
src.title,
src.order_block,
src.express_station,
src.train_station,
src.location_no_1,
src.location_no_2,
src.authorization,
src.industry,
src.check_digit,
src.data_line,
src.created_on,
src.created_by,
src.unloading_pts,
src.billing_block,
src.fiscal_address,
src.working_times,
src.alternat_payer,
src.group_key,
src.account_group,
src.customer_class,
src.vendor,
src.delivery_block,
src.location_code,
src.deletion_flag,
src.name_3,
src.name_4,
src.nielsen_id,
src.district,
src.po_box,
src.po_box_pcode,
src.county_code,
src.city_code,
src.regional_market,
src.posting_block,
src.language_key,
src.tax_number_1,
src.tax_number_2,
src.equalizatn_tax,
src.liable_for_vat,
src.telebox,
src.telephone_2,
src.teletex,
src.telex,
src.transport_zone,
src.al_payer_in_doc,
src.trading_partner,
src.vat_reg_no,
src.competitors,
src.sales_partner,
src.prospect,
src.cust_type_4,
src.default_sp,
src.legal_status,
src.industry_code_1,
src.industry_code_2,
src.industry_code_3,
src.industry_code_4,
src.industry_code_5,
src.initial_contact,
src.annual_sales,
src.sales_year,
src.currency,
src.employee,
src.year,
src.attribute_1,
src.attribute_2,
src.attribute_3,
src.attribute_4,
src.attribute_5,
src.attribute_6,
src.attribute_7,
src.attribute_8,
src.attribute_9,
src.attribute_10,
src.natural_person,
src.annual_sales_1,
src.tax_jur,
src.fi_year_variant,
src.usage,
src.by_customer,
src.after_delivery,
src.ref_acct_group,
src.p_o_box_city,
src.plant,
src.dme_indicator,
src.instruction_key,
src.data_transfer_status,
src.hier_assignment,
src.payment_block,
src.lab_cust_group,
src.non_milit_use,
src.military_use,
src.condition_grp_1,
src.condition_grp_2,
src.condition_grp_3,
src.condition_grp_4,
src.condition_grp_5,
src.alt_payer_doc,
src.tax_type,
src.tax_number_type,
src.tax_number_3,
src.tax_number_4,
src.tax_number_5,
src.icms_exempt,
src.ipi_exempt,
src.subtrib_group,
src.cfop_category,
src.icms_law,
src.ipi_law,
src.biochem_warfare,
src.nucl_nonprolif,
src.natl_security,
src.missile_techn,
src.bonded_area_confirm,
src.donate_mark,
src.sales_block,
src.url,
src.rep_s_name,
src.type_of_business,
src.type_of_industry,
src.confirm_status,
src.confirm_date,
src.confirm_time,
src.deletion_block,
src.consumer,
src.purposecomplete_flag,
src.suframa_code,
src.rg_number,
src.issued_by,
src.state,
src.rg_issuing_date,
src.ric_number,
src.foreign_national_reg,
src.rne_issuing_date,
src.cnae,
src.legal_nature,
src.crt_number,
src.icms_taxpayer,
src.industry_main_type,
src.tax_declaration_type,
src.company_size,
src.decl_reg_pis_cofi,
src.data_element_for_customer,
src.account_excluded,
src.max_stack_hght,
src.pkm_length_unit,
src.customerrelated,
src.pkm_of_custom,
src.no_layers_inpal,
src.material_spec,
src.pack_pcktype,
src.side_preference,
src.f_b_preference,
src.collunloadpoint,
src.agency_loc_cd,
src.payment_office,
src.fee_schedule,
src.duns_number,
src.duns_4,
src.processor_group,
src.slaprepr_proced,
src.name_5,
src.name_2_2,
src.name_3_1,
src.first_name,
src.title_1,
src.house_number,
src.street_1,
src.description,
src.description_1,
src.description_2,
src.description_3,
src.description_4,
src.ecc_no,
src.excise_reg_no,
src.excise_range,
src.excise_division,
src.commissionerate,
src.cst_no,
src.lst_no,
src.pan,
src.exc_ind_cust,
src.changed_on,
src.changed_by,
src.service_tax_regn_no,
src.pan_reference,
src.recipient_type,
src.reference_type,
src.wbs_element,
src.order_number,
src.ext_sold_to_party,
src.cust_int_settl,
src.dummy_recipient,
src.std_recipient,
src.stor_loc,
src.co_area,
src.cost_center,
src.retiredate_pbe,
src.retiredate_tbe,
src.settl_type,
src.hours_per_month,
src.hours_days,
src.days_month,
src.acqdate_pbe,
src.pbe_document,
src.mltpl_usg_per,
src.short_op,
src.blckinddocentry,
src.pbe_as_tbe,
src.calendar_id,
src.complete_month,
src.settlmnt_ind,
src.last_settlement,
src.current_settl,
src.with_acq_date,
src.negqtyallowed,
src.dlinelogic,
src.minusprd_rsctd,
src.relnotallunrusg,
src.srchrgeunrstuse,
src.shift_price,
src.inv_status_cs,
src.planning_area,
src.settlqtyequirel,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'customer_master' as table_name
    		,'kna1' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'customer_master') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'customer_master') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.customer_master`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.customer_master` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'customer_master'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.customer_master`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    