MERGE INTO `sap-adapter.slt_staging.transfer_order_item` tgt
USING (
WITH ltap as
(select MANDT as client,
LGNUM as warehouse_no,
TANUM as to_number,
TAPOS as tr_order_item,
TBPOS as tr_item,
POSNR as item,
MATNR as material,
WERKS as plant,
CHARG as batch,
BESTQ as stock_category,
SOBKZ as special_stock,
SONUM as spec_stock_no,
STOFF as haz_matl_no,
MEINS as base_unit,
ALTME as alternativeunit,
UMREZ as counter,
UMREN as denominator,
LETYP as stor_unit_type,
KZFEH as preallstck,
LANUM as current_number,
KZQUI as conf_required,
KZNKO as zero_stock_chck,
NULKO as zero_stock_chck_1,
KZINV as invent_method,
IVNUM as inventory_rec,
PQUIT as confirmation,
QDATU as confirmat_date,
QZEIT as confirmat_time,
QNAME as user,
BRGEW as weight,
GEWEI as weight_unit,
MBPOS as mat_doc_item,
WEMPF as recipient,
ABLAD as unloading_point,
WDATU as gr_date,
WENUM as gr_number,
WEPOS as goods_rec_item,
ZEUGN as certificate_no,
LDEST as printer,
VORGA as transfer_proc,
VLTYP as source_stor_ty,
VLBER as src_stor_sectn,
VLPLA as source_stor_bin,
VKDYN as dynamic_bin,
VPPOS as source_bin_pos,
VANZL as st_un_rem_stock,
VANBR as par_pallet_qty,
VSOLM as source_targ_qty,
VISTM as source_act_qty,
VDIFM as source_bin_dif,
VSOLA as source_targ_qty_1,
VISTA as source_act_qty_1,
VDIFA as source_b_diff,
VLQNR as quant,
VAPPC as source_it_appc,
NLTYP as deststortype,
NLBER as dest_stor_sect,
NLPLA as destination_bin,
NKDYN as dynamic_bin_1,
NPPOS as dest_bin_posit,
NANZL as su_to_be_pl_st,
NANBR as part_pallet_qty,
NSOLM as dest_target_qty,
NISTM as act_qty_dest,
NDIFM as dest_diff_qty,
NSOLA as dest_target_qty_1,
NISTA as actual_qty,
NDIFA as dest_diff_qty_1,
NLQNR as quant_1,
NAPPC as dest_it_to_appc,
RLTYP as return_stor_ty,
RLBER as return_stor_ar,
RLPLA as return_stor_bin,
RPPOS as return_bin_pos,
RSOLM as ret_target_qty,
RISTM as act_ret_qty,
RDIFM as return_diff,
RSOLA as ret_target_qty_1,
RISTA as act_ret_qty_1,
RDIFA as return_diff_1,
RLQNR as quant_2,
RAPPC as ret_item_toappc,
DLTYP as storage_type,
DLPLA as storage_bin,
DLQNR as quant_3,
DMENG as difference_qty,
DMENA as difference_qty_1,
KZDIF as difference_ind,
MAKTX as description,
DRUCK as to_item_printed,
VLENR as source_su_no,
NLENR as dest_stor_unit,
DLENR as difference_su,
VLEST as srce_su_status,
NLEST as dest_su_status,
LELAS as stor_unit_cnts,
HOMVE as removal_tot_su,
POSTY as item_category,
ORPOS as original_item,
VSUMM as totals_info,
VBLCH as mixed_batches,
NSUMM as totals_info_1,
NBLCH as mixed_batches_1,
RSPOS as item_no,
VFDAT as sled_bbd,
VKAPV as capac_material,
VKAPA as capacity_check,
NKAPA as capacity_check_1,
RKAPA as capacity_check_2,
KZSUB as item_to_subsys,
QPLOS as inspection_lot,
QPLOA as insp_lot_old,
KZSTI as inspect_sample,
RSART as record_type,
KZECH as confirm_batch,
KOBER as picking_area,
LGORT as stor_loc,
SOLPO as plnd_time_toitm,
ZEIEI as time_unit,
L2SKR as step_picking,
VOLUM as volume,
VOLEH as volume_unit,
KZBEF as inv_mgmt_active,
IMREL as posting_in_im,
NWIRM as quantity_acting,
WIRME as act_ingred_uom,
NPLEI as dest_bin_chgble,
KBNKZ as kanban_indicat,
STOAN as cancell_request,
KGVNQ as separate_conf,
PVQUI as confirmation_1,
EDATU as confirmat_date_1,
EZEIT as confirmat_time_1,
ENAME as user_1,
KZFME as leading_uom,
QUSUB as conf_ind_extsys,
FHUTA as hu_item,
VNEST as scstrgeunitnstd,
VHILM as packmaterials,
VDUMM as indicator_source_su_is_pseudo,
NDUMM as indicator_destination_su_is_p,
VSERI as indicator_source_su_is_a_hu_w,
HUPIK as indicator_source_hu_suggested,
NXIDV as handling_unit,
NOLIS as flag_do_not_update_whse_contr,
NPIPO as notransf_pckpnt,
PIPAR as assignment_of_to_item_to_handl,
PCKPF as packing_control,
KZTRM as trm,
PASSD as conf_transfrd,
VBELN as delivery,
KZXDK as cross_dock,
KZVAS as value_added,
FROM_INSP_GUID as insp_guid,
TO_INSP_GUID as insp_guid_1,
DIFF_INSP_GUID as insp_guid_2,
RETURN_INSP_GUID as insp_guid_3,
__CWM__IND_CATCH as enter_parallel_qty,
__CWM__ACT_QTY as parallel_qty,
__CWM__ACT_UOM as parallel_uom,
__CWM__TGT_QTY as target_pq,
__CWM__TGT_UOM as parallel_uom_1,
__CWM__HU_NEW_QTY as new_hu_parallel_qty,
__CWM__HU_OLD_QTY as old_hu_parallel_qty,
__CWM__VEMEH as parallel_uom_2,
__CWM__XCWMAT as cw_material,
__CWM__MEINS as parallel_uom_3,
__CWM__IND_DELUPD as pq_in_delivery,
DCNUM as decision,
ZRSTG as indicator,
TOVAS as indicator_1,
SGT_SCAT as stock_segment,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct ltap.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.ltap` as ltap
where ltap._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'transfer_order_item'),0))
select client as client_key,
warehouse_no as warehouse_no_key,
to_number as to_number_key,
tr_order_item as tr_order_item_key,
*
From  ltap
UNION ALL
select null as client_key,
null as warehouse_no_key,
null as to_number_key,
null as tr_order_item_key,
ltap.*
From ltap as ltap
INNER JOIN `sap-adapter.slt_staging.transfer_order_item` as uji
ON ltap.client = uji.client
AND ltap.warehouse_no = uji.warehouse_no
AND ltap.to_number = uji.to_number
AND ltap.tr_order_item = uji.tr_order_item
AND ltap.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.warehouse_no_key = tgt.warehouse_no
AND src.to_number_key = tgt.to_number
AND src.tr_order_item_key = tgt.tr_order_item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
warehouse_no,
to_number,
tr_order_item,
tr_item,
item,
material,
plant,
batch,
stock_category,
special_stock,
spec_stock_no,
haz_matl_no,
base_unit,
alternativeunit,
counter,
denominator,
stor_unit_type,
preallstck,
current_number,
conf_required,
zero_stock_chck,
zero_stock_chck_1,
invent_method,
inventory_rec,
confirmation,
confirmat_date,
confirmat_time,
user,
weight,
weight_unit,
mat_doc_item,
recipient,
unloading_point,
gr_date,
gr_number,
goods_rec_item,
certificate_no,
printer,
transfer_proc,
source_stor_ty,
src_stor_sectn,
source_stor_bin,
dynamic_bin,
source_bin_pos,
st_un_rem_stock,
par_pallet_qty,
source_targ_qty,
source_act_qty,
source_bin_dif,
source_targ_qty_1,
source_act_qty_1,
source_b_diff,
quant,
source_it_appc,
deststortype,
dest_stor_sect,
destination_bin,
dynamic_bin_1,
dest_bin_posit,
su_to_be_pl_st,
part_pallet_qty,
dest_target_qty,
act_qty_dest,
dest_diff_qty,
dest_target_qty_1,
actual_qty,
dest_diff_qty_1,
quant_1,
dest_it_to_appc,
return_stor_ty,
return_stor_ar,
return_stor_bin,
return_bin_pos,
ret_target_qty,
act_ret_qty,
return_diff,
ret_target_qty_1,
act_ret_qty_1,
return_diff_1,
quant_2,
ret_item_toappc,
storage_type,
storage_bin,
quant_3,
difference_qty,
difference_qty_1,
difference_ind,
description,
to_item_printed,
source_su_no,
dest_stor_unit,
difference_su,
srce_su_status,
dest_su_status,
stor_unit_cnts,
removal_tot_su,
item_category,
original_item,
totals_info,
mixed_batches,
totals_info_1,
mixed_batches_1,
item_no,
sled_bbd,
capac_material,
capacity_check,
capacity_check_1,
capacity_check_2,
item_to_subsys,
inspection_lot,
insp_lot_old,
inspect_sample,
record_type,
confirm_batch,
picking_area,
stor_loc,
plnd_time_toitm,
time_unit,
step_picking,
volume,
volume_unit,
inv_mgmt_active,
posting_in_im,
quantity_acting,
act_ingred_uom,
dest_bin_chgble,
kanban_indicat,
cancell_request,
separate_conf,
confirmation_1,
confirmat_date_1,
confirmat_time_1,
user_1,
leading_uom,
conf_ind_extsys,
hu_item,
scstrgeunitnstd,
packmaterials,
indicator_source_su_is_pseudo,
indicator_destination_su_is_p,
indicator_source_su_is_a_hu_w,
indicator_source_hu_suggested,
handling_unit,
flag_do_not_update_whse_contr,
notransf_pckpnt,
assignment_of_to_item_to_handl,
packing_control,
trm,
conf_transfrd,
delivery,
cross_dock,
value_added,
insp_guid,
insp_guid_1,
insp_guid_2,
insp_guid_3,
enter_parallel_qty,
parallel_qty,
parallel_uom,
target_pq,
parallel_uom_1,
new_hu_parallel_qty,
old_hu_parallel_qty,
parallel_uom_2,
cw_material,
parallel_uom_3,
pq_in_delivery,
decision,
indicator,
indicator_1,
stock_segment,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.warehouse_no,
src.to_number,
src.tr_order_item,
src.tr_item,
src.item,
src.material,
src.plant,
src.batch,
src.stock_category,
src.special_stock,
src.spec_stock_no,
src.haz_matl_no,
src.base_unit,
src.alternativeunit,
src.counter,
src.denominator,
src.stor_unit_type,
src.preallstck,
src.current_number,
src.conf_required,
src.zero_stock_chck,
src.zero_stock_chck_1,
src.invent_method,
src.inventory_rec,
src.confirmation,
src.confirmat_date,
src.confirmat_time,
src.user,
src.weight,
src.weight_unit,
src.mat_doc_item,
src.recipient,
src.unloading_point,
src.gr_date,
src.gr_number,
src.goods_rec_item,
src.certificate_no,
src.printer,
src.transfer_proc,
src.source_stor_ty,
src.src_stor_sectn,
src.source_stor_bin,
src.dynamic_bin,
src.source_bin_pos,
src.st_un_rem_stock,
src.par_pallet_qty,
src.source_targ_qty,
src.source_act_qty,
src.source_bin_dif,
src.source_targ_qty_1,
src.source_act_qty_1,
src.source_b_diff,
src.quant,
src.source_it_appc,
src.deststortype,
src.dest_stor_sect,
src.destination_bin,
src.dynamic_bin_1,
src.dest_bin_posit,
src.su_to_be_pl_st,
src.part_pallet_qty,
src.dest_target_qty,
src.act_qty_dest,
src.dest_diff_qty,
src.dest_target_qty_1,
src.actual_qty,
src.dest_diff_qty_1,
src.quant_1,
src.dest_it_to_appc,
src.return_stor_ty,
src.return_stor_ar,
src.return_stor_bin,
src.return_bin_pos,
src.ret_target_qty,
src.act_ret_qty,
src.return_diff,
src.ret_target_qty_1,
src.act_ret_qty_1,
src.return_diff_1,
src.quant_2,
src.ret_item_toappc,
src.storage_type,
src.storage_bin,
src.quant_3,
src.difference_qty,
src.difference_qty_1,
src.difference_ind,
src.description,
src.to_item_printed,
src.source_su_no,
src.dest_stor_unit,
src.difference_su,
src.srce_su_status,
src.dest_su_status,
src.stor_unit_cnts,
src.removal_tot_su,
src.item_category,
src.original_item,
src.totals_info,
src.mixed_batches,
src.totals_info_1,
src.mixed_batches_1,
src.item_no,
src.sled_bbd,
src.capac_material,
src.capacity_check,
src.capacity_check_1,
src.capacity_check_2,
src.item_to_subsys,
src.inspection_lot,
src.insp_lot_old,
src.inspect_sample,
src.record_type,
src.confirm_batch,
src.picking_area,
src.stor_loc,
src.plnd_time_toitm,
src.time_unit,
src.step_picking,
src.volume,
src.volume_unit,
src.inv_mgmt_active,
src.posting_in_im,
src.quantity_acting,
src.act_ingred_uom,
src.dest_bin_chgble,
src.kanban_indicat,
src.cancell_request,
src.separate_conf,
src.confirmation_1,
src.confirmat_date_1,
src.confirmat_time_1,
src.user_1,
src.leading_uom,
src.conf_ind_extsys,
src.hu_item,
src.scstrgeunitnstd,
src.packmaterials,
src.indicator_source_su_is_pseudo,
src.indicator_destination_su_is_p,
src.indicator_source_su_is_a_hu_w,
src.indicator_source_hu_suggested,
src.handling_unit,
src.flag_do_not_update_whse_contr,
src.notransf_pckpnt,
src.assignment_of_to_item_to_handl,
src.packing_control,
src.trm,
src.conf_transfrd,
src.delivery,
src.cross_dock,
src.value_added,
src.insp_guid,
src.insp_guid_1,
src.insp_guid_2,
src.insp_guid_3,
src.enter_parallel_qty,
src.parallel_qty,
src.parallel_uom,
src.target_pq,
src.parallel_uom_1,
src.new_hu_parallel_qty,
src.old_hu_parallel_qty,
src.parallel_uom_2,
src.cw_material,
src.parallel_uom_3,
src.pq_in_delivery,
src.decision,
src.indicator,
src.indicator_1,
src.stock_segment,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'transfer_order_item' as table_name
    		,'ltap' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'transfer_order_item') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'transfer_order_item') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.transfer_order_item`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.transfer_order_item` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'transfer_order_item'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.transfer_order_item`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    