MERGE INTO `sap-adapter.slt_staging.supplier_master_details` tgt
USING (
WITH lfa1 as
(select MANDT as client,
LIFNR as vendor,
LAND1 as country,
NAME1 as name,
NAME2 as name_2,
NAME3 as name_3,
NAME4 as name_4,
ORT01 as city,
ORT02 as district,
PFACH as po_box,
PSTL2 as po_box_pcode,
PSTLZ as postal_code,
REGIO as region,
SORTL as search_term,
STRAS as street,
ADRNR as address,
MCOD1 as name_1,
MCOD2 as name_2_1,
MCOD3 as city_1,
ANRED as title,
BAHNS as train_station,
BBBNR as location_no_1,
BBSNR as location_no_2,
BEGRU as authorization,
BRSCH as industry,
BUBKZ as check_digit,
DATLT as data_line,
DTAMS as dme_indicator,
DTAWS as instruction_key,
ERDAT as created_on,
ERNAM as created_by,
ESRNR as isr_number,
KONZS as group_key,
KTOKK as account_group,
KUNNR as customer,
LNRZA as alternat_payee,
LOEVM as deletion_flag,
SPERR as posting_block,
SPERM as purch_block,
SPRAS as language_key,
STCD1 as tax_number_1,
STCD2 as tax_number_2,
STKZA as equalizatn_tax,
STKZU as liable_for_vat,
TELBX as telebox,
TELF1 as telephone_1,
TELF2 as telephone_2,
TELFX as fax_number,
TELTX as teletex,
TELX1 as telex,
XCPDK as one_time_acct,
XZEMP as payee_in_doc,
VBUND as trading_partner,
FISKN as fiscal_address,
STCEG as vat_reg_no,
STKZN as natural_person,
SPERQ as block_function,
GBORT as place_of_birth,
GBDAT as date_of_birth,
SEXKZ as sex,
KRAUS as info_number,
REVDB as last_ext_review,
QSSYS as actual_qm_sys,
KTOCK as ref_acct_group,
PFORT as p_o_box_city,
WERKS as plant,
LTSNA as vsr_relevant,
WERKR as plant_relevant,
PLKAL as factory_calend,
DUEFL as data_transfer_status,
TXJCD as tax_jur,
SPERZ as payment_block,
SCACD as scac,
SFRGR as car_freight_grp,
LZONE as transport_zone,
XLFZA as alt_payee_doc,
DLGRP as servagntprocgrp,
FITYP as tax_type,
STCDT as tax_number_type,
REGSS as social_ins,
ACTSS as soc_ins_code,
STCD3 as tax_number_3,
STCD4 as tax_number_4,
STCD5 as tax_number_5,
IPISP as tax_split,
TAXBS as tax_base,
PROFS as profession,
STGDL as stat_grp_agent,
EMNFR as external_manuf,
LFURL as url,
J_1KFREPRE as rep_s_name,
J_1KFTBUS as type_of_business,
J_1KFTIND as type_of_industry,
CONFS as confirm_status,
UPDAT as confirm_date,
UPTIM as confirm_time,
NODEL as deletion_block,
QSSYSDAT as qm_system_to,
PODKZB as pod_relevant,
FISKU as tax_office,
STENR as tax_number,
CARRIER_CONF as carrier_confirmation,
MIN_COMP as micro_comp,
TERM_LI as terms_liab,
CRC_NUM as crc_number,
CVP_XBLCK as purposecomplete_flag,
RG as rg_number,
EXP as issued_by,
UF as state,
RGDATE as rg_issuing_date,
RIC as ric_number,
RNE as foreign_national_reg,
RNEDATE as rne_issuing_date,
CNAE as cnae,
LEGALNAT as legal_nature,
CRTN as crt_number,
ICMSTAXPAY as icms_taxpayer,
INDTYP as industry_main_type,
TDT as tax_declaration_type,
COMSIZE as company_size,
DECREGPC as decl_reg_pis_cofi,
LFA1_EEW_SUPP as dataelement_exstensibility_for,
J_SC_CAPITAL as capital_amount,
J_SC_CURRENCY as currency,
ALC as agency_loc_cd,
PMT_OFFICE as payment_office,
PPA_RELEVANT as ppa_relevant,
PSOFG as processor_group,
PSOIS as slaprepr_proced,
PSON1 as name_5,
PSON2 as name_2_2,
PSON3 as name_3_1,
PSOVN as first_name,
PSOTL as title_1,
PSOHS as house_number,
PSOST as street_1,
BORGR_DATUN as dtelimit_ext_id,
BORGR_YEAUN as repetition,
ADDR2_STREET as street_2,
ADDR2_HOUSE_NUM as house_number_1,
ADDR2_POST as postal_code_1,
ADDR2_CITY as city_2,
ADDR2_COUNTRY as country_1,
CATEG as business_type,
PARTNER_NAME as prtnr_trad_name,
PARTNER_UTR as partner_s_utr,
STATUS as verif_status,
VFNUM as verification_n,
VFNID as tax_status,
CRN as comp_house_reg_no,
J_1IEXCD as ecc_no,
J_1IEXRN as excise_reg_no,
J_1IEXRG as excise_range,
J_1IEXDI as excise_division,
J_1IEXCO as commissionerate,
J_1ICSTNO as cst_no,
J_1ILSTNO as lst_no,
J_1IPANNO as pan,
J_1IEXCIVE as exc_ind_vendor,
J_1ISSIST as ssi_status,
J_1IVTYP as type_of_vendor,
J_1IVENCRE as cenvat,
AEDAT as changed_on,
USNAM as changed_by,
J_1ISERN as service_tax_regn_no,
J_1IPANREF as pan_reference,
J_1IPANVALDT as pan_valid_from_date,
J_1I_CUSTOMS as customs_vendor,
J_1IDEDREF as deductee_ref_no,
VEN_CLASS as gst_ven_class,
ENTPUB as public_entity,
ESCRIT as deed_public_use,
DVALSS as ss_certif_valid_date,
FRMCSS as ss_certificate_form,
CODCAE as cae_code,
AUSDIV as absence_of_debt,
TRANSPORT_CHAIN as transportation_chain,
STAGING_TIME as staging_time,
SCHEDULING_TYPE as scheduling_procedure,
SUBMI_RELEVANT as rel_for_coll_no,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct lfa1.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.lfa1` as lfa1
where lfa1._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'supplier_master_details'),0))
select client as client_key,
vendor as vendor_key,
*
From  lfa1
UNION ALL
select null as client_key,
null as vendor_key,
lfa1.*
From lfa1 as lfa1
INNER JOIN `sap-adapter.slt_staging.supplier_master_details` as uji
ON lfa1.client = uji.client
AND lfa1.vendor = uji.vendor
AND lfa1.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.vendor_key = tgt.vendor
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
vendor,
country,
name,
name_2,
name_3,
name_4,
city,
district,
po_box,
po_box_pcode,
postal_code,
region,
search_term,
street,
address,
name_1,
name_2_1,
city_1,
title,
train_station,
location_no_1,
location_no_2,
authorization,
industry,
check_digit,
data_line,
dme_indicator,
instruction_key,
created_on,
created_by,
isr_number,
group_key,
account_group,
customer,
alternat_payee,
deletion_flag,
posting_block,
purch_block,
language_key,
tax_number_1,
tax_number_2,
equalizatn_tax,
liable_for_vat,
telebox,
telephone_1,
telephone_2,
fax_number,
teletex,
telex,
one_time_acct,
payee_in_doc,
trading_partner,
fiscal_address,
vat_reg_no,
natural_person,
block_function,
place_of_birth,
date_of_birth,
sex,
info_number,
last_ext_review,
actual_qm_sys,
ref_acct_group,
p_o_box_city,
plant,
vsr_relevant,
plant_relevant,
factory_calend,
data_transfer_status,
tax_jur,
payment_block,
scac,
car_freight_grp,
transport_zone,
alt_payee_doc,
servagntprocgrp,
tax_type,
tax_number_type,
social_ins,
soc_ins_code,
tax_number_3,
tax_number_4,
tax_number_5,
tax_split,
tax_base,
profession,
stat_grp_agent,
external_manuf,
url,
rep_s_name,
type_of_business,
type_of_industry,
confirm_status,
confirm_date,
confirm_time,
deletion_block,
qm_system_to,
pod_relevant,
tax_office,
tax_number,
carrier_confirmation,
micro_comp,
terms_liab,
crc_number,
purposecomplete_flag,
rg_number,
issued_by,
state,
rg_issuing_date,
ric_number,
foreign_national_reg,
rne_issuing_date,
cnae,
legal_nature,
crt_number,
icms_taxpayer,
industry_main_type,
tax_declaration_type,
company_size,
decl_reg_pis_cofi,
dataelement_exstensibility_for,
capital_amount,
currency,
agency_loc_cd,
payment_office,
ppa_relevant,
processor_group,
slaprepr_proced,
name_5,
name_2_2,
name_3_1,
first_name,
title_1,
house_number,
street_1,
dtelimit_ext_id,
repetition,
street_2,
house_number_1,
postal_code_1,
city_2,
country_1,
business_type,
prtnr_trad_name,
partner_s_utr,
verif_status,
verification_n,
tax_status,
comp_house_reg_no,
ecc_no,
excise_reg_no,
excise_range,
excise_division,
commissionerate,
cst_no,
lst_no,
pan,
exc_ind_vendor,
ssi_status,
type_of_vendor,
cenvat,
changed_on,
changed_by,
service_tax_regn_no,
pan_reference,
pan_valid_from_date,
customs_vendor,
deductee_ref_no,
gst_ven_class,
public_entity,
deed_public_use,
ss_certif_valid_date,
ss_certificate_form,
cae_code,
absence_of_debt,
transportation_chain,
staging_time,
scheduling_procedure,
rel_for_coll_no,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.vendor,
src.country,
src.name,
src.name_2,
src.name_3,
src.name_4,
src.city,
src.district,
src.po_box,
src.po_box_pcode,
src.postal_code,
src.region,
src.search_term,
src.street,
src.address,
src.name_1,
src.name_2_1,
src.city_1,
src.title,
src.train_station,
src.location_no_1,
src.location_no_2,
src.authorization,
src.industry,
src.check_digit,
src.data_line,
src.dme_indicator,
src.instruction_key,
src.created_on,
src.created_by,
src.isr_number,
src.group_key,
src.account_group,
src.customer,
src.alternat_payee,
src.deletion_flag,
src.posting_block,
src.purch_block,
src.language_key,
src.tax_number_1,
src.tax_number_2,
src.equalizatn_tax,
src.liable_for_vat,
src.telebox,
src.telephone_1,
src.telephone_2,
src.fax_number,
src.teletex,
src.telex,
src.one_time_acct,
src.payee_in_doc,
src.trading_partner,
src.fiscal_address,
src.vat_reg_no,
src.natural_person,
src.block_function,
src.place_of_birth,
src.date_of_birth,
src.sex,
src.info_number,
src.last_ext_review,
src.actual_qm_sys,
src.ref_acct_group,
src.p_o_box_city,
src.plant,
src.vsr_relevant,
src.plant_relevant,
src.factory_calend,
src.data_transfer_status,
src.tax_jur,
src.payment_block,
src.scac,
src.car_freight_grp,
src.transport_zone,
src.alt_payee_doc,
src.servagntprocgrp,
src.tax_type,
src.tax_number_type,
src.social_ins,
src.soc_ins_code,
src.tax_number_3,
src.tax_number_4,
src.tax_number_5,
src.tax_split,
src.tax_base,
src.profession,
src.stat_grp_agent,
src.external_manuf,
src.url,
src.rep_s_name,
src.type_of_business,
src.type_of_industry,
src.confirm_status,
src.confirm_date,
src.confirm_time,
src.deletion_block,
src.qm_system_to,
src.pod_relevant,
src.tax_office,
src.tax_number,
src.carrier_confirmation,
src.micro_comp,
src.terms_liab,
src.crc_number,
src.purposecomplete_flag,
src.rg_number,
src.issued_by,
src.state,
src.rg_issuing_date,
src.ric_number,
src.foreign_national_reg,
src.rne_issuing_date,
src.cnae,
src.legal_nature,
src.crt_number,
src.icms_taxpayer,
src.industry_main_type,
src.tax_declaration_type,
src.company_size,
src.decl_reg_pis_cofi,
src.dataelement_exstensibility_for,
src.capital_amount,
src.currency,
src.agency_loc_cd,
src.payment_office,
src.ppa_relevant,
src.processor_group,
src.slaprepr_proced,
src.name_5,
src.name_2_2,
src.name_3_1,
src.first_name,
src.title_1,
src.house_number,
src.street_1,
src.dtelimit_ext_id,
src.repetition,
src.street_2,
src.house_number_1,
src.postal_code_1,
src.city_2,
src.country_1,
src.business_type,
src.prtnr_trad_name,
src.partner_s_utr,
src.verif_status,
src.verification_n,
src.tax_status,
src.comp_house_reg_no,
src.ecc_no,
src.excise_reg_no,
src.excise_range,
src.excise_division,
src.commissionerate,
src.cst_no,
src.lst_no,
src.pan,
src.exc_ind_vendor,
src.ssi_status,
src.type_of_vendor,
src.cenvat,
src.changed_on,
src.changed_by,
src.service_tax_regn_no,
src.pan_reference,
src.pan_valid_from_date,
src.customs_vendor,
src.deductee_ref_no,
src.gst_ven_class,
src.public_entity,
src.deed_public_use,
src.ss_certif_valid_date,
src.ss_certificate_form,
src.cae_code,
src.absence_of_debt,
src.transportation_chain,
src.staging_time,
src.scheduling_procedure,
src.rel_for_coll_no,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'supplier_master_details' as table_name
    		,'lfa1' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'supplier_master_details') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'supplier_master_details') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.supplier_master_details`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.supplier_master_details` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'supplier_master_details'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.supplier_master_details`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    