MERGE INTO `sap-adapter.slt_staging.account_document_item` tgt
USING (
WITH bseg as
(select MANDT as client,
BUKRS as company_code,
BELNR as document_number,
GJAHR as fiscal_year,
BUZEI as line_item,
BUZID as line_item_id,
AUGDT as clearing,
AUGCP as clearingentdate,
AUGBL as clrng_doc,
BSCHL as posting_key,
KOART as account_type,
UMSKZ as special_g_l_ind,
UMSKS as transact_type,
ZUMSK as trg_sp_g_l_ind,
SHKZG as debit_credit,
GSBER as business_area,
PARGB as trdg_part_ba,
TAX_COUNTRY as tax_country,
MWSKZ as tax_code,
TXDAT_FROM as tax_rate_valid_from,
QSSKZ as wtax_code,
DMBTR as amount_in_lc,
WRBTR as amount,
KZBTR as orig_reduction,
PSWBT as g_l_amount,
PSWSL as g_l_currency,
TXBHW as original_tax_base_amount_in_lo,
TXBFW as original_tax_base_amount_in_do,
MWSTS as lc_tax,
WMWST as tax_amount,
HWBAS as lc_base,
FWBAS as base_amount,
HWZUZ as lc_provis,
FWZUZ as addit_tax,
SHZUZ as debit_credit_addition_for_cash,
STEKZ as component_of_the_version_numbe,
MWART as tax_type,
TXGRP as group_indicator_for_tax_line_i,
KTOSL as transaction_key,
QSSHB as wtax_base,
KURSR as hedged_ex_rt,
GBETR as hedged,
BDIFF as valuation_diff,
BDIF2 as valuation_diff_2,
VALUT as value_date,
ZUONR as assignment_number,
SGTXT as text,
ZINKZ as interest_block,
VBUND as trading_partner,
BEWAR as transactn_type,
ALTKT as group_account_number,
VORGN as activity_type,
FDLEV as planning_level,
FDGRP as planning_group,
FDWBT as planned_amount,
FDTAG as planning_date,
FKONT as fin_budget,
KOKRS as co_area,
KOSTL as cost_center,
PROJN as not_in_use,
AUFNR as order_number,
VBELN as billing_doc,
VBEL2 as sales_document,
POSN2 as item,
ETEN2 as schedule_line,
SERVICE_DOC_TYPE as service_doc_type,
SERVICE_DOC_ID as service_document,
SERVICE_DOC_ITEM_ID as service_doc_item,
ANLN1 as asset,
ANLN2 as sub_number,
ANBWA as ast_transaction_type,
BZDAT as asset_val_date,
PERNR as personnel_no,
XUMSW as sales_related,
XHRES as indicator_resident_g_l_accoun,
XKRES as line_items,
XOPVW as oi_management,
XCPDD as individ_set,
XSKST as cctposting_stat,
XSAUF as ord_post_stat,
XSPRO as projpost_stat,
XSERG as pa_post_stat,
XFAKT as indicator_billing_document_up,
XUMAN as indicator_transfer_posting_fr,
XANET as indicator_down_payment_in_net,
XSKRL as w_o_cashdsc,
XINVE as invest_id,
XPANZ as display_item,
XAUTO as auto_created,
XNCOP as indicator_items_cannot_be_cop,
XZAHL as payt_tran,
SAKNR as g_l_account,
HKONT as g_l_acct,
KUNNR as customer,
LIFNR as vendor,
FILKD as branch,
XBILK as balance_sheet_acct,
GVTYP as p_l_state_acct,
HZUON as sp_g_l_assgt,
ZFBDT as baseline_date,
ZTERM as payt_terms,
ZBD1T as days_1,
ZBD2T as days_2,
ZBD3T as days_net,
ZBD1P as disc_percent_1,
ZBD2P as disc_percent_2,
SKFBT as cd_base,
SKNTO as discount_amt,
WSKTO as cd_amount,
ZLSCH as payt_method,
ZLSPR as pmnt_block,
ZBFIX as fixed,
HBKID as house_bank,
BVTYP as part_bank_type,
NEBTR as payment_amt,
MWSK1 as tax_code_1,
TXDAT_FROM1 as tax_rate_valid_from_1,
DMBT1 as amount_1,
WRBT1 as amount_2,
MWSK2 as tax_code_2,
TXDAT_FROM2 as tax_rate_valid_from_2,
DMBT2 as amount_3,
WRBT2 as amount_4,
MWSK3 as tax_code_3,
TXDAT_FROM3 as tax_rate_valid_from_3,
DMBT3 as amount_5,
WRBT3 as amount_6,
REBZG as invoice_ref,
REBZJ as fiscal_year_1,
REBZZ as line_item_1,
REBZT as follow_on_document_type,
ZOLLT as cust_tariff_no,
ZOLLD as customs_date,
LZBKZ as scb_ind,
LANDL as suppl_cntry,
DIEKZ as service_ind,
SAMNR as collect_inv,
ABPER as settl_period,
VRSKZ as insurance_ind,
VRSDT as insurance_date,
DISBN as usage_document,
DISBJ as year,
DISBZ as line_item_2,
WVERW as usage,
ANFBN as boe_payt_req,
ANFBJ as fiscal_year_of_the_bill_of_exc,
ANFBU as company_code_1,
ANFAE as return_bef,
BLNBT as preference_amt,
BLNKZ as subs_ind,
BLNPZ as pref_rate,
MSCHL as dunning_key,
MANSP as dunn_block,
MADAT as last_dunned,
MANST as dunning_level,
MABER as dunning_area,
ESRNR as isr_number,
ESRRE as isr_qr_ref,
ESRPZ as check_digit,
KLIBT as credit_ctrl_amt,
QSZNR as exemption_no,
QBSHB as withholding_tax,
QSFBT as wtax_exempt,
NAVHW as non_deductible,
NAVFW as non_deductible_1,
MATNR as material,
WERKS as plant,
MENGE as quantity,
MEINS as base_unit,
ERFMG as quantity_in_une,
ERFME as unit_of_entry,
BPMNG as qty_in_opun,
BPRME as po_price_unit,
EBELN as purchasing_doc,
EBELP as item_1,
ZEKKN as account_assgmt_no,
ELIKZ as deliv_compl,
VPRSV as price_control,
PEINH as price_unit,
BWKEY as valuation_area,
BWTAR as valuation_type,
BUSTW as value_string,
REWRT as invoice_value,
REWWR as fc_invoice_amt,
BONFB as amount_qualifying_for_bonus_in,
BUALT as amount_7,
PSALT as alt_price_ctrl,
NPREI as new_price,
TBTKZ as subseq_dr_cr,
SPGRP as block_reas_prc,
SPGRM as block_reas_qty,
SPGRT as bl_reason_date,
SPGRG as block_reas_opq,
SPGRV as block_reas_proj,
SPGRQ as man_block_reasn,
STCEG as vat_reg_no,
EGBLD as dest_country,
EGLLD as supplying_cntry,
RSTGR as reason_code,
RYACQ as yr_of_acquisitn,
RPACQ as period_of_acq,
RDIFF as diff_realized,
RDIF2 as diff_realized_2,
PRCTR as profit_center,
XHKOM as manual_g_l_acct,
VNAME as joint_venture,
RECID as recovery_indic,
EGRUP as equity_group,
VPTNR as partner,
VERTT as contract_type,
VERTN as contract_number,
VBEWA as flow_type,
DEPOT as securities_acct,
TXJCD as tax_jur,
IMKEY as real_estate_key,
DABRZ as reference_date,
POPTS as option_rate,
FIPOS as commitment_item,
KSTRG as cost_object,
NPLNR as network,
AUFPL as tasklist_no_ops,
APLZL as counter,
PROJK as wbs_element,
PAOBJNR as profit_segment,
PASUBNR as subnumber,
SPGRS as blkg_reas_amount,
SPGRC as block_quality,
BTYPE as billing_ind,
ETYPE as equity_type,
XEGDR as eu_triang_deal,
LNRAN as sequence_number,
HRKFT as origin_group,
DMBE2 as lc2_amount,
DMBE3 as lc3_amount,
DMB21 as amount_8,
DMB22 as amount_9,
DMB23 as amount_10,
DMB31 as amount_11,
DMB32 as amount_12,
DMB33 as amount_13,
MWST2 as lc2_tax,
MWST3 as lc3_tax,
NAVH2 as lc2_non_ded,
NAVH3 as lc3_non_ded,
SKNT2 as cd_amt_lc2,
SKNT3 as cd_amt_lc3,
BDIF3 as valuation_diff_3,
RDIF3 as diff_realized_3,
HWMET as method_with_which_the_local_cu,
GLUPM as update_method_fm,
XRAGL as indicator_clearing_was_revers,
UZAWE as pmt_meth_supl,
LOKKT as altern_account,
FISTL as funds_center,
GEBER as fund,
STBUK as tax_comp_code,
TXBH2 as tax_base_original_tax_base_in,
TXBH3 as tax_base_original_tax_base_i_1,
PPRCT as partner_pc,
XREF1 as reference_key_1,
XREF2 as reference_key_2,
KBLNR as earmarked_funds,
KBLPOS as document_item,
STTAX as statistical_tax,
FKBER as functional_area,
OBZEI as original_item,
XNEGP as negative_postg,
RFZEI as payt_card_item,
CCBTC as settlement,
KKBER as cred_contr_area,
EMPFB as payer,
XREF3 as reference_key_3,
DTWS1 as instruct_key_1,
DTWS2 as instruct_key_2,
DTWS3 as instruct_key_3,
DTWS4 as instruct_key_4,
GRICD as activity_code,
GRIRG as region,
GITYP as distr_type,
XPYPR as payment_sent,
KIDNO as payment_ref,
ABSBT as hedged_amount,
IDXSP as inflation_index,
LINFV as last_adj_date,
KONTT as acct_assmt_cat,
KONTL as acct_assignment,
UEBGDAT as date_of_legal_dunn,
TXDAT as tax_date,
AGZEI as clearing_item,
PYCUR as payment_cur,
PYAMT as pmnt_c_amnt,
BUPLA as business_place,
SECCO as section_code,
LSTAR as activity_type_1,
CESSION_KZ as ar_pledging_ind,
PRZNR as business_proc,
PPDIFF as diff_realized_1,
PPDIF2 as diff_realized_4,
PPDIF3 as diff_realized_5,
PENLC1 as penalty_chge_lc,
PENLC2 as pen_charge_lc2,
PENLC3 as pen_charge_lc3,
PENFC as penalty_charge,
PENDAYS as days_in_arrears,
PENRC as reason_f_delay,
GRANT_NBR as grants,
SCTAX as fi_ca_tax_portion,
FKBER_LONG as functional_area_1,
GMVKZ as execution,
SRTYPE as addit_receivab,
INTRENO as re_code,
MEASURE as funded_program,
AUGGJ as clrg_fiscal_yr,
PPA_EX_IND as ppa_exclude,
DOCLN as line_item_3,
SEGMENT as segment,
PSEGMENT as partner_segment,
PFKBER as partner_farea,
HKTID as account_id,
KSTAR as cost_element,
XLGCLR as ldgrgrp_specclearing,
TAXPS as tax_doc_item_number,
PAYS_PROV as psp,
PAYS_TRAN as psp_payment_ref,
MNDID as mandate_ref,
XFRGE_BSEG as released,
AWTYP as ref_procedure,
AWKEY as object_key,
AWSYS as logical_system,
POSNR as position,
BUZEI_SENDER as sender_item,
H_MONAT as period,
H_BSTAT as document_status,
H_BUDAT as posting_date,
H_BLDAT as document_date,
H_WAERS as currency,
H_BLART as document_type,
H_HWAER as local_currency,
H_HWAE2 as local_curr_2,
H_HWAE3 as local_curr_3,
SK1DT as cash_discount_1,
SK2DT as cash_discount_2,
_DATAAGING as data_filter_value_for_data_agi,
FQFTYPE as flow_type_1,
LQITEM as liquidity_item,
GKONT as offsetting_acct,
GKART as offst_acct_type,
GHKON as g_l_offsetting_acct,
SQUAN as qty_sign,
ANLN2_PN as sub_number_1,
BWASL_PN as trans_type,
BZDAT_PN as asset_val_date_1,
XVABG_PN as compl_retiremnt,
ANBTR_PN as amount_posted,
PROZS_PN as percentage_rate,
DUMMY_INCL_EEW_COBL as dummy,
ACROBJTYPE as accrual_object_type,
ACROBJ_ID as accrual_object,
ACRSOBJ_ID as accrual_subobject,
ACRITMTYPE as accrual_item_type,
ACRVALDAT as accrual_value_date,
VALOBJTYPE as type_of_fin_val_obj,
VALOBJ_ID as fin_valuation_object,
VALSOBJ_ID as fin_val_sub_object,
NETDT as due_on,
RISK_CLASS as risk_class,
SDM_VERSION as sdm_versioning,
GLO_REF1 as country_specific_reference_1_o,
RE_BUKRS as company_code_2,
RE_ACCOUNT as ex_rv_a_c_in_cl,
PGEBER as partner_fund,
PGRANT_NBR as partner_grant,
BUDGET_PD as budget_period,
PBUDGET_PD as par_budper,
J_1TPBUPL as branch_code,
PEROP_BEG as per_of_perf_start,
PEROP_END as per_of_perf_end,
FASTPAY as fast_pay,
IGNR_IVREF as ignore_invoice_ref,
FMFGUS_KEY as us_govt,
FMXDOCNR as fm_ref_doc_nr,
FMXYEAR as fm_ref_year,
FMXDOCLN as fm_ref_item,
FMXZEKKN as fm_ref_aa,
PRODPER as prod_month,
GST_PART as gst_partner,
PLC_SUP as place_of_supply,
HSN_SAC as hsn_sac_code,
RECRF as recredit_flag,
BDGT_ACCOUNT as budget_account,
BDGT_ACCOUNT_COCODE as budget_account_company_code,
INWARD_NO as incg_doc_nmbr,
INWARD_DT as incg_doc_date,
GROUND_NO as payt_ground_no,
GROUND_DT as payt_ground_date,
GROUND_TYP as payt_against,
PYMTKEY as payt_prop_key,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct bseg.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.bseg` as bseg
where bseg._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'account_document_item'),0))
select client as client_key,
company_code as company_code_key,
document_number as document_number_key,
fiscal_year as fiscal_year_key,
line_item as line_item_key,
*
From  bseg
UNION ALL
select null as client_key,
null as company_code_key,
null as document_number_key,
null as fiscal_year_key,
null as line_item_key,
bseg.*
From bseg as bseg
INNER JOIN `sap-adapter.slt_staging.account_document_item` as uji
ON bseg.client = uji.client
AND bseg.company_code = uji.company_code
AND bseg.document_number = uji.document_number
AND bseg.fiscal_year = uji.fiscal_year
AND bseg.line_item = uji.line_item
AND bseg.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.company_code_key = tgt.company_code
AND src.document_number_key = tgt.document_number
AND src.fiscal_year_key = tgt.fiscal_year
AND src.line_item_key = tgt.line_item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
company_code,
document_number,
fiscal_year,
line_item,
line_item_id,
clearing,
clearingentdate,
clrng_doc,
posting_key,
account_type,
special_g_l_ind,
transact_type,
trg_sp_g_l_ind,
debit_credit,
business_area,
trdg_part_ba,
tax_country,
tax_code,
tax_rate_valid_from,
wtax_code,
amount_in_lc,
amount,
orig_reduction,
g_l_amount,
g_l_currency,
original_tax_base_amount_in_lo,
original_tax_base_amount_in_do,
lc_tax,
tax_amount,
lc_base,
base_amount,
lc_provis,
addit_tax,
debit_credit_addition_for_cash,
component_of_the_version_numbe,
tax_type,
group_indicator_for_tax_line_i,
transaction_key,
wtax_base,
hedged_ex_rt,
hedged,
valuation_diff,
valuation_diff_2,
value_date,
assignment_number,
text,
interest_block,
trading_partner,
transactn_type,
group_account_number,
activity_type,
planning_level,
planning_group,
planned_amount,
planning_date,
fin_budget,
co_area,
cost_center,
not_in_use,
order_number,
billing_doc,
sales_document,
item,
schedule_line,
service_doc_type,
service_document,
service_doc_item,
asset,
sub_number,
ast_transaction_type,
asset_val_date,
personnel_no,
sales_related,
indicator_resident_g_l_accoun,
line_items,
oi_management,
individ_set,
cctposting_stat,
ord_post_stat,
projpost_stat,
pa_post_stat,
indicator_billing_document_up,
indicator_transfer_posting_fr,
indicator_down_payment_in_net,
w_o_cashdsc,
invest_id,
display_item,
auto_created,
indicator_items_cannot_be_cop,
payt_tran,
g_l_account,
g_l_acct,
customer,
vendor,
branch,
balance_sheet_acct,
p_l_state_acct,
sp_g_l_assgt,
baseline_date,
payt_terms,
days_1,
days_2,
days_net,
disc_percent_1,
disc_percent_2,
cd_base,
discount_amt,
cd_amount,
payt_method,
pmnt_block,
fixed,
house_bank,
part_bank_type,
payment_amt,
tax_code_1,
tax_rate_valid_from_1,
amount_1,
amount_2,
tax_code_2,
tax_rate_valid_from_2,
amount_3,
amount_4,
tax_code_3,
tax_rate_valid_from_3,
amount_5,
amount_6,
invoice_ref,
fiscal_year_1,
line_item_1,
follow_on_document_type,
cust_tariff_no,
customs_date,
scb_ind,
suppl_cntry,
service_ind,
collect_inv,
settl_period,
insurance_ind,
insurance_date,
usage_document,
year,
line_item_2,
usage,
boe_payt_req,
fiscal_year_of_the_bill_of_exc,
company_code_1,
return_bef,
preference_amt,
subs_ind,
pref_rate,
dunning_key,
dunn_block,
last_dunned,
dunning_level,
dunning_area,
isr_number,
isr_qr_ref,
check_digit,
credit_ctrl_amt,
exemption_no,
withholding_tax,
wtax_exempt,
non_deductible,
non_deductible_1,
material,
plant,
quantity,
base_unit,
quantity_in_une,
unit_of_entry,
qty_in_opun,
po_price_unit,
purchasing_doc,
item_1,
account_assgmt_no,
deliv_compl,
price_control,
price_unit,
valuation_area,
valuation_type,
value_string,
invoice_value,
fc_invoice_amt,
amount_qualifying_for_bonus_in,
amount_7,
alt_price_ctrl,
new_price,
subseq_dr_cr,
block_reas_prc,
block_reas_qty,
bl_reason_date,
block_reas_opq,
block_reas_proj,
man_block_reasn,
vat_reg_no,
dest_country,
supplying_cntry,
reason_code,
yr_of_acquisitn,
period_of_acq,
diff_realized,
diff_realized_2,
profit_center,
manual_g_l_acct,
joint_venture,
recovery_indic,
equity_group,
partner,
contract_type,
contract_number,
flow_type,
securities_acct,
tax_jur,
real_estate_key,
reference_date,
option_rate,
commitment_item,
cost_object,
network,
tasklist_no_ops,
counter,
wbs_element,
profit_segment,
subnumber,
blkg_reas_amount,
block_quality,
billing_ind,
equity_type,
eu_triang_deal,
sequence_number,
origin_group,
lc2_amount,
lc3_amount,
amount_8,
amount_9,
amount_10,
amount_11,
amount_12,
amount_13,
lc2_tax,
lc3_tax,
lc2_non_ded,
lc3_non_ded,
cd_amt_lc2,
cd_amt_lc3,
valuation_diff_3,
diff_realized_3,
method_with_which_the_local_cu,
update_method_fm,
indicator_clearing_was_revers,
pmt_meth_supl,
altern_account,
funds_center,
fund,
tax_comp_code,
tax_base_original_tax_base_in,
tax_base_original_tax_base_i_1,
partner_pc,
reference_key_1,
reference_key_2,
earmarked_funds,
document_item,
statistical_tax,
functional_area,
original_item,
negative_postg,
payt_card_item,
settlement,
cred_contr_area,
payer,
reference_key_3,
instruct_key_1,
instruct_key_2,
instruct_key_3,
instruct_key_4,
activity_code,
region,
distr_type,
payment_sent,
payment_ref,
hedged_amount,
inflation_index,
last_adj_date,
acct_assmt_cat,
acct_assignment,
date_of_legal_dunn,
tax_date,
clearing_item,
payment_cur,
pmnt_c_amnt,
business_place,
section_code,
activity_type_1,
ar_pledging_ind,
business_proc,
diff_realized_1,
diff_realized_4,
diff_realized_5,
penalty_chge_lc,
pen_charge_lc2,
pen_charge_lc3,
penalty_charge,
days_in_arrears,
reason_f_delay,
grants,
fi_ca_tax_portion,
functional_area_1,
execution,
addit_receivab,
re_code,
funded_program,
clrg_fiscal_yr,
ppa_exclude,
line_item_3,
segment,
partner_segment,
partner_farea,
account_id,
cost_element,
ldgrgrp_specclearing,
tax_doc_item_number,
psp,
psp_payment_ref,
mandate_ref,
released,
ref_procedure,
object_key,
logical_system,
position,
sender_item,
period,
document_status,
posting_date,
document_date,
currency,
document_type,
local_currency,
local_curr_2,
local_curr_3,
cash_discount_1,
cash_discount_2,
data_filter_value_for_data_agi,
flow_type_1,
liquidity_item,
offsetting_acct,
offst_acct_type,
g_l_offsetting_acct,
qty_sign,
sub_number_1,
trans_type,
asset_val_date_1,
compl_retiremnt,
amount_posted,
percentage_rate,
dummy,
accrual_object_type,
accrual_object,
accrual_subobject,
accrual_item_type,
accrual_value_date,
type_of_fin_val_obj,
fin_valuation_object,
fin_val_sub_object,
due_on,
risk_class,
sdm_versioning,
country_specific_reference_1_o,
company_code_2,
ex_rv_a_c_in_cl,
partner_fund,
partner_grant,
budget_period,
par_budper,
branch_code,
per_of_perf_start,
per_of_perf_end,
fast_pay,
ignore_invoice_ref,
us_govt,
fm_ref_doc_nr,
fm_ref_year,
fm_ref_item,
fm_ref_aa,
prod_month,
gst_partner,
place_of_supply,
hsn_sac_code,
recredit_flag,
budget_account,
budget_account_company_code,
incg_doc_nmbr,
incg_doc_date,
payt_ground_no,
payt_ground_date,
payt_against,
payt_prop_key,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.company_code,
src.document_number,
src.fiscal_year,
src.line_item,
src.line_item_id,
src.clearing,
src.clearingentdate,
src.clrng_doc,
src.posting_key,
src.account_type,
src.special_g_l_ind,
src.transact_type,
src.trg_sp_g_l_ind,
src.debit_credit,
src.business_area,
src.trdg_part_ba,
src.tax_country,
src.tax_code,
src.tax_rate_valid_from,
src.wtax_code,
src.amount_in_lc,
src.amount,
src.orig_reduction,
src.g_l_amount,
src.g_l_currency,
src.original_tax_base_amount_in_lo,
src.original_tax_base_amount_in_do,
src.lc_tax,
src.tax_amount,
src.lc_base,
src.base_amount,
src.lc_provis,
src.addit_tax,
src.debit_credit_addition_for_cash,
src.component_of_the_version_numbe,
src.tax_type,
src.group_indicator_for_tax_line_i,
src.transaction_key,
src.wtax_base,
src.hedged_ex_rt,
src.hedged,
src.valuation_diff,
src.valuation_diff_2,
src.value_date,
src.assignment_number,
src.text,
src.interest_block,
src.trading_partner,
src.transactn_type,
src.group_account_number,
src.activity_type,
src.planning_level,
src.planning_group,
src.planned_amount,
src.planning_date,
src.fin_budget,
src.co_area,
src.cost_center,
src.not_in_use,
src.order_number,
src.billing_doc,
src.sales_document,
src.item,
src.schedule_line,
src.service_doc_type,
src.service_document,
src.service_doc_item,
src.asset,
src.sub_number,
src.ast_transaction_type,
src.asset_val_date,
src.personnel_no,
src.sales_related,
src.indicator_resident_g_l_accoun,
src.line_items,
src.oi_management,
src.individ_set,
src.cctposting_stat,
src.ord_post_stat,
src.projpost_stat,
src.pa_post_stat,
src.indicator_billing_document_up,
src.indicator_transfer_posting_fr,
src.indicator_down_payment_in_net,
src.w_o_cashdsc,
src.invest_id,
src.display_item,
src.auto_created,
src.indicator_items_cannot_be_cop,
src.payt_tran,
src.g_l_account,
src.g_l_acct,
src.customer,
src.vendor,
src.branch,
src.balance_sheet_acct,
src.p_l_state_acct,
src.sp_g_l_assgt,
src.baseline_date,
src.payt_terms,
src.days_1,
src.days_2,
src.days_net,
src.disc_percent_1,
src.disc_percent_2,
src.cd_base,
src.discount_amt,
src.cd_amount,
src.payt_method,
src.pmnt_block,
src.fixed,
src.house_bank,
src.part_bank_type,
src.payment_amt,
src.tax_code_1,
src.tax_rate_valid_from_1,
src.amount_1,
src.amount_2,
src.tax_code_2,
src.tax_rate_valid_from_2,
src.amount_3,
src.amount_4,
src.tax_code_3,
src.tax_rate_valid_from_3,
src.amount_5,
src.amount_6,
src.invoice_ref,
src.fiscal_year_1,
src.line_item_1,
src.follow_on_document_type,
src.cust_tariff_no,
src.customs_date,
src.scb_ind,
src.suppl_cntry,
src.service_ind,
src.collect_inv,
src.settl_period,
src.insurance_ind,
src.insurance_date,
src.usage_document,
src.year,
src.line_item_2,
src.usage,
src.boe_payt_req,
src.fiscal_year_of_the_bill_of_exc,
src.company_code_1,
src.return_bef,
src.preference_amt,
src.subs_ind,
src.pref_rate,
src.dunning_key,
src.dunn_block,
src.last_dunned,
src.dunning_level,
src.dunning_area,
src.isr_number,
src.isr_qr_ref,
src.check_digit,
src.credit_ctrl_amt,
src.exemption_no,
src.withholding_tax,
src.wtax_exempt,
src.non_deductible,
src.non_deductible_1,
src.material,
src.plant,
src.quantity,
src.base_unit,
src.quantity_in_une,
src.unit_of_entry,
src.qty_in_opun,
src.po_price_unit,
src.purchasing_doc,
src.item_1,
src.account_assgmt_no,
src.deliv_compl,
src.price_control,
src.price_unit,
src.valuation_area,
src.valuation_type,
src.value_string,
src.invoice_value,
src.fc_invoice_amt,
src.amount_qualifying_for_bonus_in,
src.amount_7,
src.alt_price_ctrl,
src.new_price,
src.subseq_dr_cr,
src.block_reas_prc,
src.block_reas_qty,
src.bl_reason_date,
src.block_reas_opq,
src.block_reas_proj,
src.man_block_reasn,
src.vat_reg_no,
src.dest_country,
src.supplying_cntry,
src.reason_code,
src.yr_of_acquisitn,
src.period_of_acq,
src.diff_realized,
src.diff_realized_2,
src.profit_center,
src.manual_g_l_acct,
src.joint_venture,
src.recovery_indic,
src.equity_group,
src.partner,
src.contract_type,
src.contract_number,
src.flow_type,
src.securities_acct,
src.tax_jur,
src.real_estate_key,
src.reference_date,
src.option_rate,
src.commitment_item,
src.cost_object,
src.network,
src.tasklist_no_ops,
src.counter,
src.wbs_element,
src.profit_segment,
src.subnumber,
src.blkg_reas_amount,
src.block_quality,
src.billing_ind,
src.equity_type,
src.eu_triang_deal,
src.sequence_number,
src.origin_group,
src.lc2_amount,
src.lc3_amount,
src.amount_8,
src.amount_9,
src.amount_10,
src.amount_11,
src.amount_12,
src.amount_13,
src.lc2_tax,
src.lc3_tax,
src.lc2_non_ded,
src.lc3_non_ded,
src.cd_amt_lc2,
src.cd_amt_lc3,
src.valuation_diff_3,
src.diff_realized_3,
src.method_with_which_the_local_cu,
src.update_method_fm,
src.indicator_clearing_was_revers,
src.pmt_meth_supl,
src.altern_account,
src.funds_center,
src.fund,
src.tax_comp_code,
src.tax_base_original_tax_base_in,
src.tax_base_original_tax_base_i_1,
src.partner_pc,
src.reference_key_1,
src.reference_key_2,
src.earmarked_funds,
src.document_item,
src.statistical_tax,
src.functional_area,
src.original_item,
src.negative_postg,
src.payt_card_item,
src.settlement,
src.cred_contr_area,
src.payer,
src.reference_key_3,
src.instruct_key_1,
src.instruct_key_2,
src.instruct_key_3,
src.instruct_key_4,
src.activity_code,
src.region,
src.distr_type,
src.payment_sent,
src.payment_ref,
src.hedged_amount,
src.inflation_index,
src.last_adj_date,
src.acct_assmt_cat,
src.acct_assignment,
src.date_of_legal_dunn,
src.tax_date,
src.clearing_item,
src.payment_cur,
src.pmnt_c_amnt,
src.business_place,
src.section_code,
src.activity_type_1,
src.ar_pledging_ind,
src.business_proc,
src.diff_realized_1,
src.diff_realized_4,
src.diff_realized_5,
src.penalty_chge_lc,
src.pen_charge_lc2,
src.pen_charge_lc3,
src.penalty_charge,
src.days_in_arrears,
src.reason_f_delay,
src.grants,
src.fi_ca_tax_portion,
src.functional_area_1,
src.execution,
src.addit_receivab,
src.re_code,
src.funded_program,
src.clrg_fiscal_yr,
src.ppa_exclude,
src.line_item_3,
src.segment,
src.partner_segment,
src.partner_farea,
src.account_id,
src.cost_element,
src.ldgrgrp_specclearing,
src.tax_doc_item_number,
src.psp,
src.psp_payment_ref,
src.mandate_ref,
src.released,
src.ref_procedure,
src.object_key,
src.logical_system,
src.position,
src.sender_item,
src.period,
src.document_status,
src.posting_date,
src.document_date,
src.currency,
src.document_type,
src.local_currency,
src.local_curr_2,
src.local_curr_3,
src.cash_discount_1,
src.cash_discount_2,
src.data_filter_value_for_data_agi,
src.flow_type_1,
src.liquidity_item,
src.offsetting_acct,
src.offst_acct_type,
src.g_l_offsetting_acct,
src.qty_sign,
src.sub_number_1,
src.trans_type,
src.asset_val_date_1,
src.compl_retiremnt,
src.amount_posted,
src.percentage_rate,
src.dummy,
src.accrual_object_type,
src.accrual_object,
src.accrual_subobject,
src.accrual_item_type,
src.accrual_value_date,
src.type_of_fin_val_obj,
src.fin_valuation_object,
src.fin_val_sub_object,
src.due_on,
src.risk_class,
src.sdm_versioning,
src.country_specific_reference_1_o,
src.company_code_2,
src.ex_rv_a_c_in_cl,
src.partner_fund,
src.partner_grant,
src.budget_period,
src.par_budper,
src.branch_code,
src.per_of_perf_start,
src.per_of_perf_end,
src.fast_pay,
src.ignore_invoice_ref,
src.us_govt,
src.fm_ref_doc_nr,
src.fm_ref_year,
src.fm_ref_item,
src.fm_ref_aa,
src.prod_month,
src.gst_partner,
src.place_of_supply,
src.hsn_sac_code,
src.recredit_flag,
src.budget_account,
src.budget_account_company_code,
src.incg_doc_nmbr,
src.incg_doc_date,
src.payt_ground_no,
src.payt_ground_date,
src.payt_against,
src.payt_prop_key,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'account_document_item' as table_name
    		,'bseg' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'account_document_item') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'account_document_item') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.account_document_item`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.account_document_item` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'account_document_item'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.account_document_item`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    