MERGE INTO `sap-adapter.slt_staging.purchase_order_history_detail` tgt
USING (
WITH ekbe as
(select MANDT as client,
EBELN as purchasing_doc,
EBELP as item,
ZEKKN as account_assgmt_no,
VGABE as trans_ev_type,
GJAHR as mat_doc_year,
BELNR as material_doc,
BUZEI as mat_doc_item,
BEWTP as po_history_cat,
BWART as movement_type,
BUDAT as posting_date,
MENGE as quantity,
BPMNG as qty_in_opun,
DMBTR as amount_in_lc,
WRBTR as amount,
WAERS as currency,
AREWR as gr_ir_clr_value,
WESBS as gr_bl_st_oun,
BPWES as gr_blocked_stck,
SHKZG as debit_credit,
BWTAR as valuation_type,
ELIKZ as deliv_compl,
XBLNR as reference,
LFGJA as fisc_yr_ref_doc,
LFBNR as reference_doc,
LFPOS as ref_doc_item,
GRUND as reason_for_mvmt,
CPUDT as entered_on,
CPUTM as entered_at,
REEWR as invoice_value,
EVERE as compliance,
REFWR as inv_value_in_fc,
MATNR as material,
WERKS as plant,
XWSBR as revgr_desp_ir,
ETENS as sequential_no,
KNUMV as doc_condition,
MWSKZ as tax_code,
LSMNG as del_note_qty,
LSMEH as del_note_unit,
EMATN as material_1,
AREWW as gr_ir_clr_value_1,
HSWAE as local_currency,
BAMNG as quantity_1,
CHARG as batch,
BLDAT as document_date,
XWOFF as calcn_of_val_open,
XUNPL as uacctassignment,
ERNAM as created_by,
SRVPOS as service,
PACKNO as package_number,
INTROW as service_line,
BEKKN as seqno_po_accass,
LEMIN as srv_returns_ind,
AREWB as gr_ir_clr_value_2,
REWRB as fc_invoice_amnt,
SAPRL as sap_release,
MENGE_POP as quantity_2,
BPMNG_POP as qty_in_opun_1,
DMBTR_POP as amount_in_lc_1,
WRBTR_POP as amount_1,
WESBB as val_gr_blstock_oun,
BPWEB as val_gr_bs_opun,
WEORA as origin_accept,
AREWR_POP as gr_ir_clr_value_3,
KUDIF as exch_rate_diff,
RETAMT_FC as retent_in_doc_crcy,
RETAMT_LC as retention_in_cc_crcy,
RETAMTP_FC as retent_in_doc_crcy_1,
RETAMTP_LC as retention_in_cc_crcy_1,
XMACC as multi_acct_assgt,
WKURS as exchange_rate,
INV_ITEM_ORIGIN as item_origin,
VBELN_ST as delivery,
VBELP_ST as item_1,
SGT_SCAT as stock_segment,
_DATAAGING as data_filter_value_for_data_agi,
SESUOM as ses_uom,
LOGSY as logical_system,
ET_UPD as slpu,
__CWM__BAMNG as cw_qty,
__CWM__WESBS as cwm_gr_blkd_stk_qty,
__CWM__TY2TQ as puom_type,
__CWM__WESBB as cwm_gr_blkd_stk_qty_1,
J_SC_DIE_COMP_F as die_complete_flag,
FSH_SEASON_YEAR as season_year,
FSH_SEASON as season,
FSH_COLLECTION as collection,
FSH_THEME as theme,
QTY_DIFF as quantity_3,
WRF_CHARSTC1 as characteristic_1,
WRF_CHARSTC2 as characteristic_2,
WRF_CHARSTC3 as characteristic_3,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct ekbe.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.ekbe` as ekbe
where ekbe._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'purchase_order_history_detail'),0))
select client as client_key,
purchasing_doc as purchasing_doc_key,
item as item_key,
account_assgmt_no as account_assgmt_no_key,
trans_ev_type as trans_ev_type_key,
mat_doc_year as mat_doc_year_key,
material_doc as material_doc_key,
mat_doc_item as mat_doc_item_key,
*
From  ekbe
UNION ALL
select null as client_key,
null as purchasing_doc_key,
null as item_key,
null as account_assgmt_no_key,
null as trans_ev_type_key,
null as mat_doc_year_key,
null as material_doc_key,
null as mat_doc_item_key,
ekbe.*
From ekbe as ekbe
INNER JOIN `sap-adapter.slt_staging.purchase_order_history_detail` as uji
ON ekbe.client = uji.client
AND ekbe.purchasing_doc = uji.purchasing_doc
AND ekbe.item = uji.item
AND ekbe.account_assgmt_no = uji.account_assgmt_no
AND ekbe.trans_ev_type = uji.trans_ev_type
AND ekbe.mat_doc_year = uji.mat_doc_year
AND ekbe.material_doc = uji.material_doc
AND ekbe.mat_doc_item = uji.mat_doc_item
AND ekbe.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.purchasing_doc_key = tgt.purchasing_doc
AND src.item_key = tgt.item
AND src.account_assgmt_no_key = tgt.account_assgmt_no
AND src.trans_ev_type_key = tgt.trans_ev_type
AND src.mat_doc_year_key = tgt.mat_doc_year
AND src.material_doc_key = tgt.material_doc
AND src.mat_doc_item_key = tgt.mat_doc_item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
purchasing_doc,
item,
account_assgmt_no,
trans_ev_type,
mat_doc_year,
material_doc,
mat_doc_item,
po_history_cat,
movement_type,
posting_date,
quantity,
qty_in_opun,
amount_in_lc,
amount,
currency,
gr_ir_clr_value,
gr_bl_st_oun,
gr_blocked_stck,
debit_credit,
valuation_type,
deliv_compl,
reference,
fisc_yr_ref_doc,
reference_doc,
ref_doc_item,
reason_for_mvmt,
entered_on,
entered_at,
invoice_value,
compliance,
inv_value_in_fc,
material,
plant,
revgr_desp_ir,
sequential_no,
doc_condition,
tax_code,
del_note_qty,
del_note_unit,
material_1,
gr_ir_clr_value_1,
local_currency,
quantity_1,
batch,
document_date,
calcn_of_val_open,
uacctassignment,
created_by,
service,
package_number,
service_line,
seqno_po_accass,
srv_returns_ind,
gr_ir_clr_value_2,
fc_invoice_amnt,
sap_release,
quantity_2,
qty_in_opun_1,
amount_in_lc_1,
amount_1,
val_gr_blstock_oun,
val_gr_bs_opun,
origin_accept,
gr_ir_clr_value_3,
exch_rate_diff,
retent_in_doc_crcy,
retention_in_cc_crcy,
retent_in_doc_crcy_1,
retention_in_cc_crcy_1,
multi_acct_assgt,
exchange_rate,
item_origin,
delivery,
item_1,
stock_segment,
data_filter_value_for_data_agi,
ses_uom,
logical_system,
slpu,
cw_qty,
cwm_gr_blkd_stk_qty,
puom_type,
cwm_gr_blkd_stk_qty_1,
die_complete_flag,
season_year,
season,
collection,
theme,
quantity_3,
characteristic_1,
characteristic_2,
characteristic_3,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.purchasing_doc,
src.item,
src.account_assgmt_no,
src.trans_ev_type,
src.mat_doc_year,
src.material_doc,
src.mat_doc_item,
src.po_history_cat,
src.movement_type,
src.posting_date,
src.quantity,
src.qty_in_opun,
src.amount_in_lc,
src.amount,
src.currency,
src.gr_ir_clr_value,
src.gr_bl_st_oun,
src.gr_blocked_stck,
src.debit_credit,
src.valuation_type,
src.deliv_compl,
src.reference,
src.fisc_yr_ref_doc,
src.reference_doc,
src.ref_doc_item,
src.reason_for_mvmt,
src.entered_on,
src.entered_at,
src.invoice_value,
src.compliance,
src.inv_value_in_fc,
src.material,
src.plant,
src.revgr_desp_ir,
src.sequential_no,
src.doc_condition,
src.tax_code,
src.del_note_qty,
src.del_note_unit,
src.material_1,
src.gr_ir_clr_value_1,
src.local_currency,
src.quantity_1,
src.batch,
src.document_date,
src.calcn_of_val_open,
src.uacctassignment,
src.created_by,
src.service,
src.package_number,
src.service_line,
src.seqno_po_accass,
src.srv_returns_ind,
src.gr_ir_clr_value_2,
src.fc_invoice_amnt,
src.sap_release,
src.quantity_2,
src.qty_in_opun_1,
src.amount_in_lc_1,
src.amount_1,
src.val_gr_blstock_oun,
src.val_gr_bs_opun,
src.origin_accept,
src.gr_ir_clr_value_3,
src.exch_rate_diff,
src.retent_in_doc_crcy,
src.retention_in_cc_crcy,
src.retent_in_doc_crcy_1,
src.retention_in_cc_crcy_1,
src.multi_acct_assgt,
src.exchange_rate,
src.item_origin,
src.delivery,
src.item_1,
src.stock_segment,
src.data_filter_value_for_data_agi,
src.ses_uom,
src.logical_system,
src.slpu,
src.cw_qty,
src.cwm_gr_blkd_stk_qty,
src.puom_type,
src.cwm_gr_blkd_stk_qty_1,
src.die_complete_flag,
src.season_year,
src.season,
src.collection,
src.theme,
src.quantity_3,
src.characteristic_1,
src.characteristic_2,
src.characteristic_3,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'purchase_order_history_detail' as table_name
    		,'ekbe' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'purchase_order_history_detail') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'purchase_order_history_detail') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.purchase_order_history_detail`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.purchase_order_history_detail` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'purchase_order_history_detail'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.purchase_order_history_detail`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    