MERGE INTO `sap-adapter.slt_staging.masterial_movement_details` tgt
USING (
WITH matdoc as
(select MANDT as client,
KEY1 as split_guid_part_1,
KEY2 as split_guid_part_2,
KEY3 as split_guid_part_3,
KEY4 as split_guid_part_4,
KEY5 as split_guid_part_5,
KEY6 as split_guid_part_6,
RECORD_TYPE as record_type,
HEADER_COUNTER as matl_doc_counter,
MATBF as stock_mat,
WERKS as plant,
LGORT_SID as stor_location_sid,
CHARG_SID as batch_sid,
LIFNR_SID as supplier_sid,
MAT_KDAUF as sales_order,
MAT_KDPOS as sales_ord_item,
MAT_PSPNR as wbs_element,
KUNNR_SID as customer_sid,
SOBKZ as special_stock,
LBBSA_SID as stock_type,
DISUB_OWNER_SID as addl_supplier_sid,
BUKRS as company_code,
CHARG_WHS_SG as batch_sid_1,
MENGU as qty_updating,
WERTU as value_updating,
VBOBJ_SG as document_object,
KZBWS as valuation,
BSTAUS_SG as stock_char,
BSTTYP_SG as stock_cat,
KALNR as prodcostest_no,
BERID as mrp_area,
WAERS as currency,
DMBTR as amount_in_lc,
BNBTR as delivery_costs,
BUALT as amount,
DMBUM as revaluation,
EXBWR as ext_amount_lc,
VKWRT as salval_inc_vat,
EXVKW as sales_value,
SALK3 as total_value,
VKWRA as salval_w_o_vat,
J_1BEXBASE as alt_base_amnt,
STOCK_VKWRT as salval_incl_vat,
DMBTR_STOCK as amt_lc_w_stk_qty,
DMBTR_CONS as amt_lc_w_cons_qty,
MEINS as base_unit,
MENGE as quantity,
LBKUM as valuated_stock,
STOCK_QTY as stock_quantity,
CONSUMPTION_QTY as consumption_quantity,
ERFME as unit_of_entry,
ERFMG as quantity_in_une,
BPRME as po_price_unit,
BPMNG as qty_in_opun,
BSTME as order_unit,
BSTMG as qty_in_oun,
LSMEH as del_note_unit,
LSMNG as del_note_qty,
PBAMG as quantity_1,
CURRENCY_A1 as analytical_currency,
PRICE_A1 as analytical_price,
PRICE_SOURCE_A1 as analytical_pr_ind,
STOCK_VALUE_A1 as analytical_value,
CONS_VALUE_A1 as analytic_val_cons,
__CWM__MENGE as qty_in_puom,
__CWM__MEINS as parallel_uom,
__CWM__ERFMG as puom_euom_qty,
__CWM__ERFME as puom_entry_uom,
__CWM__STOCK_QTY as pq_stock_quantity,
__CWM__CONSUMPTION_QTY as pq_consumption_qty,
__CWM__MEINS_SID as parallel_uom_sid,
UMMAB_CID as receiving_mat,
UMWRK_CID as plant_1,
LGORT_CID as stor_location_sid_1,
CHARG_CID as batch_sid_2,
LIFNR_CID as supplier_sid_1,
MAT_KDAUF_CID as sales_document_sid,
MAT_KDPOS_CID as item_sid,
MAT_PSPNR_CID as wbs_element_sid,
KUNNR_CID as customer_sid_1,
UMSOK_CID as special_stock_1,
LBBSA_CID as stock_type_1,
DISUB_OWNER_CID as vendor,
UMBUK_CG as company_code_1,
CHARG_WHS_CG as batch_sid_3,
UMMEN_CG as qty_updating_1,
UMWER_CG as value_updating_1,
VBOBJ_CG as document_object_1,
UMKZBWS_CG as valuation_1,
BSTAUS_CG as stock_char_1,
BSTTYP_CG as stock_cat_1,
KALNR_CG as prodcostest_no_1,
BUDAT as posting_date,
CPUDT as entered_on,
CPUTM as entered_at,
YEARDAY_BUDAT as year_day,
YEARWEEK_BUDAT as year_week,
YEARMONTH_BUDAT as year_month,
YEARQUARTER_BUDAT as year_quarter,
YEAR_BUDAT as year,
QUARTER_BUDAT as quarter_1_4,
MONTH_BUDAT as month_1_12,
WEEK_BUDAT as calendar_week,
DAY_BUDAT as day_of_year_1_366,
WEEKDAY_BUDAT as week_day,
BLDAT as document_date,
AEDAT as changed_on,
SPE_BUDAT_UHR as gi_time,
SPE_BUDAT_ZONE as time_zone,
PERIV as fi_year_variant,
GJAHR as fiscal_year,
GJPER as period_year,
GJPER_CURR_PER as period_year_1,
VFDAT as sled_bbd,
DABRBZ as reference_date,
DABRZ as reference_date_1,
HSDAT as date_of_manuf,
MBLNR as material_doc,
MJAHR as mat_doc_year,
ZEILE as mat_doc_item,
LINE_ID as line_id,
PARENT_ID as parent_id,
LINE_DEPTH as level,
MAA_URZEI as orig_line_itm,
KDAUF as sales_order_1,
KDPOS as sales_ord_item_1,
KDEIN as sorder_schedule,
EBELN as purchase_order,
EBELP as item,
LFBJA as fisc_yr_ref_doc,
LFBNR as reference_doc,
LFPOS as ref_doc_item,
SJAHR as mat_doc_year_1,
SMBLN as material_doc_1,
SMBLP as mat_doc_item_1,
AUFNR as order_number,
ANLN1 as asset,
ANLN2 as sub_number,
BELNR as document_number,
BUZEI as line_item,
BELUM as document_number_1,
BUZUM as line_item_1,
RSNUM as reservation_number,
RSPOS as item_no,
TBNUM as tr_number,
TBPOS as tr_item,
UBNUM as posting_chge_no,
TANUM as to_number,
URZEI as orig_line_itm_1,
XBLNR as reference,
VBELN_IM as delivery,
VBELP_IM as item_1,
LE_VBELN as delivery_1,
SPE_LOGSYS as logical_system,
SPE_MDNUM_EWM as material_doc_ewm,
CANCELLED as is_item_cancelled,
CANCELLATION_TYPE as rel_for_analytics,
REVERSAL_MOVEMENT as revmvmttypeind,
SERVICE_DOC_TYPE as service_doc_type,
SERVICE_DOC_ID as service_document,
SERVICE_DOC_ITEM_ID as service_doc_item,
EWM_LGNUM as warehouse_no,
EWM_GMDOC as gm_document,
BWART as movement_type,
XAUTO as auto_created,
MATNR as material,
LGORT as stor_loc,
CHARG as batch,
BWTAR as valuation_type,
INSMK as stock_type_2,
ZUSCH as status_key,
ZUSTD as batch_restr,
LIFNR as vendor_1,
KUNNR as customer,
PLPLA as distribution,
SHKZG as debit_credit,
SHKUM as d_c_ind_reval,
ELIKZ as deliv_compl,
SGTXT as text,
EQUNR as equipment,
WEMPF as recipient,
ABLAD as unloading_point,
GSBER as business_area,
KOKRS as co_area,
PARGB as trdg_part_ba,
PARBU as clearing_cocode,
KOSTL as cost_center,
PROJN as not_in_use,
XSKST as cctposting_stat,
XSAUF as ord_post_stat,
XSPRO as projpost_stat,
XSERG as pa_post_stat,
XRUEM as post_prev_per,
XRUEJ as pst_to_pr_year,
KZEAR as final_issue,
KZSTR as stat_relevant,
UMMAT as receiving_mat_1,
UMCHA as receiving_batch,
UMLGO as receiving_sloc,
UMZST as restricted_use,
UMZUS as stkeytferbatch,
KZBEW as movement_ind,
KZVBR as consumption,
KZZUG as receipt_ind,
WEUNB as gr_non_valuated,
PALAN as no_of_pallets,
LGNUM as warehouse_no_1,
LGTYP as storage_type,
LGPLA as storage_bin,
BESTQ as stock_category,
BWLVS as movement_type_1,
XBLVS as posting_in_wm,
VSCHN as int_st_pst_src,
NSCHN as inter_post_dest,
DYPLA as dynamic_bin,
TBPRI as trnsfr_priority,
WEANZ as no_of_gr_slips,
GRUND as reason_for_mvmt,
EVERS as shipping_instr,
EVERE as compliance,
IMKEY as real_estate_key,
KSTRG as cost_object,
PAOBJNR as profit_segment,
PRCTR as profit_center,
PS_PSP_PNR as wbs_element_1,
NPLNR as network,
AUFPL as plan_no_f_oper,
APLZL as counter,
AUFPS as order_item_no,
VPTNR as partner,
FIPOS as commitment_item,
SAKTO as g_l_account,
XWSBR as revgr_desp_ir,
EMLIF as supplier,
AKTNR as promotion,
ZEKKN as account_assgmt_no,
CUOBJ_CH as int_object_no,
PPRCTR as partner_pc,
RSART as record_type_1,
GEBER as fund,
FISTL as funds_center,
BUSTM as quantity_string,
BUSTW as value_string,
VPRSV as price_control,
FKBER as functional_area,
XBEAU as automatic_po,
QINSPST as status_gr_doc,
MWSKZ as tax_code,
TXJCD as tax_jur,
EMATN as mpn_material,
J_1AGIRUPD as gi_reval_o_k,
VKMWS as tax_code_1,
BERKZ as staging_ind,
XWOFF as calcn_of_val_open,
BEMOT as acctindicator,
PRZNR as business_proc,
LLIEF as goods_supplier,
LSTAR as activity_type,
XOBEW as vendor_stk_val,
GRANT_NBR as grants,
ZUSTD_T156M as stock_type_mod,
SPE_GTS_STOCK_TY as gts_stock_type,
KBLNR as earmarked_funds,
KBLPOS as document_item,
XMACC as multi_acct_assgt,
UMMAB as receiving_mat_2,
UMBAR as val_type_tfr,
UMWRK as plant_2,
UMSOK as special_stock_2,
SGT_SCAT as stock_segment,
SGT_UMSCAT as rec_stock_seg,
SGT_RCAT as reqmnt_segment,
DISUB_OWNER as vendor_2,
COMPL_MARK as compl_ind,
FZGLS_MARK as do_not_adj_crq,
ETANP_MARK as adjust_item,
POPUP_MARK as dialog_box,
SERVICEPERFORMER as service_performer,
PERNR as personnel_no,
KNTTP_GR as acct_assgmt_cat,
WORK_ITEM_ID as work_item_id,
FBUDA as serv_rendered,
DUMMY_INCL_EEW_COBL as dummy,
FSH_SEASON_YEAR as season_year,
FSH_SEASON as season,
FSH_COLLECTION as collection,
FSH_THEME as theme,
WRF_CHARSTC1 as characteristic_1,
WRF_CHARSTC2 as characteristic_2,
WRF_CHARSTC3 as characteristic_3,
OINAVNW as non_deductible,
OICONDCOD as condkey,
CONDI as condkey_1,
BLART as document_type,
BLAUM as doc_type_rev,
TCODE as undefined_range_can_be_used_f,
BKTXT as doc_header_text,
FRATH as unpl_del_costs,
FRBNR as bill_of_lading,
WEVER as print_version,
XABLN as gr_gi_slip_no,
AWSYS as logical_system_1,
BLA2D as doc_type_ad,
BFWMS as ext_wms_control,
VGART as trans_ev_type,
USNAM as user_name,
TCODE2 as transaction_code,
EXNUM as foreign_trade_datanr,
GTS_CUSREF_NO as customs_ref_no,
FLS_RSTO as enh_store_ret,
MSR_ACTIVE as adv_returns,
XCOMPL as single_character_flag,
KNUMV as doc_condition,
_DATAAGING as data_filter_value_for_data_agi,
XPRINT as print_active,
LMBMV as under_overdel,
PABPM as percentage_var,
XFMAT as missing_part,
KNBDR as print_kanban,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct matdoc.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.matdoc` as matdoc
where matdoc._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'masterial_movement_details'),0))
select client as client_key,
split_guid_part_1 as split_guid_part_1_key,
split_guid_part_2 as split_guid_part_2_key,
split_guid_part_3 as split_guid_part_3_key,
split_guid_part_4 as split_guid_part_4_key,
split_guid_part_5 as split_guid_part_5_key,
split_guid_part_6 as split_guid_part_6_key,
*
From  matdoc
UNION ALL
select null as client_key,
null as split_guid_part_1_key,
null as split_guid_part_2_key,
null as split_guid_part_3_key,
null as split_guid_part_4_key,
null as split_guid_part_5_key,
null as split_guid_part_6_key,
matdoc.*
From matdoc as matdoc
INNER JOIN `sap-adapter.slt_staging.masterial_movement_details` as uji
ON matdoc.client = uji.client
AND matdoc.split_guid_part_1 = uji.split_guid_part_1
AND matdoc.split_guid_part_2 = uji.split_guid_part_2
AND matdoc.split_guid_part_3 = uji.split_guid_part_3
AND matdoc.split_guid_part_4 = uji.split_guid_part_4
AND matdoc.split_guid_part_5 = uji.split_guid_part_5
AND matdoc.split_guid_part_6 = uji.split_guid_part_6
AND matdoc.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.split_guid_part_1_key = tgt.split_guid_part_1
AND src.split_guid_part_2_key = tgt.split_guid_part_2
AND src.split_guid_part_3_key = tgt.split_guid_part_3
AND src.split_guid_part_4_key = tgt.split_guid_part_4
AND src.split_guid_part_5_key = tgt.split_guid_part_5
AND src.split_guid_part_6_key = tgt.split_guid_part_6
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
split_guid_part_1,
split_guid_part_2,
split_guid_part_3,
split_guid_part_4,
split_guid_part_5,
split_guid_part_6,
record_type,
matl_doc_counter,
stock_mat,
plant,
stor_location_sid,
batch_sid,
supplier_sid,
sales_order,
sales_ord_item,
wbs_element,
customer_sid,
special_stock,
stock_type,
addl_supplier_sid,
company_code,
batch_sid_1,
qty_updating,
value_updating,
document_object,
valuation,
stock_char,
stock_cat,
prodcostest_no,
mrp_area,
currency,
amount_in_lc,
delivery_costs,
amount,
revaluation,
ext_amount_lc,
salval_inc_vat,
sales_value,
total_value,
salval_w_o_vat,
alt_base_amnt,
salval_incl_vat,
amt_lc_w_stk_qty,
amt_lc_w_cons_qty,
base_unit,
quantity,
valuated_stock,
stock_quantity,
consumption_quantity,
unit_of_entry,
quantity_in_une,
po_price_unit,
qty_in_opun,
order_unit,
qty_in_oun,
del_note_unit,
del_note_qty,
quantity_1,
analytical_currency,
analytical_price,
analytical_pr_ind,
analytical_value,
analytic_val_cons,
qty_in_puom,
parallel_uom,
puom_euom_qty,
puom_entry_uom,
pq_stock_quantity,
pq_consumption_qty,
parallel_uom_sid,
receiving_mat,
plant_1,
stor_location_sid_1,
batch_sid_2,
supplier_sid_1,
sales_document_sid,
item_sid,
wbs_element_sid,
customer_sid_1,
special_stock_1,
stock_type_1,
vendor,
company_code_1,
batch_sid_3,
qty_updating_1,
value_updating_1,
document_object_1,
valuation_1,
stock_char_1,
stock_cat_1,
prodcostest_no_1,
posting_date,
entered_on,
entered_at,
year_day,
year_week,
year_month,
year_quarter,
year,
quarter_1_4,
month_1_12,
calendar_week,
day_of_year_1_366,
week_day,
document_date,
changed_on,
gi_time,
time_zone,
fi_year_variant,
fiscal_year,
period_year,
period_year_1,
sled_bbd,
reference_date,
reference_date_1,
date_of_manuf,
material_doc,
mat_doc_year,
mat_doc_item,
line_id,
parent_id,
level,
orig_line_itm,
sales_order_1,
sales_ord_item_1,
sorder_schedule,
purchase_order,
item,
fisc_yr_ref_doc,
reference_doc,
ref_doc_item,
mat_doc_year_1,
material_doc_1,
mat_doc_item_1,
order_number,
asset,
sub_number,
document_number,
line_item,
document_number_1,
line_item_1,
reservation_number,
item_no,
tr_number,
tr_item,
posting_chge_no,
to_number,
orig_line_itm_1,
reference,
delivery,
item_1,
delivery_1,
logical_system,
material_doc_ewm,
is_item_cancelled,
rel_for_analytics,
revmvmttypeind,
service_doc_type,
service_document,
service_doc_item,
warehouse_no,
gm_document,
movement_type,
auto_created,
material,
stor_loc,
batch,
valuation_type,
stock_type_2,
status_key,
batch_restr,
vendor_1,
customer,
distribution,
debit_credit,
d_c_ind_reval,
deliv_compl,
text,
equipment,
recipient,
unloading_point,
business_area,
co_area,
trdg_part_ba,
clearing_cocode,
cost_center,
not_in_use,
cctposting_stat,
ord_post_stat,
projpost_stat,
pa_post_stat,
post_prev_per,
pst_to_pr_year,
final_issue,
stat_relevant,
receiving_mat_1,
receiving_batch,
receiving_sloc,
restricted_use,
stkeytferbatch,
movement_ind,
consumption,
receipt_ind,
gr_non_valuated,
no_of_pallets,
warehouse_no_1,
storage_type,
storage_bin,
stock_category,
movement_type_1,
posting_in_wm,
int_st_pst_src,
inter_post_dest,
dynamic_bin,
trnsfr_priority,
no_of_gr_slips,
reason_for_mvmt,
shipping_instr,
compliance,
real_estate_key,
cost_object,
profit_segment,
profit_center,
wbs_element_1,
network,
plan_no_f_oper,
counter,
order_item_no,
partner,
commitment_item,
g_l_account,
revgr_desp_ir,
supplier,
promotion,
account_assgmt_no,
int_object_no,
partner_pc,
record_type_1,
fund,
funds_center,
quantity_string,
value_string,
price_control,
functional_area,
automatic_po,
status_gr_doc,
tax_code,
tax_jur,
mpn_material,
gi_reval_o_k,
tax_code_1,
staging_ind,
calcn_of_val_open,
acctindicator,
business_proc,
goods_supplier,
activity_type,
vendor_stk_val,
grants,
stock_type_mod,
gts_stock_type,
earmarked_funds,
document_item,
multi_acct_assgt,
receiving_mat_2,
val_type_tfr,
plant_2,
special_stock_2,
stock_segment,
rec_stock_seg,
reqmnt_segment,
vendor_2,
compl_ind,
do_not_adj_crq,
adjust_item,
dialog_box,
service_performer,
personnel_no,
acct_assgmt_cat,
work_item_id,
serv_rendered,
dummy,
season_year,
season,
collection,
theme,
characteristic_1,
characteristic_2,
characteristic_3,
non_deductible,
condkey,
condkey_1,
document_type,
doc_type_rev,
undefined_range_can_be_used_f,
doc_header_text,
unpl_del_costs,
bill_of_lading,
print_version,
gr_gi_slip_no,
logical_system_1,
doc_type_ad,
ext_wms_control,
trans_ev_type,
user_name,
transaction_code,
foreign_trade_datanr,
customs_ref_no,
enh_store_ret,
adv_returns,
single_character_flag,
doc_condition,
data_filter_value_for_data_agi,
print_active,
under_overdel,
percentage_var,
missing_part,
print_kanban,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.split_guid_part_1,
src.split_guid_part_2,
src.split_guid_part_3,
src.split_guid_part_4,
src.split_guid_part_5,
src.split_guid_part_6,
src.record_type,
src.matl_doc_counter,
src.stock_mat,
src.plant,
src.stor_location_sid,
src.batch_sid,
src.supplier_sid,
src.sales_order,
src.sales_ord_item,
src.wbs_element,
src.customer_sid,
src.special_stock,
src.stock_type,
src.addl_supplier_sid,
src.company_code,
src.batch_sid_1,
src.qty_updating,
src.value_updating,
src.document_object,
src.valuation,
src.stock_char,
src.stock_cat,
src.prodcostest_no,
src.mrp_area,
src.currency,
src.amount_in_lc,
src.delivery_costs,
src.amount,
src.revaluation,
src.ext_amount_lc,
src.salval_inc_vat,
src.sales_value,
src.total_value,
src.salval_w_o_vat,
src.alt_base_amnt,
src.salval_incl_vat,
src.amt_lc_w_stk_qty,
src.amt_lc_w_cons_qty,
src.base_unit,
src.quantity,
src.valuated_stock,
src.stock_quantity,
src.consumption_quantity,
src.unit_of_entry,
src.quantity_in_une,
src.po_price_unit,
src.qty_in_opun,
src.order_unit,
src.qty_in_oun,
src.del_note_unit,
src.del_note_qty,
src.quantity_1,
src.analytical_currency,
src.analytical_price,
src.analytical_pr_ind,
src.analytical_value,
src.analytic_val_cons,
src.qty_in_puom,
src.parallel_uom,
src.puom_euom_qty,
src.puom_entry_uom,
src.pq_stock_quantity,
src.pq_consumption_qty,
src.parallel_uom_sid,
src.receiving_mat,
src.plant_1,
src.stor_location_sid_1,
src.batch_sid_2,
src.supplier_sid_1,
src.sales_document_sid,
src.item_sid,
src.wbs_element_sid,
src.customer_sid_1,
src.special_stock_1,
src.stock_type_1,
src.vendor,
src.company_code_1,
src.batch_sid_3,
src.qty_updating_1,
src.value_updating_1,
src.document_object_1,
src.valuation_1,
src.stock_char_1,
src.stock_cat_1,
src.prodcostest_no_1,
src.posting_date,
src.entered_on,
src.entered_at,
src.year_day,
src.year_week,
src.year_month,
src.year_quarter,
src.year,
src.quarter_1_4,
src.month_1_12,
src.calendar_week,
src.day_of_year_1_366,
src.week_day,
src.document_date,
src.changed_on,
src.gi_time,
src.time_zone,
src.fi_year_variant,
src.fiscal_year,
src.period_year,
src.period_year_1,
src.sled_bbd,
src.reference_date,
src.reference_date_1,
src.date_of_manuf,
src.material_doc,
src.mat_doc_year,
src.mat_doc_item,
src.line_id,
src.parent_id,
src.level,
src.orig_line_itm,
src.sales_order_1,
src.sales_ord_item_1,
src.sorder_schedule,
src.purchase_order,
src.item,
src.fisc_yr_ref_doc,
src.reference_doc,
src.ref_doc_item,
src.mat_doc_year_1,
src.material_doc_1,
src.mat_doc_item_1,
src.order_number,
src.asset,
src.sub_number,
src.document_number,
src.line_item,
src.document_number_1,
src.line_item_1,
src.reservation_number,
src.item_no,
src.tr_number,
src.tr_item,
src.posting_chge_no,
src.to_number,
src.orig_line_itm_1,
src.reference,
src.delivery,
src.item_1,
src.delivery_1,
src.logical_system,
src.material_doc_ewm,
src.is_item_cancelled,
src.rel_for_analytics,
src.revmvmttypeind,
src.service_doc_type,
src.service_document,
src.service_doc_item,
src.warehouse_no,
src.gm_document,
src.movement_type,
src.auto_created,
src.material,
src.stor_loc,
src.batch,
src.valuation_type,
src.stock_type_2,
src.status_key,
src.batch_restr,
src.vendor_1,
src.customer,
src.distribution,
src.debit_credit,
src.d_c_ind_reval,
src.deliv_compl,
src.text,
src.equipment,
src.recipient,
src.unloading_point,
src.business_area,
src.co_area,
src.trdg_part_ba,
src.clearing_cocode,
src.cost_center,
src.not_in_use,
src.cctposting_stat,
src.ord_post_stat,
src.projpost_stat,
src.pa_post_stat,
src.post_prev_per,
src.pst_to_pr_year,
src.final_issue,
src.stat_relevant,
src.receiving_mat_1,
src.receiving_batch,
src.receiving_sloc,
src.restricted_use,
src.stkeytferbatch,
src.movement_ind,
src.consumption,
src.receipt_ind,
src.gr_non_valuated,
src.no_of_pallets,
src.warehouse_no_1,
src.storage_type,
src.storage_bin,
src.stock_category,
src.movement_type_1,
src.posting_in_wm,
src.int_st_pst_src,
src.inter_post_dest,
src.dynamic_bin,
src.trnsfr_priority,
src.no_of_gr_slips,
src.reason_for_mvmt,
src.shipping_instr,
src.compliance,
src.real_estate_key,
src.cost_object,
src.profit_segment,
src.profit_center,
src.wbs_element_1,
src.network,
src.plan_no_f_oper,
src.counter,
src.order_item_no,
src.partner,
src.commitment_item,
src.g_l_account,
src.revgr_desp_ir,
src.supplier,
src.promotion,
src.account_assgmt_no,
src.int_object_no,
src.partner_pc,
src.record_type_1,
src.fund,
src.funds_center,
src.quantity_string,
src.value_string,
src.price_control,
src.functional_area,
src.automatic_po,
src.status_gr_doc,
src.tax_code,
src.tax_jur,
src.mpn_material,
src.gi_reval_o_k,
src.tax_code_1,
src.staging_ind,
src.calcn_of_val_open,
src.acctindicator,
src.business_proc,
src.goods_supplier,
src.activity_type,
src.vendor_stk_val,
src.grants,
src.stock_type_mod,
src.gts_stock_type,
src.earmarked_funds,
src.document_item,
src.multi_acct_assgt,
src.receiving_mat_2,
src.val_type_tfr,
src.plant_2,
src.special_stock_2,
src.stock_segment,
src.rec_stock_seg,
src.reqmnt_segment,
src.vendor_2,
src.compl_ind,
src.do_not_adj_crq,
src.adjust_item,
src.dialog_box,
src.service_performer,
src.personnel_no,
src.acct_assgmt_cat,
src.work_item_id,
src.serv_rendered,
src.dummy,
src.season_year,
src.season,
src.collection,
src.theme,
src.characteristic_1,
src.characteristic_2,
src.characteristic_3,
src.non_deductible,
src.condkey,
src.condkey_1,
src.document_type,
src.doc_type_rev,
src.undefined_range_can_be_used_f,
src.doc_header_text,
src.unpl_del_costs,
src.bill_of_lading,
src.print_version,
src.gr_gi_slip_no,
src.logical_system_1,
src.doc_type_ad,
src.ext_wms_control,
src.trans_ev_type,
src.user_name,
src.transaction_code,
src.foreign_trade_datanr,
src.customs_ref_no,
src.enh_store_ret,
src.adv_returns,
src.single_character_flag,
src.doc_condition,
src.data_filter_value_for_data_agi,
src.print_active,
src.under_overdel,
src.percentage_var,
src.missing_part,
src.print_kanban,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'masterial_movement_details' as table_name
    		,'matdoc' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'masterial_movement_details') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'masterial_movement_details') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.masterial_movement_details`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.masterial_movement_details` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'masterial_movement_details'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.masterial_movement_details`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    