MERGE INTO `sap-adapter.slt_staging.incoming_invoice_item_detail` tgt
USING (
WITH rseg as
(select MANDT as client,
BELNR as document_number,
GJAHR as fiscal_year,
BUZEI as item,
EBELN as purchasing_doc,
EBELP as item_1,
ZEKKN as account_assgmt_no,
MATNR as material,
BWKEY as valuation_area,
BWTAR as valuation_type,
BUKRS as company_code,
WERKS as plant,
WRBTR as amount,
SHKZG as debit_credit,
MWSKZ as tax_code,
TXJCD as tax_jur,
MENGE as quantity,
BSTME as order_unit,
BPMNG as qty_in_opun,
BPRME as po_price_unit,
LBKUM as total_stock,
VRKUM as stock_prev_pp,
MEINS as base_unit,
PSTYP as item_category,
KNTTP as acct_assgmt_cat,
BKLAS as valuation_class,
EREKZ as final_invoice,
EXKBE as ind_upd_po_his,
XEKBZ as ind_upd_dc,
TBTKZ as subseq_dr_cr,
SPGRP as block_reas_prc,
SPGRM as block_reas_qty,
SPGRT as bl_reason_date,
SPGRG as block_reas_opq,
SPGRV as block_reas_proj,
SPGRQ as man_block_reasn,
SPGRS as blkg_reas_amount,
SPGRC as block_quality,
SPGREXT as block_reason,
BUSTW as value_string,
XBLNR as reference,
XRUEB as back_posting,
BNKAN as dcs_share,
KSCHL as condition_type,
SALK3 as total_value,
VMSAL as total_value_pp,
XLIFO as lifo_fifo_rel,
LFBNR as reference_doc,
LFGJA as year_cur_period,
LFPOS as ref_doc_item,
MATBF as stock_mat,
RBMNG as inv_doc_qty,
BPRBM as invqty_pounit,
RBWWR as inv_amnt_dc,
LFEHL as supplier_error,
GRICD as activity_code,
GRIRG as region,
GITYP as distr_type,
PACKNO as package_number,
INTROW as service_line,
SGTXT as text,
XSKRL as w_o_cashdsc,
KZMEK as correction_id,
MRMOK as invoice_item_processed,
STUNR as step_number,
ZAEHK as counter,
STOCK_POSTING as stock_posting,
STOCK_POSTING_PP as stkpstgprevperd,
STOCK_POSTING_PY as stkpstgprevyear,
WEREC as gr_ir_clearing,
LIFNR as vendor,
FRBNR as bill_of_lading,
XHISTMA as update_multiacctasmt,
COMPLAINT_REASON as complaints_reason,
RETAMT_FC as retent_in_doc_crcy,
RETPC as retention,
RETDUEDT as due_date,
XRETTAXNET as tax_reduction,
RE_ACCOUNT as ex_rv_a_c_in_cl,
ERP_CONTRACT_ID as agreement,
ERP_CONTRACT_ITM as agreement_item,
SRM_CONTRACT_ID as central_contract,
SRM_CONTRACT_ITM as cent_contract_item,
CONT_PSTYP as item_category_1,
SRVMAPKEY as item_id,
CHARG as batch,
INV_ITM_ORIGIN as item_origin,
INVREL as grouping_characteristic,
XDINV as ind_diff_invoicing,
DIFF_AMOUNT as difference_amt,
XCPRF as comm_repricing,
PRODUCTTYPE as product_type_group,
NODE_KEY as guid,
PARENT_KEY as guid_1,
ROOT_KEY as guid_2,
DUMMY_MMIV_SI_S_ITEM_EEW_PS as dummy,
ENH_DATE1 as wka_start_date,
ENH_DATE2 as wka_end_date,
ENH_CHAR1 as work_descr,
ENH_CHAR2 as construc_site,
ENH_PERCENT as percentage,
ENH_NUMC1 as wrk_time_hours,
__CWM__MENGE as qty_in_puom,
__CWM__WEMNG as par_gr_qty,
__CWM__REMNG as cwm_ir_qty,
__CWM__BAMNG as cw_qty,
__CWM__VALUM as valuation_uom,
TXDAT as tax_date,
TXDAT_FROM as tax_rate_valid_from,
__NFM__SPGRK as rate_blk_reason,
EFKOR as own_error,
FSH_SEASON_YEAR as season_year,
FSH_SEASON as season,
FSH_COLLECTION as collection,
FSH_THEME as theme,
HSN_SAC as hsn_sac_code,
CUSTOMS_VAL as assessable_val,
LICNO as internal_no,
ZEILE as item_2,
SGT_SCAT as stock_segment,
WRF_CHARSTC1 as characteristic_1,
WRF_CHARSTC2 as characteristic_2,
WRF_CHARSTC3 as characteristic_3,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct rseg.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.rseg` as rseg
where rseg._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'incoming_invoice_item_detail'),0))
select client as client_key,
document_number as document_number_key,
fiscal_year as fiscal_year_key,
item as item_key,
*
From  rseg
UNION ALL
select null as client_key,
null as document_number_key,
null as fiscal_year_key,
null as item_key,
rseg.*
From rseg as rseg
INNER JOIN `sap-adapter.slt_staging.incoming_invoice_item_detail` as uji
ON rseg.client = uji.client
AND rseg.document_number = uji.document_number
AND rseg.fiscal_year = uji.fiscal_year
AND rseg.item = uji.item
AND rseg.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.document_number_key = tgt.document_number
AND src.fiscal_year_key = tgt.fiscal_year
AND src.item_key = tgt.item
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
document_number,
fiscal_year,
item,
purchasing_doc,
item_1,
account_assgmt_no,
material,
valuation_area,
valuation_type,
company_code,
plant,
amount,
debit_credit,
tax_code,
tax_jur,
quantity,
order_unit,
qty_in_opun,
po_price_unit,
total_stock,
stock_prev_pp,
base_unit,
item_category,
acct_assgmt_cat,
valuation_class,
final_invoice,
ind_upd_po_his,
ind_upd_dc,
subseq_dr_cr,
block_reas_prc,
block_reas_qty,
bl_reason_date,
block_reas_opq,
block_reas_proj,
man_block_reasn,
blkg_reas_amount,
block_quality,
block_reason,
value_string,
reference,
back_posting,
dcs_share,
condition_type,
total_value,
total_value_pp,
lifo_fifo_rel,
reference_doc,
year_cur_period,
ref_doc_item,
stock_mat,
inv_doc_qty,
invqty_pounit,
inv_amnt_dc,
supplier_error,
activity_code,
region,
distr_type,
package_number,
service_line,
text,
w_o_cashdsc,
correction_id,
invoice_item_processed,
step_number,
counter,
stock_posting,
stkpstgprevperd,
stkpstgprevyear,
gr_ir_clearing,
vendor,
bill_of_lading,
update_multiacctasmt,
complaints_reason,
retent_in_doc_crcy,
retention,
due_date,
tax_reduction,
ex_rv_a_c_in_cl,
agreement,
agreement_item,
central_contract,
cent_contract_item,
item_category_1,
item_id,
batch,
item_origin,
grouping_characteristic,
ind_diff_invoicing,
difference_amt,
comm_repricing,
product_type_group,
guid,
guid_1,
guid_2,
dummy,
wka_start_date,
wka_end_date,
work_descr,
construc_site,
percentage,
wrk_time_hours,
qty_in_puom,
par_gr_qty,
cwm_ir_qty,
cw_qty,
valuation_uom,
tax_date,
tax_rate_valid_from,
rate_blk_reason,
own_error,
season_year,
season,
collection,
theme,
hsn_sac_code,
assessable_val,
internal_no,
item_2,
stock_segment,
characteristic_1,
characteristic_2,
characteristic_3,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.document_number,
src.fiscal_year,
src.item,
src.purchasing_doc,
src.item_1,
src.account_assgmt_no,
src.material,
src.valuation_area,
src.valuation_type,
src.company_code,
src.plant,
src.amount,
src.debit_credit,
src.tax_code,
src.tax_jur,
src.quantity,
src.order_unit,
src.qty_in_opun,
src.po_price_unit,
src.total_stock,
src.stock_prev_pp,
src.base_unit,
src.item_category,
src.acct_assgmt_cat,
src.valuation_class,
src.final_invoice,
src.ind_upd_po_his,
src.ind_upd_dc,
src.subseq_dr_cr,
src.block_reas_prc,
src.block_reas_qty,
src.bl_reason_date,
src.block_reas_opq,
src.block_reas_proj,
src.man_block_reasn,
src.blkg_reas_amount,
src.block_quality,
src.block_reason,
src.value_string,
src.reference,
src.back_posting,
src.dcs_share,
src.condition_type,
src.total_value,
src.total_value_pp,
src.lifo_fifo_rel,
src.reference_doc,
src.year_cur_period,
src.ref_doc_item,
src.stock_mat,
src.inv_doc_qty,
src.invqty_pounit,
src.inv_amnt_dc,
src.supplier_error,
src.activity_code,
src.region,
src.distr_type,
src.package_number,
src.service_line,
src.text,
src.w_o_cashdsc,
src.correction_id,
src.invoice_item_processed,
src.step_number,
src.counter,
src.stock_posting,
src.stkpstgprevperd,
src.stkpstgprevyear,
src.gr_ir_clearing,
src.vendor,
src.bill_of_lading,
src.update_multiacctasmt,
src.complaints_reason,
src.retent_in_doc_crcy,
src.retention,
src.due_date,
src.tax_reduction,
src.ex_rv_a_c_in_cl,
src.agreement,
src.agreement_item,
src.central_contract,
src.cent_contract_item,
src.item_category_1,
src.item_id,
src.batch,
src.item_origin,
src.grouping_characteristic,
src.ind_diff_invoicing,
src.difference_amt,
src.comm_repricing,
src.product_type_group,
src.guid,
src.guid_1,
src.guid_2,
src.dummy,
src.wka_start_date,
src.wka_end_date,
src.work_descr,
src.construc_site,
src.percentage,
src.wrk_time_hours,
src.qty_in_puom,
src.par_gr_qty,
src.cwm_ir_qty,
src.cw_qty,
src.valuation_uom,
src.tax_date,
src.tax_rate_valid_from,
src.rate_blk_reason,
src.own_error,
src.season_year,
src.season,
src.collection,
src.theme,
src.hsn_sac_code,
src.assessable_val,
src.internal_no,
src.item_2,
src.stock_segment,
src.characteristic_1,
src.characteristic_2,
src.characteristic_3,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'incoming_invoice_item_detail' as table_name
    		,'rseg' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'incoming_invoice_item_detail') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'incoming_invoice_item_detail') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.incoming_invoice_item_detail`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.incoming_invoice_item_detail` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'incoming_invoice_item_detail'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.incoming_invoice_item_detail`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    