MERGE INTO `sap-adapter.slt_staging.order_header` tgt
USING (
WITH caufv as
(select MANDT as client,
AUFNR as order,
AUART as order_type,
AUTYP as order_category,
REFNR as order_1,
ERNAM as entered_by,
ERDAT as created_on,
AENAM as changed_by,
AEDAT as changed_on,
KTEXT as description,
LTEXT as long_txt_exists,
BUKRS as company_code,
WERKS as plant,
GSBER as business_area,
KOKRS as co_area,
CCKEY as cost_collector,
KOSTV as resp_cost_cntr,
STORT as location,
SOWRK as location_plant,
ASTKZ as statistical,
WAERS as currency,
STDAT as status_change,
IDAT1 as release,
IDAT2 as tech_completion,
IDAT3 as close,
OBJID as object_id,
LOEKZ as deletion_flag,
PLGKZ as plan_line_items,
KVEWE as usage,
KAPPL as application,
KALSM as costing_sheet,
ZSCHL as overhead_key,
ABKRS as process_group,
KSTAR as settlement_ce,
KOSTL as cost_center,
SETNM as allocation_set,
CYCLE as cctr_true_post,
SDATE as valid_from,
SEQNR as sequence_number,
USER4 as estimated_costs,
OBJNR as object_number,
PRCTR as profit_center,
PSPEL as wbs_element,
AWSLS as variance_key,
ABGSL as ra_key,
EB_POST as event_based_posting,
TXJCD as tax_jur,
FUNC_AREA as functional_area,
SCOPE as object_class,
PLINT as integ_planning,
KDAUF as sales_order,
KDPOS as sales_ord_item,
AUFEX as ext_order_no,
IVPRO as invest_profile,
LOGSYSTEM as logical_system,
FLG_MLTPS as multiple_items,
ABUKR as req_co_code,
AKSTL as req_cost_center,
SIZECL as scale,
IZWEK as invest_reason,
UMWKZ as envir_invest,
KSTEMPF as cost_collector_1,
ZSCHM as interest_prof,
PKOSA as cost_collector_2,
ANFAUFNR as req_order,
PROCNR as prod_proc_no,
PROTY as process_cat,
RSORD as refurbishment,
BEMOT as acctindicator,
ADRNRA as address_number,
ERFZEIT as time_created,
AEZEIT as changed_at,
CSTG_VRNT as costing_variant,
COSTESTNR as cost_estimateno,
VERAA_USER as personresponsible,
EEW_AUFK_PS_DUMMY as dummy_function_in_length_1,
VNAME as joint_venture,
RECID as recovery_indic,
ETYPE as equity_type,
OTYPE as jv_object_type,
JV_JIBCL as jib_jibe_class,
JV_JIBSA as jib_jibe_sbclsa,
JV_OCO as or_cost_obj,
CPD_UPDAT as time_stamp,
__CUM__INDCU as cu_order,
__CUM__CMNUM as cm_number,
__CUM__AUEST as auto_est_costs,
__CUM__DESNUM as cu_design_no,
AD01PROFNR as dip_profile,
VAPLZ as main_workctr,
WAWRK as plnt_workcenter,
FERC_IND as reg_indicator,
CLAIM_CONTROL as clm_creation_cntrl,
UPDATE_NEEDED as claim_inconsistent,
UPDATE_CONTROL as claim_upd_trigger,
GLTRP as basic_fin_date,
GSTRP as bas_start_date,
FTRMS as release_1,
GLTRS as sched_finish,
GSTRS as sched_start,
GSTRI as actual_start,
GETRI as actual_finish,
GLTRI as actual_finish_1,
FTRMI as actual_release,
FTRMP as planned_release,
RSNUM as reservation,
GASMG as total_scrap,
GAMNG as target_quantity,
GMEIN as base_unit,
PLNBEZ as material,
PLNTY as task_list_type,
PLNNR as group,
PLNAW as application_1,
PLNAL as group_counter,
PVERW as usage_1,
PLAUF as explosion_date,
PLSVB as lot_size_to,
PLNME as task_list_unit,
PLSVN as lot_size_from,
PDATV as valid_from_1,
PAENR as change_number,
PLGRP as planner_group,
LODIV as lot_size_div,
STLTY as bom_category,
STLBEZ as material_1,
STLST as bom_status,
STLNR as bom,
SDATV as valid_from_2,
SBMNG as base_quantity,
SBMEH as base_unit_1,
SAENR as change_number_1,
STLAL as alternative,
STLAN as usage_2,
SLSVN as from_lot_size,
SLSBS as to_lot_size,
AUFLD as bom_expl_date,
DISPO as mrp_controller,
AUFPL as plan_no_f_oper,
FEVOR as prodn_supervisor,
FHORI as schedmargin_key,
TERKZ as scheduling_type,
REDKZ as reduction_ind,
APRIO as priority,
NTZUE as network,
VORUE as superior_act,
PROFID as network_profile,
VORGZ as float_bef_prod,
SICHZ as float_aft_prod,
FREIZ as release_period,
UPTER as dates_changed,
BEDID as capacity_requirement,
PRONR as project_def,
ZAEHL as counter,
MZAEHL as counter_1,
ZKRIZ as add_crit_countr,
PRUEFLOS as inspection_lot,
KLVARP as plnd_costing_variant,
KLVARI as act_costing_variant,
RGEKZ as backflushing,
PLART as sched_basis,
FLG_AOB as ind_relshp_data,
FLG_ARBEI as ind_work,
GLTPP as finish_date,
GSTPP as start_date,
GLTPS as finish_date_1,
GSTPS as start_date_1,
FTRPS as release_2,
RDKZP as reduction_ind_1,
TRKZP as sched_type_for,
RUECK as confirmation,
RMZHL as counter_2,
IGMNG as confirmed_yield,
RATID as rate_id,
GROID as rough_sched_id,
CUOBJ as int_object_no,
GLUZS as finish_time,
GSUZS as schedstarttime,
REVLV as revision_level,
RSHTY as object_type,
RSHID as object_id_1,
RSNTY as object_type_1,
RSNID as object_id_2,
NAUTERM as no_auto_cost,
NAUCOST as noautomatcost,
STUFE as level,
WEGXX as path,
VWEGX as path_1,
ARSNR as reservation_1,
ARSPS as order_item_no,
MAUFNR as superior_order,
LKNOT as left_node,
RKNOT as right_node,
PRODNET as collective_order,
IASMG as confirmed_scrap,
ABARB as processing,
AUFNT as subnetwork_of,
AUFPT as plan_no_f_oper_1,
APLZT as counter_3,
NO_DISP as eff_mat_plng,
CSPLIT as apportionment,
AENNR as change_number_2,
CY_SEQNR as sequence_number_1,
BREAKS as exact_breaks,
VORGZ_TRM as float_bef_prod_1,
SICHZ_TRM as flt_after_prod,
TRMDT as scheduled_on,
GLUZP as basic_fin_time,
GSUZP as start_time,
GSUZI as actualstart,
GEUZI as actual_finish_2,
GLUPP as finish_time_1,
GSUPP as start_time_1,
GLUPS as finish_time_2,
GSUPS as sched_start_1,
CHSCH as search_proced,
KAPT_VORGZ as rempreprodfloat,
KAPT_SICHZ as remaining_float,
LEAD_AUFNR as leading_order,
PNETSTARTD as start,
PNETSTARTT as start_1,
PNETENDD as finish,
PNETENDT as finish_1,
KBED as no_cap_reqmts,
KKALKR as costcompind,
SFCPF as prod_sched_profile,
RMNGA as confirmed_rework,
GSBTR as commitment_date,
VFMNG as committed,
NOPCOST as no_planned_costs,
NETZKONT as account_assgnt,
ATRKZ as request_id,
OBJTYPE as changeind,
CH_PROC as changeproctype,
KAPVERSA as version,
COLORDPROC as co_processing,
KZERB as proj_summ_mastda,
CONF_KEY as identical_obj,
ST_ARBID as object_id_3,
VSNMR_V as version_1,
TERHW as sched_note,
SPLSTAT as split_status,
COSTUPD as update_costs,
MAX_GAMNG as maximum_qty,
MES_ROUTINGID as mes_routing,
TL_VERSN as routing_version,
BOM_VERSN as bom_version,
FLEXIBLE_PROCESSING as flexible,
ADPSP as pm_ps_ref_element,
RMANR as sales_document,
POSNR_RMA as item,
POSNV_RMA as item_1,
CFB_MAXLZ as max_storage,
CFB_LZEIH as time_unit,
CFB_ADTDAYS as additional_days,
CFB_DATOFM as date_of_manuf,
CFB_BBDPI as bbd_sled,
FSH_MPROD_ORD as master_prod_ord,
FLG_BUNDLE as bundle,
MILL_RATIO as adjustmt_factor,
BMEINS as base_unit_2,
BMENGE as base_quantity_1,
MILL_OC_ZUSKZ as combination_ind,
_sequence_num as dw_input_sequence,
TO_HEX(MD5((select string_agg(CAST(col as STRING), ', ' order by offset)
    				from unnest(split(trim(format('%t',(select as struct caufv.* except(_is_deleted,_row_id,_source_timestamp,_sequence_num))), '()'),', ')) col with offset
    				where not col IS NULL))) as finalmd5key
from `sap-adapter.slt_raw.caufv` as caufv
where caufv._sequence_num > coalesce((select case when full_delta_indicator = 'F'
    												then min_input_sequence_num
    											when full_delta_indicator <> 'F'
    											then max_input_sequence_num
    											end
    										from `sap-adapter.slt_staging.staging_audit_table`
    											where table_name = 'order_header'),0))
select client as client_key,
order as order_key,
*
From  caufv
UNION ALL
select null as client_key,
null as order_key,
caufv.*
From caufv as caufv
INNER JOIN `sap-adapter.slt_staging.order_header` as uji
ON caufv.client = uji.client
AND caufv.order = uji.order
AND caufv.finalmd5key != uji.finalmd5key
WHERE uji.dw_active_indicator = 'Y') as src
ON src.client_key = tgt.client
AND src.order_key = tgt.order
WHEN MATCHED AND src.finalmd5key != tgt.finalmd5key
    THEN UPDATE set tgt.dw_active_indicator = 'N',
    tgt.dw_last_update_date = CURRENT_DATETIME()
    WHEN NOT MATCHED THEN
insert(client,
order,
order_type,
order_category,
order_1,
entered_by,
created_on,
changed_by,
changed_on,
description,
long_txt_exists,
company_code,
plant,
business_area,
co_area,
cost_collector,
resp_cost_cntr,
location,
location_plant,
statistical,
currency,
status_change,
release,
tech_completion,
close,
object_id,
deletion_flag,
plan_line_items,
usage,
application,
costing_sheet,
overhead_key,
process_group,
settlement_ce,
cost_center,
allocation_set,
cctr_true_post,
valid_from,
sequence_number,
estimated_costs,
object_number,
profit_center,
wbs_element,
variance_key,
ra_key,
event_based_posting,
tax_jur,
functional_area,
object_class,
integ_planning,
sales_order,
sales_ord_item,
ext_order_no,
invest_profile,
logical_system,
multiple_items,
req_co_code,
req_cost_center,
scale,
invest_reason,
envir_invest,
cost_collector_1,
interest_prof,
cost_collector_2,
req_order,
prod_proc_no,
process_cat,
refurbishment,
acctindicator,
address_number,
time_created,
changed_at,
costing_variant,
cost_estimateno,
personresponsible,
dummy_function_in_length_1,
joint_venture,
recovery_indic,
equity_type,
jv_object_type,
jib_jibe_class,
jib_jibe_sbclsa,
or_cost_obj,
time_stamp,
cu_order,
cm_number,
auto_est_costs,
cu_design_no,
dip_profile,
main_workctr,
plnt_workcenter,
reg_indicator,
clm_creation_cntrl,
claim_inconsistent,
claim_upd_trigger,
basic_fin_date,
bas_start_date,
release_1,
sched_finish,
sched_start,
actual_start,
actual_finish,
actual_finish_1,
actual_release,
planned_release,
reservation,
total_scrap,
target_quantity,
base_unit,
material,
task_list_type,
group,
application_1,
group_counter,
usage_1,
explosion_date,
lot_size_to,
task_list_unit,
lot_size_from,
valid_from_1,
change_number,
planner_group,
lot_size_div,
bom_category,
material_1,
bom_status,
bom,
valid_from_2,
base_quantity,
base_unit_1,
change_number_1,
alternative,
usage_2,
from_lot_size,
to_lot_size,
bom_expl_date,
mrp_controller,
plan_no_f_oper,
prodn_supervisor,
schedmargin_key,
scheduling_type,
reduction_ind,
priority,
network,
superior_act,
network_profile,
float_bef_prod,
float_aft_prod,
release_period,
dates_changed,
capacity_requirement,
project_def,
counter,
counter_1,
add_crit_countr,
inspection_lot,
plnd_costing_variant,
act_costing_variant,
backflushing,
sched_basis,
ind_relshp_data,
ind_work,
finish_date,
start_date,
finish_date_1,
start_date_1,
release_2,
reduction_ind_1,
sched_type_for,
confirmation,
counter_2,
confirmed_yield,
rate_id,
rough_sched_id,
int_object_no,
finish_time,
schedstarttime,
revision_level,
object_type,
object_id_1,
object_type_1,
object_id_2,
no_auto_cost,
noautomatcost,
level,
path,
path_1,
reservation_1,
order_item_no,
superior_order,
left_node,
right_node,
collective_order,
confirmed_scrap,
processing,
subnetwork_of,
plan_no_f_oper_1,
counter_3,
eff_mat_plng,
apportionment,
change_number_2,
sequence_number_1,
exact_breaks,
float_bef_prod_1,
flt_after_prod,
scheduled_on,
basic_fin_time,
start_time,
actualstart,
actual_finish_2,
finish_time_1,
start_time_1,
finish_time_2,
sched_start_1,
search_proced,
rempreprodfloat,
remaining_float,
leading_order,
start,
start_1,
finish,
finish_1,
no_cap_reqmts,
costcompind,
prod_sched_profile,
confirmed_rework,
commitment_date,
committed,
no_planned_costs,
account_assgnt,
request_id,
changeind,
changeproctype,
version,
co_processing,
proj_summ_mastda,
identical_obj,
object_id_3,
version_1,
sched_note,
split_status,
update_costs,
maximum_qty,
mes_routing,
routing_version,
bom_version,
flexible,
pm_ps_ref_element,
sales_document,
item,
item_1,
max_storage,
time_unit,
additional_days,
date_of_manuf,
bbd_sled,
master_prod_ord,
bundle,
adjustmt_factor,
base_unit_2,
base_quantity_1,
combination_ind,
finalmd5key,
dw_input_sequence,
dw_active_indicator,
dw_start_date,
dw_end_date,
dw_last_update_date
)
values(src.client,
src.order,
src.order_type,
src.order_category,
src.order_1,
src.entered_by,
src.created_on,
src.changed_by,
src.changed_on,
src.description,
src.long_txt_exists,
src.company_code,
src.plant,
src.business_area,
src.co_area,
src.cost_collector,
src.resp_cost_cntr,
src.location,
src.location_plant,
src.statistical,
src.currency,
src.status_change,
src.release,
src.tech_completion,
src.close,
src.object_id,
src.deletion_flag,
src.plan_line_items,
src.usage,
src.application,
src.costing_sheet,
src.overhead_key,
src.process_group,
src.settlement_ce,
src.cost_center,
src.allocation_set,
src.cctr_true_post,
src.valid_from,
src.sequence_number,
src.estimated_costs,
src.object_number,
src.profit_center,
src.wbs_element,
src.variance_key,
src.ra_key,
src.event_based_posting,
src.tax_jur,
src.functional_area,
src.object_class,
src.integ_planning,
src.sales_order,
src.sales_ord_item,
src.ext_order_no,
src.invest_profile,
src.logical_system,
src.multiple_items,
src.req_co_code,
src.req_cost_center,
src.scale,
src.invest_reason,
src.envir_invest,
src.cost_collector_1,
src.interest_prof,
src.cost_collector_2,
src.req_order,
src.prod_proc_no,
src.process_cat,
src.refurbishment,
src.acctindicator,
src.address_number,
src.time_created,
src.changed_at,
src.costing_variant,
src.cost_estimateno,
src.personresponsible,
src.dummy_function_in_length_1,
src.joint_venture,
src.recovery_indic,
src.equity_type,
src.jv_object_type,
src.jib_jibe_class,
src.jib_jibe_sbclsa,
src.or_cost_obj,
src.time_stamp,
src.cu_order,
src.cm_number,
src.auto_est_costs,
src.cu_design_no,
src.dip_profile,
src.main_workctr,
src.plnt_workcenter,
src.reg_indicator,
src.clm_creation_cntrl,
src.claim_inconsistent,
src.claim_upd_trigger,
src.basic_fin_date,
src.bas_start_date,
src.release_1,
src.sched_finish,
src.sched_start,
src.actual_start,
src.actual_finish,
src.actual_finish_1,
src.actual_release,
src.planned_release,
src.reservation,
src.total_scrap,
src.target_quantity,
src.base_unit,
src.material,
src.task_list_type,
src.group,
src.application_1,
src.group_counter,
src.usage_1,
src.explosion_date,
src.lot_size_to,
src.task_list_unit,
src.lot_size_from,
src.valid_from_1,
src.change_number,
src.planner_group,
src.lot_size_div,
src.bom_category,
src.material_1,
src.bom_status,
src.bom,
src.valid_from_2,
src.base_quantity,
src.base_unit_1,
src.change_number_1,
src.alternative,
src.usage_2,
src.from_lot_size,
src.to_lot_size,
src.bom_expl_date,
src.mrp_controller,
src.plan_no_f_oper,
src.prodn_supervisor,
src.schedmargin_key,
src.scheduling_type,
src.reduction_ind,
src.priority,
src.network,
src.superior_act,
src.network_profile,
src.float_bef_prod,
src.float_aft_prod,
src.release_period,
src.dates_changed,
src.capacity_requirement,
src.project_def,
src.counter,
src.counter_1,
src.add_crit_countr,
src.inspection_lot,
src.plnd_costing_variant,
src.act_costing_variant,
src.backflushing,
src.sched_basis,
src.ind_relshp_data,
src.ind_work,
src.finish_date,
src.start_date,
src.finish_date_1,
src.start_date_1,
src.release_2,
src.reduction_ind_1,
src.sched_type_for,
src.confirmation,
src.counter_2,
src.confirmed_yield,
src.rate_id,
src.rough_sched_id,
src.int_object_no,
src.finish_time,
src.schedstarttime,
src.revision_level,
src.object_type,
src.object_id_1,
src.object_type_1,
src.object_id_2,
src.no_auto_cost,
src.noautomatcost,
src.level,
src.path,
src.path_1,
src.reservation_1,
src.order_item_no,
src.superior_order,
src.left_node,
src.right_node,
src.collective_order,
src.confirmed_scrap,
src.processing,
src.subnetwork_of,
src.plan_no_f_oper_1,
src.counter_3,
src.eff_mat_plng,
src.apportionment,
src.change_number_2,
src.sequence_number_1,
src.exact_breaks,
src.float_bef_prod_1,
src.flt_after_prod,
src.scheduled_on,
src.basic_fin_time,
src.start_time,
src.actualstart,
src.actual_finish_2,
src.finish_time_1,
src.start_time_1,
src.finish_time_2,
src.sched_start_1,
src.search_proced,
src.rempreprodfloat,
src.remaining_float,
src.leading_order,
src.start,
src.start_1,
src.finish,
src.finish_1,
src.no_cap_reqmts,
src.costcompind,
src.prod_sched_profile,
src.confirmed_rework,
src.commitment_date,
src.committed,
src.no_planned_costs,
src.account_assgnt,
src.request_id,
src.changeind,
src.changeproctype,
src.version,
src.co_processing,
src.proj_summ_mastda,
src.identical_obj,
src.object_id_3,
src.version_1,
src.sched_note,
src.split_status,
src.update_costs,
src.maximum_qty,
src.mes_routing,
src.routing_version,
src.bom_version,
src.flexible,
src.pm_ps_ref_element,
src.sales_document,
src.item,
src.item_1,
src.max_storage,
src.time_unit,
src.additional_days,
src.date_of_manuf,
src.bbd_sled,
src.master_prod_ord,
src.bundle,
src.adjustmt_factor,
src.base_unit_2,
src.base_quantity_1,
src.combination_ind,
src.finalmd5key,
src.dw_input_sequence,
'Y',
CURRENT_DATETIME(),
DATETIME(9999, 12, 31, 23, 59, 59),
CURRENT_DATETIME()
);
MERGE INTO `sap-adapter.slt_staging.staging_audit_table` tgt
USING ( SELECT
    		'order_header' as table_name
    		,'caufv' as sap_table_name
    		,CASE WHEN (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'order_header') IS NULL
    				OR (select full_delta_indicator from `sap-adapter.slt_staging.staging_audit_table` where table_name = 'order_header') = 'F'
    			THEN 'F'
    			ELSE 'D'
    		END AS full_delta_indicator
    		,0 as min_input_sequence_num
    		,(select max(dw_input_sequence) as max_input_sequence_num from `sap-adapter.slt_staging.order_header`) as max_input_sequence_num
    		,(coalesce((select COUNT(*) AS inserted_record_count from `sap-adapter.slt_staging.order_header` a
    		where a.dw_input_sequence > coalesce((select case when full_delta_indicator = 'F'
    						then min_input_sequence_num
    						when full_delta_indicator <> 'F'
    						then max_input_sequence_num
    					end
    				from `sap-adapter.slt_staging.staging_audit_table`
    				where table_name = 'order_header'),0)),(select count(*) AS inserted_record_count from `sap-adapter.slt_staging.order_header`))) AS inserted_record_count
    		,CURRENT_DATETIME() as last_update_date   
    )scr
    on tgt.table_name = scr.table_name
    WHEN MATCHED THEN 
    UPDATE set tgt.min_input_sequence_num = 0
    			,tgt.max_input_sequence_num = scr.max_input_sequence_num
    			,tgt.inserted_record_count = scr.inserted_record_count
    			,tgt.last_update_date = scr.last_update_date
    WHEN NOT MATCHED THEN
    INSERT (table_name,
    		sap_table_name,
    		full_delta_indicator,
    		min_input_sequence_num,
    		max_input_sequence_num,
    		inserted_record_count,
    		last_update_date)
    VALUES(scr.table_name,
    		scr.sap_table_name,
    		scr.full_delta_indicator,
    		scr.min_input_sequence_num,
    		scr.max_input_sequence_num,
    		scr.inserted_record_count,
    		scr.last_update_date);
    