create or replace view `{$productid}.{$slt_l2_canonical}.location_vw`
as
SELECT  cd.customer_uuid AS uuid,
        cd.customer_key AS location_uid,
       'CUSTOMER' AS location_type,
        cd.customer AS location_id,
        cd.name AS location_name,
        cd.name_1 AS location_name2,
        cd.house_number_adrc as house_number,
        cd.street_adrc as street,
        cd.city_adrc as city,
        cd.postal_code_adrc as postal_code,
        cd.district_adrc as address,
        cd.region_adrc as region,
        cd.country_adrc as country,
        CAST(NULL AS FLOAT64) as geo_lattitude,
        CAST(NULL AS FLOAT64) as geo_longitude,
        cd.time_zone as time_zone,
        cd.transport_zone as transportation_zone,
        CAST(NULL AS STRING) as shipping_calendar,
        CAST(NULL AS STRING) as receiving_calendar,
        cd.working_times as working_hour,
        cd.language_key,
        cd.created_on as valid_from_date,
        CAST(NULL AS DATETIME) as valid_to_date,
        CAST(NULL AS STRING) as active,
        CAST(NULL AS STRING) as company_code,
        CAST(NULL AS STRING) as valuation_area,
        cd.created_on as creation_date,
        cd.changed_on as change_date
FROM `{$productid}.{$slt_l1_dimension}.customer_dimension` cd
where cd.dw_active_indicator = 'Y'
UNION ALL 
SELECT  sd.supplier_uuid AS uuid,
        sd.supplier_key AS location_uid,
       'VENDOR' AS location_type,
        sd.vendor AS location_id,
        sd.name AS location_name,
        sd.name_1 AS location_name2,
        sd.house_number_adrc as house_number,
        sd.street_adrc as street,
        sd.city_adrc as city,
        sd.postal_code_adrc as postal_code,
        sd.district_adrc as district,
        sd.region_adrc as region,
        sd.country_adrc as country,
        CAST(NULL AS FLOAT64) as geo_lattitude,
        CAST(NULL AS FLOAT64) as geo_longitude,
        sd.time_zone as time_zone,
        sd.transport_zone as transportation_zone,
        CAST(NULL AS STRING) as shipping_calendar,
        CAST(NULL AS STRING) as receiving_calendar,
        CAST(NULL AS STRING) as working_hour,
        sd.language_key,
        sd.created_on as valid_from_date,
        CAST(NULL AS DATETIME) as valid_to_date,
        CAST(NULL AS STRING) as active,
        CAST(NULL AS STRING) as company_code,
        CAST(NULL AS STRING) as valuation_area,
        sd.created_on as creation_date,
        sd.changed_on as change_date
FROM `{$productid}.{$slt_l1_dimension}.supplier_dimension` sd
where sd.dw_active_indicator = 'Y'
UNION ALL 
SELECT  pd.plant_uuid AS uuid,
        pd.plant_key AS location_uid,
       'PLANT' AS location_type,
        pd.plant AS location_id,
        pd.name AS location_name,
        pd.name_1 AS location_name2,
        pd.house_number as house_number,
        pd.street as street,
        pd.city_adrc as city,
        pd.postal_code_adrc as postal_code,
        pd.district,
        pd.region_adrc as region,
        pd.country_adrc as country,
        CAST(NULL AS FLOAT64) as geo_lattitude,
        CAST(NULL AS FLOAT64) as geo_longitude,
        pd.time_zone as time_zone,
        pd.transport_zone as transportation_zone,
        CAST(NULL AS STRING) as shipping_calendar,
        CAST(NULL AS STRING) as receiving_calendar,
        CAST(NULL AS STRING) as working_hour,
        pd.language_key,
        CAST(NULL AS DATE) as valid_from_date,
        CAST(NULL AS DATETIME) as valid_to_date,
        CAST(NULL AS STRING) as active,
        CAST(NULL AS STRING) as company_code,
        CAST(NULL AS STRING) as valuation_area,
        CAST(NULL AS DATE) as creation_date,
        CAST(NULL AS DATE) as change_date
FROM `{$productid}.{$slt_l1_dimension}.plant_dimension` pd
where pd.dw_active_indicator = 'Y'
UNION ALL 
SELECT  spd.shipping_point_uuid AS uuid,
        spd.shipping_point_key AS location_uid,
       'SHIPING POINT' AS location_type,
        spd.shipping_point AS location_id,
        spd.name AS location_name,
        spd.name_1 AS location_name2,
        spd.house_number as house_number,
        spd.street as street,
        spd.city,
        spd.postal_code,
        spd.district,
        spd.region,
        spd.country_adrc as country,
        CAST(NULL AS FLOAT64) as geo_lattitude,
        CAST(NULL AS FLOAT64) as geo_longitude,
        spd.time_zone as time_zone,
        spd.transport_zone as transportation_zone,
        CAST(NULL AS STRING) as shipping_calendar,
        CAST(NULL AS STRING) as receiving_calendar,
        CAST(NULL AS STRING) as working_hour,
        spd.language_key,
        CAST(NULL AS DATE) as valid_from_date,
        CAST(NULL AS DATETIME) as valid_to_date,
        CAST(NULL AS STRING) as active,
        CAST(NULL AS STRING) as company_code,
        CAST(NULL AS STRING) as valuation_area,
        CAST(NULL AS DATE) as creation_date,
        CAST(NULL AS DATE) as change_date
FROM `{$productid}.{$slt_l1_dimension}.shipping_point_dimension` spd
where spd.dw_active_indicator = 'Y'
UNION ALL 
SELECT  thd.transportation_hub_uuid AS uuid,
        thd.transportation_hub_key AS location_uid,
       'TRANSPORTATION HUB' AS location_type,
        thd.transportplanpt AS location_id,
        thd.description AS location_name,
        thd.name_1 AS location_name2,
        thd.house_number as house_number,
        thd.street as street,
        thd.city,
        thd.postal_code,
        thd.district,
        thd.region,
        thd.country as country,
        CAST(NULL AS FLOAT64) as geo_lattitude,
        CAST(NULL AS FLOAT64) as geo_longitude,
        thd.time_zone as time_zone,
        thd.transport_zone as transportation_zone,
        CAST(NULL AS STRING) as shipping_calendar,
        CAST(NULL AS STRING) as receiving_calendar,
        CAST(NULL AS STRING) as working_hour,
        thd.language_key,
        CAST(NULL AS DATE) as valid_from_date,
        CAST(NULL AS DATETIME) as valid_to_date,
        CAST(NULL AS STRING) as active,
        CAST(NULL AS STRING) as company_code,
        CAST(NULL AS STRING) as valuation_area,
        CAST(NULL AS DATE) as creation_date,
        CAST(NULL AS DATE) as change_date
FROM `{$productid}.{$slt_l1_dimension}.transportation_hub_dimension` thd
where thd.dw_active_indicator = 'Y'
UNION ALL 
SELECT  sld.storage_location_uuid AS uuid,
        sld.storage_location_key AS location_uid,
       'STORAGE LOCATION' AS location_type,
        sld.stor_loc AS location_id,
        sld.description AS location_name,
        sld.name_1 AS location_name2,
        sld.house_number as house_number,
        sld.street as street,
        sld.city,
        sld.postal_code,
        sld.district,
        sld.region,
        sld.country as country,
        CAST(NULL AS FLOAT64) as geo_lattitude,
        CAST(NULL AS FLOAT64) as geo_longitude,
        sld.time_zone as time_zone,
        sld.transport_zone as transportation_zone,
        CAST(NULL AS STRING) as shipping_calendar,
        CAST(NULL AS STRING) as receiving_calendar,
        CAST(NULL AS STRING) as working_hour,
        sld.language_key,
        CAST(NULL AS DATE) as valid_from_date,
        CAST(NULL AS DATETIME) as valid_to_date,
        CAST(NULL AS STRING) as active,
        CAST(NULL AS STRING) as company_code,
        CAST(NULL AS STRING) as valuation_area,
        CAST(NULL AS DATE) as creation_date,
        CAST(NULL AS DATE) as change_date
FROM `{$productid}.{$slt_l1_dimension}.storage_location_dimension` sld
where sld.dw_active_indicator = 'Y';